@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_080091ac, chunk 1/2: 0x080091AC-0x0800A0DC (thumb_code, 0xF30 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x080091AC sub_080091ac
@   0x08009200 sub_08009200
@   0x08009398 sub_08009398
@   0x080093CC sub_080093cc
@   0x080093FC sub_080093fc
@   0x08009418 sub_08009418
@   0x080095C0 sub_080095c0
@   0x080095E4 sub_080095e4
@   0x08009640 sub_08009640
@   0x080096E0 sub_080096e0
@   0x0800973C sub_0800973c
@   0x080098A8 sub_080098a8
@   0x080099C8 sub_080099c8
@   0x080099FC sub_080099fc
@   0x08009AA0 sub_08009aa0
@   0x08009AB8 sub_08009ab8
@   0x08009ADC sub_08009adc
@   0x08009B2C sub_08009b2c
@   0x08009CB0 sub_08009cb0
@   0x08009E14 sub_08009e14
@   0x08009E20 sub_08009e20
@   0x08009E2C sub_08009e2c
@   0x08009E60 sub_08009e60
@   0x08009EB8 sub_08009eb8
@   0x08009EE8 sub_08009ee8
@   0x08009FCC sub_08009fcc
@   0x0800A008 sub_0800a008
@   0x0800A04C sub_0800a04c
@   0x0800A0AC sub_0800a0ac

	.section .game_code_and_rodata_080091ac, "ax"
	.global	game_code_and_rodata_080091ac
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_080091ac:
	.thumb_func
	.global	sub_080091ac
sub_080091ac:
	.thumb
	push	{r4, r5, lr}
	bl	sub_08009200	@ 0x08009200
	cmp	r0, #1
	bne.n	loc_080091f0	@ 0x080091F0
	ldr	r2, [pc, #52]	@ 0x080091EC
	movs	r0, #16
	movs	r1, #2
	bl	sub_080008e8	@ 0x080008E8
	movs	r5, #128
	lsls	r5, r5, #1
	movs	r4, #15
	.global	loc_080091c6
loc_080091c6:
	lsls	r0, r5, #16
	lsrs	r0, r0, #16
	bl	sub_08003770	@ 0x08003770
	bl	sub_080022e4	@ 0x080022E4
	subs	r5, #16
	subs	r4, #1
	cmp	r4, #0
	bge.n	loc_080091c6	@ 0x080091C6
	bl	sub_08003688	@ 0x08003688
	movs	r0, #128
	lsls	r0, r0, #1
	bl	sub_08003770	@ 0x08003770
	bl	sub_080022ac	@ 0x080022AC
	b.n	loc_080091f6	@ 0x080091F6
	.word	0x08731C88
	.global	loc_080091f0
loc_080091f0:
	ldr	r1, [pc, #8]	@ 0x080091FC
	movs	r0, #1
	strh	r0, [r1, #0]
	.global	loc_080091f6
loc_080091f6:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	gUnk_03002150
	.thumb_func
	.global	sub_08009200
sub_08009200:
	.thumb
	push	{r4, r5, r6, lr}
	mov	r6, sl
	mov	r5, r9
	mov	r4, r8
	push	{r4, r5, r6}
	bl	sub_080022ac	@ 0x080022AC
	bl	sub_080caa3c	@ 0x080CAA3C
	ldr	r0, [pc, #204]	@ 0x080092E0
	mov	sl, r0
	ldr	r1, [pc, #204]	@ 0x080092E4
	adds	r0, r1, #0
	mov	r2, sl
	strh	r0, [r2, #0]
	movs	r0, #0
	bl	sub_08008c4c	@ 0x08008C4C
	movs	r0, #6
	bl	sub_08008c64	@ 0x08008C64
	movs	r0, #7
	bl	sub_08008c64	@ 0x08008C64
	ldr	r3, [pc, #180]	@ 0x080092E8
	mov	r9, r3
	ldr	r0, [pc, #180]	@ 0x080092EC
	mov	r8, r0
	ldr	r6, [pc, #180]	@ 0x080092F0
	ldr	r5, [pc, #184]	@ 0x080092F4
	ldr	r4, [pc, #184]	@ 0x080092F8
	ldr	r3, [pc, #188]	@ 0x080092FC
	ldr	r2, [pc, #188]	@ 0x08009300
	ldr	r1, [pc, #192]	@ 0x08009304
	movs	r0, #0
	str	r0, [r1, #0]
	ldr	r0, [r1, #0]
	str	r0, [r2, #0]
	ldr	r0, [r2, #0]
	str	r0, [r3, #0]
	ldr	r0, [r3, #0]
	str	r0, [r4, #0]
	ldr	r0, [r4, #0]
	str	r0, [r5, #0]
	ldr	r0, [r5, #0]
	str	r0, [r6, #0]
	ldr	r0, [r6, #0]
	mov	r1, r8
	str	r0, [r1, #0]
	ldr	r0, [r1, #0]
	mov	r2, r9
	str	r0, [r2, #0]
	ldr	r4, [pc, #156]	@ 0x08009308
	ldrh	r1, [r4, #0]
	ldr	r5, [pc, #156]	@ 0x0800930C
	adds	r0, r5, #0
	ands	r0, r1
	strh	r0, [r4, #0]
	ldrh	r0, [r4, #0]
	movs	r3, #136
	lsls	r3, r3, #5
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r4, #0]
	bl	sub_0800214c	@ 0x0800214C
	bl	sub_08002db4	@ 0x08002DB4
	movs	r0, #60
	bl	sub_08002d54	@ 0x08002D54
	movs	r0, #0
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	movs	r0, #60
	bl	sub_08002d54	@ 0x08002D54
	movs	r0, #1
	mov	r1, sl
	strh	r0, [r1, #0]
	movs	r0, #70
	bl	sub_08009398	@ 0x08009398
	cmp	r0, #0
	bne.n	loc_080092da	@ 0x080092DA
	ldr	r0, [pc, #96]	@ 0x08009310
	bl	sub_080031b8	@ 0x080031B8
	movs	r0, #35
	bl	sub_08009398	@ 0x08009398
	cmp	r0, #0
	bne.n	loc_080092da	@ 0x080092DA
	ldrh	r1, [r4, #0]
	adds	r0, r5, #0
	ands	r0, r1
	strh	r0, [r4, #0]
	ldrh	r0, [r4, #0]
	movs	r2, #248
	lsls	r2, r2, #5
	adds	r1, r2, #0
	orrs	r0, r1
	strh	r0, [r4, #0]
	movs	r0, #21
	bl	sub_08009398	@ 0x08009398
	cmp	r0, #0
	beq.n	loc_08009314	@ 0x08009314
	.global	loc_080092da
loc_080092da:
	movs	r0, #1
	b.n	loc_0800936c	@ 0x0800936C
	movs	r0, r0
	.word	gUnk_0300243C
	.word	0x00009999
	.word	gUnk_03000010
	.word	gUnk_0300117C
	.word	gUnk_03000FC0
	.word	gUnk_03001EE0
	.word	gUnk_03001E94
	.word	gUnk_03000F8C
	.word	gUnk_03000FA8
	.word	gUnk_03000B78
	.word	gUnk_03001ED8
	.word	0x0000E0FF
	.word	0x0000010D
	.global	loc_08009314
loc_08009314:
	ldr	r1, [pc, #100]	@ 0x0800937C
	movs	r0, #49
	strb	r0, [r1, #0]
	ldr	r1, [pc, #100]	@ 0x08009380
	movs	r0, #62
	strb	r0, [r1, #0]
	ldr	r2, [pc, #96]	@ 0x08009384
	movs	r0, #255
	strh	r0, [r2, #0]
	ldr	r1, [pc, #96]	@ 0x08009388
	movs	r0, #160
	strh	r0, [r1, #0]
	ldrh	r0, [r4, #0]
	movs	r3, #128
	lsls	r3, r3, #6
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r4, #0]
	movs	r5, #85
	adds	r6, r2, #0
	movs	r4, #255
	.global	loc_0800933e
loc_0800933e:
	strh	r4, [r6, #0]
	bl	sub_080022e4	@ 0x080022E4
	subs	r4, #3
	subs	r5, #1
	cmp	r5, #0
	bge.n	loc_0800933e	@ 0x0800933E
	ldr	r2, [pc, #60]	@ 0x0800938C
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #60]	@ 0x08009390
	ands	r0, r1
	strh	r0, [r2, #0]
	ldrh	r0, [r2, #0]
	movs	r3, #240
	lsls	r3, r3, #5
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r2, #0]
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x08009394
	ands	r0, r1
	strh	r0, [r2, #0]
	movs	r0, #0
	.global	loc_0800936c
loc_0800936c:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03000B18
	.word	gUnk_03000F7C
	.word	gUnk_03000FD4
	.word	gUnk_03000044
	.word	gUnk_03001ED8
	.word	0x0000E0FF
	.word	0x0000DFFF
	.thumb_func
	.global	sub_08009398
sub_08009398:
	.thumb
	push	{r4, r5, lr}
	adds	r5, r0, #0
	movs	r4, #0
	cmp	r4, r5
	bge.n	loc_080093c2	@ 0x080093C2
	.global	loc_080093a2
loc_080093a2:
	ldr	r0, [pc, #16]	@ 0x080093B4
	ldrh	r1, [r0, #0]
	movs	r0, #11
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080093b8	@ 0x080093B8
	movs	r0, #1
	b.n	loc_080093c4	@ 0x080093C4
	movs	r0, r0
	.word	gUnk_03000038
	.global	loc_080093b8
loc_080093b8:
	bl	sub_080022e4	@ 0x080022E4
	adds	r4, #1
	cmp	r4, r5
	blt.n	loc_080093a2	@ 0x080093A2
	.global	loc_080093c2
loc_080093c2:
	movs	r0, #0
	.global	loc_080093c4
loc_080093c4:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_080093cc
sub_080093cc:
	.thumb
	push	{lr}
	b.n	loc_080093e8	@ 0x080093E8
	.global	loc_080093d0
loc_080093d0:
	ldr	r0, [pc, #12]	@ 0x080093E0
	ldrh	r1, [r0, #0]
	movs	r0, #11
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080093e4	@ 0x080093E4
	movs	r0, #1
	b.n	loc_080093f2	@ 0x080093F2
	.word	gUnk_03000038
	.global	loc_080093e4
loc_080093e4:
	bl	sub_080022e4	@ 0x080022E4
	.global	loc_080093e8
loc_080093e8:
	ldr	r0, [pc, #12]	@ 0x080093F8
	ldrh	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_080093d0	@ 0x080093D0
	movs	r0, #0
	.global	loc_080093f2
loc_080093f2:
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03001E90
	.thumb_func
	.global	sub_080093fc
sub_080093fc:
	.thumb
	push	{lr}
	ldr	r0, [pc, #20]	@ 0x08009414
	ldr	r1, [r0, #0]
	movs	r0, #0
	str	r0, [r1, #0]
	str	r0, [r1, #12]
	.global	loc_08009408
loc_08009408:
	bl	sub_080caab8	@ 0x080CAAB8
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_08009408	@ 0x08009408
	.word	gUnk_03002490
	.thumb_func
	.global	sub_08009418
sub_08009418:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	sub	sp, #4
	ldr	r0, [pc, #380]	@ 0x080095A0
	ldr	r1, [r0, #0]
	movs	r2, #0
	str	r2, [r1, #0]
	str	r2, [r1, #12]
	adds	r1, #108
	strh	r2, [r1, #0]
	adds	r4, r0, #0
	.global	loc_08009430
loc_08009430:
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	lsls	r1, r1, #5
	ldr	r5, [pc, #360]	@ 0x080095A4
	adds	r1, r1, r5
	movs	r0, #2
	ldr	r2, [pc, #356]	@ 0x080095A8
	movs	r3, #32
	bl	sub_080017e4	@ 0x080017E4
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #10
	ble.n	loc_08009430	@ 0x08009430
	ldr	r0, [pc, #316]	@ 0x080095A0
	ldr	r1, [r0, #0]
	adds	r1, #108
	movs	r2, #0
	strh	r2, [r1, #0]
	movs	r1, #208
	lsls	r1, r1, #1
	adds	r6, r5, r1
	adds	r4, r0, #0
	ldr	r7, [pc, #308]	@ 0x080095A8
	ldr	r5, [pc, #308]	@ 0x080095AC
	movs	r2, #34
	adds	r2, r2, r7
	mov	r8, r2
	.global	loc_0800947c
loc_0800947c:
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	adds	r0, #1
	lsls	r2, r0, #2
	adds	r2, r2, r0
	lsls	r2, r2, #2
	adds	r2, r2, r0
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	str	r7, [sp, #0]
	adds	r0, r6, #0
	adds	r1, r6, #0
	subs	r1, #64
	movs	r3, #16
	bl	sub_08003014	@ 0x08003014
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	adds	r0, #1
	lsls	r2, r0, #2
	adds	r2, r2, r0
	lsls	r2, r2, #2
	adds	r2, r2, r0
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	mov	r0, r8
	str	r0, [sp, #0]
	adds	r0, r5, #0
	adds	r1, r5, #0
	adds	r1, #16
	movs	r3, #8
	bl	sub_08003014	@ 0x08003014
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #11
	ble.n	loc_0800947c	@ 0x0800947C
	ldr	r0, [pc, #192]	@ 0x080095A0
	ldr	r1, [r0, #0]
	adds	r1, #108
	movs	r2, #0
	strh	r2, [r1, #0]
	ldr	r6, [pc, #196]	@ 0x080095B0
	adds	r4, r0, #0
	ldr	r7, [pc, #184]	@ 0x080095A8
	movs	r1, #34
	adds	r1, r1, r7
	mov	r8, r1
	ldr	r5, [pc, #188]	@ 0x080095B4
	.global	loc_080094f6
loc_080094f6:
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	adds	r2, #1
	lsls	r2, r2, #21
	lsrs	r2, r2, #16
	str	r7, [sp, #0]
	adds	r0, r6, #0
	adds	r1, r6, #0
	adds	r1, #32
	movs	r3, #16
	.global	loc_0800950e
loc_0800950e:
	bl	sub_08003014	@ 0x08003014
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	adds	r2, #1
	lsls	r2, r2, #21
	lsrs	r2, r2, #16
	mov	r0, r8
	str	r0, [sp, #0]
	adds	r0, r5, #0
	adds	r1, r5, #0
	subs	r1, #16
	movs	r3, #8
	bl	sub_08003014	@ 0x08003014
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #7
	ble.n	loc_080094f6	@ 0x080094F6
	ldr	r4, [pc, #84]	@ 0x080095A0
	ldr	r6, [pc, #108]	@ 0x080095B8
	ldr	r5, [pc, #108]	@ 0x080095BC
	.global	loc_0800954e
loc_0800954e:
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	strh	r1, [r0, #0]
	.global	loc_08009556
loc_08009556:
	ldr	r0, [r4, #0]
	adds	r1, r0, #0
	adds	r1, #108
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r0, #7
	ble.n	loc_0800956c	@ 0x0800956C
	movs	r0, #0
	ldrsh	r1, [r1, r0]
	movs	r0, #16
	subs	r0, r0, r1
	.global	loc_0800956c
loc_0800956c:
	lsls	r0, r0, #5
	str	r0, [r6, #0]
	ldr	r0, [pc, #68]	@ 0x080095B8
	ldrh	r2, [r0, #0]
	ldr	r0, [pc, #48]	@ 0x080095A8
	str	r0, [sp, #0]
	adds	r0, r5, #0
	adds	r1, r5, #0
	adds	r1, #32
	movs	r3, #16
	bl	sub_08003014	@ 0x08003014
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	.global	loc_08009592
loc_08009592:
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #15
	ble.n	loc_08009556	@ 0x08009556
	b.n	loc_0800954e	@ 0x0800954E
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x08541D98
	.word	0x03001430
	.word	0x08541F58
	.word	0x08541EF8
	.word	0x08541F68
	.word	gUnk_03001F2C
	.word	0x08541F18
	.thumb_func
	.global	sub_080095c0
sub_080095c0:
	.thumb
	push	{lr}
	ldr	r0, [pc, #20]	@ 0x080095D8
	ldr	r0, [r0, #0]
	ldr	r1, [r0, #24]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	bne.n	loc_080095dc	@ 0x080095DC
	bl	sub_080095e4	@ 0x080095E4
	b.n	loc_080095e0	@ 0x080095E0
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_080095dc
loc_080095dc:
	bl	sub_08009640	@ 0x08009640
	.global	loc_080095e0
loc_080095e0:
	pop	{r0}
	bx	r0
	.thumb_func
	.global	sub_080095e4
sub_080095e4:
	.thumb
	push	{r4, r5, lr}
	ldr	r4, [pc, #80]	@ 0x08009638
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #28]
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	strh	r1, [r0, #0]
	ldr	r5, [pc, #64]	@ 0x0800963C
	.global	loc_080095fa
loc_080095fa:
	movs	r0, #2
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	ldr	r2, [r4, #0]
	str	r0, [r2, #40]
	lsls	r1, r0, #3
	adds	r1, r1, r0
	lsls	r1, r1, #4
	adds	r1, r1, r5
	adds	r2, #108
	movs	r3, #0
	ldrsh	r0, [r2, r3]
	str	r0, [r1, #0]
	movs	r0, #3
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #9
	ble.n	loc_080095fa	@ 0x080095FA
	bl	TaskDispatchTrampoline	@ 0x080CFDD4
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	0x030027A8
	.thumb_func
	.global	sub_08009640
sub_08009640:
	.thumb
	push	{r4, lr}
	ldr	r2, [pc, #48]	@ 0x08009674
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #48]	@ 0x08009678
	str	r0, [r1, #0]
	ldr	r0, [pc, #48]	@ 0x0800967C
	str	r0, [r1, #12]
	ldr	r0, [pc, #48]	@ 0x08009680
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #8
	strb	r0, [r1, #0]
	ldr	r3, [r2, #0]
	ldr	r1, [r3, #24]
	adds	r4, r2, #0
	cmp	r1, #4
	bgt.n	loc_08009684	@ 0x08009684
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #18
	movs	r1, #192
	lsls	r1, r1, #13
	adds	r0, r0, r1
	str	r0, [r3, #76]
	b.n	loc_08009694	@ 0x08009694
	movs	r0, r0
	.word	gUnk_03002490
	.word	sub_080059d8+1
	.word	sub_08005ca0+1
	.word	0x087555B4
	.global	loc_08009684
loc_08009684:
	subs	r0, r1, #5
	lsls	r1, r0, #2
	adds	r1, r1, r0
	lsls	r1, r1, #18
	movs	r0, #136
	lsls	r0, r0, #16
	adds	r1, r1, r0
	str	r1, [r3, #76]
	.global	loc_08009694
loc_08009694:
	movs	r0, #128
	lsls	r0, r0, #16
	str	r0, [r3, #80]
	ldr	r1, [r4, #0]
	movs	r0, #8
	strh	r0, [r1, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r2, [r4, #0]
	ldr	r1, [pc, #20]	@ 0x080096DC
	ldr	r0, [r2, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	strh	r0, [r2, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	0x08731CC8
	.thumb_func
	.global	sub_080096e0
sub_080096e0:
	.thumb
	push	{lr}
	b.n	loc_080096e8	@ 0x080096E8
	.global	loc_080096e4
loc_080096e4:
	bl	sub_080098a8	@ 0x080098A8
	.global	loc_080096e8
loc_080096e8:
	bl	sub_0800973c	@ 0x0800973C
	cmp	r0, #0
	beq.n	loc_080096e4	@ 0x080096E4
	ldr	r1, [pc, #44]	@ 0x08009720
	movs	r0, #10
	strh	r0, [r1, #0]
	ldr	r1, [pc, #44]	@ 0x08009724
	movs	r0, #2
	strh	r0, [r1, #0]
	ldr	r1, [pc, #40]	@ 0x08009728
	movs	r0, #3
	strh	r0, [r1, #0]
	ldr	r1, [pc, #40]	@ 0x0800972C
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr	r0, [pc, #36]	@ 0x08009730
	movs	r1, #1
	strh	r1, [r0, #0]
	ldr	r0, [pc, #36]	@ 0x08009734
	strh	r1, [r0, #0]
	ldr	r1, [pc, #36]	@ 0x08009738
	movs	r0, #0
	str	r0, [r1, #0]
	bl	sub_08002db4	@ 0x08002DB4
	pop	{r0}
	bx	r0
	.word	gUnk_03001E90
	.word	gUnk_03000FB8
	.word	gUnk_030004A4
	.word	gUnk_03001174
	.word	gUnk_03001E98
	.word	gUnk_03000048
	.word	gUnk_03001ED4
	.thumb_func
	.global	sub_0800973c
sub_0800973c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	ldr	r7, [pc, #152]	@ 0x080097E0
	ldrh	r0, [r7, #0]
	cmp	r0, #1
	beq.n	loc_08009810	@ 0x08009810
	bl	sub_080022ac	@ 0x080022AC
	movs	r0, #0
	bl	sub_08008c4c	@ 0x08008C4C
	movs	r0, #7
	bl	sub_08008c64	@ 0x08008C64
	ldr	r0, [pc, #132]	@ 0x080097E4
	mov	r9, r0
	ldr	r1, [pc, #132]	@ 0x080097E8
	mov	r8, r1
	ldr	r6, [pc, #132]	@ 0x080097EC
	ldr	r5, [pc, #136]	@ 0x080097F0
	ldr	r4, [pc, #136]	@ 0x080097F4
	ldr	r3, [pc, #140]	@ 0x080097F8
	ldr	r2, [pc, #140]	@ 0x080097FC
	ldr	r1, [pc, #144]	@ 0x08009800
	movs	r0, #0
	str	r0, [r1, #0]
	ldr	r0, [r1, #0]
	str	r0, [r2, #0]
	ldr	r0, [r2, #0]
	str	r0, [r3, #0]
	ldr	r0, [r3, #0]
	str	r0, [r4, #0]
	ldr	r0, [r4, #0]
	str	r0, [r5, #0]
	ldr	r0, [r5, #0]
	str	r0, [r6, #0]
	ldr	r0, [r6, #0]
	mov	r3, r8
	str	r0, [r3, #0]
	ldr	r0, [r3, #0]
	mov	r1, r9
	str	r0, [r1, #0]
	ldr	r2, [pc, #108]	@ 0x08009804
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #108]	@ 0x08009808
	ands	r0, r1
	strh	r0, [r2, #0]
	ldrh	r0, [r2, #0]
	movs	r3, #240
	lsls	r3, r3, #5
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r2, #0]
	ldrh	r0, [r7, #0]
	cmp	r0, #1
	beq.n	loc_08009810	@ 0x08009810
	bl	sub_0800214c	@ 0x0800214C
	bl	sub_08002db4	@ 0x08002DB4
	movs	r0, #2
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	adds	r1, r0, #0
	ldr	r3, [pc, #72]	@ 0x0800980C
	lsls	r0, r1, #3
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r1, r3, #0
	adds	r1, #24
	adds	r1, r0, r1
	movs	r2, #1
	negs	r2, r2
	str	r2, [r1, #0]
	adds	r3, #28
	adds	r0, r0, r3
	movs	r1, #0
	b.n	loc_08009834	@ 0x08009834
	movs	r0, r0
	.word	gUnk_03002150
	.word	gUnk_03000010
	.word	gUnk_0300117C
	.word	gUnk_03000FC0
	.word	gUnk_03001EE0
	.word	gUnk_03001E94
	.word	gUnk_03000F8C
	.word	gUnk_03000FA8
	.word	gUnk_03000B78
	.word	gUnk_03001ED8
	.word	0x0000E0FF
	.word	gUnk_03002790
	.global	loc_08009810
loc_08009810:
	movs	r0, #2
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	adds	r1, r0, #0
	ldr	r3, [pc, #56]	@ 0x08009854
	lsls	r0, r1, #3
	adds	r0, r0, r1
	lsls	r0, r0, #4
	adds	r1, r3, #0
	adds	r1, #24
	adds	r1, r0, r1
	movs	r2, #1
	negs	r2, r2
	str	r2, [r1, #0]
	adds	r3, #28
	adds	r0, r0, r3
	movs	r1, #90
	.global	loc_08009834
loc_08009834:
	str	r1, [r0, #0]
	movs	r0, #1
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	movs	r0, #26
	bl	sub_08003110	@ 0x08003110
	ldr	r0, [pc, #16]	@ 0x08009858
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	beq.n	loc_0800985c	@ 0x0800985C
	movs	r0, #60
	bl	sub_08002d54	@ 0x08002D54
	b.n	loc_08009862	@ 0x08009862
	.word	gUnk_03002790
	.word	gUnk_03002150
	.global	loc_0800985c
loc_0800985c:
	movs	r0, #210
	bl	sub_08002d54	@ 0x08002D54
	.global	loc_08009862
loc_08009862:
	movs	r4, #150
	lsls	r4, r4, #2
	ldr	r5, [pc, #28]	@ 0x08009884
	movs	r6, #9
	.global	loc_0800986a
loc_0800986a:
	subs	r4, #1
	cmp	r4, #0
	beq.n	loc_08009888	@ 0x08009888
	bl	sub_080022e4	@ 0x080022E4
	ldrh	r1, [r5, #0]
	adds	r0, r6, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0800986a	@ 0x0800986A
	movs	r0, #1
	b.n	loc_08009898	@ 0x08009898
	movs	r0, r0
	.word	gUnk_03000038
	.global	loc_08009888
loc_08009888:
	ldr	r1, [pc, #24]	@ 0x080098A4
	movs	r0, #3
	strh	r0, [r1, #0]
	bl	sub_080021dc	@ 0x080021DC
	bl	sub_08002db4	@ 0x08002DB4
	movs	r0, #0
	.global	loc_08009898
loc_08009898:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.word	gUnk_03002150
	.thumb_func
	.global	sub_080098a8
sub_080098a8:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	bl	sub_080022ac	@ 0x080022AC
	movs	r0, #1
	bl	sub_08008c4c	@ 0x08008C4C
	movs	r0, #8
	bl	sub_08008c64	@ 0x08008C64
	ldr	r2, [pc, #224]	@ 0x080099A4
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #224]	@ 0x080099A8
	ands	r0, r1
	strh	r0, [r2, #0]
	ldrh	r0, [r2, #0]
	movs	r3, #224
	lsls	r3, r3, #5
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r2, #0]
	ldr	r1, [pc, #208]	@ 0x080099AC
	movs	r0, #84
	strb	r0, [r1, #0]
	ldr	r1, [pc, #208]	@ 0x080099B0
	movs	r0, #8
	strb	r0, [r1, #0]
	ldr	r5, [pc, #204]	@ 0x080099B4
	movs	r0, #0
	strb	r0, [r5, #0]
	ldr	r4, [pc, #204]	@ 0x080099B8
	movs	r0, #16
	strb	r0, [r4, #0]
	bl	sub_080020b8	@ 0x080020B8
	bl	sub_08002db4	@ 0x08002DB4
	movs	r7, #0
	ldr	r0, [pc, #192]	@ 0x080099BC
	mov	sl, r0
	mov	r8, r4
	mov	r9, r5
	.global	loc_08009902
loc_08009902:
	ldr	r0, [pc, #188]	@ 0x080099C0
	adds	r0, r7, r0
	ldrb	r0, [r0, #0]
	bl	sub_08008c64	@ 0x08008C64
	movs	r0, #237
	movs	r1, #0
	bl	sub_080058e4	@ 0x080058E4
	lsls	r1, r0, #3
	adds	r1, r1, r0
	lsls	r1, r1, #4
	add	r1, sl
	str	r7, [r1, #0]
	movs	r4, #0
	.global	loc_08009920
loc_08009920:
	mov	r1, r9
	strb	r4, [r1, #0]
	movs	r0, #16
	subs	r0, r0, r4
	mov	r3, r8
	strb	r0, [r3, #0]
	movs	r0, #2
	bl	sub_080099c8	@ 0x080099C8
	cmp	r0, #0
	bne.n	loc_08009974	@ 0x08009974
	adds	r4, #1
	cmp	r4, #16
	ble.n	loc_08009920	@ 0x08009920
	ldr	r1, [pc, #132]	@ 0x080099C4
	lsls	r0, r7, #1
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	bl	sub_080099c8	@ 0x080099C8
	cmp	r0, #0
	bne.n	loc_08009974	@ 0x08009974
	cmp	r7, #8
	beq.n	loc_08009974	@ 0x08009974
	movs	r4, #0
	ldr	r6, [pc, #96]	@ 0x080099B4
	movs	r5, #16
	.global	loc_08009956
loc_08009956:
	subs	r0, r5, r4
	strb	r0, [r6, #0]
	mov	r0, r8
	strb	r4, [r0, #0]
	movs	r0, #2
	bl	sub_080099c8	@ 0x080099C8
	cmp	r0, #0
	bne.n	loc_08009974	@ 0x08009974
	adds	r4, #1
	cmp	r4, #16
	ble.n	loc_08009956	@ 0x08009956
	adds	r7, #1
	cmp	r7, #8
	ble.n	loc_08009902	@ 0x08009902
	.global	loc_08009974
loc_08009974:
	bl	sub_08002198	@ 0x08002198
	bl	sub_08002db4	@ 0x08002DB4
	ldr	r4, [pc, #44]	@ 0x080099AC
	ldr	r3, [pc, #48]	@ 0x080099B0
	ldr	r2, [pc, #48]	@ 0x080099B4
	ldr	r1, [pc, #52]	@ 0x080099B8
	movs	r0, #0
	strb	r0, [r1, #0]
	ldrb	r0, [r1, #0]
	strb	r0, [r2, #0]
	ldrb	r0, [r2, #0]
	strb	r0, [r3, #0]
	ldrb	r0, [r3, #0]
	strb	r0, [r4, #0]
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03001ED8
	.word	0x0000E0FF
	.word	gUnk_0300118C
	.word	gUnk_03000040
	.word	gUnk_03000B08
	.word	gUnk_03001EAC
	.word	0x030027A8
	.word	0x08731CDC
	.word	0x08731CE6
	.thumb_func
	.global	sub_080099c8
sub_080099c8:
	.thumb
	push	{r4, r5, lr}
	adds	r5, r0, #0
	movs	r4, #0
	cmp	r4, r5
	bge.n	loc_080099f2	@ 0x080099F2
	.global	loc_080099d2
loc_080099d2:
	ldr	r0, [pc, #16]	@ 0x080099E4
	ldrh	r1, [r0, #0]
	movs	r0, #11
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080099e8	@ 0x080099E8
	movs	r0, #1
	b.n	loc_080099f4	@ 0x080099F4
	movs	r0, r0
	.word	gUnk_03000038
	.global	loc_080099e8
loc_080099e8:
	bl	sub_080022e4	@ 0x080022E4
	adds	r4, #1
	cmp	r4, r5
	blt.n	loc_080099d2	@ 0x080099D2
	.global	loc_080099f2
loc_080099f2:
	movs	r0, #0
	.global	loc_080099f4
loc_080099f4:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_080099fc
sub_080099fc:
	.thumb
	push	{r4, r5, r6, lr}
	ldr	r6, [pc, #124]	@ 0x08009A7C
	ldr	r1, [r6, #0]
	ldr	r0, [pc, #124]	@ 0x08009A80
	str	r0, [r1, #0]
	ldr	r0, [pc, #124]	@ 0x08009A84
	str	r0, [r1, #12]
	.global	loc_08009a0a
loc_08009a0a:
	adds	r1, #66
	movs	r0, #8
	strb	r0, [r1, #0]
	ldr	r1, [r6, #0]
	ldr	r0, [pc, #116]	@ 0x08009A88
	str	r0, [r1, #56]
	adds	r2, r1, #0
	adds	r2, #64
	movs	r0, #128
	lsls	r0, r0, #4
	strh	r0, [r2, #0]
	movs	r0, #192
	lsls	r0, r0, #14
	str	r0, [r1, #76]
	movs	r0, #240
	lsls	r0, r0, #15
	str	r0, [r1, #80]
	ldr	r2, [pc, #92]	@ 0x08009A8C
	ldr	r0, [r1, #24]
	lsls	r0, r0, #2
	adds	r0, r0, r2
	ldr	r4, [r0, #0]
	ldr	r1, [r4, #8]
	ldr	r2, [pc, #84]	@ 0x08009A90
	ldrh	r3, [r4, #0]
	lsls	r3, r3, #5
	movs	r0, #2
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [r4, #12]
	ldr	r5, [pc, #76]	@ 0x08009A94
	adds	r1, r5, #0
	bl	LZ77UnCompVram	@ 0x080CFA6C
	ldr	r2, [pc, #72]	@ 0x08009A98
	ldrh	r3, [r4, #2]
	lsls	r3, r3, #5
	movs	r0, #3
	adds	r1, r5, #0
	bl	sub_080017e4	@ 0x080017E4
	ldr	r1, [r6, #0]
	ldr	r0, [r1, #24]
	strh	r0, [r1, #60]
	ldr	r1, [pc, #56]	@ 0x08009A9C
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	adds	r0, #67
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	bl	TaskDispatchTrampoline	@ 0x080CFDD4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	sub_080059d8+1
	.word	sub_08005ca0+1
	.word	0x087555D8
	.word	0x087555FC
	.word	gUnk_03001470
	.word	gUnk_02020000
	.word	gUnk_06010000
	.word	0x08731CE6
	.thumb_func
	.global	sub_08009aa0
sub_08009aa0:
	.thumb
	ldr	r1, [pc, #12]	@ 0x08009AB0
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr	r1, [pc, #12]	@ 0x08009AB4
	movs	r0, #0
	str	r0, [r1, #0]
	bx	lr
	movs	r0, r0
	.word	gUnk_02006030
	.word	gUnk_03000014
	.thumb_func
	.global	sub_08009ab8
sub_08009ab8:
	.thumb
	push	{lr}
	ldr	r1, [pc, #20]	@ 0x08009AD0
	movs	r0, #1
	strb	r0, [r1, #0]
	ldr	r1, [pc, #16]	@ 0x08009AD4
	ldr	r0, [pc, #20]	@ 0x08009AD8
	str	r0, [r1, #0]
	bl	_call_via_r0	@ 0x080CFC30
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_02006030
	.word	gUnk_03000014
	.word	sub_0800aad0+1
	.thumb_func
	.global	sub_08009adc
sub_08009adc:
	.thumb
	push	{r4, r5, r6, lr}
	ldr	r0, [pc, #52]	@ 0x08009B14
	movs	r1, #0
	strb	r1, [r0, #0]
	ldr	r0, [pc, #48]	@ 0x08009B18
	strb	r1, [r0, #0]
	movs	r4, #0
	movs	r6, #0
	ldr	r5, [pc, #44]	@ 0x08009B1C
	.global	loc_08009aee
loc_08009aee:
	strh	r6, [r5, #0]
	adds	r0, r4, #0
	bl	sub_0800aa94	@ 0x0800AA94
	adds	r5, #2
	adds	r4, #1
	cmp	r4, #1
	ble.n	loc_08009aee	@ 0x08009AEE
	ldr	r2, [pc, #32]	@ 0x08009B20
	ldr	r1, [pc, #32]	@ 0x08009B24
	movs	r0, #0
	strh	r0, [r1, #0]
	strh	r0, [r2, #0]
	ldr	r1, [pc, #28]	@ 0x08009B28
	strb	r0, [r1, #0]
	strb	r0, [r1, #1]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.word	gUnk_02006014
	.word	gUnk_0200617C
	.word	gUnk_02007FBC
	.word	gUnk_02004B68
	.word	gUnk_02007D30
	.word	gUnk_020055F0
	.thumb_func
	.global	sub_08009b2c
sub_08009b2c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	adds	r6, r0, #0
	bl	sub_0800b37c	@ 0x0800B37C
	ldr	r0, [pc, #136]	@ 0x08009BC0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08009b44	@ 0x08009B44
	bl	sub_0800ab3c	@ 0x0800AB3C
	.global	loc_08009b44
loc_08009b44:
	ldr	r0, [pc, #124]	@ 0x08009BC4
	lsls	r5, r6, #1
	adds	r4, r5, r0
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	cmp	r0, #0
	bne.n	loc_08009b60	@ 0x08009B60
	ldr	r0, [pc, #116]	@ 0x08009BC8
	adds	r0, r5, r0
	movs	r1, #0
	ldrsh	r2, [r0, r1]
	cmp	r2, #0
	bne.n	loc_08009b60	@ 0x08009B60
	b.n	loc_08009c94	@ 0x08009C94
	.global	loc_08009b60
loc_08009b60:
	ldr	r0, [pc, #104]	@ 0x08009BCC
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r0, [pc, #104]	@ 0x08009BD0
	strb	r1, [r0, #0]
	bl	sub_0800b428	@ 0x0800B428
	adds	r0, r6, #0
	bl	sub_0800ab64	@ 0x0800AB64
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	bl	sub_0800abc0	@ 0x0800ABC0
	ldr	r0, [pc, #72]	@ 0x08009BC8
	adds	r0, r5, r0
	ldrh	r0, [r0, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #19
	bl	sub_0800ac38	@ 0x0800AC38
	ldr	r0, [pc, #72]	@ 0x08009BD4
	ldrb	r1, [r0, #0]
	asrs	r1, r6
	movs	r7, #1
	ands	r1, r7
	cmp	r1, #0
	beq.n	loc_08009be4	@ 0x08009BE4
	ldr	r4, [pc, #60]	@ 0x08009BD8
	adds	r4, r5, r4
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	adds	r1, r6, #0
	bl	sub_0800a130	@ 0x0800A130
	movs	r0, #0
	ldrsh	r4, [r4, r0]
	.global	loc_08009baa
loc_08009baa:
	cmp	r4, #0
	bne.n	loc_08009bf6	@ 0x08009BF6
	ldr	r0, [pc, #44]	@ 0x08009BDC
	strb	r4, [r0, #0]
	ldr	r0, [pc, #44]	@ 0x08009BE0
	strh	r4, [r0, #0]
	movs	r0, #0
	bl	sub_0800b0a4	@ 0x0800B0A4
	b.n	loc_08009c22	@ 0x08009C22
	movs	r0, r0
	.word	gUnk_03002444
	.word	gUnk_02007D48
	.word	gUnk_02005588
	.word	gUnk_02006014
	.word	gUnk_0200617C
	.word	gUnk_03002340
	.word	gUnk_02004B50
	.word	gUnk_020061D4
	.word	gUnk_0200801C
	.global	loc_08009be4
loc_08009be4:
	ldr	r0, [pc, #32]	@ 0x08009C08
	adds	r0, r6, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	beq.n	loc_08009c14	@ 0x08009C14
	movs	r0, #26
	adds	r1, r6, #0
	bl	sub_0800a130	@ 0x0800A130
	.global	loc_08009bf6
loc_08009bf6:
	ldr	r0, [pc, #20]	@ 0x08009C0C
	strb	r7, [r0, #0]
	ldr	r1, [pc, #20]	@ 0x08009C10
	movs	r0, #16
	strh	r0, [r1, #0]
	movs	r0, #2
	bl	sub_0800b0a4	@ 0x0800B0A4
	b.n	loc_08009c22	@ 0x08009C22
	.word	0x0300560C
	.word	gUnk_020061D4
	.word	gUnk_0200801C
	.global	loc_08009c14
loc_08009c14:
	ldr	r0, [pc, #32]	@ 0x08009C38
	strb	r1, [r0, #0]
	ldr	r0, [pc, #32]	@ 0x08009C3C
	strh	r1, [r0, #0]
	movs	r0, #0
	bl	sub_0800b0a4	@ 0x0800B0A4
	.global	loc_08009c22
loc_08009c22:
	ldr	r0, [pc, #28]	@ 0x08009C40
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08009c48	@ 0x08009C48
	ldr	r0, [pc, #24]	@ 0x08009C44
	lsls	r1, r6, #2
	adds	r1, r1, r0
	ldr	r0, [r1, #0]
	bl	sub_0800ad68	@ 0x0800AD68
	b.n	loc_08009c4e	@ 0x08009C4E
	.word	gUnk_020061D4
	.word	gUnk_0200801C
	.word	gUnk_02006030
	.word	gUnk_02006020
	.global	loc_08009c48
loc_08009c48:
	ldr	r0, [pc, #48]	@ 0x08009C7C
	bl	sub_0800af40	@ 0x0800AF40
	.global	loc_08009c4e
loc_08009c4e:
	ldr	r1, [pc, #48]	@ 0x08009C80
	movs	r0, #0
	strb	r0, [r1, #0]
	movs	r4, #0
	movs	r6, #0
	ldr	r5, [pc, #40]	@ 0x08009C84
	.global	loc_08009c5a
loc_08009c5a:
	strh	r6, [r5, #0]
	adds	r0, r4, #0
	bl	sub_0800aa94	@ 0x0800AA94
	adds	r5, #2
	adds	r4, #1
	cmp	r4, #1
	ble.n	loc_08009c5a	@ 0x08009C5A
	ldr	r2, [pc, #28]	@ 0x08009C88
	ldr	r1, [pc, #28]	@ 0x08009C8C
	movs	r0, #0
	strh	r0, [r1, #0]
	strh	r0, [r2, #0]
	ldr	r1, [pc, #24]	@ 0x08009C90
	strb	r0, [r1, #0]
	strb	r0, [r1, #1]
	b.n	loc_08009c9e	@ 0x08009C9E
	.word	gUnk_02006068
	.word	gUnk_0200B028
	.word	gUnk_02007FBC
	.word	gUnk_02004B68
	.word	gUnk_02007D30
	.word	gUnk_020055F0
	.global	loc_08009c94
loc_08009c94:
	ldr	r0, [pc, #16]	@ 0x08009CA8
	movs	r1, #2
	strb	r1, [r0, #0]
	ldr	r0, [pc, #16]	@ 0x08009CAC
	strb	r2, [r0, #0]
	.global	loc_08009c9e
loc_08009c9e:
	bl	sub_0800b3f8	@ 0x0800B3F8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_02006014
	.word	gUnk_0200617C
	.thumb_func
	.global	sub_08009cb0
sub_08009cb0:
	.thumb
	push	{r4, r5, r6, r7, lr}
	adds	r6, r0, #0
	ldr	r0, [pc, #120]	@ 0x08009D30
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r0, [pc, #120]	@ 0x08009D34
	strb	r1, [r0, #0]
	bl	sub_0800b3a8	@ 0x0800B3A8
	bl	sub_0800b428	@ 0x0800B428
	ldr	r0, [pc, #112]	@ 0x08009D38
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08009cd6	@ 0x08009CD6
	bl	sub_0800ab3c	@ 0x0800AB3C
	.global	loc_08009cd6
loc_08009cd6:
	adds	r0, r6, #0
	bl	sub_0800ab64	@ 0x0800AB64
	ldr	r0, [pc, #92]	@ 0x08009D3C
	lsls	r5, r6, #1
	adds	r0, r5, r0
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_0800abc0	@ 0x0800ABC0
	ldr	r0, [pc, #84]	@ 0x08009D40
	adds	r0, r5, r0
	ldrh	r0, [r0, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #19
	bl	sub_0800ac38	@ 0x0800AC38
	ldr	r0, [pc, #72]	@ 0x08009D44
	ldrb	r0, [r0, #0]
	asrs	r0, r6
	movs	r7, #1
	ands	r0, r7
	cmp	r0, #0
	beq.n	loc_08009d6c	@ 0x08009D6C
	ldr	r4, [pc, #64]	@ 0x08009D48
	adds	r4, r5, r4
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	adds	r1, r6, #0
	bl	sub_0800a130	@ 0x0800A130
	movs	r0, #0
	ldrsh	r4, [r4, r0]
	cmp	r4, #0
	beq.n	loc_08009d54	@ 0x08009D54
	.word	0x7007480B
	ldr	r1, [pc, #44]	@ 0x08009D50
	movs	r0, #16
	strh	r0, [r1, #0]
	movs	r0, #2
	bl	sub_0800b0a4	@ 0x0800B0A4
	b.n	loc_08009d74	@ 0x08009D74
	movs	r0, r0
	.word	gUnk_02006014
	.word	gUnk_0200617C
	.word	gUnk_03002444
	.word	gUnk_02007D48
	.word	gUnk_02005588
	.word	gUnk_03002340
	.word	gUnk_02004B50
	.word	gUnk_020061D4
	.word	gUnk_0200801C
	.global	loc_08009d54
loc_08009d54:
	ldr	r0, [pc, #12]	@ 0x08009D64
	strb	r4, [r0, #0]
	ldr	r0, [pc, #12]	@ 0x08009D68
	strh	r4, [r0, #0]
	movs	r0, #0
	bl	sub_0800b0a4	@ 0x0800B0A4
	b.n	loc_08009d74	@ 0x08009D74
	.word	gUnk_020061D4
	.word	gUnk_0200801C
	.global	loc_08009d6c
loc_08009d6c:
	movs	r0, #26
	adds	r1, r6, #0
	bl	sub_0800a0dc	@ 0x0800A0DC
	.global	loc_08009d74
loc_08009d74:
	ldr	r0, [pc, #28]	@ 0x08009D94
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08009dac	@ 0x08009DAC
	ldr	r0, [pc, #24]	@ 0x08009D98
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08009da0	@ 0x08009DA0
	ldr	r0, [pc, #20]	@ 0x08009D9C
	lsls	r1, r6, #2
	adds	r1, r1, r0
	ldr	r0, [r1, #0]
	bl	sub_0800ad68	@ 0x0800AD68
	b.n	loc_08009dc6	@ 0x08009DC6
	movs	r0, r0
	.word	gUnk_0200B028
	.word	gUnk_02006030
	.word	gUnk_02006020
	.global	loc_08009da0
loc_08009da0:
	ldr	r0, [pc, #4]	@ 0x08009DA8
	bl	sub_0800af40	@ 0x0800AF40
	b.n	loc_08009dc6	@ 0x08009DC6
	.word	gUnk_02006068
	.global	loc_08009dac
loc_08009dac:
	bl	sub_0800a280	@ 0x0800A280
	ldr	r1, [pc, #56]	@ 0x08009DEC
	ldr	r0, [pc, #60]	@ 0x08009DF0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #3
	adds	r0, r0, r1
	movs	r1, #4
	ldrsh	r0, [r0, r1]
	bl	sub_0800b130	@ 0x0800B130
	.global	loc_08009dc6
loc_08009dc6:
	ldr	r1, [pc, #44]	@ 0x08009DF4
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r0, #0
	beq.n	loc_08009e08	@ 0x08009E08
	cmp	r0, #2
	bne.n	loc_08009dfc	@ 0x08009DFC
	ldr	r0, [pc, #32]	@ 0x08009DF8
	adds	r0, #4
	adds	r0, r6, r0
	ldrb	r0, [r0, #0]
	lsrs	r0, r0, #4
	ldrb	r1, [r1, #0]
	lsls	r1, r1, #24
	asrs	r1, r1, #24
	bl	sub_0800b230	@ 0x0800B230
	b.n	loc_08009e08	@ 0x08009E08
	movs	r0, r0
	.word	gUnk_02006A00
	.word	gUnk_02004B58
	.word	gUnk_020055F0
	.word	gUnk_02005E00
	.global	loc_08009dfc
loc_08009dfc:
	ldrb	r1, [r1, #0]
	lsls	r1, r1, #24
	asrs	r1, r1, #24
	adds	r0, r6, #0
	bl	sub_0800b230	@ 0x0800B230
	.global	loc_08009e08
loc_08009e08:
	bl	sub_0800b3f8	@ 0x0800B3F8
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.thumb_func
	.global	sub_08009e14
sub_08009e14:
	.thumb
	ldr	r1, [pc, #4]	@ 0x08009E1C
	movs	r0, #0
	strb	r0, [r1, #0]
	bx	lr
	.word	gUnk_0200617C
	.thumb_func
	.global	sub_08009e20
sub_08009e20:
	.thumb
	ldr	r1, [pc, #4]	@ 0x08009E28
	movs	r0, #1
	strb	r0, [r1, #0]
	bx	lr
	.word	gUnk_0200617C
	.thumb_func
	.global	sub_08009e2c
sub_08009e2c:
	.thumb
	.word	0x4909B500
	movs	r0, #2
	strb	r0, [r1, #0]
	ldr	r1, [pc, #32]	@ 0x08009E58
	movs	r0, #0
	strb	r0, [r1, #0]
	bl	sub_0800b3a8	@ 0x0800B3A8
	ldr	r0, [pc, #28]	@ 0x08009E5C
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08009e4e	@ 0x08009E4E
	bl	sub_0800ab3c	@ 0x0800AB3C
	.global	loc_08009e4e
loc_08009e4e:
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_02006014
	.word	gUnk_0200617C
	.word	gUnk_03002444
	.thumb_func
	.global	sub_08009e60
sub_08009e60:
	.thumb
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r5, r1, #0
	cmp	r5, #3
	bhi.n	loc_08009eaa	@ 0x08009EAA
	ldr	r1, [pc, #24]	@ 0x08009E84
	lsls	r3, r5, #1
	adds	r4, r3, r1
	ldrh	r2, [r4, #0]
	adds	r2, r2, r6
	strh	r2, [r4, #0]
	lsls	r2, r2, #16
	asrs	r2, r2, #16
	adds	r6, r1, #0
	cmp	r2, #99
	ble.n	loc_08009e88	@ 0x08009E88
	movs	r1, #99
	b.n	loc_08009e8e	@ 0x08009E8E
	.word	gUnk_02007D48
	.global	loc_08009e88
loc_08009e88:
	cmp	r2, #0
	bge.n	loc_08009e90	@ 0x08009E90
	movs	r1, #0
	.global	loc_08009e8e
loc_08009e8e:
	strh	r1, [r4, #0]
	.global	loc_08009e90
loc_08009e90:
	ldr	r1, [pc, #28]	@ 0x08009EB0
	ldrh	r1, [r1, #0]
	cmp	r5, r1
	bne.n	loc_08009eaa	@ 0x08009EAA
	ldr	r1, [pc, #24]	@ 0x08009EB4
	ldrb	r1, [r1, #0]
	cmp	r1, #1
	bne.n	loc_08009eaa	@ 0x08009EAA
	adds	r0, r3, r6
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_0800abc0	@ 0x0800ABC0
	.global	loc_08009eaa
loc_08009eaa:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	.word	gUnk_03002360
	.word	gUnk_02006014
	.thumb_func
	.global	sub_08009eb8
sub_08009eb8:
	.thumb
	adds	r3, r0, #0
	cmp	r1, #3
	bhi.n	loc_08009ee4	@ 0x08009EE4
	ldr	r2, [pc, #24]	@ 0x08009ED8
	lsls	r1, r1, #1
	adds	r2, r1, r2
	ldrh	r1, [r2, #0]
	adds	r1, r1, r3
	strh	r1, [r2, #0]
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	cmp	r1, #99
	ble.n	loc_08009edc	@ 0x08009EDC
	movs	r1, #99
	b.n	loc_08009ee2	@ 0x08009EE2
	movs	r0, r0
	.word	gUnk_02007D48
	.global	loc_08009edc
loc_08009edc:
	cmp	r1, #0
	bge.n	loc_08009ee4	@ 0x08009EE4
	movs	r1, #0
	.global	loc_08009ee2
loc_08009ee2:
	strh	r1, [r2, #0]
	.global	loc_08009ee4
loc_08009ee4:
	bx	lr
	movs	r0, r0
	.thumb_func
	.global	sub_08009ee8
sub_08009ee8:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r3, r0, #0
	adds	r4, r1, #0
	cmp	r4, #3
	bhi.n	loc_08009fb0	@ 0x08009FB0
	ldr	r0, [pc, #36]	@ 0x08009F1C
	lsls	r1, r4, #1
	adds	r2, r1, r0
	movs	r0, #0
	ldrsh	r7, [r2, r0]
	mov	r8, r1
	cmp	r3, #0
	ble.n	loc_08009f2e	@ 0x08009F2E
	adds	r0, r7, r3
	ldr	r5, [pc, #20]	@ 0x08009F20
	movs	r6, #0
	ldrsh	r1, [r5, r6]
	cmp	r0, r1
	ble.n	loc_08009f24	@ 0x08009F24
	subs	r6, r1, r7
	ldrh	r0, [r5, #0]
	strh	r0, [r2, #0]
	b.n	loc_08009f74	@ 0x08009F74
	movs	r0, r0
	.word	gUnk_02005588
	.word	gUnk_02005580
	.global	loc_08009f24
loc_08009f24:
	adds	r6, r3, #0
	ldrh	r0, [r2, #0]
	adds	r0, r0, r6
	strh	r0, [r2, #0]
	b.n	loc_08009f74	@ 0x08009F74
	.global	loc_08009f2e
loc_08009f2e:
	adds	r0, r7, r3
	cmp	r0, #0
	bge.n	loc_08009f3a	@ 0x08009F3A
	negs	r6, r7
	movs	r0, #0
	b.n	loc_08009f40	@ 0x08009F40
	.global	loc_08009f3a
loc_08009f3a:
	adds	r6, r3, #0
	ldrh	r0, [r2, #0]
	adds	r0, r0, r6
	.global	loc_08009f40
loc_08009f40:
	strh	r0, [r2, #0]
	ldr	r0, [pc, #20]	@ 0x08009F58
	add	r0, r8
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #0
	bne.n	loc_08009f60	@ 0x08009F60
	ldr	r1, [pc, #12]	@ 0x08009F5C
	movs	r0, #1
	strb	r0, [r1, #0]
	.word	0x0000E00E
	.word	gUnk_02005588
	.word	gUnk_03001F34
	.global	loc_08009f60
loc_08009f60:
	cmp	r0, #8
	bne.n	loc_08009f74	@ 0x08009F74
	ldr	r0, [pc, #84]	@ 0x08009FBC
	ldrh	r0, [r0, #0]
	cmp	r0, r4
	bne.n	loc_08009f74	@ 0x08009F74
	movs	r0, #131
	lsls	r0, r0, #1
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_08009f74
loc_08009f74:
	ldr	r0, [pc, #72]	@ 0x08009FC0
	lsls	r2, r4, #3
	adds	r1, r2, r4
	lsls	r1, r1, #4
	adds	r1, r1, r0
	ldr	r0, [pc, #68]	@ 0x08009FC4
	add	r0, r8
	ldrh	r0, [r0, #0]
	adds	r1, #120
	strh	r0, [r1, #0]
	ldr	r0, [pc, #48]	@ 0x08009FBC
	adds	r5, r2, #0
	ldrh	r0, [r0, #0]
	cmp	r4, r0
	bne.n	loc_08009fa2	@ 0x08009FA2
	ldr	r0, [pc, #52]	@ 0x08009FC8
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne.n	loc_08009fa2	@ 0x08009FA2
	asrs	r0, r7, #3
	asrs	r1, r6, #3
	bl	sub_0800acbc	@ 0x0800ACBC
	.global	loc_08009fa2
loc_08009fa2:
	ldr	r0, [pc, #28]	@ 0x08009FC0
	adds	r1, r5, r4
	lsls	r1, r1, #4
	adds	r1, r1, r0
	adds	r1, #120
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	.global	loc_08009fb0
loc_08009fb0:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002360
	.word	gUnk_03002790
	.word	gUnk_02005588
	.word	gUnk_02006014
	.thumb_func
	.global	sub_08009fcc
sub_08009fcc:
	.thumb
	push	{r4, lr}
	adds	r3, r0, #0
	adds	r4, r1, #0
	cmp	r2, #3
	bhi.n	loc_08009ff6	@ 0x08009FF6
	ldr	r0, [pc, #36]	@ 0x08009FFC
	lsls	r1, r2, #1
	adds	r0, r1, r0
	strh	r3, [r0, #0]
	ldr	r0, [pc, #32]	@ 0x0800A000
	adds	r1, r1, r0
	strh	r4, [r1, #0]
	movs	r0, #116
	muls	r0, r2
	ldr	r1, [pc, #24]	@ 0x0800A004
	adds	r0, r0, r1
	strb	r3, [r0, #13]
	strb	r4, [r0, #14]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	.global	loc_08009ff6
loc_08009ff6:
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_02004B50
	.word	gUnk_0200AF18
	.word	gUnk_03002170
	.thumb_func
	.global	sub_0800a008
sub_0800a008:
	.thumb
	push	{r4, r5, lr}
	adds	r3, r0, #0
	adds	r5, r1, #0
	cmp	r2, #3
	bhi.n	loc_0800a03a	@ 0x0800A03A
	ldr	r0, [pc, #44]	@ 0x0800A040
	lsls	r1, r2, #1
	adds	r0, r1, r0
	strh	r3, [r0, #0]
	ldr	r0, [pc, #40]	@ 0x0800A044
	adds	r1, r1, r0
	strh	r5, [r1, #0]
	movs	r0, #116
	adds	r4, r2, #0
	muls	r4, r0
	ldr	r0, [pc, #32]	@ 0x0800A048
	adds	r4, r4, r0
	strb	r3, [r4, #13]
	strb	r5, [r4, #14]
	adds	r0, r3, #0
	adds	r1, r2, #0
	bl	sub_0800a130	@ 0x0800A130
	movs	r0, #13
	ldrsb	r0, [r4, r0]
	.global	loc_0800a03a
loc_0800a03a:
	pop	{r4, r5}
	pop	{r1}
	bx	r1
	.word	gUnk_02004B50
	.word	gUnk_0200AF18
	.word	gUnk_03002170
	.thumb_func
	.global	sub_0800a04c
sub_0800a04c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	adds	r6, r0, #0
	adds	r5, r1, #0
	cmp	r5, #3
	bhi.n	loc_0800a092	@ 0x0800A092
	ldr	r0, [pc, #64]	@ 0x0800A098
	lsls	r2, r5, #2
	adds	r3, r2, r0
	ldr	r4, [r3, #0]
	ldr	r1, [pc, #60]	@ 0x0800A09C
	adds	r7, r0, #0
	cmp	r4, r1
	bgt.n	loc_0800a072	@ 0x0800A072
	adds	r0, r4, r6
	str	r0, [r3, #0]
	adds	r1, #1
	cmp	r0, r1
	ble.n	loc_0800a072	@ 0x0800A072
	str	r1, [r3, #0]
	.global	loc_0800a072
loc_0800a072:
	ldr	r0, [pc, #44]	@ 0x0800A0A0
	ldrh	r0, [r0, #0]
	cmp	r0, r5
	bne.n	loc_0800a092	@ 0x0800A092
	ldr	r0, [pc, #40]	@ 0x0800A0A4
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0800a092	@ 0x0800A092
	ldr	r0, [pc, #36]	@ 0x0800A0A8
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0800a092	@ 0x0800A092
	adds	r0, r2, r7
	ldr	r0, [r0, #0]
	bl	sub_0800ad68	@ 0x0800AD68
	.global	loc_0800a092
loc_0800a092:
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_02006020
	.word	0x05F5E0FE
	.word	gUnk_03002360
	.word	gUnk_0200B028
	.word	gUnk_02006030
	.thumb_func
	.global	sub_0800a0ac
sub_0800a0ac:
	.thumb
	adds	r3, r0, #0
	cmp	r1, #3
	bhi.n	loc_0800a0cc	@ 0x0800A0CC
	ldr	r0, [pc, #28]	@ 0x0800A0D0
	lsls	r1, r1, #2
	adds	r1, r1, r0
	ldr	r2, [r1, #0]
	ldr	r0, [pc, #24]	@ 0x0800A0D4
	cmp	r2, r0
	bgt.n	loc_0800a0cc	@ 0x0800A0CC
	adds	r0, r2, r3
	str	r0, [r1, #0]
	ldr	r2, [pc, #16]	@ 0x0800A0D8
	cmp	r0, r2
	ble.n	loc_0800a0cc	@ 0x0800A0CC
	str	r2, [r1, #0]
	.global	loc_0800a0cc
loc_0800a0cc:
	bx	lr
	movs	r0, r0
	.word	gUnk_02006020
	.word	0x05F5E0FE
	.word	0x05F5E0FF
