@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24, chunk 1/2: 0x08039C24-0x0803AA40 (thumb_code, 0xE1C bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08039C24 sub_08039c24

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24:
	.thumb_func
	.global	sub_08039c24
sub_08039c24:
	.thumb
	push	{r4, r5, r6, r7, lr}
	ldr	r2, [pc, #272]	@ 0x08039D38
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrb	r0, [r1, #4]
	strb	r0, [r1, #5]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #19
	strb	r1, [r0, #4]
	ldr	r0, [r2, #0]
	strb	r1, [r0, #21]
	ldr	r0, [r2, #0]
	adds	r0, #67
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #240]	@ 0x08039D3C
	strh	r0, [r1, #60]
	bl	sub_080224b0	@ 0x080224B0
	ldr	r0, [pc, #236]	@ 0x08039D40
	ldr	r1, [pc, #236]	@ 0x08039D44
	ldr	r1, [r1, #0]
	bl	sub_08021c74	@ 0x08021C74
	ldr	r0, [pc, #232]	@ 0x08039D48
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08039c9e	@ 0x08039C9E
	bl	sub_0803f6e0	@ 0x0803F6E0
	ldr	r1, [pc, #224]	@ 0x08039D4C
	ldrh	r0, [r1, #0]
	cmp	r0, #1
	bls.n	loc_08039c9e	@ 0x08039C9E
	ldr	r0, [pc, #220]	@ 0x08039D50
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne.n	loc_08039c9e	@ 0x08039C9E
	movs	r5, #0
	ldrh	r1, [r1, #0]
	cmp	r5, r1
	bge.n	loc_08039c9e	@ 0x08039C9E
	ldr	r4, [pc, #208]	@ 0x08039D54
	.global	loc_08039c82
loc_08039c82:
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	cmp	r0, #0
	bne.n	loc_08039c92	@ 0x08039C92
	movs	r0, #4
	adds	r1, r5, #0
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_08039c92
loc_08039c92:
	adds	r4, #2
	adds	r5, #1
	ldr	r0, [pc, #180]	@ 0x08039D4C
	ldrh	r0, [r0, #0]
	cmp	r5, r0
	blt.n	loc_08039c82	@ 0x08039C82
	.global	loc_08039c9e
loc_08039c9e:
	ldr	r2, [pc, #152]	@ 0x08039D38
	ldr	r1, [r2, #0]
	movs	r0, #0
	str	r0, [r1, #40]
	ldr	r0, [r1, #44]
	cmp	r0, #1
	beq.n	loc_08039cb0	@ 0x08039CB0
	cmp	r0, #3
	bne.n	loc_08039cc6	@ 0x08039CC6
	.global	loc_08039cb0
loc_08039cb0:
	adds	r1, #67
	movs	r0, #255
	strb	r0, [r1, #0]
	ldr	r1, [r2, #0]
	adds	r0, r1, #0
	adds	r0, #72
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	subs	r0, #10
	lsls	r0, r0, #16
	str	r0, [r1, #76]
	.global	loc_08039cc6
loc_08039cc6:
	ldr	r1, [pc, #144]	@ 0x08039D58
	ldrh	r0, [r1, #0]
	cmp	r0, #0
	beq.n	loc_08039cdc	@ 0x08039CDC
	adds	r4, r1, #0
	.global	loc_08039cd0
loc_08039cd0:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrh	r0, [r4, #0]
	cmp	r0, #0
	bne.n	loc_08039cd0	@ 0x08039CD0
	.global	loc_08039cdc
loc_08039cdc:
	ldr	r5, [pc, #88]	@ 0x08039D38
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #44]
	cmp	r0, #0
	bne.n	loc_08039cec	@ 0x08039CEC
	bl	sub_080264b0	@ 0x080264B0
	adds	r7, r0, #0
	.global	loc_08039cec
loc_08039cec:
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r4, [r5, #0]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08039d04	@ 0x08039D04
	b.n	loc_08039e64	@ 0x08039E64
	.global	loc_08039d04
loc_08039d04:
	ldr	r2, [pc, #84]	@ 0x08039D5C
	adds	r3, r4, #0
	adds	r3, #136
	ldr	r0, [r3, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #2
	adds	r0, r0, r2
	ldrh	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #23
	bhi.n	loc_08039dc4	@ 0x08039DC4
	lsls	r0, r0, #2
	ldr	r1, [pc, #44]	@ 0x08039D60
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	gUnk_03002490
	.word	0x0000FFFF
	.word	gUnk_0873CB1C
	.word	gCurTaskIdx
	.word	gUnk_020055C4
	.word	gUnk_030023AC
	.word	gUnk_0200AF00
	.word	gUnk_02005588
	.word	gUnk_03001E90
	.word	gUnk_0873D632
	.word	0x08039D64
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #784]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	ldr	r5, [sp, #976]
	lsrs	r3, r0, #32
	.global	loc_08039dc4
loc_08039dc4:
	ldr	r4, [pc, #40]	@ 0x08039DF0
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	b.n	loc_08039e46	@ 0x08039E46
	movs	r0, r0
	.word	gUnk_03002490
	ldr	r4, [pc, #104]	@ 0x08039E60
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	.global	loc_08039e46
loc_08039e46:
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_08039ea8	@ 0x08039EA8
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_08039e64
loc_08039e64:
	movs	r0, #1
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r5, #0]
	adds	r1, #70
	strh	r0, [r1, #0]
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r5, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r5, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r5, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_08039ea8
loc_08039ea8:
	ldr	r0, [pc, #32]	@ 0x08039ECC
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08039eb6	@ 0x08039EB6
	cmp	r0, #1
	bne.n	loc_08039eb6	@ 0x08039EB6
	b.n	loc_08039fe0	@ 0x08039FE0
	.global	loc_08039eb6
loc_08039eb6:
	ldr	r0, [pc, #24]	@ 0x08039ED0
	ldr	r0, [r0, #0]
	ldr	r0, [r0, #44]
	cmp	r0, #1
	beq.n	loc_08039ef8	@ 0x08039EF8
	cmp	r0, #1
	bgt.n	loc_08039ed4	@ 0x08039ED4
	cmp	r0, #0
	beq.n	loc_08039ede	@ 0x08039EDE
	b.n	loc_08039f10	@ 0x08039F10
	movs	r0, r0
	.word	gUnk_0200AF00
	.word	gUnk_03002490
	.global	loc_08039ed4
loc_08039ed4:
	cmp	r0, #2
	beq.n	loc_08039ede	@ 0x08039EDE
	cmp	r0, #3
	beq.n	loc_08039ef8	@ 0x08039EF8
	b.n	loc_08039f10	@ 0x08039F10
	.global	loc_08039ede
loc_08039ede:
	movs	r0, #10
	movs	r1, #9
	bl	sub_08040b40	@ 0x08040B40
	ldr	r0, [pc, #12]	@ 0x08039EF4
	ldr	r2, [r0, #0]
	ldr	r1, [r2, #44]
	lsls	r1, r1, #13
	ldr	r0, [r2, #84]
	adds	r0, r0, r1
	b.n	loc_08039f0e	@ 0x08039F0E
	.word	gUnk_03002490
	.global	loc_08039ef8
loc_08039ef8:
	movs	r0, #10
	movs	r1, #10
	bl	sub_08040b40	@ 0x08040B40
	ldr	r0, [pc, #64]	@ 0x08039F44
	ldr	r2, [r0, #0]
	ldr	r1, [r2, #44]
	subs	r1, #1
	lsls	r1, r1, #13
	ldr	r0, [r2, #84]
	subs	r0, r0, r1
	.global	loc_08039f0e
loc_08039f0e:
	str	r0, [r2, #84]
	.global	loc_08039f10
loc_08039f10:
	ldr	r4, [pc, #48]	@ 0x08039F44
	ldr	r3, [r4, #0]
	adds	r0, r3, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08039f4c	@ 0x08039F4C
	ldr	r2, [pc, #36]	@ 0x08039F48
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #4
	adds	r0, r0, r2
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	b.n	loc_08039f58	@ 0x08039F58
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_0873D632
	.global	loc_08039f4c
loc_08039f4c:
	movs	r0, #2
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r4, #0]
	adds	r1, #70
	strh	r0, [r1, #0]
	.global	loc_08039f58
loc_08039f58:
	ldr	r4, [pc, #128]	@ 0x08039FDC
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #44]
	cmp	r0, #0
	bne.n	loc_08039f88	@ 0x08039F88
	adds	r0, r7, #0
	bl	sub_0802651c	@ 0x0802651C
	.global	loc_08039f88
loc_08039f88:
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	strh	r1, [r0, #0]
	.global	loc_08039f90
loc_08039f90:
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #4
	ble.n	loc_08039f90	@ 0x08039F90
	.global	loc_08039fb0
loc_08039fb0:
	movs	r0, #1
	bl	sub_0803e050	@ 0x0803E050
	ldr	r4, [pc, #36]	@ 0x08039FDC
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #44]
	cmp	r0, #0
	beq.n	loc_08039fc4	@ 0x08039FC4
	bl	loc_0803aa14	@ 0x0803AA14
	.global	loc_08039fc4
loc_08039fc4:
	bl	sub_08026584	@ 0x08026584
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	bl	sub_08040808	@ 0x08040808
	bl	loc_0803aa14	@ 0x0803AA14
	.word	gUnk_03002490
	.global	loc_08039fe0
loc_08039fe0:
	movs	r5, #0
	ldr	r2, [pc, #60]	@ 0x0803A020
	ldr	r6, [pc, #60]	@ 0x0803A024
	ldrh	r0, [r2, #0]
	cmp	r5, r0
	bge.n	loc_0803a004	@ 0x0803A004
	ldr	r0, [pc, #56]	@ 0x0803A028
	movs	r3, #64
	adds	r1, r0, #0
	adds	r1, #66
	.global	loc_08039ff4
loc_08039ff4:
	ldrh	r0, [r1, #0]
	orrs	r0, r3
	strh	r0, [r1, #0]
	adds	r1, #116
	adds	r5, #1
	ldrh	r0, [r2, #0]
	cmp	r5, r0
	blt.n	loc_08039ff4	@ 0x08039FF4
	.global	loc_0803a004
loc_0803a004:
	adds	r4, r6, #0
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #44]
	cmp	r0, #0
	bne.n	loc_0803a010	@ 0x0803A010
	b.n	loc_0803a1c8	@ 0x0803A1C8
	.global	loc_0803a010
loc_0803a010:
	cmp	r0, #1
	beq.n	loc_0803a058	@ 0x0803A058
	cmp	r0, #1
	bgt.n	loc_0803a02c	@ 0x0803A02C
	cmp	r0, #0
	beq.n	loc_0803a036	@ 0x0803A036
	b.n	loc_0803a078	@ 0x0803A078
	movs	r0, r0
	.word	gUnk_030023AC
	.word	gUnk_03002490
	.word	gUnk_03002170
	.global	loc_0803a02c
loc_0803a02c:
	cmp	r0, #2
	beq.n	loc_0803a036	@ 0x0803A036
	cmp	r0, #3
	beq.n	loc_0803a058	@ 0x0803A058
	b.n	loc_0803a078	@ 0x0803A078
	.global	loc_0803a036
loc_0803a036:
	ldr	r4, [pc, #28]	@ 0x0803A054
	ldr	r0, [r4, #0]
	adds	r0, #67
	movs	r1, #1
	strb	r1, [r0, #0]
	movs	r0, #10
	movs	r1, #9
	bl	sub_08040b40	@ 0x08040B40
	ldr	r2, [r4, #0]
	ldr	r1, [r2, #44]
	lsls	r1, r1, #13
	ldr	r0, [r2, #84]
	adds	r0, r0, r1
	b.n	loc_0803a076	@ 0x0803A076
	.word	gUnk_03002490
	.global	loc_0803a058
loc_0803a058:
	ldr	r4, [pc, #80]	@ 0x0803A0AC
	ldr	r0, [r4, #0]
	adds	r0, #67
	movs	r1, #255
	strb	r1, [r0, #0]
	movs	r0, #10
	movs	r1, #10
	bl	sub_08040b40	@ 0x08040B40
	ldr	r2, [r4, #0]
	ldr	r1, [r2, #44]
	subs	r1, #1
	lsls	r1, r1, #13
	ldr	r0, [r2, #84]
	subs	r0, r0, r1
	.global	loc_0803a076
loc_0803a076:
	str	r0, [r2, #84]
	.global	loc_0803a078
loc_0803a078:
	ldr	r4, [pc, #48]	@ 0x0803A0AC
	ldr	r3, [r4, #0]
	adds	r0, r3, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a0b4	@ 0x0803A0B4
	ldr	r2, [pc, #36]	@ 0x0803A0B0
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #4
	adds	r0, r0, r2
	ldrh	r1, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	b.n	loc_0803a0c0	@ 0x0803A0C0
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_0873D632
	.global	loc_0803a0b4
loc_0803a0b4:
	movs	r0, #2
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r4, #0]
	adds	r1, #70
	strh	r0, [r1, #0]
	.global	loc_0803a0c0
loc_0803a0c0:
	ldr	r4, [pc, #112]	@ 0x0803A134
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #108
	movs	r1, #0
	strh	r1, [r0, #0]
	.global	loc_0803a0dc
loc_0803a0dc:
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #5
	ble.n	loc_0803a0dc	@ 0x0803A0DC
	ldr	r0, [pc, #52]	@ 0x0803A134
	ldr	r3, [r0, #0]
	adds	r0, r3, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a13c	@ 0x0803A13C
	ldr	r2, [pc, #40]	@ 0x0803A138
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #13
	.global	loc_0803a118
loc_0803a118:
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #2
	adds	r0, r0, r1
	lsls	r0, r0, #1
	adds	r0, r0, r2
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #1
	.global	loc_0803a12c
loc_0803a12c:
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803a194	@ 0x0803A194
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_0873D0F8
	.global	loc_0803a13c
loc_0803a13c:
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #4
	bne.n	loc_0803a156	@ 0x0803A156
	adds	r1, r3, #0
	adds	r1, #70
	movs	r0, #148
	lsls	r0, r0, #3
	b.n	loc_0803a17e	@ 0x0803A17E
	.global	loc_0803a156
loc_0803a156:
	cmp	r0, #9
	bne.n	loc_0803a168	@ 0x0803A168
	adds	r1, r3, #0
	adds	r1, #70
	ldr	r0, [pc, #4]	@ 0x0803A164
	b.n	loc_0803a17e	@ 0x0803A17E
	movs	r0, r0
	.word	0x000007C1
	.global	loc_0803a168
loc_0803a168:
	cmp	r0, #10
	bne.n	loc_0803a178	@ 0x0803A178
	adds	r1, r3, #0
	adds	r1, #70
	ldr	r0, [pc, #0]	@ 0x0803A174
	b.n	loc_0803a17e	@ 0x0803A17E
	.word	0x000008C1
	.global	loc_0803a178
loc_0803a178:
	adds	r1, r3, #0
	adds	r1, #70
	movs	r0, #221
	.global	loc_0803a17e
loc_0803a17e:
	strh	r0, [r1, #0]
	ldr	r0, [pc, #56]	@ 0x0803A1BC
	ldr	r0, [r0, #0]
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a194
loc_0803a194:
	movs	r0, #1
	bl	sub_0803e050	@ 0x0803E050
	ldr	r0, [pc, #32]	@ 0x0803A1BC
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #24]	@ 0x0803A1C0
	ands	r0, r2
	strh	r0, [r1, #0]
	ldr	r0, [pc, #20]	@ 0x0803A1C4
	ldr	r1, [r0, #0]
	movs	r0, #15
	bl	sub_080055b0	@ 0x080055B0
	bl	loc_0803aa14	@ 0x0803AA14
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x0000FFEF
	.word	gCurTaskIdx
	.global	loc_0803a1c8
loc_0803a1c8:
	ldr	r0, [pc, #104]	@ 0x0803A234
	ldr	r1, [pc, #108]	@ 0x0803A238
	bl	LZ77UnCompWram	@ 0x080CFA70
	ldr	r1, [pc, #104]	@ 0x0803A23C
	ldr	r2, [pc, #108]	@ 0x0803A240
	movs	r3, #128
	lsls	r3, r3, #3
	movs	r0, #3
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [pc, #100]	@ 0x0803A244
	ldr	r0, [r0, #0]
	bl	sub_08027850	@ 0x08027850
	ldr	r4, [r4, #0]
	movs	r0, #128
	lsls	r0, r0, #6
	strh	r0, [r4, #62]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a1fe	@ 0x0803A1FE
	b.n	loc_0803a318	@ 0x0803A318
	.global	loc_0803a1fe
loc_0803a1fe:
	ldr	r2, [pc, #72]	@ 0x0803A248
	adds	r3, r4, #0
	adds	r3, #136
	ldr	r0, [r3, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #6
	adds	r0, r0, r2
	ldrh	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #23
	bhi.n	loc_0803a2b0	@ 0x0803A2B0
	lsls	r0, r0, #2
	ldr	r1, [pc, #32]	@ 0x0803A24C
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
	.word	0x080D07C8
	.word	gUnk_02020000
	.word	0x080DCC68
	.word	0x06014000
	.word	gCurTaskIdx
	.word	gUnk_0873D632
	.word	0x0803A250
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2B0
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.short	0xA2CC
	lsrs	r3, r0, #32
	.global	loc_0803a2b0
loc_0803a2b0:
	movs	r0, #10
	movs	r1, #11
	bl	sub_08040b40	@ 0x08040B40
	ldr	r4, [pc, #12]	@ 0x0803A2C8
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #4
	b.n	loc_0803a2fe	@ 0x0803A2FE
	.word	gUnk_03002490
	movs	r0, #10
	movs	r1, #12
	bl	sub_08040b40	@ 0x08040B40
	ldr	r4, [pc, #60]	@ 0x0803A314
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	.global	loc_0803a2fe
loc_0803a2fe:
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803a344	@ 0x0803A344
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803a318
loc_0803a318:
	movs	r0, #10
	movs	r1, #11
	bl	sub_08040b40	@ 0x08040B40
	movs	r0, #3
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r6, #0]
	adds	r2, r1, #0
	adds	r2, #70
	strh	r0, [r2, #0]
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a344
loc_0803a344:
	movs	r0, #10
	movs	r1, #13
	bl	sub_08040b40	@ 0x08040B40
	ldr	r4, [pc, #52]	@ 0x0803A384
	ldr	r0, [r4, #0]
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a38c	@ 0x0803A38C
	movs	r0, #20
	bl	sub_080413a4	@ 0x080413A4
	ldr	r3, [r4, #0]
	ldr	r2, [pc, #32]	@ 0x0803A388
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #8
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	adds	r3, #70
	strh	r0, [r3, #0]
	b.n	loc_0803a39e	@ 0x0803A39E
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_0873D632
	.global	loc_0803a38c
loc_0803a38c:
	movs	r0, #21
	.short	0xF007
	.global	loc_0803a390
loc_0803a390:
	.short	0xF809
	movs	r0, #4
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r4, #0]
	adds	r1, #70
	strh	r0, [r1, #0]
	.global	loc_0803a39e
loc_0803a39e:
	ldr	r6, [pc, #304]	@ 0x0803A4D0
	ldr	r1, [r6, #0]
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	adds	r0, r7, #0
	bl	sub_0802651c	@ 0x0802651C
	ldr	r1, [r6, #0]
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a3f0
loc_0803a3f0:
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #2
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r6, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	movs	r0, #3
	bl	sub_0803e050	@ 0x0803E050
	bl	sub_0802653c	@ 0x0802653C
	adds	r5, r0, #0
	movs	r0, #2
	bl	sub_080261d4	@ 0x080261D4
	ldr	r0, [r6, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #20
	movs	r2, #0
	bl	sub_0805afac	@ 0x0805AFAC
	ldr	r0, [r6, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #20
	movs	r2, #1
	bl	sub_0805afac	@ 0x0805AFAC
	movs	r0, #14
	bl	sub_0803e650	@ 0x0803E650
	movs	r0, #238
	bl	sub_080031b8	@ 0x080031B8
	ldr	r4, [r6, #0]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a49c	@ 0x0803A49C
	b.n	loc_0803a598	@ 0x0803A598
	.global	loc_0803a49c
loc_0803a49c:
	ldr	r2, [pc, #52]	@ 0x0803A4D4
	adds	r3, r4, #0
	adds	r3, #136
	ldr	r0, [r3, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #10
	adds	r0, r0, r2
	ldrh	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #23
	bhi.n	loc_0803a53c	@ 0x0803A53C
	lsls	r0, r0, #2
	ldr	r1, [pc, #12]	@ 0x0803A4D8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	gUnk_03002490
	.word	gUnk_0873D632
	.word	0x0803A4DC
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA554
	lsrs	r3, r0, #32
	.short	0xA554
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA554
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.global	loc_0803a514
loc_0803a514:
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA53C
	lsrs	r3, r0, #32
	.global	loc_0803a520
loc_0803a520:
	.short	0xA53C
	lsrs	r3, r0, #32
	.global	loc_0803a524
loc_0803a524:
	.short	0xA53C
	lsrs	r3, r0, #32
	.short	0xA554
	lsrs	r3, r0, #32
	.global	loc_0803a52c
loc_0803a52c:
	.short	0xA53C
	lsrs	r3, r0, #32
	.global	loc_0803a530
loc_0803a530:
	.short	0xA53C
	lsrs	r3, r0, #32
	.global	loc_0803a534
loc_0803a534:
	.short	0xA554
	lsrs	r3, r0, #32
	.global	loc_0803a538
loc_0803a538:
	.short	0xA554
	lsrs	r3, r0, #32
	.global	loc_0803a53c
loc_0803a53c:
	ldr	r0, [pc, #16]	@ 0x0803A550
	ldr	r1, [r0, #0]
	.global	loc_0803a540
loc_0803a540:
	adds	r0, r1, #0
	adds	r0, #70
	.global	loc_0803a544
loc_0803a544:
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	.global	loc_0803a548
loc_0803a548:
	movs	r0, #24
	.short	0xF095
	.global	loc_0803a54c
loc_0803a54c:
	.short	0xFC3F
	b.n	loc_0803a5a8	@ 0x0803A5A8
	.global	loc_0803a550
loc_0803a550:
	.word	gUnk_03002490
	.global	loc_0803a554
loc_0803a554:
	ldr	r0, [pc, #60]	@ 0x0803A594
	ldr	r1, [r0, #0]
	.global	loc_0803a558
loc_0803a558:
	adds	r1, #108
	movs	r2, #0
	.global	loc_0803a55c
loc_0803a55c:
	strh	r2, [r1, #0]
	adds	r4, r0, #0
	.global	loc_0803a560
loc_0803a560:
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	.global	loc_0803a564
loc_0803a564:
	adds	r0, #70
	ldrh	r0, [r0, #0]
	.global	loc_0803a568
loc_0803a568:
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	.global	loc_0803a588
loc_0803a588:
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	.global	loc_0803a58c
loc_0803a58c:
	cmp	r0, #5
	ble.n	loc_0803a560	@ 0x0803A560
	b.n	loc_0803a5a8	@ 0x0803A5A8
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803a598
loc_0803a598:
	movs	r0, #5
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r6, #0]
	strh	r0, [r1, #60]
	movs	r0, #24
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a5a8
loc_0803a5a8:
	ldr	r4, [pc, #72]	@ 0x0803A5F4
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #64]	@ 0x0803A5F8
	ands	r0, r2
	strh	r0, [r1, #0]
	ldr	r0, [pc, #64]	@ 0x0803A5FC
	ldr	r1, [r0, #0]
	movs	r0, #14
	bl	sub_080055b0	@ 0x080055B0
	bl	sub_0802672c	@ 0x0802672C
	ldr	r4, [r4, #0]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	.global	loc_0803a5d0
loc_0803a5d0:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a5da	@ 0x0803A5DA
	b.n	loc_0803a6d4	@ 0x0803A6D4
	.global	loc_0803a5da
loc_0803a5da:
	adds	r0, r4, #0
	.global	loc_0803a5dc
loc_0803a5dc:
	adds	r0, #136
	ldr	r0, [r0, #0]
	.global	loc_0803a5e0
loc_0803a5e0:
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #23
	.global	loc_0803a5e8
loc_0803a5e8:
	bhi.n	loc_0803a664	@ 0x0803A664
	lsls	r0, r0, #2
	.global	loc_0803a5ec
loc_0803a5ec:
	ldr	r1, [pc, #16]	@ 0x0803A600
	adds	r0, r0, r1
	.global	loc_0803a5f0
loc_0803a5f0:
	ldr	r0, [r0, #0]
	mov	pc, r0
	.global	loc_0803a5f4
loc_0803a5f4:
	.word	gUnk_03002490
	.global	loc_0803a5f8
loc_0803a5f8:
	.word	0x0000FFEF
	.global	loc_0803a5fc
loc_0803a5fc:
	.word	gCurTaskIdx
	.global	loc_0803a600
loc_0803a600:
	.word	0x0803A604
	.global	loc_0803a604
loc_0803a604:
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a608
loc_0803a608:
	.short	0xA680
	lsrs	r3, r0, #32
	.global	loc_0803a60c
loc_0803a60c:
	.short	0xA680
	lsrs	r3, r0, #32
	.global	loc_0803a610
loc_0803a610:
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a614
loc_0803a614:
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a618
loc_0803a618:
	.short	0xA680
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a620
loc_0803a620:
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a624
loc_0803a624:
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a634
loc_0803a634:
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a638
loc_0803a638:
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.global	loc_0803a644
loc_0803a644:
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA680
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA664
	lsrs	r3, r0, #32
	.short	0xA680
	lsrs	r3, r0, #32
	.short	0xA680
	lsrs	r3, r0, #32
	.global	loc_0803a664
loc_0803a664:
	ldr	r1, [pc, #20]	@ 0x0803A67C
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	bne.n	loc_0803a6ea	@ 0x0803A6EA
	adds	r4, r1, #0
	.global	loc_0803a66e
loc_0803a66e:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	beq.n	loc_0803a66e	@ 0x0803A66E
	b.n	loc_0803a6ea	@ 0x0803A6EA
	.global	loc_0803a67c
loc_0803a67c:
	.word	gUnk_020055E8
	ldr	r6, [pc, #4]	@ 0x0803A688
	ldr	r4, [pc, #8]	@ 0x0803A68C
	b.n	loc_0803a6bc	@ 0x0803A6BC
	movs	r0, r0
	.global	loc_0803a688
loc_0803a688:
	.word	gUnk_03002490
	.global	loc_0803a68c
loc_0803a68c:
	.word	gUnk_020055E8
	.global	loc_0803a690
loc_0803a690:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	bne.n	loc_0803a6ea	@ 0x0803A6EA
	ldr	r0, [r6, #0]
	ldrh	r1, [r0, #60]
	adds	r1, #1
	strh	r1, [r0, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	bne.n	loc_0803a6ea	@ 0x0803A6EA
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	bne.n	loc_0803a6ea	@ 0x0803A6EA
	.global	loc_0803a6bc
loc_0803a6bc:
	ldr	r0, [r6, #0]
	adds	r1, r0, #0
	adds	r1, #70
	ldrh	r1, [r1, #0]
	strh	r1, [r0, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	beq.n	loc_0803a690	@ 0x0803A690
	b.n	loc_0803a6ea	@ 0x0803A6EA
	.global	loc_0803a6d4
loc_0803a6d4:
	ldr	r1, [pc, #148]	@ 0x0803A76C
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	bne.n	loc_0803a6ea	@ 0x0803A6EA
	adds	r4, r1, #0
	.global	loc_0803a6de
loc_0803a6de:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	beq.n	loc_0803a6de	@ 0x0803A6DE
	.global	loc_0803a6ea
loc_0803a6ea:
	ldr	r0, [pc, #132]	@ 0x0803A770
	ldr	r1, [r0, #0]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_0803a6f4
loc_0803a6f4:
	ldr	r4, [pc, #124]	@ 0x0803A774
	ldr	r1, [r4, #0]
	movs	r0, #128
	lsls	r0, r0, #7
	strh	r0, [r1, #62]
	adds	r0, r5, #0
	bl	sub_08026704	@ 0x08026704
	ldr	r1, [pc, #112]	@ 0x0803A778
	ldr	r2, [pc, #116]	@ 0x0803A77C
	movs	r3, #128
	lsls	r3, r3, #3
	movs	r0, #3
	bl	sub_080017e4	@ 0x080017E4
	bl	sub_08027908	@ 0x08027908
	movs	r0, #10
	movs	r1, #14
	bl	sub_08040b40	@ 0x08040B40
	ldr	r0, [r4, #0]
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r5, #1
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a730	@ 0x0803A730
	b.n	loc_0803a93c	@ 0x0803A93C
	.global	loc_0803a730
loc_0803a730:
	movs	r0, #20
	bl	sub_080413a4	@ 0x080413A4
	ldr	r2, [r4, #0]
	ldr	r1, [pc, #68]	@ 0x0803A780
	adds	r3, r2, #0
	adds	r3, #136
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #2
	adds	r1, #2
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	adds	r2, #70
	strh	r0, [r2, #0]
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #21
	bls.n	loc_0803a760	@ 0x0803A760
	b.n	loc_0803a860	@ 0x0803A860
	.global	loc_0803a760
loc_0803a760:
	lsls	r0, r0, #2
	ldr	r1, [pc, #32]	@ 0x0803A784
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
	.word	gUnk_020055E8
	.word	gCurTaskIdx
	.word	gUnk_03002490
	.word	gUnk_02020000
	.word	0x06014000
	.word	gUnk_0873D3B8
	.word	0x0803A788
	.short	0xA7E0
	lsrs	r3, r0, #32
	add	r0, sp, #384
	lsrs	r3, r0, #32
	add	r0, sp, #368
	lsrs	r3, r0, #32
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a798
loc_0803a798:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	add	r0, sp, #384
	lsrs	r3, r0, #32
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7a4
loc_0803a7a4:
	.short	0xA7E0
	lsrs	r3, r0, #32
	.global	loc_0803a7a8
loc_0803a7a8:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7b0
loc_0803a7b0:
	add	r0, sp, #288
	lsrs	r3, r0, #32
	.global	loc_0803a7b4
loc_0803a7b4:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7b8
loc_0803a7b8:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7bc
loc_0803a7bc:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7c0
loc_0803a7c0:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7c4
loc_0803a7c4:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7c8
loc_0803a7c8:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7cc
loc_0803a7cc:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7d0
loc_0803a7d0:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7d4
loc_0803a7d4:
	add	r0, sp, #384
	lsrs	r3, r0, #32
	.global	loc_0803a7d8
loc_0803a7d8:
	.short	0xA7E0
	lsrs	r3, r0, #32
	.global	loc_0803a7dc
loc_0803a7dc:
	.short	0xA7E0
	lsrs	r3, r0, #32
	.global	loc_0803a7e0
loc_0803a7e0:
	ldr	r4, [pc, #92]	@ 0x0803A840
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #70
	.global	loc_0803a7e8
loc_0803a7e8:
	ldrh	r0, [r0, #0]
	movs	r5, #0
	.global	loc_0803a7ec
loc_0803a7ec:
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r3, [r4, #0]
	ldr	r2, [pc, #76]	@ 0x0803A844
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #13
	ldrsb	r1, [r0, r1]
	lsls	r0, r1, #3
	subs	r0, r0, r1
	lsls	r0, r0, #1
	adds	r2, #12
	adds	r0, r0, r2
	.global	loc_0803a80c
loc_0803a80c:
	ldrh	r0, [r0, #0]
	strh	r0, [r3, #60]
	.global	loc_0803a810
loc_0803a810:
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #108
	strh	r5, [r0, #0]
	.global	loc_0803a81c
loc_0803a81c:
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #4
	ble.n	loc_0803a81c	@ 0x0803A81C
	b.n	loc_0803a8c6	@ 0x0803A8C6
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_0873D632
	ldr	r0, [pc, #8]	@ 0x0803A854
	ldr	r0, [r0, #0]
	.global	loc_0803a84c
loc_0803a84c:
	adds	r0, #70
	ldr	r1, [pc, #8]	@ 0x0803A858
	strh	r1, [r0, #0]
	b.n	loc_0803a860	@ 0x0803A860
	.global	loc_0803a854
loc_0803a854:
	.word	gUnk_03002490
	.word	0x00000841
	bl	sub_08049a58	@ 0x08049A58
	.global	loc_0803a860
loc_0803a860:
	ldr	r4, [pc, #212]	@ 0x0803A938
	ldr	r1, [r4, #0]
	.global	loc_0803a864
loc_0803a864:
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	.global	loc_0803a8ac
loc_0803a8ac:
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a8c6
loc_0803a8c6:
	movs	r0, #10
	movs	r1, #15
	bl	sub_08040b40	@ 0x08040B40
	ldr	r4, [pc, #104]	@ 0x0803A938
	movs	r5, #1
	.global	loc_0803a8d2
loc_0803a8d2:
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #70
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a97e	@ 0x0803A97E
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r2, [r4, #0]
	adds	r0, r2, #0
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a97e	@ 0x0803A97E
	ldrh	r0, [r2, #60]
	adds	r0, #1
	strh	r0, [r2, #60]
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a97e	@ 0x0803A97E
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a8d2	@ 0x0803A8D2
	b.n	loc_0803a97e	@ 0x0803A97E
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803a93c
loc_0803a93c:
	movs	r0, #21
	bl	sub_080413a4	@ 0x080413A4
	movs	r0, #6
	bl	sub_0803f7e0	@ 0x0803F7E0
	ldr	r1, [r4, #0]
	strh	r0, [r1, #60]
	movs	r0, #14
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	movs	r0, #10
	movs	r1, #15
	bl	sub_08040b40	@ 0x08040B40
	ldr	r0, [r4, #0]
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a97e	@ 0x0803A97E
	movs	r5, #1
	.global	loc_0803a96a
loc_0803a96a:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #122
	ldrb	r1, [r0, #0]
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803a96a	@ 0x0803A96A
	.global	loc_0803a97e
loc_0803a97e:
	movs	r0, #3
	bl	sub_0803e050	@ 0x0803E050
	ldr	r2, [pc, #36]	@ 0x0803A9AC
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #62
	movs	r1, #2
	strb	r1, [r0, #0]
	ldr	r0, [r2, #0]
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0803a9a4	@ 0x0803A9A4
	bl	sub_0803cd60	@ 0x0803CD60
	.global	loc_0803a9a4
loc_0803a9a4:
	bl	sub_08026584	@ 0x08026584
	.global	loc_0803a9a8
loc_0803a9a8:
	b.n	loc_0803a9b6	@ 0x0803A9B6
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803a9b0
loc_0803a9b0:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803a9b6
loc_0803a9b6:
	bl	sub_08027a30	@ 0x08027A30
	cmp	r0, #0
	beq.n	loc_0803a9b0	@ 0x0803A9B0
	bl	sub_08027a60	@ 0x08027A60
	movs	r5, #0
	ldr	r0, [pc, #96]	@ 0x0803AA28
	ldrh	r0, [r0, #0]
	cmp	r5, r0
	bge.n	loc_0803aa10	@ 0x0803AA10
	ldr	r4, [pc, #92]	@ 0x0803AA2C
	.global	loc_0803a9ce
loc_0803a9ce:
	movs	r0, #116
	adds	r2, r5, #0
	muls	r2, r0
	adds	r2, r2, r4
	adds	r2, #66
	ldrh	r0, [r2, #0]
	ldr	r3, [pc, #84]	@ 0x0803AA30
	adds	r1, r3, #0
	ands	r0, r1
	strh	r0, [r2, #0]
	ldr	r1, [pc, #80]	@ 0x0803AA34
	lsls	r0, r5, #1
	adds	r0, r0, r1
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	cmp	r0, #0
	beq.n	loc_0803a9f6	@ 0x0803A9F6
	adds	r0, r5, #0
	bl	sub_08040808	@ 0x08040808
	.global	loc_0803a9f6
loc_0803a9f6:
	ldr	r0, [pc, #64]	@ 0x0803AA38
	ldr	r0, [r0, #0]
	cmp	r5, r0
	beq.n	loc_0803aa06	@ 0x0803AA06
	movs	r0, #0
	adds	r1, r5, #0
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_0803aa06
loc_0803aa06:
	adds	r5, #1
	ldr	r0, [pc, #28]	@ 0x0803AA28
	ldrh	r0, [r0, #0]
	cmp	r5, r0
	blt.n	loc_0803a9ce	@ 0x0803A9CE
	.global	loc_0803aa10
loc_0803aa10:
	bl	sub_08049738	@ 0x08049738
	.global	loc_0803aa14
loc_0803aa14:
	ldr	r0, [pc, #36]	@ 0x0803AA3C
	ldr	r1, [r0, #0]
	ldr	r0, [r1, #40]
	adds	r0, #1
	str	r0, [r1, #40]
	bl	sub_08006138	@ 0x08006138
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_030023AC
	.word	gUnk_03002170
	.word	0x0000FFBF
	.word	gUnk_02005588
	.word	gCurTaskIdx
	.word	gUnk_03002490
