@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24_0803bde8, chunk 1/2: 0x0803BDE8-0x0803CCD8 (thumb_code, 0xEF0 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x0803BDE8 sub_0803bde8
@   0x0803C990 sub_0803c990
@   0x0803C9B4 sub_0803c9b4
@   0x0803CBD8 sub_0803cbd8

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24_0803bde8, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24_0803bde8
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_08036280_08039c24_0803bde8:
	.thumb_func
	.global	sub_0803bde8
sub_0803bde8:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #16
	ldr	r4, [pc, #200]	@ 0x0803BEC0
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrb	r0, [r1, #4]
	strb	r0, [r1, #5]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #23
	strb	r0, [r1, #4]
	ldr	r1, [r4, #0]
	movs	r0, #18
	strb	r0, [r1, #21]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrb	r0, [r1, #6]
	cmp	r0, #2
	bne.n	loc_0803be20	@ 0x0803BE20
	movs	r0, #0
	strb	r0, [r1, #6]
	.global	loc_0803be20
loc_0803be20:
	movs	r0, #146
	lsls	r0, r0, #1
	ldr	r1, [r4, #0]
	adds	r1, #136
	ldr	r1, [r1, #0]
	ldrb	r1, [r1, #0]
	lsls	r1, r1, #24
	asrs	r1, r1, #24
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	bl	sub_0803e34c	@ 0x0803E34C
	ldr	r2, [r4, #0]
	adds	r0, r2, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	ldr	r0, [r2, #24]
	cmp	r0, r1
	beq.n	loc_0803be4c	@ 0x0803BE4C
	b.n	loc_0803c02a	@ 0x0803C02A
	.global	loc_0803be4c
loc_0803be4c:
	adds	r1, r2, #0
	adds	r1, #66
	movs	r0, #5
	strb	r0, [r1, #0]
	ldr	r0, [pc, #108]	@ 0x0803BEC4
	ldr	r1, [r0, #0]
	movs	r0, #14
	bl	sub_080055b0	@ 0x080055B0
	ldr	r4, [r4, #0]
	adds	r3, r4, #0
	adds	r3, #136
	ldr	r1, [r3, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	movs	r5, #128
	lsls	r5, r5, #1
	adds	r0, r5, #0
	orrs	r0, r2
	strh	r0, [r1, #0]
	ldr	r1, [r3, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #76]	@ 0x0803BEC8
	ands	r0, r2
	strh	r0, [r1, #0]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803be90	@ 0x0803BE90
	b.n	loc_0803bfa8	@ 0x0803BFA8
	.global	loc_0803be90
loc_0803be90:
	ldr	r1, [pc, #56]	@ 0x0803BECC
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #2
	adds	r1, #2
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #24
	bhi.n	loc_0803bf50	@ 0x0803BF50
	lsls	r0, r0, #2
	ldr	r1, [pc, #24]	@ 0x0803BED0
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	gCurTaskIdx
	.word	0x0000FFEF
	.word	0x0873DA62
	.word	0x0803BED4
	.short	0xBF38
	.short	0x0803
	.short	0xBF62
	.short	0x0803
	.short	0xBF62
	.short	0x0803
	.short	0xBF50
	.short	0x0803
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF62
	.short	0x0803
	.short	0xBF50
	.short	0x0803
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF62
	.short	0x0803
	.short	0xBF50
	.short	0x0803
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF62
	.short	0x0803
	.short	0xBF50
	.short	0x0803
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF50
	lsrs	r3, r0, #32
	.short	0xBF5E
	.short	0x0803
	.short	0x481A
	.short	0x6801
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #6]
	cmp	r0, #1
	bne.n	loc_0803bf50	@ 0x0803BF50
	adds	r1, #70
	movs	r0, #162
	lsls	r0, r0, #1
	strh	r0, [r1, #0]
	.global	loc_0803bf50
loc_0803bf50:
	ldr	r0, [pc, #80]	@ 0x0803BFA4
	ldr	r0, [r0, #0]
	adds	r0, #70
	movs	r6, #0
	ldrsh	r0, [r0, r6]
	bl	sub_08006338	@ 0x08006338
	bl	sub_08006138	@ 0x08006138
	ldr	r4, [pc, #64]	@ 0x0803BFA4
	.global	loc_0803bf64
loc_0803bf64:
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	.short	0xF093
	.global	loc_0803bf90
loc_0803bf90:
	.short	0xFF1D
	ldr	r1, [r4, #0]
	.global	loc_0803bf94
loc_0803bf94:
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803bfa0
loc_0803bfa0:
	b.n	loc_0803bf64	@ 0x0803BF64
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803bfa8
loc_0803bfa8:
	ldr	r0, [pc, #24]	@ 0x0803BFC4
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	.global	loc_0803bfb0
loc_0803bfb0:
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #9
	beq.n	loc_0803c00c	@ 0x0803C00C
	cmp	r0, #9
	bgt.n	loc_0803bfc8	@ 0x0803BFC8
	cmp	r0, #4
	beq.n	loc_0803bffc	@ 0x0803BFFC
	b.n	loc_0803bfd0	@ 0x0803BFD0
	.word	gUnk_03002490
	.global	loc_0803bfc8
loc_0803bfc8:
	cmp	r0, #10
	beq.n	loc_0803c01c	@ 0x0803C01C
	cmp	r0, #24
	beq.n	loc_0803c026	@ 0x0803C026
	.global	loc_0803bfd0
loc_0803bfd0:
	ldr	r0, [pc, #20]	@ 0x0803BFE8
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #6]
	cmp	r0, #1
	bne.n	loc_0803bfec	@ 0x0803BFEC
	movs	r0, #163
	lsls	r0, r0, #1
	bl	sub_08006338	@ 0x08006338
	b.n	loc_0803c026	@ 0x0803C026
	.word	gUnk_03002490
	.global	loc_0803bfec
loc_0803bfec:
	ldr	r0, [pc, #8]	@ 0x0803BFF8
	movs	r2, #2
	ldrsh	r0, [r0, r2]
	bl	sub_08006338	@ 0x08006338
	b.n	loc_0803c026	@ 0x0803C026
	.word	0x0873DACA
	.global	loc_0803bffc
loc_0803bffc:
	ldr	r0, [pc, #8]	@ 0x0803C008
	movs	r3, #6
	ldrsh	r0, [r0, r3]
	bl	sub_08006338	@ 0x08006338
	b.n	loc_0803c026	@ 0x0803C026
	.word	0x0873DACA
	.global	loc_0803c00c
loc_0803c00c:
	ldr	r0, [pc, #8]	@ 0x0803C018
	movs	r5, #10
	ldrsh	r0, [r0, r5]
	bl	sub_08006338	@ 0x08006338
	b.n	loc_0803c026	@ 0x0803C026
	.word	0x0873DACA
	.global	loc_0803c01c
loc_0803c01c:
	ldr	r0, [pc, #160]	@ 0x0803C0C0
	movs	r6, #14
	ldrsh	r0, [r0, r6]
	bl	sub_08006338	@ 0x08006338
	.global	loc_0803c026
loc_0803c026:
	bl	sub_08006138	@ 0x08006138
	.global	loc_0803c02a
loc_0803c02a:
	ldr	r4, [pc, #152]	@ 0x0803C0C4
	ldr	r0, [r4, #0]
	ldr	r1, [r0, #24]
	movs	r0, #116
	adds	r2, r1, #0
	muls	r2, r0
	ldr	r0, [pc, #144]	@ 0x0803C0C8
	adds	r5, r2, r0
	lsls	r0, r1, #3
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr	r1, [pc, #136]	@ 0x0803C0CC
	adds	r0, r0, r1
	mov	r8, r0
	movs	r0, #15
	bl	sub_0803e3e4	@ 0x0803E3E4
	ldr	r0, [pc, #128]	@ 0x0803C0D0
	ldr	r1, [r0, #0]
	movs	r0, #12
	bl	sub_080055b0	@ 0x080055B0
	ldr	r0, [r4, #0]
	.global	loc_0803c058
loc_0803c058:
	ldr	r1, [r0, #24]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #67
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	str	r0, [sp, #0]
	adds	r1, #66
	ldrb	r1, [r1, #0]
	str	r1, [sp, #8]
	movs	r0, #3
	bl	sub_0803e050	@ 0x0803E050
	ldr	r4, [r4, #0]
	adds	r3, r4, #0
	adds	r3, #136
	ldr	r1, [r3, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	movs	r6, #128
	lsls	r6, r6, #1
	adds	r0, r6, #0
	orrs	r0, r2
	strh	r0, [r1, #0]
	ldr	r1, [r3, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #56]	@ 0x0803C0D4
	ands	r0, r2
	strh	r0, [r1, #0]
	mov	r0, r8
	adds	r0, #72
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	adds	r1, r4, #0
	adds	r1, #72
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	subs	r0, r0, r1
	cmp	r0, #0
	ble.n	loc_0803c0d8	@ 0x0803C0D8
	adds	r1, r4, #0
	adds	r1, #67
	movs	r0, #1
	b.n	loc_0803c0de	@ 0x0803C0DE
	movs	r0, r0
	.word	0x0873DACA
	.word	gUnk_03002490
	.word	gUnk_03002170
	.word	gUnk_03002790
	.word	gCurTaskIdx
	.word	0x0000FFEF
	.global	loc_0803c0d8
loc_0803c0d8:
	adds	r1, r4, #0
	adds	r1, #67
	movs	r0, #255
	.global	loc_0803c0de
loc_0803c0de:
	strb	r0, [r1, #0]
	ldr	r3, [pc, #80]	@ 0x0803C134
	ldr	r0, [r3, #0]
	adds	r0, #66
	movs	r2, #0
	movs	r1, #4
	strb	r1, [r0, #0]
	mov	r1, r8
	adds	r1, #67
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	str	r0, [sp, #4]
	mov	r4, r8
	adds	r4, #66
	ldrb	r6, [r4, #0]
	str	r6, [sp, #12]
	mov	r0, r8
	str	r2, [r0, #100]
	str	r2, [r0, #92]
	str	r2, [r0, #84]
	str	r2, [r0, #104]
	str	r2, [r0, #96]
	str	r2, [r0, #88]
	ldr	r0, [r3, #0]
	adds	r0, #67
	ldrb	r0, [r0, #0]
	negs	r0, r0
	strb	r0, [r1, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	mov	sl, r1
	mov	r9, r4
	cmp	r0, #1
	bne.n	loc_0803c13c	@ 0x0803C13C
	mov	r2, r8
	ldrh	r1, [r2, #62]
	ldr	r0, [pc, #12]	@ 0x0803C138
	ands	r0, r1
	strh	r0, [r2, #62]
	b.n	loc_0803c14a	@ 0x0803C14A
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x00007FFF
	.global	loc_0803c13c
loc_0803c13c:
	mov	r6, r8
	ldrh	r1, [r6, #62]
	movs	r2, #128
	lsls	r2, r2, #8
	adds	r0, r2, #0
	orrs	r0, r1
	strh	r0, [r6, #62]
	.global	loc_0803c14a
loc_0803c14a:
	ldr	r4, [r3, #0]
	adds	r0, r4, #0
	adds	r0, #123
	ldrb	r1, [r0, #0]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803c15c	@ 0x0803C15C
	b.n	loc_0803c6e4	@ 0x0803C6E4
	.global	loc_0803c15c
loc_0803c15c:
	ldr	r1, [pc, #44]	@ 0x0803C18C
	adds	r2, r4, #0
	adds	r2, #136
	ldr	r0, [r2, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r4, #0
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r0, [r2, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #23
	bhi.n	loc_0803c1f4	@ 0x0803C1F4
	lsls	r0, r0, #2
	ldr	r1, [pc, #8]	@ 0x0803C190
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	0x0873DA62
	.word	0x0803C194
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r1!, {r2, r4, r5, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	stmia	r3!, {r2, r6, r7}
	lsrs	r3, r0, #32
	.global	loc_0803c1f4
loc_0803c1f4:
	ldr	r4, [pc, #28]	@ 0x0803C214
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #6]
	cmp	r0, #1
	bne.n	loc_0803c21c	@ 0x0803C21C
	ldr	r0, [pc, #16]	@ 0x0803C218
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803c252	@ 0x0803C252
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x00000145
	.global	loc_0803c21c
loc_0803c21c:
	adds	r0, r1, #0
	adds	r0, #70
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	.global	loc_0803c252
loc_0803c252:
	ldr	r4, [pc, #28]	@ 0x0803C270
	.global	loc_0803c254
loc_0803c254:
	ldr	r3, [r4, #0]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #58
	ldrb	r0, [r0, #0]
	cmp	r0, #2
	beq.n	loc_0803c2dc	@ 0x0803C2DC
	cmp	r0, #2
	bgt.n	loc_0803c274	@ 0x0803C274
	cmp	r0, #1
	beq.n	loc_0803c27c	@ 0x0803C27C
	b.n	loc_0803c3a2	@ 0x0803C3A2
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803c274
loc_0803c274:
	cmp	r0, #3
	bne.n	loc_0803c27a	@ 0x0803C27A
	b.n	loc_0803c374	@ 0x0803C374
	.global	loc_0803c27a
loc_0803c27a:
	b.n	loc_0803c3a2	@ 0x0803C3A2
	.global	loc_0803c27c
loc_0803c27c:
	ldr	r1, [pc, #80]	@ 0x0803C2D0
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #76]	@ 0x0803C2D4
	movs	r5, #0
	ldrsh	r2, [r0, r5]
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r2, r0
	bge.n	loc_0803c35a	@ 0x0803C35A
	.global	loc_0803c292
loc_0803c292:
	ldr	r0, [pc, #68]	@ 0x0803C2D8
	ldrh	r2, [r0, #0]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c2ae	@ 0x0803C2AE
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c2b4	@ 0x0803C2B4
	.global	loc_0803c2ae
loc_0803c2ae:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c2b4
loc_0803c2b4:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r4, #0]
	str	r0, [r1, #40]
	movs	r0, #8
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #40]
	cmp	r0, #0
	beq.n	loc_0803c292	@ 0x0803C292
	b.n	loc_0803c35a	@ 0x0803C35A
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002360
	.global	loc_0803c2dc
loc_0803c2dc:
	ldr	r1, [pc, #132]	@ 0x0803C364
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #128]	@ 0x0803C368
	movs	r5, #0
	ldrsh	r2, [r0, r5]
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r2, r0
	bge.n	loc_0803c35a	@ 0x0803C35A
	ldr	r0, [pc, #120]	@ 0x0803C36C
	ldrb	r0, [r0, #0]
	movs	r1, #1
	cmp	r0, #0
	bne.n	loc_0803c2fe	@ 0x0803C2FE
	movs	r1, #2
	.global	loc_0803c2fe
loc_0803c2fe:
	adds	r0, r3, #0
	adds	r0, #108
	movs	r2, #0
	strh	r2, [r0, #0]
	lsls	r0, r1, #16
	asrs	r1, r0, #16
	adds	r6, r0, #0
	cmp	r2, r1
	bge.n	loc_0803c35a	@ 0x0803C35A
	.global	loc_0803c310
loc_0803c310:
	ldr	r0, [pc, #92]	@ 0x0803C370
	ldrh	r2, [r0, #0]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c32c	@ 0x0803C32C
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c332	@ 0x0803C332
	.global	loc_0803c32c
loc_0803c32c:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c332
loc_0803c332:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r4, #0]
	str	r0, [r1, #40]
	movs	r0, #8
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldr	r0, [r1, #40]
	cmp	r0, #0
	bne.n	loc_0803c35a	@ 0x0803C35A
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	cmp	r0, r6
	blt.n	loc_0803c310	@ 0x0803C310
	.global	loc_0803c35a
loc_0803c35a:
	movs	r0, #16
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803c3a2	@ 0x0803C3A2
	movs	r0, r0
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002464
	.word	gUnk_03002360
	.global	loc_0803c374
loc_0803c374:
	adds	r0, r5, #0
	adds	r0, #34
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0803c388	@ 0x0803C388
	movs	r0, #0
	strh	r0, [r5, #32]
	strh	r0, [r5, #30]
	.global	loc_0803c388
loc_0803c388:
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #23]
	strb	r0, [r5, #23]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrh	r0, [r0, #24]
	strh	r0, [r5, #24]
	movs	r0, #32
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803c3a2
loc_0803c3a2:
	ldr	r4, [pc, #24]	@ 0x0803C3BC
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #6]
	cmp	r0, #1
	beq.n	loc_0803c3b4	@ 0x0803C3B4
	b.n	loc_0803c6b4	@ 0x0803C6B4
	.global	loc_0803c3b4
loc_0803c3b4:
	ldr	r0, [pc, #8]	@ 0x0803C3C0
	bl	sub_08006338	@ 0x08006338
	b.n	loc_0803c6d6	@ 0x0803C6D6
	.word	gUnk_03002490
	.word	0x0000013F
	ldr	r4, [pc, #76]	@ 0x0803C414
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	movs	r7, #0
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r3, [r4, #0]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #58
	ldrb	r0, [r0, #0]
	cmp	r0, #2
	bne.n	loc_0803c408	@ 0x0803C408
	b.n	loc_0803c510	@ 0x0803C510
	.global	loc_0803c408
loc_0803c408:
	cmp	r0, #2
	bgt.n	loc_0803c418	@ 0x0803C418
	cmp	r0, #1
	beq.n	loc_0803c420	@ 0x0803C420
	b.n	loc_0803c69a	@ 0x0803C69A
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803c418
loc_0803c418:
	cmp	r0, #3
	bne.n	loc_0803c41e	@ 0x0803C41E
	b.n	loc_0803c630	@ 0x0803C630
	.global	loc_0803c41e
loc_0803c41e:
	b.n	loc_0803c69a	@ 0x0803C69A
	.global	loc_0803c420
loc_0803c420:
	ldr	r1, [pc, #220]	@ 0x0803C500
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #216]	@ 0x0803C504
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	movs	r5, #0
	ldrsh	r0, [r1, r5]
	cmp	r2, r0
	bge.n	loc_0803c4b4	@ 0x0803C4B4
	adds	r5, r4, #0
	.global	loc_0803c438
loc_0803c438:
	ldr	r0, [pc, #204]	@ 0x0803C508
	ldrh	r2, [r0, #0]
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c454	@ 0x0803C454
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c45a	@ 0x0803C45A
	.global	loc_0803c454
loc_0803c454:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c45a
loc_0803c45a:
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r5, #0]
	str	r0, [r1, #40]
	adds	r1, #108
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr	r4, [pc, #156]	@ 0x0803C50C
	.global	loc_0803c46e
loc_0803c46e:
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #15
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #1
	ble.n	loc_0803c46e	@ 0x0803C46E
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #40]
	cmp	r0, #0
	beq.n	loc_0803c438	@ 0x0803C438
	.global	loc_0803c4b4
loc_0803c4b4:
	ldr	r0, [pc, #84]	@ 0x0803C50C
	ldr	r1, [r0, #0]
	adds	r1, #108
	movs	r2, #0
	strh	r2, [r1, #0]
	adds	r4, r0, #0
	.global	loc_0803c4c0
loc_0803c4c0:
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #15
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #3
	ble.n	loc_0803c4c0	@ 0x0803C4C0
	b.n	loc_0803c69a	@ 0x0803C69A
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002360
	.word	gUnk_03002490
	.global	loc_0803c510
loc_0803c510:
	ldr	r1, [pc, #264]	@ 0x0803C61C
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #260]	@ 0x0803C620
	movs	r6, #0
	ldrsh	r2, [r0, r6]
	movs	r5, #0
	ldrsh	r0, [r1, r5]
	cmp	r2, r0
	bge.n	loc_0803c5ce	@ 0x0803C5CE
	ldr	r0, [pc, #252]	@ 0x0803C624
	ldrb	r0, [r0, #0]
	movs	r1, #1
	cmp	r0, #0
	bne.n	loc_0803c532	@ 0x0803C532
	movs	r1, #2
	.global	loc_0803c532
loc_0803c532:
	adds	r0, r3, #0
	adds	r0, #108
	strh	r7, [r0, #0]
	lsls	r0, r1, #16
	asrs	r1, r0, #16
	adds	r6, r0, #0
	cmp	r7, r1
	bge.n	loc_0803c5ce	@ 0x0803C5CE
	adds	r5, r4, #0
	.global	loc_0803c544
loc_0803c544:
	ldr	r0, [pc, #224]	@ 0x0803C628
	ldrh	r2, [r0, #0]
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c560	@ 0x0803C560
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c566	@ 0x0803C566
	.global	loc_0803c560
loc_0803c560:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c566
loc_0803c566:
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r5, #0]
	str	r0, [r1, #40]
	adds	r1, #110
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr	r4, [pc, #176]	@ 0x0803C62C
	.global	loc_0803c57a
loc_0803c57a:
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #15
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #110
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #1
	ble.n	loc_0803c57a	@ 0x0803C57A
	ldr	r1, [r5, #0]
	ldr	r0, [r1, #40]
	cmp	r0, #0
	bne.n	loc_0803c5ce	@ 0x0803C5CE
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	cmp	r0, r6
	blt.n	loc_0803c544	@ 0x0803C544
	.global	loc_0803c5ce
loc_0803c5ce:
	ldr	r0, [pc, #92]	@ 0x0803C62C
	ldr	r1, [r0, #0]
	adds	r1, #110
	movs	r2, #0
	strh	r2, [r1, #0]
	adds	r4, r0, #0
	.global	loc_0803c5da
loc_0803c5da:
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #15
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #110
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #3
	ble.n	loc_0803c5da	@ 0x0803C5DA
	b.n	loc_0803c69a	@ 0x0803C69A
	movs	r0, r0
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002464
	.word	gUnk_03002360
	.word	gUnk_03002490
	.global	loc_0803c630
loc_0803c630:
	adds	r0, r5, #0
	adds	r0, #34
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0803c642	@ 0x0803C642
	strh	r7, [r5, #32]
	strh	r7, [r5, #30]
	.global	loc_0803c642
loc_0803c642:
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #23]
	strb	r0, [r5, #23]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrh	r0, [r0, #24]
	strh	r0, [r5, #24]
	adds	r1, #108
	strh	r7, [r1, #0]
	.global	loc_0803c65c
loc_0803c65c:
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #15
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #7
	ble.n	loc_0803c65c	@ 0x0803C65C
	.global	loc_0803c69a
loc_0803c69a:
	ldr	r4, [pc, #68]	@ 0x0803C6E0
	ldr	r0, [r4, #0]
	adds	r0, #70
	ldrh	r0, [r0, #0]
	adds	r0, #3
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	.global	loc_0803c6a8
loc_0803c6a8:
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	.global	loc_0803c6b4
loc_0803c6b4:
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803c6c0
loc_0803c6c0:
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	.short	0xF093
	.global	loc_0803c6cc
loc_0803c6cc:
	.short	0xFB7F
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	.global	loc_0803c6d6
loc_0803c6d6:
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803c8f0	@ 0x0803C8F0
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803c6e4
loc_0803c6e4:
	adds	r0, r4, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #9
	beq.n	loc_0803c720	@ 0x0803C720
	cmp	r0, #9
	bgt.n	loc_0803c6fe	@ 0x0803C6FE
	cmp	r0, #4
	beq.n	loc_0803c714	@ 0x0803C714
	b.n	loc_0803c706	@ 0x0803C706
	.global	loc_0803c6fe
loc_0803c6fe:
	cmp	r0, #10
	beq.n	loc_0803c72c	@ 0x0803C72C
	cmp	r0, #24
	beq.n	loc_0803c738	@ 0x0803C738
	.global	loc_0803c706
loc_0803c706:
	ldr	r0, [r3, #0]
	ldr	r1, [pc, #4]	@ 0x0803C710
	ldrh	r1, [r1, #0]
	b.n	loc_0803c73e	@ 0x0803C73E
	movs	r0, r0
	.word	0x0873DACA
	.global	loc_0803c714
loc_0803c714:
	ldr	r0, [pc, #4]	@ 0x0803C71C
	ldrh	r1, [r0, #4]
	b.n	loc_0803c73c	@ 0x0803C73C
	movs	r0, r0
	.word	0x0873DACA
	.global	loc_0803c720
loc_0803c720:
	ldr	r0, [pc, #4]	@ 0x0803C728
	ldrh	r1, [r0, #8]
	b.n	loc_0803c73c	@ 0x0803C73C
	movs	r0, r0
	.word	0x0873DACA
	.global	loc_0803c72c
loc_0803c72c:
	ldr	r0, [pc, #4]	@ 0x0803C734
	ldrh	r1, [r0, #12]
	b.n	loc_0803c73c	@ 0x0803C73C
	movs	r0, r0
	.word	0x0873DACA
	.global	loc_0803c738
loc_0803c738:
	ldr	r0, [pc, #88]	@ 0x0803C794
	ldrh	r1, [r0, #16]
	.global	loc_0803c73c
loc_0803c73c:
	adds	r0, r4, #0
	.global	loc_0803c73e
loc_0803c73e:
	adds	r0, #70
	strh	r1, [r0, #0]
	ldr	r4, [pc, #84]	@ 0x0803C798
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r6, #0
	ldrsh	r0, [r0, r6]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	movs	r7, #0
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r3, [r4, #0]
	ldrh	r0, [r3, #60]
	adds	r0, #1
	strh	r0, [r3, #60]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #58
	ldrb	r0, [r0, #0]
	cmp	r0, #2
	beq.n	loc_0803c804	@ 0x0803C804
	cmp	r0, #2
	bgt.n	loc_0803c79c	@ 0x0803C79C
	cmp	r0, #1
	beq.n	loc_0803c7a2	@ 0x0803C7A2
	b.n	loc_0803c8c4	@ 0x0803C8C4
	.word	0x0873DACA
	.word	gUnk_03002490
	.global	loc_0803c79c
loc_0803c79c:
	cmp	r0, #3
	beq.n	loc_0803c898	@ 0x0803C898
	b.n	loc_0803c8c4	@ 0x0803C8C4
	.global	loc_0803c7a2
loc_0803c7a2:
	ldr	r1, [pc, #84]	@ 0x0803C7F8
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #80]	@ 0x0803C7FC
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	movs	r5, #0
	ldrsh	r0, [r1, r5]
	cmp	r2, r0
	bge.n	loc_0803c880	@ 0x0803C880
	.global	loc_0803c7b8
loc_0803c7b8:
	ldr	r0, [pc, #68]	@ 0x0803C800
	ldrh	r2, [r0, #0]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c7d4	@ 0x0803C7D4
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c7da	@ 0x0803C7DA
	.global	loc_0803c7d4
loc_0803c7d4:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c7da
loc_0803c7da:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r4, #0]
	str	r0, [r1, #40]
	movs	r0, #8
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #40]
	cmp	r0, #0
	beq.n	loc_0803c7b8	@ 0x0803C7B8
	b.n	loc_0803c880	@ 0x0803C880
	movs	r0, r0
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002360
	.global	loc_0803c804
loc_0803c804:
	ldr	r1, [pc, #128]	@ 0x0803C888
	ldr	r0, [r3, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #124]	@ 0x0803C88C
	movs	r6, #0
	ldrsh	r2, [r0, r6]
	movs	r5, #0
	ldrsh	r0, [r1, r5]
	cmp	r2, r0
	bge.n	loc_0803c880	@ 0x0803C880
	ldr	r0, [pc, #116]	@ 0x0803C890
	ldrb	r0, [r0, #0]
	movs	r1, #1
	cmp	r0, #0
	bne.n	loc_0803c826	@ 0x0803C826
	movs	r1, #2
	.global	loc_0803c826
loc_0803c826:
	adds	r0, r3, #0
	adds	r0, #108
	strh	r7, [r0, #0]
	lsls	r0, r1, #16
	asrs	r1, r0, #16
	adds	r6, r0, #0
	cmp	r7, r1
	bge.n	loc_0803c880	@ 0x0803C880
	.global	loc_0803c836
loc_0803c836:
	ldr	r0, [pc, #92]	@ 0x0803C894
	ldrh	r2, [r0, #0]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	beq.n	loc_0803c852	@ 0x0803C852
	ldr	r0, [r1, #24]
	cmp	r2, r0
	bne.n	loc_0803c858	@ 0x0803C858
	.global	loc_0803c852
loc_0803c852:
	movs	r0, #221
	bl	sub_080031b8	@ 0x080031B8
	.global	loc_0803c858
loc_0803c858:
	ldr	r0, [r4, #0]
	ldr	r0, [r0, #24]
	bl	sub_080b4204	@ 0x080B4204
	ldr	r1, [r4, #0]
	str	r0, [r1, #40]
	movs	r0, #8
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldr	r0, [r1, #40]
	cmp	r0, #0
	bne.n	loc_0803c880	@ 0x0803C880
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	cmp	r0, r6
	blt.n	loc_0803c836	@ 0x0803C836
	.global	loc_0803c880
loc_0803c880:
	movs	r0, #16
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0803c8c4	@ 0x0803C8C4
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_03002464
	.word	gUnk_03002360
	.global	loc_0803c898
loc_0803c898:
	adds	r0, r5, #0
	adds	r0, #34
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0803c8aa	@ 0x0803C8AA
	strh	r7, [r5, #32]
	strh	r7, [r5, #30]
	.global	loc_0803c8aa
loc_0803c8aa:
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #23]
	strb	r0, [r5, #23]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrh	r0, [r0, #24]
	strh	r0, [r5, #24]
	movs	r0, #32
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803c8c4
loc_0803c8c4:
	ldr	r4, [pc, #184]	@ 0x0803C980
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0803c8f0
loc_0803c8f0:
	ldr	r4, [pc, #140]	@ 0x0803C980
	ldr	r0, [r4, #0]
	adds	r0, #67
	mov	r6, sp
	ldrb	r6, [r6, #0]
	strb	r6, [r0, #0]
	ldr	r0, [r4, #0]
	adds	r0, #66
	mov	r1, sp
	ldrb	r1, [r1, #8]
	strb	r1, [r0, #0]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #66
	ldrh	r3, [r1, #0]
	ldr	r2, [pc, #112]	@ 0x0803C984
	adds	r0, r2, #0
	ands	r0, r3
	strh	r0, [r1, #0]
	mov	r3, sp
	ldrb	r5, [r3, #4]
	mov	r3, sl
	strb	r5, [r3, #0]
	mov	r6, sp
	ldrb	r0, [r6, #12]
	mov	r6, r9
	strb	r0, [r6, #0]
	ldr	r3, [pc, #92]	@ 0x0803C988
	ldr	r0, [r4, #0]
	ldr	r1, [r0, #24]
	movs	r0, #116
	muls	r0, r1
	adds	r0, r0, r3
	adds	r0, #66
	ldrh	r1, [r0, #0]
	ands	r2, r1
	strh	r2, [r0, #0]
	mov	r1, r8
	ldrb	r0, [r1, #18]
	subs	r0, #1
	strb	r0, [r1, #18]
	movs	r0, #0
	bl	sub_0803e3e4	@ 0x0803E3E4
	ldr	r0, [pc, #64]	@ 0x0803C98C
	ldr	r1, [r0, #0]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r2, [r0, #0]
	adds	r2, #59
	ldr	r1, [r1, #24]
	movs	r0, #1
	lsls	r0, r1
	ldrb	r1, [r2, #0]
	orrs	r0, r1
	strb	r0, [r2, #0]
	bl	sub_08006138	@ 0x08006138
	add	sp, #16
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x0000FEFF
	.word	gUnk_03002170
	.word	gCurTaskIdx
	.thumb_func
	.global	sub_0803c990
sub_0803c990:
	.thumb
	push	{lr}
	ldr	r0, [pc, #20]	@ 0x0803C9A8
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #13
	ldrsb	r0, [r1, r0]
	cmp	r0, #24
	beq.n	loc_0803c9ac	@ 0x0803C9AC
	bl	sub_08040710	@ 0x08040710
	b.n	loc_0803c9b0	@ 0x0803C9B0
	.word	gUnk_03002490
	.global	loc_0803c9ac
loc_0803c9ac:
	movs	r0, #55
	strb	r0, [r1, #1]
	.global	loc_0803c9b0
loc_0803c9b0:
	pop	{r0}
	bx	r0
	.thumb_func
	.global	sub_0803c9b4
sub_0803c9b4:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #8
	mov	r8, r0
	movs	r0, #0
	mov	r9, r0
	ldr	r1, [pc, #100]	@ 0x0803CA2C
	mov	sl, r1
	.global	loc_0803c9ca
loc_0803c9ca:
	mov	r2, sl
	ldr	r3, [r2, #0]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r2, r0, #1
	adds	r2, r2, r0
	lsls	r2, r2, #4
	mov	r1, r9
	lsls	r0, r1, #4
	ldr	r1, [pc, #72]	@ 0x0803CA30
	adds	r0, r0, r1
	adds	r4, r2, r0
	ldrb	r1, [r3, #19]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803ca38	@ 0x0803CA38
	movs	r7, #0
	mov	r2, r8
	cmp	r2, #0
	bne.n	loc_0803ca06	@ 0x0803CA06
	adds	r0, r3, #0
	adds	r0, #64
	ldrh	r0, [r0, #0]
	ldr	r1, [pc, #48]	@ 0x0803CA34
	adds	r7, r0, r1
	.global	loc_0803ca06
loc_0803ca06:
	ldrb	r5, [r4, #13]
	mov	r2, r8
	cmp	r2, #0
	beq.n	loc_0803ca10	@ 0x0803CA10
	b.n	loc_0803cb46	@ 0x0803CB46
	.global	loc_0803ca10
loc_0803ca10:
	cmp	r5, #0
	beq.n	loc_0803ca16	@ 0x0803CA16
	b.n	loc_0803cb46	@ 0x0803CB46
	.global	loc_0803ca16
loc_0803ca16:
	adds	r0, r3, #0
	adds	r0, #67
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r5, #3
	cmp	r0, #1
	beq.n	loc_0803ca28	@ 0x0803CA28
	b.n	loc_0803cb46	@ 0x0803CB46
	.global	loc_0803ca28
loc_0803ca28:
	movs	r5, #2
	b.n	loc_0803cb46	@ 0x0803CB46
	.word	gUnk_03002490
	.word	gUnk_02007E90
	.word	0x0000180C
	.global	loc_0803ca38
loc_0803ca38:
	ldr	r1, [r4, #0]
	cmp	r1, #0
	bne.n	loc_0803ca8c	@ 0x0803CA8C
	str	r1, [r4, #8]
	movs	r0, #16
	bl	sub_08002ee8	@ 0x08002EE8
	adds	r2, r0, #0
	mov	r3, sl
	ldr	r0, [r3, #0]
	adds	r0, #67
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_0803ca6c	@ 0x0803CA6C
	ldr	r1, [pc, #12]	@ 0x0803CA68
	lsls	r2, r2, #1
	adds	r0, r2, r1
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #16
	b.n	loc_0803ca7a	@ 0x0803CA7A
	movs	r0, r0
	.word	0x0873A924
	.global	loc_0803ca6c
loc_0803ca6c:
	ldr	r1, [pc, #56]	@ 0x0803CAA8
	lsls	r2, r2, #1
	adds	r0, r2, r1
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	lsls	r0, r0, #16
	negs	r0, r0
	.global	loc_0803ca7a
loc_0803ca7a:
	str	r0, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #32
	adds	r0, r2, r0
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	lsls	r0, r0, #16
	str	r0, [r4, #4]
	ldr	r1, [r4, #0]
	.global	loc_0803ca8c
loc_0803ca8c:
	adds	r2, r1, #0
	cmp	r1, #0
	bge.n	loc_0803ca94	@ 0x0803CA94
	negs	r2, r1
	.global	loc_0803ca94
loc_0803ca94:
	movs	r0, #240
	lsls	r0, r0, #12
	cmp	r2, r0
	bgt.n	loc_0803caac	@ 0x0803CAAC
	movs	r1, #0
	str	r1, [r4, #0]
	movs	r0, #1
	strb	r0, [r4, #12]
	strb	r1, [r4, #13]
	b.n	loc_0803cba6	@ 0x0803CBA6
	.word	0x0873A924
	.global	loc_0803caac
loc_0803caac:
	cmp	r1, #0
	ble.n	loc_0803cabc	@ 0x0803CABC
	ldr	r0, [r4, #8]
	ldr	r2, [pc, #4]	@ 0x0803CAB8
	adds	r0, r0, r2
	b.n	loc_0803cac4	@ 0x0803CAC4
	.word	0xFFFFA000
	.global	loc_0803cabc
loc_0803cabc:
	.short	0x68A0
	movs	r3, #192
	lsls	r3, r3, #7
	adds	r0, r0, r3
	.global	loc_0803cac4
loc_0803cac4:
	str	r0, [r4, #8]
	ldr	r1, [r4, #0]
	ldr	r0, [r4, #8]
	adds	r1, r1, r0
	str	r1, [r4, #0]
	cmp	r1, #0
	bge.n	loc_0803cad4	@ 0x0803CAD4
	negs	r1, r1
	.global	loc_0803cad4
loc_0803cad4:
	asrs	r0, r1, #20
	adds	r2, r0, #1
	ldr	r1, [r4, #4]
	cmp	r1, #0
	bge.n	loc_0803cae0	@ 0x0803CAE0
	negs	r1, r1
	.global	loc_0803cae0
loc_0803cae0:
	ldr	r0, [pc, #64]	@ 0x0803CB24
	ands	r0, r1
	lsrs	r0, r2
	ldr	r1, [r4, #4]
	cmp	r1, #0
	ble.n	loc_0803caee	@ 0x0803CAEE
	negs	r0, r0
	.global	loc_0803caee
loc_0803caee:
	adds	r0, r1, r0
	str	r0, [r4, #4]
	mov	r5, r8
	movs	r7, #0
	cmp	r5, #0
	bne.n	loc_0803cb46	@ 0x0803CB46
	ldrb	r0, [r4, #12]
	subs	r0, #1
	strb	r0, [r4, #12]
	lsls	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_0803cb38	@ 0x0803CB38
	ldrb	r0, [r4, #13]
	adds	r1, r0, #0
	cmp	r1, #0
	bne.n	loc_0803cb2c	@ 0x0803CB2C
	mov	r1, sl
	ldr	r0, [r1, #0]
	adds	r0, #67
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_0803cb28	@ 0x0803CB28
	movs	r0, #2
	b.n	loc_0803cb32	@ 0x0803CB32
	movs	r0, r0
	.word	0xFFFF0000
	.global	loc_0803cb28
loc_0803cb28:
	.short	0x2003
	b.n	loc_0803cb32	@ 0x0803CB32
	.global	loc_0803cb2c
loc_0803cb2c:
	cmp	r1, #9
	bhi.n	loc_0803cb34	@ 0x0803CB34
	adds	r0, #2
	.global	loc_0803cb32
loc_0803cb32:
	strb	r0, [r4, #13]
	.global	loc_0803cb34
loc_0803cb34:
	movs	r0, #1
	strb	r0, [r4, #12]
	.global	loc_0803cb38
loc_0803cb38:
	ldrb	r5, [r4, #13]
	ldr	r2, [pc, #136]	@ 0x0803CBC4
	ldr	r0, [r2, #0]
	adds	r0, #64
	ldrh	r0, [r0, #0]
	ldr	r3, [pc, #132]	@ 0x0803CBC8
	adds	r7, r0, r3
	.global	loc_0803cb46
loc_0803cb46:
	ldr	r0, [pc, #124]	@ 0x0803CBC4
	ldr	r1, [r0, #0]
	adds	r0, r1, #0
	adds	r0, #72
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	movs	r3, #2
	ldrsh	r0, [r4, r3]
	adds	r6, r2, r0
	adds	r1, #74
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	movs	r3, #6
	ldrsh	r1, [r4, r3]
	adds	r0, r0, r1
	adds	r4, r0, #4
	lsls	r0, r6, #16
	asrs	r0, r0, #16
	lsls	r1, r4, #16
	asrs	r1, r1, #16
	bl	sub_0800641c	@ 0x0800641C
	cmp	r0, #0
	beq.n	loc_0803cba6	@ 0x0803CBA6
	ldr	r0, [pc, #84]	@ 0x0803CBCC
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	subs	r6, r6, r0
	ldr	r0, [pc, #80]	@ 0x0803CBD0
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	subs	r4, r4, r0
	ldr	r3, [pc, #60]	@ 0x0803CBC4
	ldr	r0, [r3, #0]
	adds	r0, #66
	ldrb	r0, [r0, #0]
	ldr	r2, [pc, #68]	@ 0x0803CBD4
	lsls	r1, r5, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	str	r6, [sp, #0]
	lsls	r2, r4, #16
	asrs	r2, r2, #16
	str	r2, [sp, #4]
	movs	r2, #0
	adds	r3, r7, #0
	bl	sub_08001a94	@ 0x08001A94
	.global	loc_0803cba6
loc_0803cba6:
	movs	r0, #1
	add	r9, r0
	mov	r1, r9
	cmp	r1, #2
	bgt.n	loc_0803cbb2	@ 0x0803CBB2
	b.n	loc_0803c9ca	@ 0x0803C9CA
	.global	loc_0803cbb2
loc_0803cbb2:
	add	sp, #8
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x0000180C
	.word	gUnk_03002348
	.word	gUnk_030023E4
	.word	0x0873A964
	.thumb_func
	.global	sub_0803cbd8
sub_0803cbd8:
	.thumb
	push	{r4, r5, lr}
	ldr	r5, [pc, #36]	@ 0x0803CC00
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #41
	ldrb	r0, [r1, #0]
	subs	r0, #1
	strb	r0, [r1, #0]
	lsls	r0, r0, #24
	cmp	r0, #0
	ble.n	loc_0803cc04	@ 0x0803CC04
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #41
	ldrb	r0, [r1, #0]
	subs	r0, #1
	strb	r0, [r1, #0]
	b.n	loc_0803ccca	@ 0x0803CCCA
	.word	gUnk_03002490
	.global	loc_0803cc04
loc_0803cc04:
	ldr	r1, [pc, #92]	@ 0x0803CC64
	ldr	r0, [r5, #0]
	adds	r3, r0, #0
	adds	r3, #136
	ldr	r2, [r3, #0]
	adds	r0, r2, #0
	adds	r0, #42
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r4, [r0, #0]
	adds	r0, r2, #0
	adds	r0, #40
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #3
	adds	r4, r4, r0
	ldrb	r1, [r4, #4]
	adds	r0, r1, #0
	cmp	r0, #0
	beq.n	loc_0803ccb0	@ 0x0803CCB0
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803cc46	@ 0x0803CC46
	ldr	r0, [pc, #40]	@ 0x0803CC68
	ldr	r1, [r0, #0]
	movs	r0, #3
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_0803cc46
loc_0803cc46:
	ldrb	r1, [r4, #4]
	movs	r0, #64
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803cc78	@ 0x0803CC78
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #67
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_0803cc6c	@ 0x0803CC6C
	adds	r0, r1, #0
	b.n	loc_0803cc7a	@ 0x0803CC7A
	.word	0x0873A994
	.word	gCurTaskIdx
	.global	loc_0803cc6c
loc_0803cc6c:
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrh	r0, [r4, #0]
	negs	r0, r0
	b.n	loc_0803cc80	@ 0x0803CC80
	.global	loc_0803cc78
loc_0803cc78:
	ldr	r0, [r5, #0]
	.global	loc_0803cc7a
loc_0803cc7a:
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrh	r0, [r4, #0]
	.global	loc_0803cc80
loc_0803cc80:
	strh	r0, [r1, #36]
	ldr	r3, [pc, #40]	@ 0x0803CCAC
	ldr	r0, [r3, #0]
	adds	r0, #136
	ldr	r2, [r0, #0]
	ldrh	r1, [r4, #2]
	strh	r1, [r2, #38]
	ldr	r1, [r0, #0]
	ldrb	r2, [r4, #4]
	movs	r0, #15
	ands	r0, r2
	adds	r1, #41
	strb	r0, [r1, #0]
	ldr	r0, [r3, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #40
	ldrb	r0, [r1, #0]
	adds	r0, #1
	strb	r0, [r1, #0]
	b.n	loc_0803ccca	@ 0x0803CCCA
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_0803ccb0
loc_0803ccb0:
	strh	r0, [r2, #38]
	strh	r0, [r2, #36]
	ldr	r1, [r3, #0]
	adds	r1, #64
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #20]	@ 0x0803CCD0
	ands	r0, r2
	strh	r0, [r1, #0]
	ldr	r0, [pc, #16]	@ 0x0803CCD4
	ldr	r1, [r0, #0]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_0803ccca
loc_0803ccca:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	0x0000FFFE
	.word	gCurTaskIdx
