#ifndef GUARD_CONSTANTS_ABILITIES_H
#define GUARD_CONSTANTS_ABILITIES_H

/*
 * Abilities (#155 run 6, the owner's decision D6).
 * The ability ids that PlayerState.ability, Actor.ability, ActorDef.ability,
 * PlayerState.pendingAbility, the player's u80.attackAbility,
 * gPlayerAbilities[] and SetPlayerAbility take, fixed by the HUD ability
 * pictures gAbilityPictures[id], whose banners carry the name
 * (docs/naming.md 2.3). gAbilityPictures also holds two pictures that are
 * not abilities: 26 (WAIT) and 27 (a second NORMAL banner the ability
 * roulette opens with, left a number). Generated by tools/constants.py; each
 * define is logged with its evidence in docs/analysis/constants.csv.
 */

/* Abilities - PlayerState.ability, Actor.ability, ActorDef.ability, u80.attackAbility */
#define ABILITY_NORMAL    0
#define ABILITY_FIRE      1
#define ABILITY_SPARK     2
#define ABILITY_CUTTER    3
#define ABILITY_SWORD     4
#define ABILITY_BURNING   5
#define ABILITY_LASER     6
#define ABILITY_MIKE      7
#define ABILITY_WHEEL     8
#define ABILITY_HAMMER    9
#define ABILITY_PARASOL   10
#define ABILITY_SLEEP     11
#define ABILITY_NEEDLE    12
#define ABILITY_ICE       13
#define ABILITY_FREEZE    14
#define ABILITY_HI_JUMP   15
#define ABILITY_BEAM      16
#define ABILITY_STONE     17
#define ABILITY_BALL      18
#define ABILITY_TORNADO   19
#define ABILITY_CRASH     20
#define ABILITY_LIGHT     21
#define ABILITY_BACKDROP  22
#define ABILITY_THROW     23
#define ABILITY_UFO       24
#define ABILITY_STAR_ROD  25

/* HUD ability pictures - gAbilityPictures[N] beyond the abilities (HudShowAbility, HudShowAbilityAnimated) */
#define ABILITY_PICTURE_WAIT  26

#endif // GUARD_CONSTANTS_ABILITIES_H
