#ifndef GUARD_CONSTANTS_GAME_STATES_H
#define GUARD_CONSTANTS_GAME_STATES_H

/*
 * Game states and stage requests (#155 run 6, the owner's decision D6).
 * gGameState (u16) is the case AgbMain's loop dispatches on (src/main.c);
 * gPrevGameState holds a game state too: the one a cutscene returns to, or
 * the one the menu and the result screens look back at. gStageRequest (s8)
 * is what the frame loops of the hub, the stage, the Big Switch view and
 * Boss Endurance (src/mode_075b8.c, src/mode_08664.c) do next; each request
 * names the game state or action it leads to. The extra modes 0-7 are game
 * states 14-21 (gExtraModeIndex + 14) and hub requests 9-14 (game state =
 * request + 5). Generated by tools/constants.py; each define is logged with
 * its evidence in docs/analysis/constants.csv.
 */

/* Game states - gGameState and gPrevGameState: the case of AgbMain's dispatch (src/main.c), named after the case body */
#define GAME_STATE_RESET              0  /* resets the session cells, then GAME_STATE_BOOT_LOGO */
#define GAME_STATE_BOOT_LOGO          1
#define GAME_STATE_TITLE              3
#define GAME_STATE_MAIN_MENU          4
#define GAME_STATE_HUB                5  /* parks in GAME_STATE_CUTSCENE first while gCutscenePending */
#define GAME_STATE_STAGE_START        6  /* the way into GAME_STATE_STAGE */
#define GAME_STATE_CUTSCENE           7
#define GAME_STATE_STAGE              8
#define GAME_STATE_BIG_SWITCH_VIEW    9
#define GAME_STATE_GOAL_GAME          10
#define GAME_STATE_ENDING             11
#define GAME_STATE_CREDITS            12 /* the staff credits and the final results screen */
#define GAME_STATE_EXTRA_MODE_TITLE   13
#define GAME_STATE_QUICK_DRAW         14 /* extra mode 0 */
#define GAME_STATE_BOMB_RALLY         15 /* extra mode 1 */
#define GAME_STATE_AIR_GRIND          16 /* extra mode 2 */
#define GAME_STATE_WARP_STAR_STATION  17 /* extra mode 3 */
#define GAME_STATE_MUSEUM             18 /* extra mode 4 */
#define GAME_STATE_ARENA              19 /* extra mode 5 */
#define GAME_STATE_BOSS_ENDURANCE     20 /* extra mode 6 */
#define GAME_STATE_META_KNIGHTMARE    21 /* extra mode 7: starts Meta Knightmare in the hub */
#define GAME_STATE_GAME_OVER          22

/* Stage requests - gStageRequest: what the frame loops of HubMain, StageMain, BigSwitchViewMain and BossEnduranceMain do when it is set (src/mode_075b8.c, src/mode_08664.c) */
#define STAGE_REQUEST_NONE               0
#define STAGE_REQUEST_HUB                1  /* BossEnduranceMain just ends its loop on it (src/mode_08664.c:176): the next boss room ExitClearedStage chose */
#define STAGE_REQUEST_STAGE_START        2
#define STAGE_REQUEST_CHANGE_ROOM        3
#define STAGE_REQUEST_BIG_SWITCH_VIEW    4
#define STAGE_REQUEST_PAUSE              5
#define STAGE_REQUEST_LOST_LIFE          6
#define STAGE_REQUEST_ENDING             7
#define STAGE_REQUEST_GOAL_GAME          8
#define STAGE_REQUEST_QUICK_DRAW         9
#define STAGE_REQUEST_BOMB_RALLY         10
#define STAGE_REQUEST_AIR_GRIND          11
#define STAGE_REQUEST_WARP_STAR_STATION  12
#define STAGE_REQUEST_MUSEUM             13
#define STAGE_REQUEST_ARENA              14

#endif // GUARD_CONSTANTS_GAME_STATES_H
