#ifndef GUARD_CONSTANTS_SOUND_H
#define GUARD_CONSTANTS_SOUND_H

/*
 * Sound effect ids (#155 run 6, the owner's decision D6). The id PlaySfx,
 * PlaySfxIfLocalPlayer and PlayerStartSfx play (the m4a song number of the
 * effect). An id is named only where every call site plays it for the same
 * thing; the sounds themselves are assets and stay in the ROM. Generated by
 * tools/constants.py; each define is logged with its evidence in
 * docs/analysis/constants.csv.
 */

/* Sound effects - the id PlaySfx, PlaySfxIfLocalPlayer and PlayerStartSfx take (argument 0), named only where every call site plays it for the same thing */
#define SE_JUMP              100 /* Meta Knight's jump is SE_META_KNIGHT_JUMP */
#define SE_CURSOR_MOVE       101 /* the roulette's selection moving is the one non-menu caller */
#define SE_CONFIRM           102
#define SE_FIRE_ATTACK       128 /* gPlayerActions' FIRE attack */
#define SE_HAMMER_HIT        132
#define SE_SPARK_ATTACK      136
#define SE_BURNING_ATTACK    137
#define SE_NEEDLE_ATTACK     138
#define SE_NEEDLE_HIT        139
#define SE_ICE_ATTACK        140
#define SE_FREEZE_ATTACK     141
#define SE_ICE_HIT           142
#define SE_STONE_LAND        143
#define SE_CUTTER_ATTACK     144
#define SE_CUTTER_HIT        145
#define SE_SWORD_HIT         146
#define SE_TORNADO_ATTACK    150
#define SE_PARASOL_ATTACK    151
#define SE_STONE_ATTACK      152
#define SE_LASER_ATTACK      172
#define SE_HI_JUMP_ATTACK    174
#define SE_ENTER_DOOR        181
#define SE_THROW_GRAB        201
#define SE_CANCEL            215
#define SE_CRASH_ATTACK      248
#define SE_META_KNIGHT_JUMP  264

/* Songs - the id PlayBgm takes (argument 0), named only where every call site plays it for the same scene and no room plays it (RoomDef.bgm, gRoomBgmRemap) */
#define BGM_LOST_LIFE   3
#define BGM_GAME_OVER   16
#define BGM_INVINCIBLE  19
#define BGM_TITLE       26

#endif // GUARD_CONSTANTS_SOUND_H
