@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment irq_handler_table_14: 0x080CFDE8-0x080CFE20 (data, 0x38 bytes)

	.section .irq_handler_table_14, "a"
	.global	irq_handler_table_14
	.syntax	unified
	.cpu	arm7tdmi
irq_handler_table_14:
	.global	gUnk_080cfde8
gUnk_080cfde8:
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_080010cc+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
	.word	sub_08001518+1
