@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment task_switch_helpers: 0x08000234-0x080002E8 (arm_code, 0xB4 bytes)
@ Stays asm: the ARM coroutine switch (TaskSwitch, TaskYield, TaskExit and
@   the task-done check) saves and swaps sp, which no C source can express
@   (docs/analysis/rom-map.md section 6).
@ Functions (docs/analysis/symbols.csv):
@   0x08000234 TaskSwitch
@   0x08000258 TaskYield
@   0x08000288 TaskExit
@   0x080002A8 sub_080002a8

	.section .task_switch_helpers, "ax"
	.global	task_switch_helpers
	.align	2
	.syntax	unified
	.cpu	arm7tdmi
task_switch_helpers:
	.global	TaskSwitch
TaskSwitch:
	.arm
	stmfd	sp!, {lr}
	push	{r4, r5, r6, r7, r8, r9, sl, fp}
	ldr	r3, [pc, #:pc_g0:(task_literals - 8)]	@ 0x080002E8
	str	sp, [r3]
	mov	sp, r2
	pop	{r4, r5, r6, r7, r8, r9, sl, fp}
	mov	r2, #1
	orr	r1, r1, r2
	bx	r1
	.global	TaskYield
TaskYield:
	.arm
	push	{r4, r5, r6, r7, r8, r9, sl, fp}
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x4 - 8)]	@ 0x080002EC
	str	sp, [r3]
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x8 - 8)]	@ 0x080002F0
	str	lr, [r3]
	ldr	r3, [pc, #:pc_g0:(task_literals + 0xC - 8)]	@ 0x080002F4
	str	r0, [r3]
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x10 - 8)]	@ 0x080002F8
	ldr	sp, [r3]
	pop	{r4, r5, r6, r7, r8, r9, sl, fp}
	ldmfd	sp!, {r1}
	bx	r1
	.global	TaskExit
TaskExit:
	.arm
	ldr	r0, [pc, #:pc_g0:(task_literals + 0x14 - 8)]	@ 0x080002FC
	ldr	r0, [r0]
	bl	sub_080cfddc	@ 0x080CFDDC
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x18 - 8)]	@ 0x08000300
	ldr	sp, [r3]
	pop	{r4, r5, r6, r7, r8, r9, sl, fp}
	ldmfd	sp!, {r1}
	bx	r1
	.global	sub_080002a8
sub_080002a8:
	.arm
	mov	r2, #0
	sub	r2, r2, #1
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x1C - 8)]	@ 0x08000304
	ldr	r3, [r3]
	cmp	r2, r3
	bne	.L_080002e0	@ 0x080002E0
	ldr	r3, [pc, #:pc_g0:(task_literals + 0x20 - 8)]	@ 0x08000308
	ldr	r3, [r3]
	lsls	r3, r3, #2
	ldr	r2, [pc, #:pc_g0:(task_literals + 0x24 - 8)]	@ 0x0800030C
	add	r2, r2, r3
	ldr	r2, [r2]
	cmp	r2, #0
	bne	.L_080002e4	@ 0x080002E4
.L_080002e0:
	bx	lr
.L_080002e4:
	b	.L_080002e4	@ 0x080002E4
