@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_0800b920, chunk 1/2: 0x0800B920-0x0800BF6C (thumb_code, 0x64C bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x0800B920 sub_0800b920
@   0x0800BCF0 sub_0800bcf0
@   0x0800BDA4 sub_0800bda4
@   0x0800BE8C sub_0800be8c
@   0x0800BF10 sub_0800bf10

	.section .game_code_and_rodata_0800b920, "ax"
	.global	game_code_and_rodata_0800b920
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_0800b920:
	.thumb_func
	.global	sub_0800b920
sub_0800b920:
	.thumb
	push	{r4, r5, lr}
	bl	sub_08003964	@ 0x08003964
	bl	sub_08006868	@ 0x08006868
	ldr	r1, [pc, #136]	@ 0x0800B9B4
	movs	r0, #0
	str	r0, [r1, #0]
	bl	sub_080022ac	@ 0x080022AC
	bl	sub_08002028	@ 0x08002028
	bl	sub_080b6e44	@ 0x080B6E44
	ldr	r0, [pc, #120]	@ 0x0800B9B8
	ldr	r1, [r0, #0]
	movs	r0, #1
	negs	r0, r0
	.global	loc_0800b944
loc_0800b944:
	cmp	r1, r0
	beq.n	loc_0800b94c	@ 0x0800B94C
	cmp	r1, #3
	bne.n	loc_0800b950	@ 0x0800B950
	.global	loc_0800b94c
loc_0800b94c:
	bl	sub_080b78e4	@ 0x080B78E4
	.global	loc_0800b950
loc_0800b950:
	ldr	r1, [pc, #104]	@ 0x0800B9BC
	movs	r2, #0
	movs	r0, #0
	strh	r0, [r1, #0]
	strh	r0, [r1, #2]
	ldr	r1, [pc, #100]	@ 0x0800B9C0
	movs	r0, #10
	strh	r0, [r1, #0]
	ldr	r1, [pc, #96]	@ 0x0800B9C4
	movs	r0, #6
	strh	r0, [r1, #0]
	ldr	r0, [pc, #96]	@ 0x0800B9C8
	strb	r2, [r0, #0]
	movs	r0, #2
	bl	sub_08008c4c	@ 0x08008C4C
	movs	r0, #22
	bl	sub_08008c64	@ 0x08008C64
	.short	0xF004
	.global	loc_0800b978
loc_0800b978:
	.short	0xF9A1
	ldr	r0, [pc, #80]	@ 0x0800B9CC
	movs	r1, #32
	bl	sub_080058e4	@ 0x080058E4
	movs	r0, #129
	lsls	r0, r0, #1
	movs	r1, #32
	bl	sub_080058e4	@ 0x080058E4
	ldr	r0, [pc, #64]	@ 0x0800B9D0
	movs	r1, #32
	bl	sub_080058e4	@ 0x080058E4
	movs	r0, #128
	lsls	r0, r0, #1
	movs	r1, #32
	bl	sub_080058e4	@ 0x080058E4
	ldr	r0, [pc, #52]	@ 0x0800B9D4
	ldrh	r0, [r0, #0]
	subs	r0, #3
	cmp	r0, #18
	bls.n	loc_0800b9aa	@ 0x0800B9AA
	b.n	loc_0800baca	@ 0x0800BACA
	.global	loc_0800b9aa
loc_0800b9aa:
	lsls	r0, r0, #2
	ldr	r1, [pc, #40]	@ 0x0800B9D8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	gUnk_03004D70
	.word	gUnk_030023E8
	.word	gUnk_0200A6E0
	.word	gUnk_03000FC8
	.global	loc_0800b9c4
loc_0800b9c4:
	.word	gUnk_03001ECC
	.word	gUnk_02006180
	.word	0x00000101
	.word	0x00000103
	.word	gUnk_03002150
	.word	0x0800B9DC
	.short	0xBA28
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBA74
	lsrs	r0, r0, #32
	.short	0xBA74
	lsrs	r0, r0, #32
	.short	0xBA74
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBACA
	lsrs	r0, r0, #32
	.short	0xBA74
	lsrs	r0, r0, #32
	.short	0xBA74
	lsrs	r0, r0, #32
	ldr	r1, [pc, #56]	@ 0x0800BA64
	movs	r0, #64
	str	r0, [r1, #0]
	movs	r0, #128
	lsls	r0, r0, #12
	movs	r1, #80
	movs	r2, #3
	bl	sub_0800fdb8	@ 0x0800FDB8
	ldr	r2, [pc, #44]	@ 0x0800BA68
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x0800BA6C
	ands	r0, r1
	strh	r0, [r2, #0]
	ldrh	r0, [r2, #0]
	movs	r3, #224
	lsls	r3, r3, #5
	adds	r1, r3, #0
	orrs	r0, r1
	strh	r0, [r2, #0]
	ldr	r1, [pc, #28]	@ 0x0800BA70
	movs	r0, #0
	strb	r0, [r1, #0]
	bl	sub_0800bcf0	@ 0x0800BCF0
	movs	r0, #0
	bl	sub_0800da9c	@ 0x0800DA9C
	b.n	loc_0800baca	@ 0x0800BACA
	movs	r0, r0
	.word	gUnk_03000FA8
	.word	gUnk_03001ED8
	.word	0x0000E0FF
	.word	gUnk_020060D0
	ldr	r1, [pc, #32]	@ 0x0800BA98
	movs	r0, #64
	str	r0, [r1, #0]
	movs	r0, #128
	lsls	r0, r0, #12
	movs	r1, #80
	movs	r2, #3
	bl	sub_0800fdb8	@ 0x0800FDB8
	ldr	r0, [pc, #20]	@ 0x0800BA9C
	ldrh	r0, [r0, #0]
	adds	r1, r0, #0
	cmp	r1, #16
	bhi.n	loc_0800baa4	@ 0x0800BAA4
	ldr	r1, [pc, #12]	@ 0x0800BAA0
	subs	r0, #14
	b.n	loc_0800bab8	@ 0x0800BAB8
	movs	r0, r0
	.word	gUnk_03000FA8
	.word	gUnk_03002150
	.word	gUnk_0200B074
	.global	loc_0800baa4
loc_0800baa4:
	cmp	r1, #20
	bne.n	loc_0800bab4	@ 0x0800BAB4
	ldr	r1, [pc, #4]	@ 0x0800BAB0
	movs	r0, #3
	b.n	loc_0800bab8	@ 0x0800BAB8
	movs	r0, r0
	.word	gUnk_0200B074
	.global	loc_0800bab4
loc_0800bab4:
	ldr	r1, [pc, #100]	@ 0x0800BB1C
	movs	r0, #4
	.global	loc_0800bab8
loc_0800bab8:
	strb	r0, [r1, #0]
	ldr	r1, [pc, #100]	@ 0x0800BB20
	movs	r0, #11
	strb	r0, [r1, #0]
	bl	sub_0800ca10	@ 0x0800CA10
	ldr	r1, [pc, #92]	@ 0x0800BB24
	movs	r0, #0
	str	r0, [r1, #0]
	.global	loc_0800baca
loc_0800baca:
	movs	r0, #40
	bl	sub_08003110	@ 0x08003110
	ldr	r1, [pc, #84]	@ 0x0800BB28
	movs	r0, #10
	strh	r0, [r1, #0]
	ldr	r1, [pc, #84]	@ 0x0800BB2C
	movs	r0, #30
	strh	r0, [r1, #0]
	ldr	r1, [pc, #80]	@ 0x0800BB30
	movs	r2, #3
	negs	r2, r2
	adds	r0, r2, #0
	strh	r0, [r1, #0]
	ldr	r1, [pc, #76]	@ 0x0800BB34
	movs	r0, #0
	strh	r0, [r1, #0]
	ldr	r0, [pc, #72]	@ 0x0800BB38
	movs	r1, #1
	strh	r1, [r0, #0]
	ldr	r0, [pc, #72]	@ 0x0800BB3C
	strh	r1, [r0, #0]
	ldr	r1, [pc, #72]	@ 0x0800BB40
	movs	r0, #0
	str	r0, [r1, #0]
	bl	sub_08002db4	@ 0x08002DB4
	movs	r0, #6
	bl	sub_08002d54	@ 0x08002D54
	.global	loc_0800bb06
loc_0800bb06:
	ldr	r0, [pc, #24]	@ 0x0800BB20
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #8
	bhi.n	loc_0800bba0	@ 0x0800BBA0
	lsls	r0, r0, #2
	ldr	r1, [pc, #44]	@ 0x0800BB44
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	gUnk_0200B074
	.word	gUnk_020060D0
	.word	gUnk_02004B70
	.word	gUnk_03001E90
	.word	gUnk_03000FB8
	.word	gUnk_030004A4
	.word	gUnk_03001174
	.word	gUnk_03001E98
	.word	gUnk_03000048
	.word	gUnk_03001ED4
	.word	0x0800BB48
	.short	0xBB6C
	lsrs	r0, r0, #32
	.short	0xBB72
	lsrs	r0, r0, #32
	.short	0xBB78
	lsrs	r0, r0, #32
	.short	0xBB7E
	lsrs	r0, r0, #32
	.short	0xBB84
	lsrs	r0, r0, #32
	.short	0xBB8A
	lsrs	r0, r0, #32
	.short	0xBB90
	lsrs	r0, r0, #32
	.short	0xBB96
	lsrs	r0, r0, #32
	.short	0xBB9C
	lsrs	r0, r0, #32
	bl	sub_0800c09c	@ 0x0800C09C
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800c34c	@ 0x0800C34C
	b.n	loc_0800bba0	@ 0x0800BBA0
	.word	0xFCEEF000
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800c610	@ 0x0800C610
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800cd60	@ 0x0800CD60
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800d0f4	@ 0x0800D0F4
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800c8a0	@ 0x0800C8A0
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800d450	@ 0x0800D450
	b.n	loc_0800bba0	@ 0x0800BBA0
	bl	sub_0800d85c	@ 0x0800D85C
	.global	loc_0800bba0
loc_0800bba0:
	ldr	r0, [pc, #32]	@ 0x0800BBC4
	ldrb	r0, [r0, #0]
	subs	r0, #9
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	cmp	r0, #1
	bhi.n	loc_0800bb06	@ 0x0800BB06
	bl	sub_080021dc	@ 0x080021DC
	ldr	r0, [pc, #20]	@ 0x0800BBC8
	ldr	r0, [r0, #0]
	cmp	r0, #2
	bne.n	loc_0800bc10	@ 0x0800BC10
	movs	r0, #16
	bl	sub_0800374c	@ 0x0800374C
	b.n	loc_0800bbe0	@ 0x0800BBE0
	movs	r0, r0
	.word	gUnk_020060D0
	.word	gUnk_0200EC48
	.global	loc_0800bbcc
loc_0800bbcc:
	bl	sub_080022e4	@ 0x080022E4
	ldr	r0, [pc, #40]	@ 0x0800BBFC
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl	sub_08004000	@ 0x08004000
	.global	loc_0800bbe0
loc_0800bbe0:
	ldr	r0, [pc, #28]	@ 0x0800BC00
	ldrh	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0800bbcc	@ 0x0800BBCC
	ldr	r0, [pc, #24]	@ 0x0800BC04
	movs	r1, #0
	strh	r1, [r0, #0]
	ldr	r0, [pc, #24]	@ 0x0800BC08
	strb	r1, [r0, #0]
	ldr	r1, [pc, #24]	@ 0x0800BC0C
	movs	r0, #13
	strh	r0, [r1, #0]
	b.n	loc_0800bc56	@ 0x0800BC56
	movs	r0, r0
	.word	gUnk_02000004
	.word	gUnk_03001E90
	.word	gUnk_03000048
	.word	gUnk_03001F30
	.word	gUnk_030023D8
	.global	loc_0800bc10
loc_0800bc10:
	ldr	r0, [pc, #48]	@ 0x0800BC44
	ldrh	r0, [r0, #0]
	cmp	r0, #5
	beq.n	loc_0800bc1c	@ 0x0800BC1C
	cmp	r0, #3
	bne.n	loc_0800bc22	@ 0x0800BC22
	.global	loc_0800bc1c
loc_0800bc1c:
	movs	r0, #16
	bl	sub_0800374c	@ 0x0800374C
	.global	loc_0800bc22
loc_0800bc22:
	ldr	r0, [pc, #36]	@ 0x0800BC48
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bls.n	loc_0800bc4c	@ 0x0800BC4C
	ldr	r0, [pc, #24]	@ 0x0800BC44
	ldrh	r0, [r0, #0]
	cmp	r0, #5
	bne.n	loc_0800bc3a	@ 0x0800BC3A
	bl	sub_080b8888	@ 0x080B8888
	bl	sub_080b8918	@ 0x080B8918
	.global	loc_0800bc3a
loc_0800bc3a:
	bl	sub_08002338	@ 0x08002338
	bl	sub_08002e0c	@ 0x08002E0C
	b.n	loc_0800bc56	@ 0x0800BC56
	.word	gUnk_030023D8
	.word	gUnk_030023AC
	.global	loc_0800bc4c
loc_0800bc4c:
	ldr	r1, [pc, #48]	@ 0x0800BC80
	movs	r0, #1
	strh	r0, [r1, #0]
	bl	sub_08002db4	@ 0x08002DB4
	.global	loc_0800bc56
loc_0800bc56:
	movs	r0, #0
	movs	r1, #0
	movs	r2, #0
	movs	r3, #0
	bl	sub_08010020	@ 0x08010020
	ldr	r2, [pc, #32]	@ 0x0800BC84
	ldrh	r1, [r2, #0]
	ldr	r0, [pc, #32]	@ 0x0800BC88
	ands	r0, r1
	strh	r0, [r2, #0]
	ldr	r0, [pc, #28]	@ 0x0800BC8C
	.global	loc_0800bc6e
loc_0800bc6e:
	ldrh	r0, [r0, #0]
	cmp	r0, #5
	beq.n	loc_0800bc90	@ 0x0800BC90
	cmp	r0, #5
	ble.n	loc_0800bcdc	@ 0x0800BCDC
	cmp	r0, #13
	beq.n	loc_0800bcb0	@ 0x0800BCB0
	b.n	loc_0800bcdc	@ 0x0800BCDC
	movs	r0, r0
	.word	gUnk_0300244C
	.word	gUnk_03001ED8
	.word	0x0000DFFF
	.word	gUnk_030023D8
	.global	loc_0800bc90
loc_0800bc90:
	ldr	r0, [pc, #20]	@ 0x0800BCA8
	ldr	r0, [r0, #0]
	bl	sub_080b8070	@ 0x080B8070
	bl	sub_080b8290	@ 0x080B8290
	bl	sub_0800b4a8	@ 0x0800B4A8
	ldr	r1, [pc, #8]	@ 0x0800BCAC
	movs	r0, #1
	strb	r0, [r1, #0]
	b.n	loc_0800bcdc	@ 0x0800BCDC
	.word	gUnk_030023E8
	.word	gUnk_02007FC0
	.global	loc_0800bcb0
loc_0800bcb0:
	ldr	r5, [pc, #48]	@ 0x0800BCE4
	ldrb	r0, [r5, #0]
	subs	r0, #6
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	cmp	r0, #1
	bhi.n	loc_0800bcd6	@ 0x0800BCD6
	ldr	r4, [pc, #40]	@ 0x0800BCE8
	ldr	r0, [r4, #0]
	bl	sub_080b8070	@ 0x080B8070
	bl	sub_080b8290	@ 0x080B8290
	ldrb	r0, [r5, #0]
	cmp	r0, #7
	bne.n	loc_0800bcd6	@ 0x0800BCD6
	ldr	r0, [r4, #0]
	bl	sub_080b81a0	@ 0x080B81A0
	.global	loc_0800bcd6
loc_0800bcd6:
	ldr	r1, [pc, #20]	@ 0x0800BCEC
	movs	r0, #4
	strh	r0, [r1, #0]
	.global	loc_0800bcdc
loc_0800bcdc:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_02006090
	.word	gUnk_030023E8
	.word	gUnk_03002150
	.thumb_func
	.global	sub_0800bcf0
sub_0800bcf0:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	ldr	r0, [pc, #60]	@ 0x0800BD38
	ldr	r1, [pc, #64]	@ 0x0800BD3C
	ldr	r1, [r1, #0]
	strb	r1, [r0, #0]
	movs	r0, #18
	bl	sub_08008c64	@ 0x08008C64
	movs	r5, #0
	ldr	r0, [pc, #52]	@ 0x0800BD40
	mov	r8, r0
	ldr	r7, [pc, #52]	@ 0x0800BD44
	movs	r2, #22
	add	r2, r8
	mov	r9, r2
	mov	r6, r8
	movs	r4, #0
	.global	loc_0800bd18
loc_0800bd18:
	adds	r0, r5, #0
	bl	sub_0800bda4	@ 0x0800BDA4
	ldrh	r0, [r6, #20]
	cmp	r0, #0
	beq.n	loc_0800bd48	@ 0x0800BD48
	mov	r0, r8
	adds	r0, #4
	adds	r0, r4, r0
	ldr	r0, [r0, #0]
	adds	r1, r4, #0
	cmp	r0, r7
	beq.n	loc_0800bd4a	@ 0x0800BD4A
	adds	r1, r4, #1
	b.n	loc_0800bd4a	@ 0x0800BD4A
	movs	r0, r0
	.word	gUnk_0200B074
	.word	gUnk_030023E8
	.global	loc_0800bd40
loc_0800bd40:
	.word	gUnk_0200E600
	.word	0x99999999
	.global	loc_0800bd48
loc_0800bd48:
	adds	r1, r4, #0
	.global	loc_0800bd4a
loc_0800bd4a:
	mov	r2, r9
	adds	r0, r2, r1
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	adds	r0, r5, #0
	bl	sub_0800be8c	@ 0x0800BE8C
	ldr	r2, [pc, #24]	@ 0x0800BD74
	adds	r0, r4, r2
	ldrh	r0, [r0, #20]
	cmp	r0, #0
	beq.n	loc_0800bd78	@ 0x0800BD78
	adds	r0, r2, #4
	adds	r0, r4, r0
	ldr	r0, [r0, #0]
	adds	r1, r4, #0
	cmp	r0, r7
	beq.n	loc_0800bd7a	@ 0x0800BD7A
	adds	r1, r4, #2
	b.n	loc_0800bd7a	@ 0x0800BD7A
	movs	r0, r0
	.word	gUnk_0200E600
	.global	loc_0800bd78
loc_0800bd78:
	adds	r1, r4, #0
	.global	loc_0800bd7a
loc_0800bd7a:
	adds	r0, r2, #0
	adds	r0, #18
	adds	r0, r0, r1
	ldrh	r1, [r0, #0]
	adds	r0, r5, #0
	movs	r2, #0
	bl	sub_0800bf6c	@ 0x0800BF6C
	movs	r0, #128
	lsls	r0, r0, #1
	adds	r6, r6, r0
	adds	r4, r4, r0
	adds	r5, #1
	cmp	r5, #2
	ble.n	loc_0800bd18	@ 0x0800BD18
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.thumb_func
	.global	sub_0800bda4
sub_0800bda4:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r5, r0, #0
	ldr	r3, [pc, #16]	@ 0x0800BDC0
	lsls	r2, r5, #8
	adds	r0, r3, #4
	adds	r0, r2, r0
	ldr	r1, [r0, #0]
	ldr	r0, [pc, #12]	@ 0x0800BDC4
	cmp	r1, r0
	bne.n	loc_0800bdcc	@ 0x0800BDCC
	ldr	r4, [pc, #8]	@ 0x0800BDC8
	b.n	loc_0800bdda	@ 0x0800BDDA
	.word	gUnk_0200E600
	.word	0x99999999
	.word	0x08553510
	.global	loc_0800bdcc
loc_0800bdcc:
	adds	r2, r2, r3
	ldrh	r1, [r2, #16]
	movs	r0, #2
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0800be18	@ 0x0800BE18
	ldr	r4, [pc, #52]	@ 0x0800BE10
	.global	loc_0800bdda
loc_0800bdda:
	lsls	r5, r5, #6
	mov	r8, r5
	movs	r2, #144
	lsls	r2, r2, #2
	add	r2, r8
	lsls	r2, r2, #5
	ldr	r5, [pc, #44]	@ 0x0800BE14
	adds	r2, r2, r5
	movs	r6, #192
	lsls	r6, r6, #1
	movs	r0, #3
	adds	r1, r4, #0
	adds	r3, r6, #0
	bl	sub_080017e4	@ 0x080017E4
	adds	r4, r4, r6
	movs	r2, #152
	lsls	r2, r2, #2
	add	r2, r8
	lsls	r2, r2, #5
	adds	r2, r2, r5
	movs	r0, #3
	adds	r1, r4, #0
	adds	r3, r6, #0
	bl	sub_080017e4	@ 0x080017E4
	b.n	loc_0800be74	@ 0x0800BE74
	.word	0x08553210
	.word	gUnk_06010000
	.global	loc_0800be18
loc_0800be18:
	movs	r1, #18
	ldrsh	r0, [r2, r1]
	bl	sub_08002f14	@ 0x08002F14
	ldr	r0, [pc, #92]	@ 0x0800BE80
	movs	r1, #1
	ldrsb	r1, [r0, r1]
	movs	r2, #2
	ldrsb	r2, [r0, r2]
	lsls	r0, r2, #2
	adds	r0, r0, r2
	lsls	r0, r0, #1
	adds	r1, r1, r0
	lsls	r4, r1, #1
	lsls	r1, r1, #2
	adds	r1, r1, r4
	lsls	r1, r1, #7
	ldr	r6, [pc, #72]	@ 0x0800BE84
	adds	r1, r1, r6
	lsls	r7, r5, #6
	movs	r0, #144
	lsls	r0, r0, #2
	adds	r2, r7, r0
	lsls	r2, r2, #5
	ldr	r5, [pc, #60]	@ 0x0800BE88
	adds	r2, r2, r5
	subs	r0, #192
	mov	r8, r0
	movs	r0, #3
	mov	r3, r8
	bl	sub_080017e4	@ 0x080017E4
	adds	r4, #1
	lsls	r1, r4, #1
	adds	r1, r1, r4
	lsls	r1, r1, #7
	adds	r1, r1, r6
	movs	r0, #152
	lsls	r0, r0, #2
	adds	r2, r7, r0
	lsls	r2, r2, #5
	adds	r2, r2, r5
	movs	r0, #3
	mov	r3, r8
	bl	sub_080017e4	@ 0x080017E4
	.global	loc_0800be74
loc_0800be74:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03001F08
	.word	0x08551110
	.word	gUnk_06010000
	.thumb_func
	.global	sub_0800be8c
sub_0800be8c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	mov	r9, r0
	adds	r7, r1, #0
	cmp	r7, #6
	bls.n	loc_0800be9e	@ 0x0800BE9E
	movs	r7, #7
	.global	loc_0800be9e
loc_0800be9e:
	lsls	r4, r7, #4
	subs	r4, r4, r7
	lsls	r1, r4, #5
	ldr	r0, [pc, #92]	@ 0x0800BF04
	mov	r8, r0
	add	r1, r8
	ldr	r0, [pc, #92]	@ 0x0800BF08
	mov	r2, r9
	lsls	r5, r2, #1
	adds	r5, r5, r0
	ldrh	r2, [r5, #0]
	lsls	r2, r2, #5
	ldr	r6, [pc, #84]	@ 0x0800BF0C
	adds	r2, r2, r6
	movs	r0, #3
	movs	r3, #160
	bl	sub_080017e4	@ 0x080017E4
	adds	r1, r4, #5
	lsls	r1, r1, #5
	add	r1, r8
	ldrh	r2, [r5, #0]
	adds	r2, #32
	lsls	r2, r2, #5
	adds	r2, r2, r6
	movs	r0, #3
	movs	r3, #160
	bl	sub_080017e4	@ 0x080017E4
	adds	r4, #10
	lsls	r4, r4, #5
	add	r4, r8
	ldrh	r2, [r5, #0]
	adds	r2, #64
	lsls	r2, r2, #5
	adds	r2, r2, r6
	movs	r0, #3
	adds	r1, r4, #0
	movs	r3, #160
	bl	sub_080017e4	@ 0x080017E4
	mov	r0, r9
	adds	r1, r7, #0
	bl	sub_0800bf10	@ 0x0800BF10
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	0x08553810
	.word	0x08731E18
	.word	gUnk_06010000
	.thumb_func
	.global	sub_0800bf10
sub_0800bf10:
	.thumb
	push	{lr}
	adds	r2, r0, #0
	cmp	r1, #6
	bls.n	loc_0800bf1a	@ 0x0800BF1A
	movs	r1, #7
	.global	loc_0800bf1a
loc_0800bf1a:
	ldr	r0, [pc, #32]	@ 0x0800BF3C
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r2, r0
	bne.n	loc_0800bf48	@ 0x0800BF48
	lsls	r1, r1, #5
	ldr	r0, [pc, #20]	@ 0x0800BF40
	adds	r1, r1, r0
	lsls	r2, r2, #5
	ldr	r0, [pc, #20]	@ 0x0800BF44
	adds	r2, r2, r0
	movs	r0, #2
	movs	r3, #32
	bl	sub_080017e4	@ 0x080017E4
	b.n	loc_0800bf5e	@ 0x0800BF5E
	.word	gUnk_0200B074
	.word	0x08554B78
	.word	gUnk_03001490
	.global	loc_0800bf48
loc_0800bf48:
	adds	r1, #8
	lsls	r1, r1, #5
	ldr	r0, [pc, #20]	@ 0x0800BF64
	adds	r1, r1, r0
	lsls	r2, r2, #5
	ldr	r0, [pc, #20]	@ 0x0800BF68
	adds	r2, r2, r0
	movs	r0, #2
	movs	r3, #32
	bl	sub_080017e4	@ 0x080017E4
	.global	loc_0800bf5e
loc_0800bf5e:
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	0x08554B78
	.word	gUnk_03001490
