@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08040b40_0804335c_080449c8_08047fe8_08049f98, chunk 1/2: 0x08049F98-0x0804A258 (thumb_code, 0x2C0 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08049F98 sub_08049f98

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08040b40_0804335c_080449c8_08047fe8_08049f98, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08040b40_0804335c_080449c8_08047fe8_08049f98
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08040b40_0804335c_080449c8_08047fe8_08049f98:
	.thumb_func
	.global	sub_08049f98
sub_08049f98:
	.thumb
	push	{r4, r5, lr}
	ldr	r2, [pc, #52]	@ 0x08049FD0
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrb	r0, [r1, #4]
	strb	r0, [r1, #5]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #13
	strb	r0, [r1, #4]
	ldr	r1, [r2, #0]
	movs	r0, #43
	strb	r0, [r1, #21]
	ldr	r1, [r2, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #5]
	cmp	r0, #13
	beq.n	loc_08049fe2	@ 0x08049FE2
	cmp	r0, #5
	bne.n	loc_08049fd4	@ 0x08049FD4
	adds	r1, #115
	movs	r0, #4
	b.n	loc_08049fd8	@ 0x08049FD8
	movs	r0, r0
	.word	gUnk_03002490
	.global	loc_08049fd4
loc_08049fd4:
	adds	r1, #115
	movs	r0, #0
	.global	loc_08049fd8
loc_08049fd8:
	strb	r0, [r1, #0]
	ldr	r0, [r2, #0]
	adds	r0, #128
	movs	r1, #15
	strb	r1, [r0, #0]
	.global	loc_08049fe2
loc_08049fe2:
	ldr	r0, [r2, #0]
	adds	r0, #115
	ldrb	r0, [r0, #0]
	cmp	r0, #4
	bls.n	loc_08049fee	@ 0x08049FEE
	b.n	loc_0804a250	@ 0x0804A250
	.global	loc_08049fee
loc_08049fee:
	lsls	r0, r0, #2
	ldr	r1, [pc, #4]	@ 0x08049FF8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	.word	0x08049FFC
	.short	0xA010
	lsrs	r4, r0, #32
	.short	0xA050
	lsrs	r4, r0, #32
	.short	0xA0FA
	lsrs	r4, r0, #32
	.short	0xA134
	lsrs	r4, r0, #32
	.short	0xA1B6
	lsrs	r4, r0, #32
	ldr	r4, [pc, #548]	@ 0x0804A238
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #42
	movs	r2, #5
	bl	sub_0805afac	@ 0x0805AFAC
	movs	r0, #2
	bl	sub_0803e050	@ 0x0803E050
	movs	r0, #5
	bl	sub_0803e650	@ 0x0803E650
	ldr	r0, [pc, #520]	@ 0x0804A23C
	bl	sub_08006338	@ 0x08006338
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	.global	loc_0804a040
loc_0804a040:
	adds	r0, #115
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #4
	strh	r0, [r1, #20]
	movs	r0, #38
	bl	sub_080413a4	@ 0x080413A4
	ldr	r4, [pc, #480]	@ 0x0804A238
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	movs	r0, #3
	movs	r1, #0
	bl	sub_0803e1b8	@ 0x0803E1B8
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r2, [r0, #0]
	ldr	r1, [pc, #460]	@ 0x0804A240
	str	r1, [r2, #108]
	ldr	r0, [r0, #0]
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	movs	r0, #174
	bl	sub_0803e374	@ 0x0803E374
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #42
	movs	r2, #0
	bl	sub_0805afac	@ 0x0805AFAC
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #42
	movs	r2, #1
	bl	sub_0805afac	@ 0x0805AFAC
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #42
	movs	r2, #2
	bl	sub_0805afac	@ 0x0805AFAC
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #42
	movs	r2, #4
	bl	sub_0805afac	@ 0x0805AFAC
	ldr	r1, [r4, #0]
	adds	r2, r1, #0
	adds	r2, #70
	movs	r0, #0
	.global	loc_0804a0dc
loc_0804a0dc:
	strh	r0, [r2, #0]
	movs	r5, #2
	str	r5, [r1, #40]
	movs	r0, #23
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	movs	r0, #0
	bl	sub_080413a4	@ 0x080413A4
	movs	r0, #10
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #115
	strb	r5, [r0, #0]
	ldr	r4, [pc, #316]	@ 0x0804A238
	ldr	r2, [r4, #0]
	adds	r2, #136
	ldr	r1, [r2, #0]
	adds	r1, #66
	ldrh	r3, [r1, #0]
	ldr	r0, [pc, #316]	@ 0x0804A244
	ands	r0, r3
	strh	r0, [r1, #0]
	ldr	r0, [r2, #0]
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	movs	r0, #255
	movs	r1, #0
	bl	sub_0803e1b8	@ 0x0803E1B8
	movs	r0, #13
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	movs	r0, #1
	bl	sub_080413a4	@ 0x080413A4
	movs	r0, #5
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #115
	movs	r1, #3
	strb	r1, [r0, #0]
	ldr	r4, [pc, #256]	@ 0x0804A238
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #66
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #256]	@ 0x0804A244
	ands	r0, r2
	.global	loc_0804a144
loc_0804a144:
	movs	r5, #0
	strh	r0, [r1, #0]
	movs	r0, #2
	bl	sub_080413a4	@ 0x080413A4
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	ldrb	r0, [r1, #4]
	strb	r0, [r1, #5]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #5
	strb	r0, [r1, #4]
	ldr	r1, [r4, #0]
	movs	r0, #7
	strb	r0, [r1, #21]
	ldr	r1, [r4, #0]
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	str	r5, [r0, #108]
	adds	r1, #115
	movs	r0, #4
	strb	r0, [r1, #0]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #150
	lsls	r0, r0, #1
	strh	r0, [r1, #20]
	ldr	r0, [pc, #192]	@ 0x0804A248
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r4, #0]
	adds	r0, #108
	strh	r5, [r0, #0]
	.global	loc_0804a196
loc_0804a196:
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	adds	r1, #108
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	cmp	r0, #4
	ble.n	loc_0804a196	@ 0x0804A196
	ldr	r4, [pc, #128]	@ 0x0804A238
	ldr	r2, [r4, #0]
	adds	r2, #136
	ldr	r1, [r2, #0]
	adds	r1, #66
	.global	loc_0804a1c0
loc_0804a1c0:
	ldrh	r3, [r1, #0]
	ldr	r0, [pc, #128]	@ 0x0804A244
	ands	r0, r3
	strh	r0, [r1, #0]
	ldr	r2, [r2, #0]
	ldrb	r0, [r2, #4]
	cmp	r0, #5
	beq.n	loc_0804a1f2	@ 0x0804A1F2
	strb	r0, [r2, #5]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #5
	strb	r0, [r1, #4]
	ldr	r1, [r4, #0]
	movs	r0, #7
	strb	r0, [r1, #21]
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #0
	str	r0, [r1, #108]
	movs	r0, #2
	bl	sub_080413a4	@ 0x080413A4
	.global	loc_0804a1f2
loc_0804a1f2:
	ldr	r2, [r4, #0]
	adds	r3, r2, #0
	adds	r3, #136
	ldr	r1, [r3, #0]
	movs	r0, #30
	strh	r0, [r1, #20]
	ldr	r1, [pc, #76]	@ 0x0804A24C
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #13]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #2
	adds	r1, #2
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	adds	r2, #70
	strh	r0, [r2, #0]
	.global	loc_0804a214
loc_0804a214:
	ldr	r0, [r4, #0]
	adds	r0, #70
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	bl	sub_08006338	@ 0x08006338
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0804a214	@ 0x0804A214
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x00000B2D
	.word	0x0873CF5C
	.word	0x0000FFEF
	.word	0x00000AD2
	.word	gUnk_0873D3B8
	.global	loc_0804a250
loc_0804a250:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.short	0x0000
