@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930, chunk 2/2: 0x0801FF84-0x0802069C (thumb_code, 0x718 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x0801FF84 sub_0801ff84

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930_01:
	.thumb_func
	.global	sub_0801ff84
sub_0801ff84:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r0, [pc, #96]	@ 0x0801FFF0
	ldr	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0801ff98	@ 0x0801FF98
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0801ff98
loc_0801ff98:
	cmp	r0, #0
	bgt.n	loc_0801ff9e	@ 0x0801FF9E
	b.n	loc_080201e8	@ 0x080201E8
	.global	loc_0801ff9e
loc_0801ff9e:
	ldr	r0, [pc, #84]	@ 0x0801FFF4
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #80]	@ 0x0801FFF8
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	adds	r0, r0, r1
	ldr	r4, [pc, #76]	@ 0x0801FFFC
	movs	r3, #0
	ldrsh	r1, [r4, r3]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_08020078	@ 0x08020078
	ldr	r2, [pc, #68]	@ 0x08020000
	ldrb	r0, [r2, #11]
	movs	r3, #251
	ands	r3, r0
	strb	r3, [r2, #11]
	ldr	r0, [pc, #60]	@ 0x08020004
	ldr	r1, [pc, #64]	@ 0x08020008
	ldrh	r1, [r1, #0]
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r5, r2, #0
	cmp	r0, #0
	beq.n	loc_08020010	@ 0x08020010
	ldr	r0, [pc, #48]	@ 0x0802000C
	adds	r0, r1, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08020010	@ 0x08020010
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020010	@ 0x08020010
	movs	r1, #4
	b.n	loc_08020236	@ 0x08020236
	movs	r0, r0
	.word	gUnk_03005598
	.word	gUnk_03005560
	.word	gUnk_0300559C
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.global	loc_08020010
loc_08020010:
	ldr	r0, [pc, #76]	@ 0x08020060
	ldr	r1, [pc, #80]	@ 0x08020064
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08020024	@ 0x08020024
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020024
loc_08020024:
	ldr	r0, [pc, #64]	@ 0x08020068
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_08020030	@ 0x08020030
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020030
loc_08020030:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802003a	@ 0x0802003A
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0802003a
loc_0802003a:
	ldr	r0, [pc, #48]	@ 0x0802006C
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08020056	@ 0x08020056
	ldr	r0, [pc, #36]	@ 0x08020070
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_08020056	@ 0x08020056
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020056
loc_08020056:
	ldr	r2, [pc, #28]	@ 0x08020074
	ldrb	r1, [r2, #11]
	movs	r0, #4
	b.n	loc_080202a8	@ 0x080202A8
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005510
	.word	gUnk_08732CF0
	.word	0x08732DF0
	.word	gUnk_03005570
	.word	gUnk_03005530
	.global	loc_08020078
loc_08020078:
	ldr	r0, [pc, #116]	@ 0x080200F0
	ldr	r1, [pc, #120]	@ 0x080200F4
	ldrh	r3, [r1, #0]
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_080200a0	@ 0x080200A0
	ldr	r0, [pc, #108]	@ 0x080200F8
	movs	r5, #0
	ldrsh	r1, [r0, r5]
	ldr	r2, [pc, #104]	@ 0x080200FC
	ands	r1, r2
	movs	r7, #0
	ldrsh	r0, [r4, r7]
	ands	r0, r2
	cmp	r1, r0
	beq.n	loc_080200a0	@ 0x080200A0
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080200a0
loc_080200a0:
	ldr	r0, [pc, #92]	@ 0x08020100
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020114	@ 0x08020114
	ldr	r0, [pc, #84]	@ 0x08020104
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_080200ba	@ 0x080200BA
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080200ba
loc_080200ba:
	ldr	r0, [pc, #76]	@ 0x08020108
	ldrb	r1, [r0, #11]
	movs	r0, #4
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080200c8	@ 0x080200C8
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080200c8
loc_080200c8:
	ldr	r0, [pc, #64]	@ 0x0802010C
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080200e2	@ 0x080200E2
	ldrh	r1, [r4, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_080200e2	@ 0x080200E2
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080200e2
loc_080200e2:
	ldr	r0, [pc, #44]	@ 0x08020110
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	b.n	loc_08020116	@ 0x08020116
	movs	r0, r0
	.word	gUnk_087339F0
	.word	gUnk_03005578
	.word	gUnk_03005520
	.word	0x0000FFF0
	.word	gUnk_087336F0
	.word	gUnk_08732CF0
	.word	gUnk_03005530
	.word	0x08732DF0
	.word	0x087338F0
	.global	loc_08020114
loc_08020114:
	adds	r0, r3, #0
	.global	loc_08020116
loc_08020116:
	ldr	r1, [pc, #152]	@ 0x080201B0
	mov	r8, r1
	movs	r5, #1
	strb	r5, [r1, #0]
	ldr	r4, [pc, #148]	@ 0x080201B4
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r7, [pc, #136]	@ 0x080201B8
	ldr	r6, [pc, #136]	@ 0x080201BC
	ldrh	r0, [r6, #0]
	adds	r0, r0, r7
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08020146	@ 0x08020146
	adds	r0, r5, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020146	@ 0x08020146
	b.n	loc_0802042e	@ 0x0802042E
	.global	loc_08020146
loc_08020146:
	movs	r2, #0
	ldrsh	r0, [r4, r2]
	ldr	r1, [pc, #116]	@ 0x080201C0
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	adds	r0, r0, r1
	ldr	r4, [pc, #112]	@ 0x080201C4
	movs	r5, #0
	ldrsh	r1, [r4, r5]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_08020162	@ 0x08020162
	b.n	loc_0802042e	@ 0x0802042E
	.global	loc_08020162
loc_08020162:
	ldr	r0, [pc, #100]	@ 0x080201C8
	ldrh	r2, [r6, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080201d4	@ 0x080201D4
	adds	r0, r2, r7
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0802017c	@ 0x0802017C
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0802017c
loc_0802017c:
	mov	r7, r8
	ldrb	r1, [r7, #11]
	movs	r0, #4
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802018a	@ 0x0802018A
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0802018a
loc_0802018a:
	ldr	r0, [pc, #64]	@ 0x080201CC
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080201a4	@ 0x080201A4
	ldrh	r1, [r4, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_080201a4	@ 0x080201A4
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080201a4
loc_080201a4:
	ldr	r0, [pc, #40]	@ 0x080201D0
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	b.n	loc_080201d6	@ 0x080201D6
	.word	gUnk_03005530
	.word	gUnk_03005560
	.word	gUnk_08732CF0
	.word	gUnk_03005578
	.word	gUnk_0300559C
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	0x08732DF0
	.word	0x087338F0
	.global	loc_080201d4
loc_080201d4:
	adds	r0, r2, #0
	.global	loc_080201d6
loc_080201d6:
	ldr	r4, [pc, #12]	@ 0x080201E4
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	b.n	loc_08020428	@ 0x08020428
	movs	r0, r0
	.word	gUnk_03005560
	.global	loc_080201e8
loc_080201e8:
	ldr	r0, [pc, #84]	@ 0x08020240
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #84]	@ 0x08020244
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	adds	r0, r0, r1
	ldr	r4, [pc, #80]	@ 0x08020248
	movs	r3, #0
	ldrsh	r1, [r4, r3]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_080202c8	@ 0x080202C8
	ldr	r2, [pc, #68]	@ 0x0802024C
	ldrb	r0, [r2, #11]
	movs	r3, #253
	ands	r3, r0
	strb	r3, [r2, #11]
	ldr	r0, [pc, #64]	@ 0x08020250
	ldr	r1, [pc, #64]	@ 0x08020254
	ldrh	r1, [r1, #0]
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r5, r2, #0
	cmp	r0, #0
	beq.n	loc_0802025c	@ 0x0802025C
	ldr	r0, [pc, #52]	@ 0x08020258
	adds	r0, r1, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_0802025c	@ 0x0802025C
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802025c	@ 0x0802025C
	movs	r1, #2
	.global	loc_08020236
loc_08020236:
	adds	r0, r3, #0
	orrs	r0, r1
	strb	r0, [r5, #11]
	b.n	loc_0802043c	@ 0x0802043C
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.global	loc_0802025c
loc_0802025c:
	ldr	r0, [pc, #80]	@ 0x080202B0
	ldr	r1, [pc, #84]	@ 0x080202B4
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08020270	@ 0x08020270
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020270
loc_08020270:
	ldr	r0, [pc, #68]	@ 0x080202B8
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_0802027c	@ 0x0802027C
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0802027c
loc_0802027c:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020286	@ 0x08020286
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020286
loc_08020286:
	ldr	r0, [pc, #52]	@ 0x080202BC
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080202a2	@ 0x080202A2
	ldr	r0, [pc, #40]	@ 0x080202C0
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_080202a2	@ 0x080202A2
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080202a2
loc_080202a2:
	ldr	r2, [pc, #32]	@ 0x080202C4
	ldrb	r1, [r2, #11]
	movs	r0, #2
	.global	loc_080202a8
loc_080202a8:
	orrs	r0, r1
	strb	r0, [r2, #11]
	b.n	loc_0802043c	@ 0x0802043C
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005594
	.word	gUnk_08732CF0
	.word	0x08732DF0
	.word	gUnk_03005570
	.word	gUnk_03005530
	.global	loc_080202c8
loc_080202c8:
	ldr	r0, [pc, #116]	@ 0x08020340
	ldr	r1, [pc, #120]	@ 0x08020344
	ldrh	r3, [r1, #0]
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_080202f0	@ 0x080202F0
	ldr	r0, [pc, #108]	@ 0x08020348
	movs	r5, #0
	ldrsh	r1, [r0, r5]
	ldr	r2, [pc, #104]	@ 0x0802034C
	ands	r1, r2
	movs	r7, #0
	ldrsh	r0, [r4, r7]
	ands	r0, r2
	cmp	r1, r0
	beq.n	loc_080202f0	@ 0x080202F0
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_080202f0
loc_080202f0:
	ldr	r0, [pc, #92]	@ 0x08020350
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020364	@ 0x08020364
	ldr	r0, [pc, #84]	@ 0x08020354
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0802030a	@ 0x0802030A
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_0802030a
loc_0802030a:
	ldr	r0, [pc, #76]	@ 0x08020358
	ldrb	r1, [r0, #11]
	movs	r0, #2
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020318	@ 0x08020318
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020318
loc_08020318:
	ldr	r0, [pc, #64]	@ 0x0802035C
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08020332	@ 0x08020332
	ldrh	r1, [r4, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_08020332	@ 0x08020332
	b.n	loc_0802043c	@ 0x0802043C
	.global	loc_08020332
loc_08020332:
	ldr	r0, [pc, #44]	@ 0x08020360
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	b.n	loc_08020366	@ 0x08020366
	movs	r0, r0
	.word	gUnk_087339F0
	.word	gUnk_03005578
	.word	gUnk_03005520
	.word	0x0000FFF0
	.word	gUnk_087336F0
	.word	gUnk_08732CF0
	.word	gUnk_03005530
	.word	0x08732DF0
	.word	0x087338F0
	.global	loc_08020364
loc_08020364:
	adds	r0, r3, #0
	.global	loc_08020366
loc_08020366:
	ldr	r7, [pc, #144]	@ 0x080203F8
	movs	r1, #2
	mov	r8, r1
	mov	r2, r8
	strb	r2, [r7, #0]
	ldr	r4, [pc, #136]	@ 0x080203FC
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r6, [pc, #124]	@ 0x08020400
	ldr	r5, [pc, #128]	@ 0x08020404
	ldrh	r0, [r5, #0]
	adds	r0, r0, r6
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_08020396	@ 0x08020396
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802042e	@ 0x0802042E
	.global	loc_08020396
loc_08020396:
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	ldr	r1, [pc, #108]	@ 0x08020408
	movs	r4, #0
	ldrsh	r1, [r1, r4]
	adds	r0, r0, r1
	ldr	r4, [pc, #104]	@ 0x0802040C
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_0802042e	@ 0x0802042E
	ldr	r0, [pc, #92]	@ 0x08020410
	ldrh	r2, [r5, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802041c	@ 0x0802041C
	adds	r0, r2, r6
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_0802043c	@ 0x0802043C
	ldrb	r1, [r7, #11]
	mov	r0, r8
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0802043c	@ 0x0802043C
	ldr	r0, [pc, #64]	@ 0x08020414
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080203ea	@ 0x080203EA
	ldrh	r1, [r4, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	bgt.n	loc_0802043c	@ 0x0802043C
	.global	loc_080203ea
loc_080203ea:
	ldr	r0, [pc, #44]	@ 0x08020418
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	b.n	loc_0802041e	@ 0x0802041E
	movs	r0, r0
	.word	gUnk_03005530
	.word	gUnk_03005560
	.word	gUnk_08732CF0
	.word	gUnk_03005578
	.word	gUnk_0300551C
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	0x08732DF0
	.word	0x087338F0
	.global	loc_0802041c
loc_0802041c:
	adds	r0, r2, #0
	.global	loc_0802041e
loc_0802041e:
	ldr	r4, [pc, #436]	@ 0x080205D4
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	.global	loc_08020428
loc_08020428:
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_0802042e
loc_0802042e:
	ldr	r2, [pc, #424]	@ 0x080205D8
	ldr	r1, [pc, #424]	@ 0x080205DC
	ldr	r0, [pc, #428]	@ 0x080205E0
	ldrh	r0, [r0, #0]
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	strb	r0, [r2, #4]
	.global	loc_0802043c
loc_0802043c:
	ldr	r0, [pc, #420]	@ 0x080205E4
	ldr	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08020446	@ 0x08020446
	b.n	loc_080205fc	@ 0x080205FC
	.global	loc_08020446
loc_08020446:
	ldr	r3, [pc, #396]	@ 0x080205D4
	mov	r9, r3
	movs	r4, #0
	ldrsh	r0, [r3, r4]
	ldr	r5, [pc, #408]	@ 0x080205E8
	movs	r7, #0
	ldrsh	r1, [r5, r7]
	ldr	r2, [pc, #404]	@ 0x080205EC
	mov	r8, r2
	movs	r3, #0
	ldrsh	r2, [r2, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_080204d8	@ 0x080204D8
	ldr	r0, [pc, #392]	@ 0x080205F0
	ldr	r4, [pc, #372]	@ 0x080205E0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r0, #0
	bne.n	loc_080204d8	@ 0x080204D8
	ldr	r6, [pc, #352]	@ 0x080205D8
	movs	r0, #1
	strb	r0, [r6, #1]
	ldr	r7, [pc, #348]	@ 0x080205DC
	mov	sl, r7
	ldrh	r0, [r4, #0]
	add	r0, sl
	ldrb	r0, [r0, #0]
	strb	r0, [r6, #4]
	ldrh	r0, [r4, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	ldr	r1, [pc, #348]	@ 0x080205F4
	ldrh	r0, [r4, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #64
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080204d2	@ 0x080204D2
	mov	r1, r9
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	movs	r3, #0
	ldrsh	r1, [r5, r3]
	mov	r7, r8
	movs	r3, #0
	ldrsh	r2, [r7, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_080204d2	@ 0x080204D2
	ldrh	r0, [r4, #0]
	add	r0, sl
	ldrb	r0, [r0, #0]
	strb	r0, [r6, #4]
	ldrh	r0, [r4, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	.global	loc_080204d2
loc_080204d2:
	ldr	r1, [pc, #260]	@ 0x080205D8
	movs	r0, #0
	strb	r0, [r1, #11]
	.global	loc_080204d8
loc_080204d8:
	ldr	r4, [pc, #248]	@ 0x080205D4
	movs	r5, #0
	ldrsh	r0, [r4, r5]
	ldr	r7, [pc, #280]	@ 0x080205F8
	movs	r2, #0
	ldrsh	r1, [r7, r2]
	ldr	r4, [pc, #256]	@ 0x080205E8
	movs	r3, #0
	ldrsh	r2, [r4, r3]
	adds	r1, r1, r2
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	bne.n	loc_080204f6	@ 0x080204F6
	b.n	loc_080205fc	@ 0x080205FC
	.global	loc_080204f6
loc_080204f6:
	ldr	r5, [pc, #248]	@ 0x080205F0
	mov	sl, r5
	ldr	r6, [pc, #228]	@ 0x080205E0
	ldrh	r0, [r6, #0]
	add	r0, sl
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802052e	@ 0x0802052E
	ldr	r2, [pc, #204]	@ 0x080205D8
	ldrb	r1, [r2, #11]
	movs	r0, #1
	ands	r0, r1
	adds	r5, r2, #0
	cmp	r0, #0
	bne.n	loc_0802051a	@ 0x0802051A
	b.n	loc_08020680	@ 0x08020680
	.global	loc_0802051a
loc_0802051a:
	ldrb	r0, [r5, #12]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	movs	r3, #0
	ldrsh	r2, [r7, r3]
	adds	r1, r1, r2
	asrs	r1, r1, #4
	cmp	r0, r1
	ble.n	loc_0802052e	@ 0x0802052E
	b.n	loc_08020680	@ 0x08020680
	.global	loc_0802052e
loc_0802052e:
	ldr	r5, [pc, #168]	@ 0x080205D8
	movs	r0, #1
	mov	r8, r0
	mov	r1, r8
	strb	r1, [r5, #2]
	ldr	r2, [pc, #160]	@ 0x080205DC
	mov	r9, r2
	ldrh	r0, [r6, #0]
	add	r0, r9
	ldrb	r0, [r0, #0]
	strb	r0, [r5, #4]
	ldrh	r0, [r6, #0]
	bl	sub_080219b0	@ 0x080219B0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r1, [pc, #160]	@ 0x080205F4
	ldrh	r0, [r6, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080205b8	@ 0x080205B8
	ldr	r3, [pc, #112]	@ 0x080205D4
	movs	r1, #0
	ldrsh	r0, [r3, r1]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	movs	r3, #0
	ldrsh	r2, [r7, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_080205b8	@ 0x080205B8
	ldrh	r2, [r6, #0]
	mov	r1, sl
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080205a4	@ 0x080205A4
	ldrb	r1, [r5, #11]
	mov	r0, r8
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080205b8	@ 0x080205B8
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	movs	r3, #0
	ldrsh	r1, [r7, r3]
	adds	r0, r0, r1
	asrs	r0, r0, #4
	ldrb	r7, [r5, #12]
	cmp	r0, r7
	blt.n	loc_080205b8	@ 0x080205B8
	.global	loc_080205a4
loc_080205a4:
	mov	r1, r9
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	strb	r0, [r5, #4]
	adds	r0, r2, #0
	bl	sub_080219b0	@ 0x080219B0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_080205b8
loc_080205b8:
	ldr	r2, [pc, #28]	@ 0x080205D8
	movs	r0, #1
	strb	r0, [r2, #6]
	ldr	r0, [pc, #40]	@ 0x080205E8
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	ldr	r1, [pc, #48]	@ 0x080205F8
	movs	r4, #0
	ldrsh	r1, [r1, r4]
	adds	r0, r0, r1
	adds	r0, #1
	asrs	r0, r0, #4
	strb	r0, [r2, #12]
	b.n	loc_08020688	@ 0x08020688
	.word	gUnk_03005560
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005578
	.word	gUnk_03005514
	.word	gUnk_03005570
	.word	gUnk_0300557C
	.word	gUnk_087336F0
	.word	0x08732DF0
	.word	gUnk_03005584
	.global	loc_080205fc
loc_080205fc:
	ldr	r2, [pc, #68]	@ 0x08020644
	ldr	r0, [pc, #72]	@ 0x08020648
	ldrh	r0, [r0, #0]
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	ldr	r5, [pc, #64]	@ 0x0802064C
	cmp	r0, #0
	beq.n	loc_08020680	@ 0x08020680
	ldrb	r1, [r5, #11]
	movs	r0, #1
	orrs	r0, r1
	strb	r0, [r5, #11]
	ldr	r0, [pc, #52]	@ 0x08020650
	ldrh	r1, [r0, #0]
	adds	r0, r1, r2
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020660	@ 0x08020660
	ldr	r0, [pc, #40]	@ 0x08020654
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08020660	@ 0x08020660
	ldr	r0, [pc, #36]	@ 0x08020658
	movs	r7, #0
	ldrsh	r0, [r0, r7]
	ldr	r1, [pc, #32]	@ 0x0802065C
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	adds	r0, r0, r1
	b.n	loc_08020670	@ 0x08020670
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005588
	.word	gUnk_03005530
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.word	gUnk_03005570
	.word	gUnk_03005584
	.global	loc_08020660
loc_08020660:
	ldr	r0, [pc, #20]	@ 0x08020678
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	ldr	r1, [pc, #20]	@ 0x0802067C
	movs	r4, #0
	ldrsh	r1, [r1, r4]
	adds	r0, r0, r1
	adds	r0, #16
	.global	loc_08020670
loc_08020670:
	asrs	r0, r0, #4
	strb	r0, [r5, #12]
	b.n	loc_08020688	@ 0x08020688
	movs	r0, r0
	.word	gUnk_03005570
	.word	gUnk_03005584
	.global	loc_08020680
loc_08020680:
	ldrb	r1, [r5, #11]
	movs	r0, #254
	ands	r0, r1
	strb	r0, [r5, #11]
	.global	loc_08020688
loc_08020688:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	bx	lr
	.short	0x0000
