@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930, chunk 2/2: 0x08020698-0x0802069C (thumb_code, 0x4 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08020698 sub_08020698

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_0801c444_0801c690_0801c930_01:
	.thumb_func
	.global	sub_08020698
sub_08020698:
	.thumb
	bx	lr
	.short	0x0000
