@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0, chunk 1/2: 0x080207A0-0x08020B38 (thumb_code, 0x398 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x080207A0 sub_080207a0

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0:
	.thumb_func
	.global	sub_080207a0
sub_080207a0:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r0, [pc, #72]	@ 0x080207F4
	mov	r8, r0
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r4, [pc, #68]	@ 0x080207F8
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	beq.n	loc_08020850	@ 0x08020850
	ldr	r0, [pc, #56]	@ 0x080207FC
	ldr	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_0802080c	@ 0x0802080C
	cmp	r0, #0
	bgt.n	loc_0802088c	@ 0x0802088C
	ldr	r0, [pc, #48]	@ 0x08020800
	ldr	r1, [pc, #52]	@ 0x08020804
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r3, r1, #0
	cmp	r0, #0
	bne.n	loc_080207e2	@ 0x080207E2
	b.n	loc_08020976	@ 0x08020976
	.global	loc_080207e2
loc_080207e2:
	ldr	r2, [pc, #36]	@ 0x08020808
	ldrb	r1, [r2, #11]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080207f0	@ 0x080207F0
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_080207f0
loc_080207f0:
	b.n	loc_0802096c	@ 0x0802096C
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_03005598
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_03005530
	.global	loc_0802080c
loc_0802080c:
	ldr	r0, [pc, #52]	@ 0x08020844
	ldr	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08020816	@ 0x08020816
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020816
loc_08020816:
	cmp	r0, #0
	ble.n	loc_0802081c	@ 0x0802081C
	b.n	loc_08020a84	@ 0x08020A84
	.global	loc_0802081c
loc_0802081c:
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_08020830	@ 0x08020830
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020830
loc_08020830:
	ldr	r0, [pc, #20]	@ 0x08020848
	ldr	r5, [pc, #24]	@ 0x0802084C
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r0, #0
	beq.n	loc_08020842	@ 0x08020842
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020842
loc_08020842:
	b.n	loc_08020a18	@ 0x08020A18
	.word	gUnk_03005514
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.global	loc_08020850
loc_08020850:
	ldr	r1, [pc, #28]	@ 0x08020870
	ldr	r0, [pc, #32]	@ 0x08020874
	ldrh	r0, [r0, #0]
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802087c	@ 0x0802087C
	ldr	r2, [pc, #20]	@ 0x08020878
	ldrb	r1, [r2, #11]
	movs	r0, #1
	orrs	r0, r1
	strb	r0, [r2, #11]
	b.n	loc_08020b16	@ 0x08020B16
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005588
	.word	gUnk_03005530
	.global	loc_0802087c
loc_0802087c:
	ldr	r2, [pc, #8]	@ 0x08020888
	ldrb	r1, [r2, #11]
	movs	r0, #254
	ands	r0, r1
	strb	r0, [r2, #11]
	b.n	loc_08020b16	@ 0x08020B16
	.word	gUnk_03005530
	.global	loc_0802088c
loc_0802088c:
	ldr	r0, [pc, #40]	@ 0x080208B8
	ldr	r1, [pc, #44]	@ 0x080208BC
	ldrh	r3, [r1, #0]
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080208c8	@ 0x080208C8
	ldr	r2, [pc, #32]	@ 0x080208C0
	ldrb	r1, [r2, #11]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080208ac	@ 0x080208AC
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_080208ac
loc_080208ac:
	ldr	r0, [pc, #20]	@ 0x080208C4
	adds	r0, r3, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	b.n	loc_080208ca	@ 0x080208CA
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_03005530
	.word	0x087338F0
	.global	loc_080208c8
loc_080208c8:
	adds	r2, r3, #0
	.global	loc_080208ca
loc_080208ca:
	movs	r6, #1
	ldr	r0, [pc, #128]	@ 0x08020950
	strb	r6, [r0, #0]
	ldr	r4, [pc, #128]	@ 0x08020954
	adds	r0, r2, r4
	ldrb	r0, [r0, #0]
	ldr	r1, [pc, #120]	@ 0x08020950
	strb	r0, [r1, #4]
	ldr	r5, [pc, #124]	@ 0x08020958
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	ldr	r7, [pc, #112]	@ 0x0802095C
	ldrh	r0, [r7, #0]
	adds	r0, r0, r4
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08020900	@ 0x08020900
	adds	r0, r6, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020900	@ 0x08020900
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020900
loc_08020900:
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	ldr	r1, [pc, #88]	@ 0x08020960
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_08020914	@ 0x08020914
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020914
loc_08020914:
	ldr	r0, [pc, #76]	@ 0x08020964
	ldrh	r2, [r7, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802093a	@ 0x0802093A
	ldr	r0, [pc, #40]	@ 0x08020950
	ldrb	r1, [r0, #11]
	adds	r0, r6, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020932	@ 0x08020932
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020932
loc_08020932:
	ldr	r0, [pc, #52]	@ 0x08020968
	adds	r0, r2, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	.global	loc_0802093a
loc_0802093a:
	ldr	r1, [pc, #20]	@ 0x08020950
	ldr	r0, [pc, #20]	@ 0x08020954
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r4, [pc, #16]	@ 0x08020958
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	b.n	loc_08020b10	@ 0x08020B10
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005560
	.word	gUnk_03005578
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	0x087338F0
	.global	loc_0802096c
loc_0802096c:
	ldr	r1, [pc, #140]	@ 0x080209FC
	ldrh	r0, [r3, #0]
	adds	r0, r0, r1
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	.global	loc_08020976
loc_08020976:
	movs	r0, #2
	ldr	r1, [pc, #132]	@ 0x08020A00
	strb	r0, [r1, #0]
	ldr	r4, [pc, #132]	@ 0x08020A04
	adds	r0, r2, r4
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r5, [pc, #128]	@ 0x08020A08
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	ldr	r6, [pc, #116]	@ 0x08020A0C
	ldrh	r0, [r6, #0]
	adds	r0, r0, r4
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_080209aa	@ 0x080209AA
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080209aa	@ 0x080209AA
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_080209aa
loc_080209aa:
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	ldr	r1, [pc, #96]	@ 0x08020A10
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_080209be	@ 0x080209BE
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_080209be
loc_080209be:
	ldr	r0, [pc, #84]	@ 0x08020A14
	ldrh	r2, [r6, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080209e4	@ 0x080209E4
	ldr	r0, [pc, #48]	@ 0x08020A00
	ldrb	r1, [r0, #11]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080209dc	@ 0x080209DC
	b.n	loc_08020b16	@ 0x08020B16
	.global	loc_080209dc
loc_080209dc:
	ldr	r0, [pc, #28]	@ 0x080209FC
	adds	r0, r2, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	.global	loc_080209e4
loc_080209e4:
	ldr	r1, [pc, #24]	@ 0x08020A00
	ldr	r0, [pc, #28]	@ 0x08020A04
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r4, [pc, #24]	@ 0x08020A08
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	b.n	loc_08020b10	@ 0x08020B10
	movs	r0, r0
	.word	0x087338F0
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005560
	.word	gUnk_03005578
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.global	loc_08020a18
loc_08020a18:
	ldr	r6, [pc, #84]	@ 0x08020A70
	movs	r0, #1
	strb	r0, [r6, #1]
	ldr	r7, [pc, #84]	@ 0x08020A74
	ldrh	r0, [r5, #0]
	adds	r0, r0, r7
	ldrb	r0, [r0, #0]
	strb	r0, [r6, #4]
	ldr	r4, [pc, #76]	@ 0x08020A78
	ldrh	r0, [r5, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r1, [pc, #68]	@ 0x08020A7C
	ldrh	r0, [r5, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #64
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020b16	@ 0x08020B16
	ldr	r0, [pc, #56]	@ 0x08020A80
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08020b16	@ 0x08020B16
	ldrh	r0, [r5, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldrh	r0, [r5, #0]
	adds	r0, r0, r7
	ldrb	r0, [r0, #0]
	strb	r0, [r6, #4]
	b.n	loc_08020b16	@ 0x08020B16
	movs	r0, r0
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005570
	.word	0x08732DF0
	.word	gUnk_03005560
	.global	loc_08020a84
loc_08020a84:
	ldr	r0, [pc, #156]	@ 0x08020B24
	mov	sl, r0
	ldr	r6, [pc, #156]	@ 0x08020B28
	ldrh	r0, [r6, #0]
	add	r0, sl
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020aa4	@ 0x08020AA4
	ldr	r2, [pc, #144]	@ 0x08020B2C
	ldrb	r1, [r2, #11]
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020aa4
loc_08020aa4:
	ldr	r5, [pc, #132]	@ 0x08020B2C
	movs	r7, #1
	strb	r7, [r5, #2]
	strb	r7, [r5, #6]
	ldrh	r0, [r6, #0]
	bl	sub_080219b0	@ 0x080219B0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r0, [pc, #116]	@ 0x08020B30
	mov	r9, r0
	ldrh	r0, [r6, #0]
	add	r0, r9
	ldrb	r0, [r0, #0]
	strb	r0, [r5, #4]
	ldr	r1, [pc, #108]	@ 0x08020B34
	ldrh	r0, [r6, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020b16	@ 0x08020B16
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08020b16	@ 0x08020B16
	ldrh	r2, [r6, #0]
	mov	r1, sl
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020b00	@ 0x08020B00
	ldrb	r1, [r5, #11]
	adds	r0, r7, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020b16	@ 0x08020B16
	.global	loc_08020b00
loc_08020b00:
	mov	r1, r9
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	ldr	r1, [pc, #36]	@ 0x08020B2C
	strb	r0, [r1, #4]
	adds	r0, r2, #0
	bl	sub_080219b0	@ 0x080219B0
	.global	loc_08020b10
loc_08020b10:
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08020b16
loc_08020b16:
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	0x08732DF0
