@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0, chunk 2/2: 0x08020B38-0x08021130 (thumb_code, 0x5F8 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08020B38 sub_08020b38

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_080207a0_01:
	.thumb_func
	.global	sub_08020b38
sub_08020b38:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	ldr	r0, [pc, #68]	@ 0x08020B84
	ldr	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08020b9c	@ 0x08020B9C
	cmp	r0, #0
	bgt.n	loc_08020bec	@ 0x08020BEC
	ldr	r0, [pc, #60]	@ 0x08020B88
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #56]	@ 0x08020B8C
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	beq.n	loc_08020b60	@ 0x08020B60
	b.n	loc_08020e30	@ 0x08020E30
	.global	loc_08020b60
loc_08020b60:
	ldr	r5, [pc, #44]	@ 0x08020B90
	ldrb	r0, [r5, #11]
	movs	r4, #253
	ands	r4, r0
	strb	r4, [r5, #11]
	ldr	r1, [pc, #40]	@ 0x08020B94
	ldr	r0, [pc, #40]	@ 0x08020B98
	ldrh	r3, [r0, #0]
	adds	r0, r3, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	mov	r8, r5
	cmp	r0, #0
	bne.n	loc_08020b80	@ 0x08020B80
	b.n	loc_08020dd0	@ 0x08020DD0
	.global	loc_08020b80
loc_08020b80:
	b.n	loc_08020db0	@ 0x08020DB0
	movs	r0, r0
	.word	gUnk_03005598
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.global	loc_08020b9c
loc_08020b9c:
	ldr	r0, [pc, #56]	@ 0x08020BD8
	ldr	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08020ba6	@ 0x08020BA6
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020ba6
loc_08020ba6:
	cmp	r0, #0
	ble.n	loc_08020bac	@ 0x08020BAC
	b.n	loc_08021000	@ 0x08021000
	.global	loc_08020bac
loc_08020bac:
	ldr	r0, [pc, #44]	@ 0x08020BDC
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #44]	@ 0x08020BE0
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_08020bc2	@ 0x08020BC2
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020bc2
loc_08020bc2:
	ldr	r0, [pc, #32]	@ 0x08020BE4
	ldr	r5, [pc, #32]	@ 0x08020BE8
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r0, #0
	beq.n	loc_08020bd4	@ 0x08020BD4
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020bd4
loc_08020bd4:
	b.n	loc_08020f2c	@ 0x08020F2C
	movs	r0, r0
	.word	gUnk_03005514
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.global	loc_08020bec
loc_08020bec:
	ldr	r0, [pc, #80]	@ 0x08020C40
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #80]	@ 0x08020C44
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_08020cb4	@ 0x08020CB4
	ldr	r1, [pc, #68]	@ 0x08020C48
	ldrb	r0, [r1, #11]
	movs	r4, #249
	ands	r4, r0
	strb	r4, [r1, #11]
	ldr	r2, [pc, #64]	@ 0x08020C4C
	ldr	r0, [pc, #64]	@ 0x08020C50
	ldrh	r3, [r0, #0]
	adds	r0, r3, r2
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	mov	r8, r1
	adds	r1, r2, #0
	cmp	r0, #0
	beq.n	loc_08020c58	@ 0x08020C58
	ldr	r0, [pc, #48]	@ 0x08020C54
	adds	r0, r3, r0
	ldrb	r3, [r0, #0]
	cmp	r3, #0
	beq.n	loc_08020c58	@ 0x08020C58
	movs	r0, #1
	ands	r0, r3
	cmp	r0, #0
	beq.n	loc_08020c58	@ 0x08020C58
	movs	r1, #4
	adds	r0, r4, #0
	orrs	r0, r1
	mov	r1, r8
	strb	r0, [r1, #11]
	b.n	loc_08021118	@ 0x08021118
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.global	loc_08020c58
loc_08020c58:
	ldr	r0, [pc, #72]	@ 0x08020CA4
	ldrh	r3, [r0, #0]
	adds	r0, r3, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08020c6a	@ 0x08020C6A
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020c6a
loc_08020c6a:
	ldr	r0, [pc, #60]	@ 0x08020CA8
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_08020c76	@ 0x08020C76
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020c76
loc_08020c76:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020c80	@ 0x08020C80
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020c80
loc_08020c80:
	ldr	r0, [pc, #40]	@ 0x08020CAC
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08020c9c	@ 0x08020C9C
	ldr	r0, [pc, #32]	@ 0x08020CB0
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_08020c9c	@ 0x08020C9C
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020c9c
loc_08020c9c:
	mov	r2, r8
	ldrb	r1, [r2, #11]
	movs	r0, #4
	b.n	loc_08020e1a	@ 0x08020E1A
	.word	gUnk_03005510
	.word	gUnk_08732CF0
	.word	gUnk_08732DF0
	.word	gUnk_03005570
	.global	loc_08020cb4
loc_08020cb4:
	ldr	r0, [pc, #40]	@ 0x08020CE0
	ldr	r1, [pc, #44]	@ 0x08020CE4
	ldrh	r3, [r1, #0]
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020cf0	@ 0x08020CF0
	ldr	r2, [pc, #32]	@ 0x08020CE8
	ldrb	r1, [r2, #11]
	movs	r0, #4
	ands	r0, r1
	mov	r8, r2
	cmp	r0, #0
	bne.n	loc_08020cd6	@ 0x08020CD6
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020cd6
loc_08020cd6:
	ldr	r0, [pc, #20]	@ 0x08020CEC
	adds	r0, r3, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	b.n	loc_08020cf6	@ 0x08020CF6
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_03005530
	.word	gUnk_087338F0
	.global	loc_08020cf0
loc_08020cf0:
	adds	r2, r3, #0
	ldr	r0, [pc, #160]	@ 0x08020D94
	mov	r8, r0
	.global	loc_08020cf6
loc_08020cf6:
	movs	r6, #1
	mov	r1, r8
	strb	r6, [r1, #0]
	ldr	r4, [pc, #152]	@ 0x08020D98
	adds	r0, r2, r4
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r5, [pc, #148]	@ 0x08020D9C
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	ldr	r7, [pc, #136]	@ 0x08020DA0
	ldrh	r0, [r7, #0]
	adds	r0, r0, r4
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08020d28	@ 0x08020D28
	adds	r0, r6, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020d7a	@ 0x08020D7A
	.global	loc_08020d28
loc_08020d28:
	movs	r2, #0
	ldrsh	r0, [r5, r2]
	ldr	r1, [pc, #116]	@ 0x08020DA4
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08020d7a	@ 0x08020D7A
	ldr	r0, [pc, #108]	@ 0x08020DA8
	ldrh	r2, [r7, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020d60	@ 0x08020D60
	mov	r0, r8
	ldrb	r1, [r0, #11]
	movs	r0, #4
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020d58	@ 0x08020D58
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020d58
loc_08020d58:
	ldr	r0, [pc, #80]	@ 0x08020DAC
	adds	r0, r2, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	.global	loc_08020d60
loc_08020d60:
	ldr	r1, [pc, #48]	@ 0x08020D94
	ldr	r0, [pc, #52]	@ 0x08020D98
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r4, [pc, #48]	@ 0x08020D9C
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219f0	@ 0x080219F0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08020d7a
loc_08020d7a:
	ldr	r0, [pc, #24]	@ 0x08020D94
	movs	r1, #0
	strb	r1, [r0, #11]
	ldrb	r0, [r0, #4]
	cmp	r0, #0
	bne.n	loc_08020d88	@ 0x08020D88
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020d88
loc_08020d88:
	ldr	r1, [pc, #16]	@ 0x08020D9C
	ldrh	r0, [r1, #0]
	adds	r0, #1
	strh	r0, [r1, #0]
	b.n	loc_08021118	@ 0x08021118
	movs	r0, r0
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005560
	.word	gUnk_03005578
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	gUnk_087338F0
	.global	loc_08020db0
loc_08020db0:
	ldr	r0, [pc, #24]	@ 0x08020DCC
	adds	r0, r3, r0
	ldrb	r3, [r0, #0]
	cmp	r3, #0
	beq.n	loc_08020dd0	@ 0x08020DD0
	movs	r0, #1
	ands	r0, r3
	cmp	r0, #0
	bne.n	loc_08020dd0	@ 0x08020DD0
	movs	r1, #2
	adds	r0, r4, #0
	orrs	r0, r1
	strb	r0, [r5, #11]
	b.n	loc_08021118	@ 0x08021118
	.word	gUnk_08732CF0
	.global	loc_08020dd0
loc_08020dd0:
	ldr	r0, [pc, #76]	@ 0x08020E20
	ldrh	r3, [r0, #0]
	adds	r0, r3, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08020de2	@ 0x08020DE2
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020de2
loc_08020de2:
	ldr	r0, [pc, #64]	@ 0x08020E24
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_08020dee	@ 0x08020DEE
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020dee
loc_08020dee:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020df8	@ 0x08020DF8
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020df8
loc_08020df8:
	ldr	r0, [pc, #44]	@ 0x08020E28
	adds	r0, r3, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08020e14	@ 0x08020E14
	ldr	r0, [pc, #36]	@ 0x08020E2C
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_08020e14	@ 0x08020E14
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020e14
loc_08020e14:
	mov	r2, r8
	ldrb	r1, [r2, #11]
	movs	r0, #2
	.global	loc_08020e1a
loc_08020e1a:
	orrs	r0, r1
	strb	r0, [r2, #11]
	b.n	loc_08021118	@ 0x08021118
	.word	gUnk_03005594
	.word	gUnk_08732CF0
	.word	gUnk_08732DF0
	.word	gUnk_03005570
	.global	loc_08020e30
loc_08020e30:
	ldr	r0, [pc, #40]	@ 0x08020E5C
	ldr	r1, [pc, #44]	@ 0x08020E60
	ldrh	r3, [r1, #0]
	adds	r0, r3, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020e6c	@ 0x08020E6C
	ldr	r2, [pc, #32]	@ 0x08020E64
	ldrb	r1, [r2, #11]
	movs	r0, #2
	ands	r0, r1
	mov	r8, r2
	cmp	r0, #0
	bne.n	loc_08020e52	@ 0x08020E52
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020e52
loc_08020e52:
	ldr	r0, [pc, #20]	@ 0x08020E68
	adds	r0, r3, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	b.n	loc_08020e72	@ 0x08020E72
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_03005530
	.word	gUnk_087338F0
	.global	loc_08020e6c
loc_08020e6c:
	adds	r2, r3, #0
	ldr	r0, [pc, #160]	@ 0x08020F10
	mov	r8, r0
	.global	loc_08020e72
loc_08020e72:
	mov	r1, r8
	movs	r7, #2
	strb	r7, [r1, #0]
	ldr	r4, [pc, #152]	@ 0x08020F14
	adds	r0, r2, r4
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r5, [pc, #148]	@ 0x08020F18
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	ldr	r6, [pc, #136]	@ 0x08020F1C
	ldrh	r0, [r6, #0]
	adds	r0, r0, r4
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08020ea4	@ 0x08020EA4
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020ef6	@ 0x08020EF6
	.global	loc_08020ea4
loc_08020ea4:
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	ldr	r1, [pc, #116]	@ 0x08020F20
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08020ef6	@ 0x08020EF6
	ldr	r0, [pc, #108]	@ 0x08020F24
	ldrh	r2, [r6, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08020edc	@ 0x08020EDC
	mov	r0, r8
	ldrb	r1, [r0, #11]
	adds	r0, r7, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020ed4	@ 0x08020ED4
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020ed4
loc_08020ed4:
	ldr	r0, [pc, #80]	@ 0x08020F28
	adds	r0, r2, r0
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	.global	loc_08020edc
loc_08020edc:
	ldr	r1, [pc, #48]	@ 0x08020F10
	ldr	r0, [pc, #52]	@ 0x08020F14
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #4]
	ldr	r4, [pc, #48]	@ 0x08020F18
	lsls	r0, r2, #16
	lsrs	r0, r0, #16
	bl	sub_080219d0	@ 0x080219D0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08020ef6
loc_08020ef6:
	ldr	r0, [pc, #24]	@ 0x08020F10
	movs	r1, #0
	strb	r1, [r0, #11]
	ldrb	r0, [r0, #4]
	cmp	r0, #0
	bne.n	loc_08020f04	@ 0x08020F04
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020f04
loc_08020f04:
	ldr	r1, [pc, #16]	@ 0x08020F18
	ldrh	r0, [r1, #0]
	subs	r0, #1
	strh	r0, [r1, #0]
	b.n	loc_08021118	@ 0x08021118
	movs	r0, r0
	.word	gUnk_03005530
	.word	gUnk_08732CF0
	.word	gUnk_03005560
	.word	gUnk_03005578
	.word	gUnk_03005570
	.word	gUnk_087336F0
	.word	gUnk_087338F0
	.global	loc_08020f2c
loc_08020f2c:
	ldr	r1, [pc, #176]	@ 0x08020FE0
	movs	r0, #1
	strb	r0, [r1, #1]
	ldr	r4, [pc, #176]	@ 0x08020FE4
	ldrh	r0, [r5, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r1, [pc, #164]	@ 0x08020FE8
	ldrh	r0, [r5, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #64
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08020f6e	@ 0x08020F6E
	ldr	r0, [pc, #152]	@ 0x08020FEC
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08020f6e	@ 0x08020F6E
	ldrh	r0, [r5, #0]
	bl	sub_08021990	@ 0x08021990
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08020f6e
loc_08020f6e:
	ldr	r6, [pc, #112]	@ 0x08020FE0
	movs	r0, #0
	strb	r0, [r6, #11]
	ldr	r5, [pc, #120]	@ 0x08020FF0
	ldr	r0, [pc, #124]	@ 0x08020FF4
	ldrh	r0, [r0, #0]
	adds	r0, r0, r5
	ldrb	r2, [r0, #0]
	strb	r2, [r6, #4]
	lsls	r0, r2, #24
	cmp	r0, #0
	bne.n	loc_08020f88	@ 0x08020F88
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020f88
loc_08020f88:
	ldr	r1, [pc, #88]	@ 0x08020FE4
	ldrh	r0, [r1, #0]
	subs	r3, r0, #1
	strh	r3, [r1, #0]
	movs	r4, #1
	adds	r0, r4, #0
	ands	r0, r2
	cmp	r0, #0
	bne.n	loc_08020f9c	@ 0x08020F9C
	b.n	loc_080210dc	@ 0x080210DC
	.global	loc_08020f9c
loc_08020f9c:
	ldr	r0, [pc, #88]	@ 0x08020FF8
	ldr	r1, [pc, #92]	@ 0x08020FFC
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08020fb0	@ 0x08020FB0
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020fb0
loc_08020fb0:
	adds	r0, r2, r5
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_08020fba	@ 0x08020FBA
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020fba
loc_08020fba:
	adds	r0, r4, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08020fc4	@ 0x08020FC4
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020fc4
loc_08020fc4:
	ldr	r0, [pc, #32]	@ 0x08020FE8
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08020fdc	@ 0x08020FDC
	movs	r0, #15
	ands	r3, r0
	cmp	r3, #7
	ble.n	loc_08020fdc	@ 0x08020FDC
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08020fdc
loc_08020fdc:
	movs	r0, #2
	b.n	loc_08021116	@ 0x08021116
	.word	gUnk_03005530
	.word	gUnk_03005570
	.word	gUnk_08732DF0
	.word	gUnk_03005560
	.word	gUnk_08732CF0
	.word	gUnk_03005578
	.word	gUnk_087336F0
	.word	gUnk_03005594
	.global	loc_08021000
loc_08021000:
	ldr	r6, [pc, #184]	@ 0x080210BC
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	ldr	r4, [pc, #184]	@ 0x080210C0
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_08021016	@ 0x08021016
	b.n	loc_08021118	@ 0x08021118
	.global	loc_08021016
loc_08021016:
	ldr	r1, [pc, #172]	@ 0x080210C4
	movs	r0, #1
	strb	r0, [r1, #2]
	ldr	r5, [pc, #168]	@ 0x080210C8
	ldrh	r0, [r5, #0]
	bl	sub_080219b0	@ 0x080219B0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r1, [pc, #160]	@ 0x080210CC
	ldrh	r0, [r5, #0]
	adds	r0, r0, r1
	ldrb	r1, [r0, #0]
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08021056	@ 0x08021056
	movs	r1, #0
	ldrsh	r0, [r6, r1]
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08021056	@ 0x08021056
	ldrh	r0, [r5, #0]
	bl	sub_080219b0	@ 0x080219B0
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08021056
loc_08021056:
	ldr	r6, [pc, #108]	@ 0x080210C4
	movs	r0, #0
	strb	r0, [r6, #11]
	ldr	r5, [pc, #112]	@ 0x080210D0
	ldr	r0, [pc, #104]	@ 0x080210C8
	ldrh	r0, [r0, #0]
	adds	r0, r0, r5
	ldrb	r2, [r0, #0]
	strb	r2, [r6, #4]
	lsls	r0, r2, #24
	cmp	r0, #0
	beq.n	loc_08021118	@ 0x08021118
	ldr	r1, [pc, #80]	@ 0x080210C0
	ldrh	r0, [r1, #0]
	adds	r3, r0, #1
	strh	r3, [r1, #0]
	movs	r4, #1
	adds	r0, r4, #0
	ands	r0, r2
	cmp	r0, #0
	beq.n	loc_080210dc	@ 0x080210DC
	ldr	r0, [pc, #80]	@ 0x080210D4
	ldr	r1, [pc, #84]	@ 0x080210D8
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08021118	@ 0x08021118
	adds	r0, r2, r5
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08021118	@ 0x08021118
	adds	r0, r4, #0
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08021118	@ 0x08021118
	ldr	r0, [pc, #40]	@ 0x080210CC
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080210b8	@ 0x080210B8
	movs	r0, #15
	ands	r3, r0
	cmp	r3, #6
	bgt.n	loc_08021118	@ 0x08021118
	.global	loc_080210b8
loc_080210b8:
	movs	r0, #2
	b.n	loc_08021116	@ 0x08021116
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_03005578
	.word	gUnk_08732DF0
	.word	gUnk_08732CF0
	.word	gUnk_087336F0
	.word	gUnk_03005594
	.global	loc_080210dc
loc_080210dc:
	ldr	r0, [pc, #68]	@ 0x08021124
	ldr	r1, [pc, #72]	@ 0x08021128
	ldrh	r2, [r1, #0]
	adds	r0, r2, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08021118	@ 0x08021118
	adds	r0, r2, r5
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_08021118	@ 0x08021118
	adds	r0, r4, #0
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08021118	@ 0x08021118
	ldr	r0, [pc, #44]	@ 0x0802112C
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08021114	@ 0x08021114
	movs	r0, #15
	ands	r3, r0
	cmp	r3, #7
	bgt.n	loc_08021118	@ 0x08021118
	.global	loc_08021114
loc_08021114:
	movs	r0, #4
	.global	loc_08021116
loc_08021116:
	strb	r0, [r6, #11]
	.global	loc_08021118
loc_08021118:
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005510
	.word	gUnk_08732DF0
