@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_0800b920_0800f180, chunk 2/2: 0x0800FB94-0x0800FCBC (thumb_code, 0x128 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x0800FB94 sub_0800fb94

	.section .game_code_and_rodata_0800b920_0800f180, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_0800b920_0800f180_01:
	.thumb_func
	.global	sub_0800fb94
sub_0800fb94:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	sub	sp, #4
	ldr	r5, [pc, #136]	@ 0x0800FC28
	ldr	r2, [r5, #0]
	ldr	r6, [pc, #136]	@ 0x0800FC2C
	movs	r0, #0
	ldrsb	r0, [r6, r0]
	str	r0, [r2, #24]
	str	r0, [r2, #28]
	movs	r1, #0
	str	r1, [r2, #32]
	str	r1, [r2, #36]
	ldr	r1, [pc, #124]	@ 0x0800FC30
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	bl	sub_08008c64	@ 0x08008C64
	ldr	r4, [pc, #116]	@ 0x0800FC34
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #24]
	lsls	r0, r0, #2
	adds	r0, r0, r4
	ldr	r1, [r0, #0]
	ldr	r2, [pc, #108]	@ 0x0800FC38
	movs	r0, #2
	movs	r3, #32
	bl	sub_080017e4	@ 0x080017E4
	adds	r7, r4, #0
	mov	r9, r6
	mov	r8, r7
	movs	r6, #0
	.global	loc_0800fbdc
loc_0800fbdc:
	mov	r1, r9
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	lsls	r0, r0, #2
	adds	r0, r0, r7
	ldr	r3, [r0, #0]
	ldr	r4, [pc, #60]	@ 0x0800FC28
	cmp	r3, #0
	beq.n	loc_0800fc0c	@ 0x0800FC0C
	ldr	r1, [r4, #0]
	ldr	r2, [r1, #24]
	lsls	r0, r2, #2
	adds	r0, r0, r7
	ldr	r0, [r0, #0]
	cmp	r0, r3
	beq.n	loc_0800fc0c	@ 0x0800FC0C
	str	r2, [r1, #28]
	mov	r2, r9
	movs	r0, #0
	ldrsb	r0, [r2, r0]
	str	r0, [r1, #24]
	str	r6, [r1, #36]
	movs	r0, #1
	str	r0, [r1, #32]
	.global	loc_0800fc0c
loc_0800fc0c:
	adds	r5, r4, #0
	ldr	r1, [r5, #0]
	ldr	r3, [r1, #32]
	cmp	r3, #0
	beq.n	loc_0800fcac	@ 0x0800FCAC
	ldr	r0, [r1, #36]
	adds	r2, r0, #0
	adds	r2, #32
	str	r2, [r1, #36]
	cmp	r3, #1
	beq.n	loc_0800fc3c	@ 0x0800FC3C
	cmp	r3, #2
	beq.n	loc_0800fc84	@ 0x0800FC84
	b.n	loc_0800fcac	@ 0x0800FCAC
	.word	gUnk_03002490
	.word	gUnk_020060D0
	.word	0x08731D58
	.word	0x08731CF8
	.word	gUnk_030012B0
	.global	loc_0800fc3c
loc_0800fc3c:
	ldr	r0, [r1, #28]
	lsls	r0, r0, #2
	add	r0, r8
	ldr	r0, [r0, #0]
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	ldr	r1, [pc, #44]	@ 0x0800FC78
	str	r1, [sp, #0]
	ldr	r1, [pc, #44]	@ 0x0800FC7C
	movs	r3, #16
	bl	sub_08003014	@ 0x08003014
	ldr	r2, [r5, #0]
	ldr	r1, [r2, #36]
	movs	r0, #128
	lsls	r0, r0, #1
	cmp	r1, r0
	bne.n	loc_0800fcac	@ 0x0800FCAC
	str	r6, [r2, #36]
	movs	r0, #2
	str	r0, [r2, #32]
	ldr	r1, [pc, #24]	@ 0x0800FC80
	ldr	r0, [r2, #24]
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	bl	sub_08008c64	@ 0x08008C64
	b.n	loc_0800fcac	@ 0x0800FCAC
	movs	r0, r0
	.word	gUnk_030012B0
	.word	0x085563C8
	.word	0x08731D58
	.global	loc_0800fc84
loc_0800fc84:
	ldr	r0, [r1, #24]
	lsls	r0, r0, #2
	add	r0, r8
	ldr	r1, [r0, #0]
	lsls	r2, r2, #16
	lsrs	r2, r2, #16
	ldr	r0, [pc, #32]	@ 0x0800FCB4
	str	r0, [sp, #0]
	ldr	r0, [pc, #32]	@ 0x0800FCB8
	movs	r3, #16
	bl	sub_08003014	@ 0x08003014
	ldr	r2, [r4, #0]
	ldr	r1, [r2, #36]
	movs	r0, #128
	lsls	r0, r0, #1
	cmp	r1, r0
	bne.n	loc_0800fcac	@ 0x0800FCAC
	str	r6, [r2, #36]
	str	r6, [r2, #32]
	.global	loc_0800fcac
loc_0800fcac:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0800fbdc	@ 0x0800FBDC
	.word	gUnk_030012B0
	.word	0x085563C8
