@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18, chunk 1/2: 0x08021B18-0x080235EC (thumb_code, 0x1AD4 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08021B18 sub_08021b18
@   0x08021B2C sub_08021b2c
@   0x08021B70 sub_08021b70
@   0x08021BB4 sub_08021bb4
@   0x08021C14 sub_08021c14
@   0x08021C4C sub_08021c4c
@   0x08021C74 sub_08021c74
@   0x0802205C sub_0802205c
@   0x080222B0 sub_080222b0
@   0x0802233C sub_0802233c
@   0x080224B0 sub_080224b0
@   0x080224F8 sub_080224f8
@   0x08022540 sub_08022540
@   0x0802259C sub_0802259c
@   0x08022624 sub_08022624
@   0x08022650 sub_08022650
@   0x08022760 sub_08022760
@   0x08022788 sub_08022788
@   0x080227A4 sub_080227a4
@   0x08022810 sub_08022810
@   0x080228C4 sub_080228c4
@   0x0802294C sub_0802294c
@   0x0802296C sub_0802296c
@   0x08022C3C sub_08022c3c
@   0x08022F50 sub_08022f50
@   0x08022F98 sub_08022f98
@   0x08022F9C sub_08022f9c
@   0x08022FA8 sub_08022fa8
@   0x080233E0 sub_080233e0

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18:
	.thumb_func
	.global	sub_08021b18
sub_08021b18:
	.thumb
	push	{lr}
	lsls	r0, r0, #16
	lsls	r1, r1, #16
	lsrs	r0, r0, #20
	lsrs	r1, r1, #20
	bl	sub_08021b2c	@ 0x08021B2C
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_08021b2c
sub_08021b2c:
	.thumb
	push	{r4, lr}
	adds	r3, r0, #0
	adds	r2, r1, #0
	ldr	r0, [pc, #24]	@ 0x08021B4C
	movs	r4, #0
	ldrsh	r1, [r0, r4]
	cmp	r3, r1
	bcs.n	loc_08021b46	@ 0x08021B46
	ldr	r0, [pc, #16]	@ 0x08021B50
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	cmp	r2, r0
	bcc.n	loc_08021b54	@ 0x08021B54
	.global	loc_08021b46
loc_08021b46:
	movs	r0, #0
	b.n	loc_08021b66	@ 0x08021B66
	movs	r0, r0
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.global	loc_08021b54
loc_08021b54:
	adds	r0, r2, #0
	muls	r0, r1
	ldr	r1, [pc, #16]	@ 0x08021B6C
	ldr	r2, [r1, #0]
	lsls	r1, r3, #2
	lsls	r0, r0, #2
	adds	r0, r0, r2
	adds	r1, r1, r0
	ldrb	r0, [r1, #3]
	.global	loc_08021b66
loc_08021b66:
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_03005660
	.thumb_func
	.global	sub_08021b70
sub_08021b70:
	.thumb
	push	{r4, lr}
	adds	r3, r0, #0
	lsrs	r3, r3, #4
	lsrs	r1, r1, #4
	ldr	r0, [pc, #20]	@ 0x08021B90
	movs	r4, #0
	ldrsh	r2, [r0, r4]
	cmp	r3, r2
	bcs.n	loc_08021b8c	@ 0x08021B8C
	ldr	r0, [pc, #16]	@ 0x08021B94
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	cmp	r1, r0
	bcc.n	loc_08021b98	@ 0x08021B98
	.global	loc_08021b8c
loc_08021b8c:
	movs	r0, #0
	b.n	loc_08021baa	@ 0x08021BAA
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.global	loc_08021b98
loc_08021b98:
	adds	r0, r1, #0
	muls	r0, r2
	ldr	r1, [pc, #16]	@ 0x08021BB0
	ldr	r2, [r1, #0]
	lsls	r1, r3, #2
	lsls	r0, r0, #2
	adds	r0, r0, r2
	adds	r1, r1, r0
	ldrb	r0, [r1, #2]
	.global	loc_08021baa
loc_08021baa:
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_03005660
	.thumb_func
	.global	sub_08021bb4
sub_08021bb4:
	.thumb
	push	{r4, lr}
	lsls	r0, r0, #16
	asrs	r0, r0, #20
	lsls	r2, r2, #16
	asrs	r2, r2, #16
	adds	r4, r0, r2
	lsls	r1, r1, #16
	asrs	r1, r1, #20
	lsls	r3, r3, #16
	asrs	r3, r3, #16
	adds	r1, r1, r3
	cmp	r4, #0
	ble.n	loc_08021bea	@ 0x08021BEA
	ldr	r0, [pc, #32]	@ 0x08021BF0
	movs	r3, #0
	ldrsh	r2, [r0, r3]
	subs	r0, r2, #1
	cmp	r4, r0
	bge.n	loc_08021bea	@ 0x08021BEA
	cmp	r1, #0
	ble.n	loc_08021bea	@ 0x08021BEA
	ldr	r0, [pc, #20]	@ 0x08021BF4
	movs	r3, #0
	ldrsh	r0, [r0, r3]
	subs	r0, #1
	cmp	r1, r0
	blt.n	loc_08021bf8	@ 0x08021BF8
	.global	loc_08021bea
loc_08021bea:
	movs	r0, #1
	negs	r0, r0
	b.n	loc_08021c0a	@ 0x08021C0A
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.global	loc_08021bf8
loc_08021bf8:
	adds	r0, r1, #0
	muls	r0, r2
	ldr	r1, [pc, #16]	@ 0x08021C10
	ldr	r2, [r1, #0]
	lsls	r1, r4, #2
	lsls	r0, r0, #2
	adds	r0, r0, r2
	adds	r1, r1, r0
	ldrb	r0, [r1, #3]
	.global	loc_08021c0a
loc_08021c0a:
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_03005660
	.thumb_func
	.global	sub_08021c14
sub_08021c14:
	.thumb
	push	{lr}
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	bl	sub_08021634	@ 0x08021634
	ldr	r1, [pc, #24]	@ 0x08021C3C
	ldrh	r0, [r1, #0]
	cmp	r0, #127
	bhi.n	loc_08021c44	@ 0x08021C44
	ldr	r0, [pc, #20]	@ 0x08021C40
	ldrh	r1, [r1, #0]
	adds	r1, r1, r0
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r0, #0
	bne.n	loc_08021c44	@ 0x08021C44
	movs	r0, #0
	b.n	loc_08021c46	@ 0x08021C46
	.word	gUnk_03005578
	.word	gUnk_087339F0
	.global	loc_08021c44
loc_08021c44:
	movs	r0, #1
	.global	loc_08021c46
loc_08021c46:
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_08021c4c
sub_08021c4c:
	.thumb
	push	{lr}
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	lsls	r1, r1, #16
	asrs	r1, r1, #16
	bl	sub_08021634	@ 0x08021634
	ldr	r0, [pc, #12]	@ 0x08021C68
	ldrh	r0, [r0, #0]
	cmp	r0, #127
	bhi.n	loc_08021c6c	@ 0x08021C6C
	movs	r0, #0
	b.n	loc_08021c6e	@ 0x08021C6E
	movs	r0, r0
	.word	gUnk_03005578
	.global	loc_08021c6c
loc_08021c6c:
	movs	r0, #1
	.global	loc_08021c6e
loc_08021c6e:
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_08021c74
sub_08021c74:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	mov	r9, r0
	lsls	r0, r1, #3
	adds	r0, r0, r1
	lsls	r0, r0, #4
	ldr	r1, [pc, #180]	@ 0x08021D40
	adds	r7, r0, r1
	ldr	r3, [pc, #180]	@ 0x08021D44
	ldr	r1, [r7, #76]
	asrs	r1, r1, #16
	mov	r2, r9
	movs	r0, #0
	ldrsb	r0, [r2, r0]
	adds	r0, r0, r1
	strh	r0, [r3, #0]
	ldr	r4, [pc, #168]	@ 0x08021D48
	ldr	r1, [r7, #80]
	asrs	r1, r1, #16
	movs	r0, #1
	ldrsb	r0, [r2, r0]
	adds	r0, r0, r1
	strh	r0, [r4, #0]
	ldr	r1, [pc, #160]	@ 0x08021D4C
	movs	r0, #2
	ldrsb	r0, [r2, r0]
	strh	r0, [r1, #0]
	ldr	r2, [pc, #156]	@ 0x08021D50
	mov	r5, r9
	movs	r0, #3
	ldrsb	r0, [r5, r0]
	strh	r0, [r2, #0]
	movs	r0, #4
	ldrsb	r0, [r5, r0]
	ldr	r1, [pc, #144]	@ 0x08021D54
	strh	r0, [r1, #0]
	ldr	r5, [pc, #144]	@ 0x08021D58
	mov	sl, r5
	mov	r1, r9
	movs	r0, #5
	ldrsb	r0, [r1, r0]
	strh	r0, [r5, #0]
	ldr	r1, [pc, #136]	@ 0x08021D5C
	ldrb	r0, [r1, #2]
	adds	r0, #1
	strb	r0, [r1, #2]
	movs	r5, #1
	mov	r8, r5
	mov	r0, r8
	strb	r0, [r1, #6]
	movs	r1, #0
	ldrsh	r0, [r3, r1]
	movs	r5, #0
	ldrsh	r1, [r4, r5]
	movs	r5, #0
	ldrsh	r2, [r2, r5]
	adds	r1, r1, r2
	str	r3, [sp, #0]
	bl	sub_080216d8	@ 0x080216D8
	ldr	r0, [pc, #104]	@ 0x08021D60
	ldr	r1, [pc, #108]	@ 0x08021D64
	ldrh	r1, [r1, #0]
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	ldr	r3, [sp, #0]
	cmp	r0, #0
	beq.n	loc_08021d0a	@ 0x08021D0A
	b.n	loc_08021e4c	@ 0x08021E4C
	.global	loc_08021d0a
loc_08021d0a:
	ldr	r1, [pc, #92]	@ 0x08021D68
	ldr	r0, [pc, #92]	@ 0x08021D6C
	ldrh	r2, [r0, #0]
	lsls	r0, r2, #1
	adds	r0, r0, r1
	ldrh	r5, [r0, #0]
	mov	ip, r1
	cmp	r5, #0
	beq.n	loc_08021da2	@ 0x08021DA2
	movs	r6, #0
	mov	r0, r8
	ands	r2, r0
	cmp	r2, #0
	beq.n	loc_08021d74	@ 0x08021D74
	movs	r2, #0
	ldrsh	r1, [r3, r2]
	ldr	r2, [pc, #68]	@ 0x08021D70
	ldr	r3, [pc, #36]	@ 0x08021D54
	movs	r4, #0
	ldrsh	r0, [r3, r4]
	adds	r0, r1, r0
	eors	r0, r1
	ands	r0, r2
	negs	r1, r0
	orrs	r1, r0
	lsrs	r6, r1, #31
	b.n	loc_08021d90	@ 0x08021D90
	.word	gUnk_03002790
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_0300557C
	.word	gUnk_03005584
	.word	gUnk_0300551C
	.word	gUnk_0300559C
	.word	gUnk_03005530
	.word	gUnk_08732EF0
	.word	gUnk_03005578
	.word	0x08735018
	.word	gUnk_03005574
	.word	0x0000FFF0
	.global	loc_08021d74
loc_08021d74:
	movs	r1, #0
	ldrsh	r0, [r3, r1]
	ldr	r3, [pc, #112]	@ 0x08021DEC
	adds	r2, r0, #0
	ands	r2, r3
	mov	r4, sl
	movs	r1, #0
	ldrsh	r4, [r4, r1]
	mov	r8, r4
	add	r0, r8
	ands	r0, r3
	cmp	r2, r0
	beq.n	loc_08021d90	@ 0x08021D90
	movs	r6, #2
	.global	loc_08021d90
loc_08021d90:
	cmp	r6, #0
	beq.n	loc_08021d96	@ 0x08021D96
	b.n	loc_08021ea4	@ 0x08021EA4
	.global	loc_08021d96
loc_08021d96:
	ldr	r0, [pc, #88]	@ 0x08021DF0
	ldrh	r0, [r0, #0]
	adds	r0, #16
	cmp	r0, #255
	bgt.n	loc_08021da2	@ 0x08021DA2
	b.n	loc_08021ea4	@ 0x08021EA4
	.global	loc_08021da2
loc_08021da2:
	ldr	r0, [pc, #80]	@ 0x08021DF4
	ldr	r1, [pc, #80]	@ 0x08021DF8
	ldrh	r1, [r1, #0]
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08021e38	@ 0x08021E38
	ldr	r0, [pc, #68]	@ 0x08021DFC
	ldrh	r2, [r0, #0]
	lsls	r0, r2, #1
	add	r0, ip
	ldrh	r5, [r0, #0]
	cmp	r5, #0
	bne.n	loc_08021dc4	@ 0x08021DC4
	b.n	loc_08021f34	@ 0x08021F34
	.global	loc_08021dc4
loc_08021dc4:
	movs	r0, #1
	ands	r2, r0
	cmp	r2, #0
	beq.n	loc_08021e08	@ 0x08021E08
	ldr	r0, [pc, #48]	@ 0x08021E00
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	ldr	r3, [pc, #24]	@ 0x08021DEC
	adds	r2, r1, #0
	ands	r2, r3
	ldr	r0, [pc, #40]	@ 0x08021E04
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	adds	r1, r1, r0
	ands	r1, r3
	cmp	r2, r1
	beq.n	loc_08021e24	@ 0x08021E24
	movs	r6, #1
	b.n	loc_08021ea4	@ 0x08021EA4
	movs	r0, r0
	.word	0x0000FFF0
	.word	gUnk_03005508
	.word	gUnk_08732EF0
	.word	gUnk_03005588
	.word	gUnk_030055AC
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.global	loc_08021e08
loc_08021e08:
	ldr	r0, [pc, #32]	@ 0x08021E2C
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	ldr	r3, [pc, #32]	@ 0x08021E30
	adds	r2, r1, #0
	ands	r2, r3
	ldr	r0, [pc, #28]	@ 0x08021E34
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	adds	r1, r1, r0
	ands	r1, r3
	cmp	r2, r1
	beq.n	loc_08021e24	@ 0x08021E24
	movs	r6, #2
	.global	loc_08021e24
loc_08021e24:
	cmp	r6, #0
	bne.n	loc_08021e2a	@ 0x08021E2A
	b.n	loc_08021f34	@ 0x08021F34
	.global	loc_08021e2a
loc_08021e2a:
	b.n	loc_08021ea4	@ 0x08021EA4
	.word	gUnk_03005560
	.word	0x0000FFF0
	.word	gUnk_0300559C
	.global	loc_08021e38
loc_08021e38:
	ldr	r4, [pc, #12]	@ 0x08021E48
	adds	r0, r1, #0
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r4, #0]
	adds	r1, #16
	b.n	loc_08021e54	@ 0x08021E54
	movs	r0, r0
	.word	gUnk_03005570
	.global	loc_08021e4c
loc_08021e4c:
	adds	r0, r1, #0
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r4, #0]
	.global	loc_08021e54
loc_08021e54:
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	ldr	r0, [pc, #52]	@ 0x08021E90
	movs	r5, #0
	ldrsh	r0, [r0, r5]
	ldr	r4, [pc, #52]	@ 0x08021E94
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	ldr	r5, [pc, #48]	@ 0x08021E98
	movs	r3, #0
	ldrsh	r2, [r5, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	beq.n	loc_08021e82	@ 0x08021E82
	ldr	r0, [pc, #36]	@ 0x08021E9C
	ldrh	r0, [r0, #0]
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08021e82
loc_08021e82:
	ldr	r0, [pc, #28]	@ 0x08021EA0
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	movs	r3, #0
	ldrsh	r2, [r5, r3]
	b.n	loc_08021faa	@ 0x08021FAA
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_03005570
	.word	gUnk_03005584
	.word	gUnk_03005578
	.word	gUnk_03005530
	.global	loc_08021ea4
loc_08021ea4:
	cmp	r6, #1
	beq.n	loc_08021eac	@ 0x08021EAC
	cmp	r6, #2
	bne.n	loc_08021eba	@ 0x08021EBA
	.global	loc_08021eac
loc_08021eac:
	ldr	r4, [pc, #108]	@ 0x08021F1C
	adds	r0, r5, #0
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r4, #0]
	adds	r1, r1, r0
	strh	r1, [r4, #0]
	.global	loc_08021eba
loc_08021eba:
	ldr	r4, [pc, #100]	@ 0x08021F20
	mov	r8, r4
	movs	r5, #0
	ldrsh	r0, [r4, r5]
	ldr	r1, [pc, #96]	@ 0x08021F24
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	adds	r0, r0, r1
	ldr	r5, [pc, #80]	@ 0x08021F1C
	movs	r3, #0
	ldrsh	r1, [r5, r3]
	ldr	r4, [pc, #84]	@ 0x08021F28
	movs	r3, #0
	ldrsh	r2, [r4, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_08021ee6	@ 0x08021EE6
	movs	r0, #2
	negs	r0, r0
	ands	r6, r0
	.global	loc_08021ee6
loc_08021ee6:
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	ldr	r1, [pc, #60]	@ 0x08021F2C
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r5, r2]
	movs	r3, #0
	ldrsh	r2, [r4, r3]
	adds	r1, r1, r2
	bl	sub_08021634	@ 0x08021634
	cmp	r0, #0
	bne.n	loc_08021f0c	@ 0x08021F0C
	movs	r0, #3
	negs	r0, r0
	ands	r6, r0
	.global	loc_08021f0c
loc_08021f0c:
	cmp	r6, #0
	beq.n	loc_08021fd4	@ 0x08021FD4
	ldr	r0, [pc, #28]	@ 0x08021F30
	movs	r2, #0
	ldrsh	r1, [r5, r2]
	movs	r3, #0
	ldrsh	r2, [r4, r3]
	b.n	loc_08021faa	@ 0x08021FAA
	.word	gUnk_03005570
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.word	gUnk_03005584
	.word	gUnk_0300559C
	.word	gUnk_03005530
	.global	loc_08021f34
loc_08021f34:
	movs	r4, #0
	ldr	r5, [pc, #128]	@ 0x08021FB8
	mov	r8, r5
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	ldr	r1, [pc, #124]	@ 0x08021FBC
	movs	r2, #0
	ldrsh	r1, [r1, r2]
	adds	r0, r0, r1
	ldr	r5, [pc, #120]	@ 0x08021FC0
	movs	r3, #0
	ldrsh	r1, [r5, r3]
	ldr	r6, [pc, #116]	@ 0x08021FC4
	movs	r3, #0
	ldrsh	r2, [r6, r3]
	adds	r1, r1, r2
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	beq.n	loc_08021f6c	@ 0x08021F6C
	ldr	r0, [pc, #104]	@ 0x08021FC8
	ldrh	r0, [r0, #0]
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	movs	r4, #2
	.global	loc_08021f6c
loc_08021f6c:
	mov	r1, r8
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	ldr	r1, [pc, #88]	@ 0x08021FCC
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r5, r2]
	movs	r3, #0
	ldrsh	r2, [r6, r3]
	adds	r1, r1, r2
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	beq.n	loc_08021f9c	@ 0x08021F9C
	ldr	r0, [pc, #56]	@ 0x08021FC8
	ldrh	r0, [r0, #0]
	bl	sub_08021970	@ 0x08021970
	ldrh	r1, [r5, #0]
	adds	r1, r1, r0
	strh	r1, [r5, #0]
	adds	r4, #1
	.global	loc_08021f9c
loc_08021f9c:
	cmp	r4, #0
	beq.n	loc_08021fd4	@ 0x08021FD4
	ldr	r0, [pc, #44]	@ 0x08021FD0
	movs	r4, #0
	ldrsh	r1, [r5, r4]
	movs	r5, #0
	ldrsh	r2, [r6, r5]
	.global	loc_08021faa
loc_08021faa:
	adds	r1, r1, r2
	adds	r1, #1
	asrs	r1, r1, #4
	strb	r1, [r0, #12]
	adds	r1, r0, #0
	b.n	loc_08021fde	@ 0x08021FDE
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.word	gUnk_03005570
	.word	gUnk_03005584
	.word	gUnk_03005578
	.word	gUnk_0300559C
	.word	gUnk_03005530
	.global	loc_08021fd4
loc_08021fd4:
	ldr	r1, [pc, #120]	@ 0x08022050
	movs	r0, #0
	strb	r0, [r1, #6]
	strb	r0, [r1, #2]
	strb	r0, [r1, #11]
	.global	loc_08021fde
loc_08021fde:
	ldrb	r0, [r1, #6]
	adds	r2, r7, #0
	adds	r2, #122
	strb	r0, [r2, #0]
	ldrb	r0, [r1, #12]
	lsls	r0, r0, #8
	ldrb	r1, [r1, #11]
	orrs	r1, r0
	adds	r0, r7, #0
	adds	r0, #132
	strh	r1, [r0, #0]
	ldr	r0, [pc, #92]	@ 0x08022054
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	mov	r3, r9
	movs	r0, #0
	ldrsb	r0, [r3, r0]
	subs	r4, r1, r0
	ldr	r0, [r7, #76]
	asrs	r0, r0, #16
	cmp	r0, r4
	beq.n	loc_0802201a	@ 0x0802201A
	lsls	r0, r4, #16
	movs	r1, #128
	lsls	r1, r1, #8
	adds	r0, r0, r1
	str	r0, [r7, #76]
	adds	r0, r7, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	.global	loc_0802201a
loc_0802201a:
	ldr	r0, [pc, #60]	@ 0x08022058
	movs	r4, #0
	ldrsh	r1, [r0, r4]
	mov	r5, r9
	movs	r0, #1
	ldrsb	r0, [r5, r0]
	subs	r4, r1, r0
	ldr	r0, [r7, #80]
	asrs	r0, r0, #16
	cmp	r0, r4
	beq.n	loc_08022040	@ 0x08022040
	lsls	r0, r4, #16
	movs	r1, #128
	lsls	r1, r1, #8
	adds	r0, r0, r1
	str	r0, [r7, #80]
	adds	r0, r7, #0
	adds	r0, #74
	strh	r4, [r0, #0]
	.global	loc_08022040
loc_08022040:
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_03005530
	.word	gUnk_03005560
	.word	gUnk_03005570
	.thumb_func
	.global	sub_0802205c
sub_0802205c:
	.thumb
	push	{r4, r5, r6, lr}
	ldr	r5, [pc, #220]	@ 0x0802213C
	ldr	r1, [pc, #220]	@ 0x08022140
	ldr	r3, [r1, #0]
	ldr	r2, [r3, #76]
	asrs	r2, r2, #16
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	adds	r1, r1, r2
	strh	r1, [r5, #0]
	ldr	r4, [pc, #208]	@ 0x08022144
	ldr	r2, [r3, #80]
	asrs	r2, r2, #16
	movs	r1, #1
	ldrsb	r1, [r0, r1]
	adds	r1, r1, r2
	strh	r1, [r4, #0]
	ldr	r2, [pc, #200]	@ 0x08022148
	movs	r1, #2
	ldrsb	r1, [r0, r1]
	strh	r1, [r2, #0]
	ldr	r2, [pc, #196]	@ 0x0802214C
	movs	r1, #3
	ldrsb	r1, [r0, r1]
	strh	r1, [r2, #0]
	ldr	r6, [pc, #192]	@ 0x08022150
	movs	r1, #4
	ldrsb	r1, [r0, r1]
	strh	r1, [r6, #0]
	ldr	r2, [pc, #188]	@ 0x08022154
	ldrb	r0, [r0, #5]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	strh	r0, [r2, #0]
	ldr	r1, [pc, #180]	@ 0x08022158
	movs	r0, #0
	strb	r0, [r1, #11]
	adds	r3, #67
	movs	r1, #0
	ldrsb	r1, [r3, r1]
	subs	r0, #1
	cmp	r1, r0
	beq.n	loc_08022170	@ 0x08022170
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	adds	r0, r0, r1
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	beq.n	loc_080220ca	@ 0x080220CA
	b.n	loc_080221f0	@ 0x080221F0
	.global	loc_080220ca
loc_080220ca:
	ldr	r1, [pc, #144]	@ 0x0802215C
	ldr	r0, [pc, #144]	@ 0x08022160
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080220ee	@ 0x080220EE
	ldr	r0, [pc, #132]	@ 0x08022164
	adds	r0, r2, r0
	ldrb	r2, [r0, #0]
	cmp	r2, #0
	beq.n	loc_080220ee	@ 0x080220EE
	movs	r0, #1
	ands	r0, r2
	cmp	r0, #0
	bne.n	loc_08022132	@ 0x08022132
	.global	loc_080220ee
loc_080220ee:
	ldr	r0, [pc, #120]	@ 0x08022168
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08022100	@ 0x08022100
	b.n	loc_0802228e	@ 0x0802228E
	.global	loc_08022100
loc_08022100:
	ldr	r0, [pc, #96]	@ 0x08022164
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	bne.n	loc_0802210c	@ 0x0802210C
	b.n	loc_0802228e	@ 0x0802228E
	.global	loc_0802210c
loc_0802210c:
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_08022116	@ 0x08022116
	b.n	loc_0802228e	@ 0x0802228E
	.global	loc_08022116
loc_08022116:
	ldr	r0, [pc, #84]	@ 0x0802216C
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08022132	@ 0x08022132
	ldr	r0, [pc, #28]	@ 0x08022144
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	ble.n	loc_08022132	@ 0x08022132
	b.n	loc_0802228e	@ 0x0802228E
	.global	loc_08022132
loc_08022132:
	ldr	r2, [pc, #36]	@ 0x08022158
	ldrb	r1, [r2, #11]
	movs	r0, #4
	b.n	loc_080221ec	@ 0x080221EC
	movs	r0, r0
	.word	gUnk_03005560
	.word	gUnk_03002490
	.word	gUnk_03005570
	.word	gUnk_0300557C
	.word	gUnk_03005584
	.word	gUnk_0300551C
	.word	gUnk_0300559C
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.word	gUnk_03005510
	.word	gUnk_08732DF0
	.global	loc_08022170
loc_08022170:
	movs	r3, #0
	ldrsh	r0, [r5, r3]
	movs	r2, #0
	ldrsh	r1, [r6, r2]
	adds	r0, r0, r1
	movs	r3, #0
	ldrsh	r1, [r4, r3]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	bne.n	loc_080221f0	@ 0x080221F0
	ldr	r1, [pc, #200]	@ 0x08022250
	ldr	r0, [pc, #200]	@ 0x08022254
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080221aa	@ 0x080221AA
	ldr	r0, [pc, #188]	@ 0x08022258
	adds	r0, r2, r0
	ldrb	r2, [r0, #0]
	cmp	r2, #0
	beq.n	loc_080221aa	@ 0x080221AA
	movs	r0, #1
	ands	r0, r2
	cmp	r0, #0
	beq.n	loc_080221e6	@ 0x080221E6
	.global	loc_080221aa
loc_080221aa:
	ldr	r0, [pc, #176]	@ 0x0802225C
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802228e	@ 0x0802228E
	ldr	r0, [pc, #156]	@ 0x08022258
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_0802228e	@ 0x0802228E
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802228e	@ 0x0802228E
	ldr	r0, [pc, #144]	@ 0x08022260
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080221e6	@ 0x080221E6
	ldr	r0, [pc, #136]	@ 0x08022264
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	bgt.n	loc_0802228e	@ 0x0802228E
	.global	loc_080221e6
loc_080221e6:
	ldr	r2, [pc, #128]	@ 0x08022268
	ldrb	r1, [r2, #11]
	movs	r0, #2
	.global	loc_080221ec
loc_080221ec:
	orrs	r0, r1
	strb	r0, [r2, #11]
	.global	loc_080221f0
loc_080221f0:
	ldr	r0, [pc, #120]	@ 0x0802226C
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r5, [pc, #108]	@ 0x08022264
	movs	r2, #0
	ldrsh	r1, [r5, r2]
	ldr	r4, [pc, #112]	@ 0x08022270
	movs	r3, #0
	ldrsh	r2, [r4, r3]
	adds	r1, r1, r2
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	bne.n	loc_0802228e	@ 0x0802228E
	ldr	r3, [pc, #64]	@ 0x08022250
	ldr	r0, [pc, #100]	@ 0x08022274
	ldrh	r0, [r0, #0]
	adds	r0, r0, r3
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802228e	@ 0x0802228E
	ldr	r2, [pc, #72]	@ 0x08022268
	ldrb	r1, [r2, #11]
	movs	r0, #1
	orrs	r0, r1
	strb	r0, [r2, #11]
	ldr	r0, [pc, #40]	@ 0x08022254
	ldrh	r1, [r0, #0]
	adds	r0, r1, r3
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08022278	@ 0x08022278
	ldr	r0, [pc, #28]	@ 0x08022258
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08022278	@ 0x08022278
	movs	r1, #0
	ldrsh	r0, [r5, r1]
	movs	r3, #0
	ldrsh	r1, [r4, r3]
	adds	r0, r0, r1
	b.n	loc_0802228a	@ 0x0802228A
	movs	r0, r0
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.word	gUnk_03005594
	.word	gUnk_08732DF0
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_03005560
	.word	gUnk_03005584
	.word	gUnk_03005588
	.global	loc_08022278
loc_08022278:
	ldr	r2, [pc, #36]	@ 0x080222A0
	ldr	r0, [pc, #40]	@ 0x080222A4
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #36]	@ 0x080222A8
	movs	r3, #0
	ldrsh	r1, [r1, r3]
	adds	r0, r0, r1
	adds	r0, #16
	.global	loc_0802228a
loc_0802228a:
	asrs	r0, r0, #4
	strb	r0, [r2, #12]
	.global	loc_0802228e
loc_0802228e:
	ldr	r0, [pc, #28]	@ 0x080222AC
	ldr	r0, [r0, #0]
	ldr	r1, [pc, #12]	@ 0x080222A0
	ldrb	r1, [r1, #11]
	adds	r0, #132
	strh	r1, [r0, #0]
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	.word	gUnk_03005530
	.word	gUnk_03005570
	.word	gUnk_03005584
	.word	gUnk_03002490
	.thumb_func
	.global	sub_080222b0
sub_080222b0:
	.thumb
	push	{r4, r5, lr}
	adds	r4, r1, #0
	ldr	r5, [pc, #72]	@ 0x08022300
	movs	r1, #0
	strb	r1, [r5, #11]
	strb	r1, [r5, #12]
	adds	r1, r4, #0
	bl	sub_080216d8	@ 0x080216D8
	cmp	r0, #0
	bne.n	loc_08022324	@ 0x08022324
	ldr	r2, [pc, #60]	@ 0x08022304
	ldr	r0, [pc, #60]	@ 0x08022308
	ldrh	r0, [r0, #0]
	adds	r0, r0, r2
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08022324	@ 0x08022324
	ldrb	r0, [r5, #11]
	movs	r1, #1
	orrs	r0, r1
	strb	r0, [r5, #11]
	ldr	r0, [pc, #40]	@ 0x0802230C
	ldrh	r1, [r0, #0]
	adds	r0, r1, r2
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08022314	@ 0x08022314
	ldr	r0, [pc, #28]	@ 0x08022310
	adds	r0, r1, r0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08022314	@ 0x08022314
	asrs	r0, r4, #4
	strb	r0, [r5, #12]
	b.n	loc_08022332	@ 0x08022332
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005588
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.global	loc_08022314
loc_08022314:
	ldr	r1, [pc, #8]	@ 0x08022320
	adds	r0, r4, #0
	adds	r0, #16
	asrs	r0, r0, #4
	strb	r0, [r1, #12]
	b.n	loc_08022332	@ 0x08022332
	.word	gUnk_03005530
	.global	loc_08022324
loc_08022324:
	ldr	r1, [pc, #16]	@ 0x08022338
	ldrb	r2, [r1, #11]
	movs	r0, #254
	ands	r0, r2
	movs	r2, #0
	strb	r0, [r1, #11]
	strb	r2, [r1, #12]
	.global	loc_08022332
loc_08022332:
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	gUnk_03005530
	.thumb_func
	.global	sub_0802233c
sub_0802233c:
	.thumb
	push	{r4, r5, lr}
	ldr	r4, [pc, #176]	@ 0x080223F0
	ldr	r5, [pc, #176]	@ 0x080223F4
	ldr	r3, [r5, #0]
	ldr	r2, [r3, #76]
	asrs	r2, r2, #16
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	adds	r1, r1, r2
	strh	r1, [r4, #0]
	ldr	r2, [pc, #164]	@ 0x080223F8
	ldr	r1, [r3, #80]
	asrs	r1, r1, #16
	ldrb	r0, [r0, #1]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	adds	r0, r0, r1
	strh	r0, [r2, #0]
	ldr	r1, [pc, #152]	@ 0x080223FC
	movs	r0, #0
	strb	r0, [r1, #11]
	movs	r1, #0
	ldrsh	r0, [r4, r1]
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	bl	sub_080217dc	@ 0x080217DC
	cmp	r0, #0
	beq.n	loc_08022378	@ 0x08022378
	b.n	loc_0802247e	@ 0x0802247E
	.global	loc_08022378
loc_08022378:
	ldr	r0, [r5, #0]
	adds	r0, #67
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_08022414	@ 0x08022414
	ldr	r1, [pc, #116]	@ 0x08022400
	ldr	r0, [pc, #120]	@ 0x08022404
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_080223ac	@ 0x080223AC
	ldr	r0, [pc, #108]	@ 0x08022408
	adds	r0, r2, r0
	ldrb	r2, [r0, #0]
	cmp	r2, #0
	beq.n	loc_080223ac	@ 0x080223AC
	movs	r0, #1
	ands	r0, r2
	cmp	r0, #0
	bne.n	loc_080223e8	@ 0x080223E8
	.global	loc_080223ac
loc_080223ac:
	ldr	r0, [pc, #92]	@ 0x0802240C
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802247e	@ 0x0802247E
	ldr	r0, [pc, #72]	@ 0x08022408
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_0802247e	@ 0x0802247E
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0802247e	@ 0x0802247E
	ldr	r0, [pc, #64]	@ 0x08022410
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_080223e8	@ 0x080223E8
	ldr	r0, [pc, #24]	@ 0x080223F8
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	bgt.n	loc_0802247e	@ 0x0802247E
	.global	loc_080223e8
loc_080223e8:
	ldr	r2, [pc, #16]	@ 0x080223FC
	ldrb	r1, [r2, #11]
	movs	r0, #4
	b.n	loc_0802247a	@ 0x0802247A
	.word	gUnk_03005560
	.word	gUnk_03002490
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.word	gUnk_03005510
	.word	gUnk_08732DF0
	.global	loc_08022414
loc_08022414:
	ldr	r1, [pc, #120]	@ 0x08022490
	ldr	r0, [pc, #124]	@ 0x08022494
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08022438	@ 0x08022438
	ldr	r0, [pc, #112]	@ 0x08022498
	adds	r0, r2, r0
	ldrb	r2, [r0, #0]
	cmp	r2, #0
	beq.n	loc_08022438	@ 0x08022438
	movs	r0, #1
	ands	r0, r2
	cmp	r0, #0
	beq.n	loc_08022474	@ 0x08022474
	.global	loc_08022438
loc_08022438:
	ldr	r0, [pc, #96]	@ 0x0802249C
	ldrh	r2, [r0, #0]
	adds	r0, r2, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802247e	@ 0x0802247E
	ldr	r0, [pc, #76]	@ 0x08022498
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	cmp	r1, #0
	beq.n	loc_0802247e	@ 0x0802247E
	movs	r0, #1
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_0802247e	@ 0x0802247E
	ldr	r0, [pc, #68]	@ 0x080224A0
	adds	r0, r2, r0
	ldrb	r1, [r0, #0]
	movs	r0, #207
	ands	r0, r1
	cmp	r0, #131
	bne.n	loc_08022474	@ 0x08022474
	ldr	r0, [pc, #56]	@ 0x080224A4
	ldrh	r1, [r0, #0]
	movs	r0, #15
	ands	r0, r1
	cmp	r0, #7
	bgt.n	loc_0802247e	@ 0x0802247E
	.global	loc_08022474
loc_08022474:
	ldr	r2, [pc, #48]	@ 0x080224A8
	ldrb	r1, [r2, #11]
	movs	r0, #2
	.global	loc_0802247a
loc_0802247a:
	orrs	r0, r1
	strb	r0, [r2, #11]
	.global	loc_0802247e
loc_0802247e:
	ldr	r0, [pc, #44]	@ 0x080224AC
	ldr	r0, [r0, #0]
	ldr	r1, [pc, #36]	@ 0x080224A8
	ldrb	r1, [r1, #11]
	adds	r0, #132
	strh	r1, [r0, #0]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	gUnk_087336F0
	.word	gUnk_03005578
	.word	gUnk_08732CF0
	.word	gUnk_03005594
	.word	gUnk_08732DF0
	.word	gUnk_03005570
	.word	gUnk_03005530
	.word	gUnk_03002490
	.thumb_func
	.global	sub_080224b0
sub_080224b0:
	.thumb
	push	{r4, lr}
	ldr	r4, [pc, #32]	@ 0x080224D4
	ldr	r1, [r4, #0]
	ldr	r0, [r1, #76]
	asrs	r0, r0, #16
	ldr	r1, [r1, #80]
	asrs	r1, r1, #16
	bl	sub_08021634	@ 0x08021634
	ldr	r0, [pc, #20]	@ 0x080224D8
	ldrh	r0, [r0, #0]
	cmp	r0, #127
	bls.n	loc_080224dc	@ 0x080224DC
	ldr	r0, [r4, #0]
	adds	r0, #123
	movs	r1, #3
	b.n	loc_080224e2	@ 0x080224E2
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_03005578
	.global	loc_080224dc
loc_080224dc:
	ldr	r0, [r4, #0]
	adds	r0, #123
	movs	r1, #0
	.global	loc_080224e2
loc_080224e2:
	strb	r1, [r0, #0]
	ldr	r0, [pc, #12]	@ 0x080224F4
	ldr	r0, [r0, #0]
	adds	r0, #132
	movs	r1, #128
	strh	r1, [r0, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.thumb_func
	.global	sub_080224f8
sub_080224f8:
	.thumb
	push	{r4, lr}
	lsls	r1, r0, #3
	adds	r1, r1, r0
	lsls	r1, r1, #4
	ldr	r0, [pc, #28]	@ 0x08022520
	adds	r4, r1, r0
	ldr	r0, [r4, #76]
	asrs	r0, r0, #16
	ldr	r1, [r4, #80]
	asrs	r1, r1, #16
	bl	sub_08021634	@ 0x08021634
	ldr	r0, [pc, #16]	@ 0x08022524
	ldrh	r0, [r0, #0]
	cmp	r0, #127
	bls.n	loc_08022528	@ 0x08022528
	adds	r1, r4, #0
	adds	r1, #123
	movs	r0, #3
	b.n	loc_0802252e	@ 0x0802252E
	.word	gUnk_03002790
	.word	gUnk_03005578
	.global	loc_08022528
loc_08022528:
	adds	r1, r4, #0
	adds	r1, #123
	movs	r0, #0
	.global	loc_0802252e
loc_0802252e:
	strb	r0, [r1, #0]
	adds	r1, r4, #0
	adds	r1, #132
	movs	r0, #128
	strh	r0, [r1, #0]
	pop	{r4}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.thumb_func
	.global	sub_08022540
sub_08022540:
	.thumb
	push	{r4, lr}
	adds	r2, r0, #0
	lsrs	r2, r2, #4
	lsrs	r1, r1, #4
	ldr	r0, [pc, #64]	@ 0x0802258C
	movs	r4, #0
	ldrsh	r3, [r0, r4]
	cmp	r2, r3
	bcs.n	loc_08022582	@ 0x08022582
	ldr	r0, [pc, #60]	@ 0x08022590
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	cmp	r1, r0
	bcs.n	loc_08022582	@ 0x08022582
	adds	r0, r1, #0
	muls	r0, r3
	adds	r0, r0, r2
	ldr	r1, [pc, #48]	@ 0x08022594
	lsls	r0, r0, #1
	adds	r2, r0, r1
	ldrh	r0, [r2, #0]
	cmp	r0, #0
	beq.n	loc_08022582	@ 0x08022582
	ldr	r0, [pc, #40]	@ 0x08022598
	ldr	r1, [r0, #0]
	ldrh	r0, [r2, #0]
	ldr	r1, [r1, #16]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldrb	r0, [r0, #7]
	subs	r0, #56
	cmp	r0, #5
	bls.n	loc_08022586	@ 0x08022586
	.global	loc_08022582
loc_08022582:
	movs	r0, #1
	negs	r0, r0
	.global	loc_08022586
loc_08022586:
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.word	gUnk_02008160
	.word	gUnk_030055EC
	.thumb_func
	.global	sub_0802259c
sub_0802259c:
	.thumb
	push	{r4, r5, r6, lr}
	lsls	r0, r0, #16
	lsls	r1, r1, #16
	lsrs	r4, r0, #20
	lsrs	r3, r1, #20
	ldr	r0, [pc, #24]	@ 0x080225C0
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	cmp	r4, r1
	bge.n	loc_080225ba	@ 0x080225BA
	ldr	r0, [pc, #16]	@ 0x080225C4
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r3, r0
	blt.n	loc_080225c8	@ 0x080225C8
	.global	loc_080225ba
loc_080225ba:
	movs	r0, #0
	b.n	loc_08022612	@ 0x08022612
	movs	r0, r0
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.global	loc_080225c8
loc_080225c8:
	adds	r0, r3, #0
	muls	r0, r1
	ldr	r1, [pc, #72]	@ 0x08022618
	ldr	r2, [r1, #0]
	lsls	r1, r4, #2
	lsls	r0, r0, #2
	adds	r0, r0, r2
	adds	r1, r1, r0
	ldrb	r5, [r1, #3]
	movs	r6, #0
	cmp	r5, #127
	ble.n	loc_080225e4	@ 0x080225E4
	movs	r6, #128
	lsls	r6, r6, #1
	.global	loc_080225e4
loc_080225e4:
	ldr	r1, [pc, #52]	@ 0x0802261C
	lsls	r0, r5, #2
	adds	r0, r0, r1
	movs	r2, #15
	ands	r3, r2
	lsls	r1, r3, #4
	ands	r4, r2
	ldr	r0, [r0, #0]
	adds	r1, r1, r4
	adds	r0, r0, r1
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_0802260e	@ 0x0802260E
	ldr	r0, [pc, #28]	@ 0x08022620
	adds	r0, r5, r0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	orrs	r6, r0
	.global	loc_0802260e
loc_0802260e:
	lsls	r0, r6, #16
	lsrs	r0, r0, #16
	.global	loc_08022612
loc_08022612:
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	.word	gUnk_03005660
	.word	gUnk_087328F0
	.word	0x087335F0
	.thumb_func
	.global	sub_08022624
sub_08022624:
	.thumb
	push	{r4, lr}
	lsls	r0, r0, #16
	lsrs	r0, r0, #16
	lsls	r1, r1, #16
	lsrs	r1, r1, #16
	ldr	r4, [pc, #20]	@ 0x08022644
	bl	sub_08021b18	@ 0x08021B18
	adds	r0, r0, r4
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	beq.n	loc_08022648	@ 0x08022648
	movs	r0, #0
	b.n	loc_0802264a	@ 0x0802264A
	.word	gUnk_08732EF0
	.global	loc_08022648
loc_08022648:
	movs	r0, #1
	.global	loc_0802264a
loc_0802264a:
	pop	{r4}
	pop	{r1}
	bx	r1
	.thumb_func
	.global	sub_08022650
sub_08022650:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	ldr	r5, [pc, #80]	@ 0x080226B0
	movs	r0, #0
	strb	r0, [r5, #0]
	ldr	r3, [pc, #80]	@ 0x080226B4
	movs	r0, #0
	strh	r0, [r3, #0]
	ldr	r1, [pc, #76]	@ 0x080226B8
	ldr	r2, [pc, #80]	@ 0x080226BC
	ldr	r0, [r2, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r1
	movs	r6, #0
	ldrsh	r4, [r0, r6]
	mov	sl, r4
	ldr	r7, [pc, #68]	@ 0x080226C0
	movs	r4, #0
	ldrsh	r0, [r7, r4]
	str	r0, [sp, #0]
	ldr	r6, [pc, #64]	@ 0x080226C4
	mov	ip, r6
	movs	r4, #0
	ldrsh	r0, [r6, r4]
	ldr	r6, [sp, #0]
	adds	r0, r6, r0
	mov	r8, r5
	mov	r9, r3
	adds	r5, r1, #0
	adds	r3, r2, #0
	cmp	sl, r0
	ble.n	loc_080226c8	@ 0x080226C8
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	ldrh	r0, [r0, #0]
	mov	r2, ip
	ldrh	r1, [r2, #0]
	subs	r0, r0, r1
	strh	r0, [r7, #0]
	movs	r0, #1
	mov	r4, r8
	strb	r0, [r4, #0]
	b.n	loc_080226f4	@ 0x080226F4
	.word	gUnk_03005568
	.word	0x03005544
	.word	gUnk_03005640
	.word	gCurTaskIdx
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.global	loc_080226c8
loc_080226c8:
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	movs	r6, #2
	ldrsh	r1, [r0, r6]
	ldr	r2, [pc, #124]	@ 0x08022750
	movs	r4, #0
	ldrsh	r0, [r2, r4]
	ldr	r6, [sp, #0]
	adds	r0, r6, r0
	cmp	r1, r0
	bge.n	loc_080226f4	@ 0x080226F4
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	ldrh	r0, [r0, #2]
	ldrh	r1, [r2, #0]
	subs	r0, r0, r1
	strh	r0, [r7, #0]
	movs	r0, #2
	mov	r7, r8
	strb	r0, [r7, #0]
	.global	loc_080226f4
loc_080226f4:
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	movs	r1, #4
	ldrsh	r2, [r0, r1]
	ldr	r6, [pc, #84]	@ 0x08022754
	movs	r4, #0
	ldrsh	r0, [r6, r4]
	ldr	r4, [pc, #80]	@ 0x08022758
	movs	r7, #0
	ldrsh	r1, [r4, r7]
	adds	r0, r0, r1
	cmp	r2, r0
	ble.n	loc_0802273e	@ 0x0802273E
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	ldrh	r0, [r0, #4]
	ldrh	r1, [r4, #0]
	subs	r0, r0, r1
	strh	r0, [r6, #0]
	mov	r1, r8
	ldrb	r0, [r1, #0]
	movs	r1, #4
	orrs	r0, r1
	mov	r2, r8
	strb	r0, [r2, #0]
	ldr	r0, [pc, #48]	@ 0x0802275C
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0802273e	@ 0x0802273E
	ldr	r0, [r3, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r5
	ldrh	r0, [r0, #4]
	mov	r4, r9
	strh	r0, [r4, #0]
	.global	loc_0802273e
loc_0802273e:
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_0300559C
	.word	gUnk_03005570
	.word	gUnk_0300557C
	.word	gUnk_02005574
	.thumb_func
	.global	sub_08022760
sub_08022760:
	.thumb
	ldr	r2, [pc, #24]	@ 0x0802277C
	ldr	r1, [pc, #28]	@ 0x08022780
	ldr	r1, [r1, #0]
	lsls	r1, r1, #3
	adds	r1, r1, r2
	adds	r0, #74
	movs	r2, #6
	ldrsh	r1, [r1, r2]
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r1, r0
	blt.n	loc_08022784	@ 0x08022784
	movs	r0, #0
	b.n	loc_08022786	@ 0x08022786
	.word	gUnk_03005640
	.word	gCurTaskIdx
	.global	loc_08022784
loc_08022784:
	movs	r0, #1
	.global	loc_08022786
loc_08022786:
	bx	lr
	.thumb_func
	.global	sub_08022788
sub_08022788:
	.thumb
	ldr	r2, [pc, #16]	@ 0x0802279C
	lsls	r1, r1, #3
	adds	r1, r1, r2
	movs	r2, #4
	ldrsh	r1, [r1, r2]
	cmp	r1, r0
	beq.n	loc_080227a0	@ 0x080227A0
	movs	r0, #0
	b.n	loc_080227a2	@ 0x080227A2
	movs	r0, r0
	.word	gUnk_03005640
	.global	loc_080227a0
loc_080227a0:
	movs	r0, #1
	.global	loc_080227a2
loc_080227a2:
	bx	lr
	.thumb_func
	.global	sub_080227a4
sub_080227a4:
	.thumb
	push	{r4, r5, r6, lr}
	mov	ip, r0
	movs	r5, #0
	ldr	r0, [pc, #40]	@ 0x080227D4
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r2, r1, #0
	subs	r2, #111
	movs	r3, #2
	ldrsh	r1, [r0, r3]
	adds	r1, #111
	mov	r3, ip
	adds	r3, #72
	movs	r6, #0
	ldrsh	r4, [r3, r6]
	adds	r6, r0, #0
	cmp	r2, r4
	ble.n	loc_080227d8	@ 0x080227D8
	lsls	r0, r2, #16
	mov	r1, ip
	str	r0, [r1, #76]
	strh	r2, [r3, #0]
	movs	r5, #1
	b.n	loc_080227e6	@ 0x080227E6
	.word	gUnk_03005628
	.global	loc_080227d8
loc_080227d8:
	cmp	r1, r4
	bge.n	loc_080227e6	@ 0x080227E6
	lsls	r0, r1, #16
	mov	r2, ip
	str	r0, [r2, #76]
	strh	r1, [r3, #0]
	movs	r5, #2
	.global	loc_080227e6
loc_080227e6:
	movs	r3, #4
	ldrsh	r0, [r6, r3]
	adds	r2, r0, #0
	subs	r2, #72
	mov	r1, ip
	adds	r1, #74
	movs	r6, #0
	ldrsh	r0, [r1, r6]
	cmp	r2, r0
	ble.n	loc_08022806	@ 0x08022806
	lsls	r0, r2, #16
	mov	r3, ip
	str	r0, [r3, #80]
	strh	r2, [r1, #0]
	movs	r0, #4
	orrs	r5, r0
	.global	loc_08022806
loc_08022806:
	adds	r0, r5, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_08022810
sub_08022810:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	ldr	r1, [pc, #60]	@ 0x08022858
	mov	ip, r1
	movs	r1, #0
	mov	r2, ip
	strb	r1, [r2, #0]
	ldr	r2, [pc, #56]	@ 0x0802285C
	movs	r3, #0
	ldrsh	r1, [r2, r3]
	adds	r4, r1, #0
	subs	r4, #117
	movs	r5, #2
	ldrsh	r1, [r2, r5]
	adds	r3, r1, #0
	adds	r3, #117
	ldr	r6, [pc, #40]	@ 0x08022860
	movs	r1, #0
	ldrsh	r7, [r6, r1]
	mov	r9, r7
	ldr	r5, [pc, #36]	@ 0x08022864
	movs	r7, #0
	ldrsh	r1, [r5, r7]
	add	r1, r9
	cmp	r4, r1
	ble.n	loc_08022868	@ 0x08022868
	ldrh	r1, [r5, #0]
	subs	r1, r4, r1
	strh	r1, [r6, #0]
	movs	r1, #1
	mov	r3, ip
	strb	r1, [r3, #0]
	b.n	loc_08022880	@ 0x08022880
	movs	r0, r0
	.word	gUnk_03005568
	.word	gUnk_030055F8
	.word	gUnk_03005560
	.word	gUnk_0300551C
	.global	loc_08022868
loc_08022868:
	ldr	r4, [pc, #76]	@ 0x080228B8
	movs	r5, #0
	ldrsh	r1, [r4, r5]
	add	r1, r9
	cmp	r3, r1
	bge.n	loc_08022880	@ 0x08022880
	ldrh	r1, [r4, #0]
	subs	r1, r3, r1
	strh	r1, [r6, #0]
	movs	r1, #2
	mov	r7, ip
	strb	r1, [r7, #0]
	.global	loc_08022880
loc_08022880:
	movs	r3, #4
	ldrsh	r1, [r2, r3]
	adds	r4, r1, #0
	subs	r4, #76
	ldr	r6, [pc, #48]	@ 0x080228BC
	movs	r5, #0
	ldrsh	r1, [r6, r5]
	ldr	r5, [pc, #48]	@ 0x080228C0
	movs	r7, #0
	ldrsh	r2, [r5, r7]
	adds	r1, r1, r2
	cmp	r4, r1
	ble.n	loc_080228ac	@ 0x080228AC
	ldrh	r1, [r5, #0]
	subs	r1, r4, r1
	strh	r1, [r6, #0]
	mov	r2, ip
	ldrb	r1, [r2, #0]
	movs	r2, #4
	orrs	r1, r2
	mov	r3, ip
	strb	r1, [r3, #0]
	.global	loc_080228ac
loc_080228ac:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.word	gUnk_0300559C
	.word	gUnk_03005570
	.word	gUnk_0300557C
	.thumb_func
	.global	sub_080228c4
sub_080228c4:
	.thumb
	push	{r4, r5, r6, lr}
	mov	ip, r0
	movs	r5, #0
	ldr	r0, [pc, #48]	@ 0x080228FC
	movs	r2, #0
	ldrsh	r1, [r0, r2]
	adds	r3, r1, #0
	subs	r3, #111
	movs	r6, #2
	ldrsh	r1, [r0, r6]
	adds	r1, #111
	mov	r4, ip
	adds	r4, #72
	movs	r6, #0
	ldrsh	r2, [r4, r6]
	adds	r6, r0, #0
	cmp	r2, r3
	bge.n	loc_08022900	@ 0x08022900
	subs	r0, r3, r2
	cmp	r0, #11
	bgt.n	loc_08022914	@ 0x08022914
	lsls	r0, r3, #16
	mov	r1, ip
	str	r0, [r1, #76]
	strh	r3, [r4, #0]
	movs	r5, #1
	b.n	loc_08022914	@ 0x08022914
	movs	r0, r0
	.word	gUnk_030055F8
	.global	loc_08022900
loc_08022900:
	cmp	r1, r2
	bge.n	loc_08022914	@ 0x08022914
	subs	r0, r2, r3
	cmp	r0, #12
	ble.n	loc_08022914	@ 0x08022914
	lsls	r0, r1, #16
	mov	r2, ip
	str	r0, [r2, #76]
	strh	r1, [r4, #0]
	movs	r5, #2
	.global	loc_08022914
loc_08022914:
	movs	r1, #4
	ldrsh	r0, [r6, r1]
	adds	r3, r0, #0
	subs	r3, #72
	mov	r1, ip
	adds	r1, #74
	movs	r2, #0
	ldrsh	r0, [r1, r2]
	cmp	r3, r0
	ble.n	loc_08022942	@ 0x08022942
	mov	r0, ip
	adds	r0, #72
	movs	r6, #0
	ldrsh	r0, [r0, r6]
	subs	r0, r3, r0
	cmp	r0, #11
	bgt.n	loc_08022942	@ 0x08022942
	lsls	r0, r3, #16
	mov	r2, ip
	str	r0, [r2, #80]
	strh	r3, [r1, #0]
	movs	r0, #4
	orrs	r5, r0
	.global	loc_08022942
loc_08022942:
	adds	r0, r5, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.thumb_func
	.global	sub_0802294c
sub_0802294c:
	.thumb
	ldr	r1, [pc, #20]	@ 0x08022964
	movs	r2, #6
	ldrsh	r1, [r1, r2]
	adds	r1, #104
	adds	r0, #74
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r1, r0
	blt.n	loc_08022968	@ 0x08022968
	movs	r0, #0
	b.n	loc_0802296a	@ 0x0802296A
	movs	r0, r0
	.word	gUnk_03005628
	.global	loc_08022968
loc_08022968:
	movs	r0, #1
	.global	loc_0802296a
loc_0802296a:
	bx	lr
	.thumb_func
	.global	sub_0802296c
sub_0802296c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	ldr	r0, [pc, #152]	@ 0x08022A14
	movs	r1, #0
	strb	r1, [r0, #0]
	ldr	r0, [pc, #152]	@ 0x08022A18
	strb	r1, [r0, #0]
	ldr	r0, [pc, #152]	@ 0x08022A1C
	movs	r1, #0
	strh	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022A20
	strb	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022A24
	strb	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022A28
	strh	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022A2C
	strh	r1, [r0, #0]
	ldr	r2, [pc, #148]	@ 0x08022A30
	movs	r3, #1
	negs	r3, r3
	adds	r0, r3, #0
	strh	r0, [r2, #0]
	ldr	r0, [pc, #144]	@ 0x08022A34
	strb	r1, [r0, #0]
	movs	r3, #0
	ldr	r7, [pc, #140]	@ 0x08022A38
	mov	ip, r7
	movs	r4, #0
	ldr	r2, [pc, #140]	@ 0x08022A3C
	.global	loc_080229b0
loc_080229b0:
	movs	r1, #7
	adds	r0, r2, #0
	adds	r0, #28
	.global	loc_080229b6
loc_080229b6:
	str	r4, [r0, #0]
	subs	r0, #4
	subs	r1, #1
	cmp	r1, #0
	bge.n	loc_080229b6	@ 0x080229B6
	adds	r2, #32
	adds	r3, #1
	cmp	r3, #7
	ble.n	loc_080229b0	@ 0x080229B0
	movs	r3, #0
	ldr	r0, [pc, #116]	@ 0x08022A40
	movs	r1, #128
	lsls	r1, r1, #1
	mov	sl, r1
	ldr	r2, [pc, #112]	@ 0x08022A44
	mov	r9, r2
	ldr	r6, [pc, #92]	@ 0x08022A34
	movs	r7, #0
	str	r7, [sp, #0]
	adds	r5, r0, #0
	adds	r5, #12
	ldr	r4, [pc, #100]	@ 0x08022A48
	ldr	r0, [pc, #104]	@ 0x08022A4C
	mov	r8, r0
	.global	loc_080229e6
loc_080229e6:
	ldr	r1, [pc, #104]	@ 0x08022A50
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	beq.n	loc_080229f0	@ 0x080229F0
	movs	r0, #15
	.global	loc_080229f0
loc_080229f0:
	strb	r0, [r4, #0]
	ldrh	r1, [r5, #0]
	mov	r0, sl
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08022a54	@ 0x08022A54
	movs	r0, #255
	ands	r0, r1
	movs	r2, #1
	adds	r1, r2, #0
	lsls	r1, r0
	mov	r7, r9
	ldr	r0, [r7, #0]
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08022a6c	@ 0x08022A6C
	adds	r0, r2, #0
	b.n	loc_08022a64	@ 0x08022A64
	.word	0x02004C98
	.word	gUnk_0200AF08
	.word	gUnk_0200001C
	.word	gUnk_02004B64
	.word	0x0200B038
	.word	gUnk_02007FF0
	.word	gUnk_02007D60
	.word	gUnk_0200AF0C
	.word	gUnk_0200B04C
	.word	gUnk_03001F20
	.word	gUnk_02007BF0
	.word	0x08732348
	.word	gUnk_030023C8
	.word	gUnk_02007D58
	.word	gUnk_03002400
	.word	gUnk_03001F30
	.global	loc_08022a54
loc_08022a54:
	ldrh	r0, [r5, #0]
	ldr	r1, [sp, #0]
	adds	r0, r0, r1
	add	r0, r8
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08022a6c	@ 0x08022A6C
	movs	r0, #1
	.global	loc_08022a64
loc_08022a64:
	lsls	r0, r3
	ldrb	r1, [r6, #0]
	orrs	r0, r1
	strb	r0, [r6, #0]
	.global	loc_08022a6c
loc_08022a6c:
	ldr	r2, [sp, #0]
	adds	r2, #7
	str	r2, [sp, #0]
	adds	r5, #18
	adds	r4, #1
	adds	r3, #1
	cmp	r3, #6
	ble.n	loc_080229e6	@ 0x080229E6
	movs	r0, #8
	ldr	r3, [pc, #92]	@ 0x08022ADC
	strb	r0, [r3, #0]
	ldr	r7, [pc, #92]	@ 0x08022AE0
	ldrb	r1, [r7, #0]
	ldr	r0, [pc, #92]	@ 0x08022AE4
	strb	r1, [r0, #0]
	movs	r0, #0
	ldr	r2, [pc, #88]	@ 0x08022AE8
	strb	r0, [r2, #0]
	ldr	r3, [pc, #88]	@ 0x08022AEC
	strb	r0, [r3, #0]
	ldr	r7, [pc, #88]	@ 0x08022AF0
	strb	r1, [r7, #0]
	mov	r1, ip
	ldrb	r0, [r1, #0]
	ldr	r2, [pc, #84]	@ 0x08022AF4
	strb	r0, [r2, #0]
	ldr	r3, [pc, #64]	@ 0x08022AE4
	movs	r0, #0
	ldrsb	r0, [r3, r0]
	lsls	r0, r0, #2
	movs	r7, #128
	lsls	r7, r7, #1
	adds	r0, r0, r7
	ldr	r1, [pc, #72]	@ 0x08022AF8
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	ldr	r1, [r0, #0]
	ldr	r2, [r1, #68]
	ldr	r3, [pc, #64]	@ 0x08022AFC
	movs	r0, #0
	ldrsb	r0, [r3, r0]
	cmp	r0, #0
	bne.n	loc_08022b0c	@ 0x08022B0C
	ldr	r0, [pc, #60]	@ 0x08022B00
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08022b0c	@ 0x08022B0C
	ldr	r7, [pc, #52]	@ 0x08022B04
	strb	r0, [r7, #0]
	movs	r0, #2
	ldr	r1, [pc, #48]	@ 0x08022B08
	strb	r0, [r1, #0]
	b.n	loc_08022c16	@ 0x08022C16
	movs	r0, r0
	.word	gUnk_0300238C
	.word	gUnk_030023B8
	.word	gUnk_030023EC
	.word	gUnk_03002468
	.word	gUnk_0200AF04
	.word	0x02005578
	.word	0x02007FF8
	.word	gUnk_087E1D58
	.word	gUnk_030023E0
	.word	gUnk_03002384
	.word	gUnk_02006170
	.word	gUnk_020069F0
	.global	loc_08022b0c
loc_08022b0c:
	mov	r3, ip
	movs	r0, #0
	ldrsb	r0, [r3, r0]
	cmp	r0, #16
	bne.n	loc_08022b68	@ 0x08022B68
	movs	r3, #0
	ldrh	r4, [r1, #58]
	ldr	r6, [pc, #8]	@ 0x08022B24
	ldr	r7, [pc, #8]	@ 0x08022B28
	ldr	r5, [pc, #12]	@ 0x08022B2C
	b.n	loc_08022b34	@ 0x08022B34
	movs	r0, r0
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.word	gUnk_0200AF00
	.global	loc_08022b30
loc_08022b30:
	adds	r2, #12
	adds	r3, #1
	.global	loc_08022b34
loc_08022b34:
	cmp	r3, r4
	bge.n	loc_08022b48	@ 0x08022B48
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #32]	@ 0x08022B60
	cmp	r1, r0
	bne.n	loc_08022b30	@ 0x08022B30
	ldrb	r0, [r2, #6]
	cmp	r0, #1
	bne.n	loc_08022b30	@ 0x08022B30
	.global	loc_08022b48
loc_08022b48:
	ldrh	r0, [r2, #2]
	lsls	r0, r0, #4
	adds	r0, #22
	strh	r0, [r6, #0]
	ldrh	r0, [r2, #4]
	lsls	r0, r0, #4
	adds	r0, #5
	strh	r0, [r7, #0]
	movs	r0, #1
	ldr	r1, [pc, #8]	@ 0x08022B64
	strb	r0, [r1, #0]
	b.n	loc_08022c0c	@ 0x08022C0C
	.word	0x0000270F
	.word	gUnk_020069F0
	.global	loc_08022b68
loc_08022b68:
	cmp	r0, #32
	bne.n	loc_08022bb8	@ 0x08022BB8
	movs	r3, #0
	ldrh	r4, [r1, #58]
	ldr	r6, [pc, #4]	@ 0x08022B78
	ldr	r7, [pc, #8]	@ 0x08022B7C
	b.n	loc_08022b84	@ 0x08022B84
	movs	r0, r0
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.global	loc_08022b80
loc_08022b80:
	adds	r2, #12
	adds	r3, #1
	.global	loc_08022b84
loc_08022b84:
	cmp	r3, r4
	bge.n	loc_08022b98	@ 0x08022B98
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #32]	@ 0x08022BB0
	cmp	r1, r0
	bne.n	loc_08022b80	@ 0x08022B80
	ldrb	r0, [r2, #6]
	cmp	r0, #2
	bne.n	loc_08022b80	@ 0x08022B80
	.global	loc_08022b98
loc_08022b98:
	ldrh	r0, [r2, #2]
	lsls	r0, r0, #4
	adds	r0, #16
	strh	r0, [r6, #0]
	ldrh	r0, [r2, #4]
	lsls	r0, r0, #4
	adds	r0, #53
	strh	r0, [r7, #0]
	movs	r0, #0
	ldr	r1, [pc, #8]	@ 0x08022BB4
	strb	r0, [r1, #0]
	b.n	loc_08022c10	@ 0x08022C10
	.word	0x0000270F
	.word	gUnk_020069F0
	.global	loc_08022bb8
loc_08022bb8:
	movs	r3, #0
	ldrh	r4, [r1, #58]
	ldr	r6, [pc, #4]	@ 0x08022BC4
	ldr	r7, [pc, #8]	@ 0x08022BC8
	ldr	r5, [pc, #8]	@ 0x08022BCC
	b.n	loc_08022bd4	@ 0x08022BD4
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.word	gUnk_0200AF00
	.global	loc_08022bd0
loc_08022bd0:
	adds	r2, #12
	adds	r3, #1
	.global	loc_08022bd4
loc_08022bd4:
	cmp	r3, r4
	bge.n	loc_08022bf6	@ 0x08022BF6
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #76]	@ 0x08022C2C
	cmp	r1, r0
	bne.n	loc_08022bd0	@ 0x08022BD0
	ldrb	r0, [r2, #6]
	cmp	r0, #0
	bne.n	loc_08022bd0	@ 0x08022BD0
	ldrh	r1, [r2, #8]
	mov	r8, r1
	mov	r1, ip
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	cmp	r8, r0
	bne.n	loc_08022bd0	@ 0x08022BD0
	.global	loc_08022bf6
loc_08022bf6:
	ldrh	r0, [r2, #2]
	lsls	r0, r0, #4
	adds	r0, #22
	strh	r0, [r6, #0]
	ldrh	r0, [r2, #4]
	lsls	r0, r0, #4
	adds	r0, #5
	strh	r0, [r7, #0]
	movs	r0, #1
	ldr	r2, [pc, #36]	@ 0x08022C30
	strb	r0, [r2, #0]
	.global	loc_08022c0c
loc_08022c0c:
	movs	r0, #0
	strb	r0, [r5, #0]
	.global	loc_08022c10
loc_08022c10:
	movs	r0, #1
	ldr	r3, [pc, #32]	@ 0x08022C34
	strb	r0, [r3, #0]
	.global	loc_08022c16
loc_08022c16:
	movs	r0, #1
	ldr	r7, [pc, #28]	@ 0x08022C38
	strb	r0, [r7, #0]
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	0x0000270F
	.word	gUnk_020069F0
	.word	gUnk_02006170
	.word	gUnk_02007FC0
	.thumb_func
	.global	sub_08022c3c
sub_08022c3c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	sub	sp, #4
	ldr	r0, [pc, #152]	@ 0x08022CE4
	movs	r1, #0
	strb	r1, [r0, #0]
	ldr	r0, [pc, #152]	@ 0x08022CE8
	strb	r1, [r0, #0]
	ldr	r0, [pc, #152]	@ 0x08022CEC
	movs	r1, #0
	strh	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022CF0
	strb	r1, [r0, #0]
	ldr	r3, [pc, #148]	@ 0x08022CF4
	strb	r1, [r3, #0]
	ldr	r0, [pc, #148]	@ 0x08022CF8
	strh	r1, [r0, #0]
	ldr	r0, [pc, #148]	@ 0x08022CFC
	strh	r1, [r0, #0]
	ldr	r2, [pc, #148]	@ 0x08022D00
	movs	r4, #1
	negs	r4, r4
	adds	r0, r4, #0
	strh	r0, [r2, #0]
	ldr	r0, [pc, #144]	@ 0x08022D04
	strb	r1, [r0, #0]
	movs	r4, #0
	.word	0x46B84F23
	ldr	r0, [pc, #140]	@ 0x08022D0C
	mov	ip, r0
	ldr	r1, [pc, #140]	@ 0x08022D10
	mov	r9, r1
	movs	r3, #0
	ldr	r2, [pc, #140]	@ 0x08022D14
	.global	loc_08022c88
loc_08022c88:
	movs	r1, #7
	adds	r0, r2, #0
	adds	r0, #28
	.global	loc_08022c8e
loc_08022c8e:
	str	r3, [r0, #0]
	subs	r0, #4
	subs	r1, #1
	cmp	r1, #0
	bge.n	loc_08022c8e	@ 0x08022C8E
	adds	r2, #32
	adds	r4, #1
	cmp	r4, #7
	ble.n	loc_08022c88	@ 0x08022C88
	movs	r4, #0
	ldr	r0, [pc, #116]	@ 0x08022D18
	ldr	r6, [pc, #92]	@ 0x08022D04
	movs	r2, #0
	str	r2, [sp, #0]
	adds	r5, r0, #0
	adds	r5, #12
	ldr	r3, [pc, #108]	@ 0x08022D1C
	ldr	r7, [pc, #108]	@ 0x08022D20
	mov	sl, r7
	.global	loc_08022cb4
loc_08022cb4:
	ldr	r1, [pc, #108]	@ 0x08022D24
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	beq.n	loc_08022cbe	@ 0x08022CBE
	movs	r0, #15
	.global	loc_08022cbe
loc_08022cbe:
	strb	r0, [r3, #0]
	ldrh	r1, [r5, #0]
	movs	r0, #128
	lsls	r0, r0, #1
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08022d2c	@ 0x08022D2C
	movs	r0, #255
	ands	r0, r1
	movs	r2, #1
	adds	r1, r2, #0
	lsls	r1, r0
	ldr	r7, [pc, #80]	@ 0x08022D28
	ldr	r0, [r7, #0]
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08022d44	@ 0x08022D44
	adds	r0, r2, #0
	b.n	loc_08022d3c	@ 0x08022D3C
	.word	0x02004C98
	.word	gUnk_0200AF08
	.word	gUnk_0200001C
	.word	gUnk_02004B64
	.word	0x0200B038
	.word	gUnk_02007FF0
	.word	gUnk_02007D60
	.word	gUnk_0200AF0C
	.word	gUnk_0200B04C
	.word	gUnk_0300238C
	.word	gUnk_030023EC
	.word	gUnk_03002468
	.word	gUnk_02007BF0
	.word	0x08732348
	.word	gUnk_02007D58
	.word	gUnk_03002400
	.word	gUnk_03001F30
	.word	gUnk_030023C8
	.global	loc_08022d2c
loc_08022d2c:
	ldrh	r0, [r5, #0]
	ldr	r1, [sp, #0]
	adds	r0, r0, r1
	add	r0, sl
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	beq.n	loc_08022d44	@ 0x08022D44
	movs	r0, #1
	.global	loc_08022d3c
loc_08022d3c:
	lsls	r0, r4
	ldrb	r1, [r6, #0]
	orrs	r0, r1
	strb	r0, [r6, #0]
	.global	loc_08022d44
loc_08022d44:
	ldr	r2, [sp, #0]
	adds	r2, #7
	str	r2, [sp, #0]
	adds	r5, #18
	adds	r3, #1
	adds	r4, #1
	cmp	r4, #6
	ble.n	loc_08022cb4	@ 0x08022CB4
	ldr	r3, [pc, #40]	@ 0x08022D80
	movs	r0, #0
	ldrsb	r0, [r3, r0]
	cmp	r0, #7
	bne.n	loc_08022d94	@ 0x08022D94
	mov	r4, r8
	strb	r0, [r4, #0]
	movs	r1, #0
	mov	r7, ip
	strb	r1, [r7, #0]
	mov	r0, r9
	strb	r1, [r0, #0]
	ldr	r2, [pc, #20]	@ 0x08022D84
	strb	r1, [r2, #0]
	movs	r0, #2
	ldr	r3, [pc, #20]	@ 0x08022D88
	strb	r0, [r3, #0]
	ldr	r4, [pc, #20]	@ 0x08022D8C
	strb	r1, [r4, #0]
	ldr	r7, [pc, #20]	@ 0x08022D90
	strb	r1, [r7, #0]
	b.n	loc_08022f18	@ 0x08022F18
	.word	gUnk_030023B8
	.word	gUnk_02006170
	.word	gUnk_03002438
	.word	gUnk_0200AF00
	.word	gUnk_020069F0
	.global	loc_08022d94
loc_08022d94:
	movs	r0, #8
	mov	r1, r8
	strb	r0, [r1, #0]
	ldr	r0, [pc, #64]	@ 0x08022DDC
	ldrb	r0, [r0, #0]
	mov	r2, ip
	strb	r0, [r2, #0]
	movs	r1, #0
	mov	r3, r9
	strb	r1, [r3, #0]
	ldr	r0, [pc, #52]	@ 0x08022DE0
	strb	r1, [r0, #0]
	ldr	r0, [pc, #52]	@ 0x08022DE4
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	bne.n	loc_08022e00	@ 0x08022E00
	ldr	r0, [pc, #44]	@ 0x08022DE8
	movs	r2, #0
	ldrsb	r2, [r0, r2]
	cmp	r2, #0
	bne.n	loc_08022e00	@ 0x08022E00
	ldr	r1, [pc, #40]	@ 0x08022DEC
	movs	r0, #70
	strh	r0, [r1, #0]
	ldr	r1, [pc, #36]	@ 0x08022DF0
	ldr	r4, [pc, #40]	@ 0x08022DF4
	adds	r0, r4, #0
	strh	r0, [r1, #0]
	ldr	r7, [pc, #36]	@ 0x08022DF8
	strb	r2, [r7, #0]
	ldr	r0, [pc, #36]	@ 0x08022DFC
	strb	r2, [r0, #0]
	b.n	loc_08022f0e	@ 0x08022F0E
	movs	r0, r0
	.word	0x02005578
	.word	gUnk_0200AF04
	.word	gUnk_030023E0
	.word	gUnk_03002384
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.word	0x00000105
	.word	gUnk_020069F0
	.word	gUnk_0200AF00
	.global	loc_08022e00
loc_08022e00:
	ldr	r2, [pc, #56]	@ 0x08022E3C
	mov	r3, ip
	movs	r1, #0
	ldrsb	r1, [r3, r1]
	lsls	r1, r1, #2
	mov	r4, r8
	movs	r0, #0
	ldrsb	r0, [r4, r0]
	lsls	r0, r0, #5
	adds	r1, r1, r0
	adds	r1, r1, r2
	mov	r7, r9
	movs	r0, #0
	ldrsb	r0, [r7, r0]
	ldr	r1, [r1, #0]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r3, [r0, #0]
	ldr	r2, [r3, #68]
	ldr	r0, [pc, #24]	@ 0x08022E40
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	adds	r5, r0, #0
	cmp	r1, #16
	bne.n	loc_08022e6c	@ 0x08022E6C
	movs	r4, #0
	ldr	r6, [pc, #12]	@ 0x08022E44
	ldr	r7, [pc, #16]	@ 0x08022E48
	ldrh	r3, [r3, #58]
	b.n	loc_08022e50	@ 0x08022E50
	.word	gUnk_087E1D58
	.word	0x02007FF8
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.global	loc_08022e4c
loc_08022e4c:
	adds	r2, #12
	adds	r4, #1
	.global	loc_08022e50
loc_08022e50:
	cmp	r4, r3
	bge.n	loc_08022ef2	@ 0x08022EF2
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #12]	@ 0x08022E68
	cmp	r1, r0
	bne.n	loc_08022e4c	@ 0x08022E4C
	ldrb	r0, [r2, #6]
	cmp	r0, #1
	bne.n	loc_08022e4c	@ 0x08022E4C
	b.n	loc_08022ef2	@ 0x08022EF2
	movs	r0, r0
	.word	0x0000270F
	.global	loc_08022e6c
loc_08022e6c:
	cmp	r1, #32
	bne.n	loc_08022ebc	@ 0x08022EBC
	movs	r4, #0
	ldr	r6, [pc, #8]	@ 0x08022E7C
	ldr	r7, [pc, #8]	@ 0x08022E80
	ldrh	r3, [r3, #58]
	b.n	loc_08022e88	@ 0x08022E88
	movs	r0, r0
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.global	loc_08022e84
loc_08022e84:
	.word	0x3401320C
	.global	loc_08022e88
loc_08022e88:
	cmp	r4, r3
	bge.n	loc_08022e9c	@ 0x08022E9C
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #32]	@ 0x08022EB4
	cmp	r1, r0
	bne.n	loc_08022e84	@ 0x08022E84
	ldrb	r0, [r2, #6]
	cmp	r0, #2
	bne.n	loc_08022e84	@ 0x08022E84
	.global	loc_08022e9c
loc_08022e9c:
	ldrh	r0, [r2, #2]
	lsls	r0, r0, #4
	adds	r0, #16
	strh	r0, [r6, #0]
	ldrh	r0, [r2, #4]
	lsls	r0, r0, #4
	adds	r0, #53
	strh	r0, [r7, #0]
	movs	r0, #0
	ldr	r1, [pc, #8]	@ 0x08022EB8
	strb	r0, [r1, #0]
	b.n	loc_08022f0a	@ 0x08022F0A
	.word	0x0000270F
	.word	gUnk_020069F0
	.global	loc_08022ebc
loc_08022ebc:
	movs	r4, #0
	ldr	r6, [pc, #8]	@ 0x08022EC8
	ldr	r7, [pc, #8]	@ 0x08022ECC
	ldrh	r3, [r3, #58]
	b.n	loc_08022ed4	@ 0x08022ED4
	movs	r0, r0
	.word	gUnk_020055E0
	.word	gUnk_0200AEF0
	.global	loc_08022ed0
loc_08022ed0:
	adds	r2, #12
	adds	r4, #1
	.global	loc_08022ed4
loc_08022ed4:
	cmp	r4, r3
	bge.n	loc_08022ef2	@ 0x08022EF2
	movs	r0, #0
	ldrsh	r1, [r2, r0]
	ldr	r0, [pc, #84]	@ 0x08022F34
	cmp	r1, r0
	bne.n	loc_08022ed0	@ 0x08022ED0
	ldrb	r0, [r2, #6]
	cmp	r0, #0
	bne.n	loc_08022ed0	@ 0x08022ED0
	ldrh	r1, [r2, #8]
	movs	r0, #0
	ldrsb	r0, [r5, r0]
	cmp	r1, r0
	bne.n	loc_08022ed0	@ 0x08022ED0
	.global	loc_08022ef2
loc_08022ef2:
	ldrh	r0, [r2, #2]
	lsls	r0, r0, #4
	adds	r0, #22
	strh	r0, [r6, #0]
	ldrh	r0, [r2, #4]
	lsls	r0, r0, #4
	adds	r0, #5
	strh	r0, [r7, #0]
	movs	r0, #1
	ldr	r1, [pc, #48]	@ 0x08022F38
	strb	r0, [r1, #0]
	movs	r0, #0
	.global	loc_08022f0a
loc_08022f0a:
	ldr	r2, [pc, #48]	@ 0x08022F3C
	strb	r0, [r2, #0]
	.global	loc_08022f0e
loc_08022f0e:
	movs	r0, #1
	ldr	r3, [pc, #44]	@ 0x08022F40
	strb	r0, [r3, #0]
	ldr	r4, [pc, #44]	@ 0x08022F44
	strb	r0, [r4, #0]
	.global	loc_08022f18
loc_08022f18:
	movs	r0, #0
	ldr	r7, [pc, #44]	@ 0x08022F48
	strb	r0, [r7, #0]
	movs	r0, #1
	ldr	r1, [pc, #40]	@ 0x08022F4C
	strb	r0, [r1, #0]
	add	sp, #4
	pop	{r3, r4, r5}
	mov	r8, r3
	mov	r9, r4
	mov	sl, r5
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	0x0000270F
	.word	gUnk_020069F0
	.word	gUnk_0200AF00
	.word	gUnk_03002438
	.word	gUnk_02006170
	.word	0x0200B038
	.word	gUnk_02007FC0
	.thumb_func
	.global	sub_08022f50
sub_08022f50:
	.thumb
	push	{lr}
	ldr	r1, [pc, #40]	@ 0x08022F7C
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr	r2, [pc, #36]	@ 0x08022F80
	ldr	r0, [pc, #40]	@ 0x08022F84
	movs	r1, #0
	ldrb	r0, [r0, #0]
	subs	r0, #1
	strb	r0, [r2, #0]
	ldr	r0, [pc, #32]	@ 0x08022F88
	strb	r1, [r0, #0]
	ldr	r0, [pc, #32]	@ 0x08022F8C
	strb	r1, [r0, #0]
	ldr	r0, [pc, #32]	@ 0x08022F90
	strb	r1, [r0, #0]
	ldr	r0, [pc, #32]	@ 0x08022F94
	strb	r1, [r0, #0]
	bl	sub_08009ab8	@ 0x08009AB8
	pop	{r0}
	bx	r0
	.word	gUnk_0300238C
	.word	gUnk_030023EC
	.word	0x08334EB4
	.word	gUnk_03002468
	.word	gUnk_020069F0
	.word	gUnk_02006170
	.word	gUnk_02007FC0
	.thumb_func
	.global	sub_08022f98
sub_08022f98:
	.thumb
	bx	lr
	movs	r0, r0
	.thumb_func
	.global	sub_08022f9c
sub_08022f9c:
	.thumb
	ldr	r1, [pc, #4]	@ 0x08022FA4
	movs	r0, #0
	strb	r0, [r1, #0]
	bx	lr
	.word	0x020055C8
	.thumb_func
	.global	sub_08022fa8
sub_08022fa8:
	.thumb
	push	{r4, r5, r6, r7, lr}
	sub	sp, #4
	bl	sub_080022ac	@ 0x080022AC
	ldr	r1, [pc, #36]	@ 0x08022FD8
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr	r0, [pc, #36]	@ 0x08022FDC
	ldrb	r1, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #8
	bne.n	loc_08022fec	@ 0x08022FEC
	ldr	r1, [pc, #24]	@ 0x08022FE0
	ldr	r0, [pc, #28]	@ 0x08022FE4
	ldrb	r0, [r0, #0]
	strb	r0, [r1, #0]
	ldr	r1, [pc, #24]	@ 0x08022FE8
	movs	r2, #1
	negs	r2, r2
	adds	r0, r2, #0
	b.n	loc_08022ff6	@ 0x08022FF6
	movs	r0, r0
	.word	gUnk_03002444
	.word	gUnk_0300238C
	.word	gUnk_030023B8
	.word	gUnk_030023EC
	.word	gUnk_03001F20
	.global	loc_08022fec
loc_08022fec:
	ldr	r0, [pc, #24]	@ 0x08023008
	strb	r1, [r0, #0]
	ldr	r1, [pc, #24]	@ 0x0802300C
	ldr	r0, [pc, #28]	@ 0x08023010
	ldrb	r0, [r0, #0]
	.global	loc_08022ff6
loc_08022ff6:
	strb	r0, [r1, #0]
	ldr	r0, [pc, #24]	@ 0x08023014
	ldrb	r0, [r0, #0]
	cmp	r0, #2
	bne.n	loc_0802301c	@ 0x0802301C
	ldr	r1, [pc, #20]	@ 0x08023018
	movs	r0, #5
	b.n	loc_08023020	@ 0x08023020
	movs	r0, r0
	.word	gUnk_030023B8
	.word	gUnk_03001F20
	.word	gUnk_030023EC
	.word	gUnk_020069F0
	.word	gUnk_030055C0
	.global	loc_0802301c
loc_0802301c:
	ldr	r1, [pc, #188]	@ 0x080230DC
	movs	r0, #0
	.global	loc_08023020
loc_08023020:
	strh	r0, [r1, #0]
	movs	r0, #1
	bl	sub_08008c64	@ 0x08008C64
	movs	r0, #0
	bl	sub_080235ec	@ 0x080235EC
	ldr	r7, [pc, #176]	@ 0x080230E0
	ldr	r2, [pc, #176]	@ 0x080230E4
	ldr	r0, [pc, #180]	@ 0x080230E8
	movs	r1, #0
	ldrsb	r1, [r0, r1]
	lsls	r1, r1, #2
	ldr	r0, [pc, #176]	@ 0x080230EC
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #5
	adds	r1, r1, r0
	adds	r1, r1, r2
	ldr	r0, [pc, #164]	@ 0x080230F0
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	ldr	r1, [r1, #0]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r1, [r0, #0]
	str	r1, [r7, #0]
	ldr	r2, [pc, #152]	@ 0x080230F4
	adds	r0, r1, #0
	adds	r0, #87
	ldrb	r0, [r0, #0]
	strb	r0, [r2, #0]
	ldr	r2, [pc, #144]	@ 0x080230F8
	adds	r1, #85
	ldrb	r0, [r1, #0]
	strb	r0, [r2, #0]
	bl	sub_0802923c	@ 0x0802923C
	bl	sub_080291d0	@ 0x080291D0
	bl	sub_08029204	@ 0x08029204
	bl	sub_08029270	@ 0x08029270
	ldr	r0, [pc, #124]	@ 0x080230FC
	ldr	r3, [r7, #0]
	ldrh	r2, [r3, #20]
	strh	r2, [r0, #0]
	ldr	r0, [pc, #120]	@ 0x08023100
	ldrh	r1, [r3, #22]
	strh	r1, [r0, #0]
	ldr	r6, [pc, #120]	@ 0x08023104
	adds	r0, r2, #0
	muls	r0, r1
	strh	r0, [r6, #0]
	ldr	r1, [pc, #116]	@ 0x08023108
	ldrh	r0, [r3, #36]
	strh	r0, [r1, #0]
	ldrh	r0, [r3, #38]
	strh	r0, [r1, #2]
	ldr	r1, [pc, #108]	@ 0x0802310C
	ldrh	r0, [r3, #52]
	strh	r0, [r1, #0]
	ldrh	r0, [r3, #54]
	strh	r0, [r1, #2]
	ldr	r1, [pc, #104]	@ 0x08023110
	ldrh	r0, [r3, #60]
	strh	r0, [r1, #0]
	ldrh	r0, [r3, #62]
	strh	r0, [r1, #2]
	ldr	r0, [r3, #72]
	str	r0, [r1, #4]
	ldr	r0, [pc, #92]	@ 0x08023114
	ldr	r5, [pc, #96]	@ 0x08023118
	str	r5, [r0, #0]
	ldrb	r0, [r3, #5]
	cmp	r0, #0
	beq.n	loc_08023120	@ 0x08023120
	ldr	r1, [r3, #8]
	movs	r0, #8
	adds	r2, r5, #0
	movs	r3, #0
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [r7, #0]
	ldr	r1, [r0, #12]
	ldr	r2, [pc, #72]	@ 0x0802311C
	movs	r0, #8
	movs	r3, #0
	bl	sub_080017e4	@ 0x080017E4
	b.n	loc_08023142	@ 0x08023142
	.word	gUnk_030055C0
	.word	gUnk_030055EC
	.word	gUnk_087E1D58
	.word	gUnk_030023EC
	.word	gUnk_0300238C
	.word	gUnk_03002468
	.word	gUnk_02007D64
	.word	gUnk_02000000
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.word	gUnk_030055E4
	.word	gUnk_03005600
	.word	gUnk_03005608
	.word	gUnk_020055D8
	.word	gUnk_03005660
	.word	gUnk_02000040
	.word	gUnk_02008160
	.global	loc_08023120
loc_08023120:
	ldr	r0, [r3, #8]
	movs	r3, #0
	ldrsh	r2, [r6, r3]
	lsls	r2, r2, #1
	ldr	r4, [pc, #268]	@ 0x08023238
	ands	r2, r4
	adds	r1, r5, #0
	bl	CpuSet	@ 0x080CFA58
	ldr	r0, [r7, #0]
	ldr	r0, [r0, #12]
	ldr	r1, [pc, #260]	@ 0x0802323C
	movs	r3, #0
	ldrsh	r2, [r6, r3]
	ands	r2, r4
	bl	CpuSet	@ 0x080CFA58
	.global	loc_08023142
loc_08023142:
	ldr	r0, [pc, #252]	@ 0x08023240
	ldr	r0, [r0, #0]
	ldr	r1, [r0, #32]
	ldr	r2, [pc, #248]	@ 0x08023244
	movs	r0, #8
	movs	r3, #0
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [pc, #244]	@ 0x08023248
	movs	r4, #0
	strb	r4, [r0, #0]
	ldr	r0, [pc, #240]	@ 0x0802324C
	strb	r4, [r0, #0]
	ldr	r0, [pc, #240]	@ 0x08023250
	strb	r4, [r0, #0]
	ldr	r1, [pc, #240]	@ 0x08023254
	movs	r0, #31
	strh	r0, [r1, #0]
	bl	sub_08030724	@ 0x08030724
	bl	sub_0802cd24	@ 0x0802CD24
	bl	sub_0802885c	@ 0x0802885C
	bl	sub_08028948	@ 0x08028948
	bl	sub_08027e28	@ 0x08027E28
	bl	sub_080b4e40	@ 0x080B4E40
	bl	sub_08028e4c	@ 0x08028E4C
	bl	sub_08029110	@ 0x08029110
	bl	sub_0802d0f4	@ 0x0802D0F4
	bl	sub_08029318	@ 0x08029318
	bl	sub_08028304	@ 0x08028304
	ldr	r0, [pc, #196]	@ 0x08023258
	strb	r4, [r0, #0]
	ldr	r0, [pc, #196]	@ 0x0802325C
	strb	r4, [r0, #0]
	ldr	r0, [pc, #196]	@ 0x08023260
	strb	r4, [r0, #0]
	movs	r5, #0
	ldr	r0, [pc, #192]	@ 0x08023264
	ldrh	r0, [r0, #0]
	cmp	r5, r0
	blt.n	loc_080231aa	@ 0x080231AA
	b.n	loc_080232cc	@ 0x080232CC
	.global	loc_080231aa
loc_080231aa:
	movs	r6, #0
	movs	r4, #0
	.global	loc_080231ae
loc_080231ae:
	ldr	r0, [pc, #184]	@ 0x08023268
	adds	r0, r4, r0
	movs	r1, #0
	ldrsh	r0, [r0, r1]
	ldr	r1, [pc, #180]	@ 0x0802326C
	cmp	r0, #0
	bne.n	loc_080231c6	@ 0x080231C6
	adds	r0, r4, r1
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	cmp	r0, #0
	beq.n	loc_0802328c	@ 0x0802328C
	.global	loc_080231c6
loc_080231c6:
	adds	r1, r4, r1
	movs	r3, #0
	ldrsh	r2, [r1, r3]
	cmp	r2, #0
	bne.n	loc_080231ee	@ 0x080231EE
	ldr	r0, [pc, #156]	@ 0x08023270
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #0]
	ldr	r0, [pc, #156]	@ 0x08023274
	adds	r0, r4, r0
	strh	r2, [r0, #0]
	ldr	r0, [pc, #152]	@ 0x08023278
	adds	r0, r4, r0
	ldr	r1, [pc, #152]	@ 0x0802327C
	strh	r1, [r0, #0]
	movs	r0, #1
	negs	r0, r0
	adds	r1, r5, #0
	bl	sub_08009e60	@ 0x08009E60
	.global	loc_080231ee
loc_080231ee:
	ldr	r0, [pc, #132]	@ 0x08023274
	adds	r3, r4, r0
	ldrh	r1, [r3, #0]
	movs	r2, #0
	ldrsh	r0, [r3, r2]
	cmp	r0, #0
	beq.n	loc_08023214	@ 0x08023214
	ldr	r0, [pc, #128]	@ 0x08023280
	adds	r0, r4, r0
	strh	r1, [r0, #0]
	ldr	r2, [pc, #128]	@ 0x08023284
	adds	r2, r4, r2
	ldr	r1, [pc, #112]	@ 0x08023278
	adds	r1, r4, r1
	ldrh	r0, [r1, #0]
	strh	r0, [r2, #0]
	strh	r6, [r3, #0]
	ldr	r0, [pc, #104]	@ 0x0802327C
	strh	r0, [r1, #0]
	.global	loc_08023214
loc_08023214:
	ldr	r2, [pc, #64]	@ 0x08023258
	movs	r0, #1
	lsls	r0, r5
	ldrb	r1, [r2, #0]
	orrs	r0, r1
	strb	r0, [r2, #0]
	ldr	r1, [pc, #56]	@ 0x0802325C
	ldrb	r0, [r1, #0]
	adds	r0, #1
	strb	r0, [r1, #0]
	ldr	r1, [pc, #52]	@ 0x08023260
	ldrb	r0, [r1, #0]
	adds	r0, #1
	strb	r0, [r1, #0]
	ldr	r0, [pc, #84]	@ 0x08023288
	adds	r0, r5, r0
	strb	r6, [r0, #0]
	b.n	loc_08023294	@ 0x08023294
	.word	0x001FFFFF
	.word	gUnk_02008160
	.word	gUnk_030055EC
	.word	gUnk_0200B080
	.word	gUnk_02000020
	.word	gUnk_0200B078
	.word	gUnk_0200B040
	.word	gUnk_03005624
	.word	gUnk_03002340
	.word	gUnk_03002350
	.word	gUnk_0300234C
	.word	gUnk_030023AC
	.word	gUnk_02007D48
	.word	gUnk_02005588
	.word	gUnk_02005580
	.word	gUnk_02008008
	.word	gUnk_02007FA8
	.word	0x0000FFFF
	.word	gUnk_02004B50
	.word	gUnk_0200AF18
	.word	gUnk_0300560C
	.global	loc_0802328c
loc_0802328c:
	ldr	r0, [pc, #80]	@ 0x080232E0
	adds	r0, r5, r0
	movs	r1, #3
	strb	r1, [r0, #0]
	.global	loc_08023294
loc_08023294:
	adds	r0, r5, #0
	bl	sub_0803d034	@ 0x0803D034
	adds	r0, r5, #0
	bl	sub_0803d1c4	@ 0x0803D1C4
	ldr	r2, [pc, #64]	@ 0x080232E4
	adds	r2, r4, r2
	ldr	r0, [pc, #64]	@ 0x080232E8
	adds	r0, r4, r0
	ldrh	r1, [r0, #0]
	strh	r6, [r0, #0]
	ldrh	r0, [r0, #0]
	ldrh	r1, [r2, #0]
	strh	r0, [r2, #0]
	ldr	r1, [pc, #56]	@ 0x080232EC
	adds	r1, r4, r1
	ldr	r0, [pc, #56]	@ 0x080232F0
	adds	r0, r4, r0
	strh	r6, [r0, #0]
	strh	r6, [r1, #0]
	adds	r4, #2
	adds	r5, #1
	ldr	r0, [pc, #48]	@ 0x080232F4
	ldrh	r0, [r0, #0]
	cmp	r5, r0
	bge.n	loc_080232cc	@ 0x080232CC
	b.n	loc_080231ae	@ 0x080231AE
	.global	loc_080232cc
loc_080232cc:
	bl	sub_080b5024	@ 0x080B5024
	ldr	r0, [pc, #32]	@ 0x080232F4
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne.n	loc_080232f8	@ 0x080232F8
	bl	sub_08028b1c	@ 0x08028B1C
	b.n	loc_080232fc	@ 0x080232FC
	movs	r0, r0
	.word	gUnk_0300560C
	.word	gUnk_03000F98
	.word	gUnk_03001EB8
	.word	gUnk_03002458
	.word	gUnk_030023C0
	.word	gUnk_030023AC
	.global	loc_080232f8
loc_080232f8:
	bl	sub_08028990	@ 0x08028990
	.global	loc_080232fc
loc_080232fc:
	ldr	r0, [pc, #28]	@ 0x0802331C
	ldrh	r0, [r0, #0]
	bl	sub_08009b2c	@ 0x08009B2C
	ldr	r0, [pc, #24]	@ 0x08023320
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	beq.n	loc_08023324	@ 0x08023324
	cmp	r0, #3
	ble.n	loc_08023314	@ 0x08023314
	cmp	r0, #5
	beq.n	loc_0802332a	@ 0x0802332A
	.global	loc_08023314
loc_08023314:
	bl	sub_0802b4bc	@ 0x0802B4BC
	b.n	loc_0802332e	@ 0x0802332E
	movs	r0, r0
	.word	gUnk_03002360
	.word	gUnk_030055C0
	.global	loc_08023324
loc_08023324:
	bl	sub_0802be80	@ 0x0802BE80
	b.n	loc_0802332e	@ 0x0802332E
	.global	loc_0802332a
loc_0802332a:
	bl	sub_0802c42c	@ 0x0802C42C
	.global	loc_0802332e
loc_0802332e:
	bl	sub_080290dc	@ 0x080290DC
	bl	sub_08029930	@ 0x08029930
	bl	sub_080292d0	@ 0x080292D0
	movs	r0, #0
	str	r0, [sp, #0]
	ldr	r1, [pc, #28]	@ 0x0802335C
	ldr	r2, [pc, #28]	@ 0x08023360
	mov	r0, sp
	bl	CpuFastSet	@ 0x080CFA54
	ldr	r0, [pc, #24]	@ 0x08023364
	ldrb	r0, [r0, #0]
	cmp	r0, #5
	bhi.n	loc_08023384	@ 0x08023384
	lsls	r0, r0, #2
	ldr	r1, [pc, #20]	@ 0x08023368
	adds	r0, r0, r1
	ldr	r0, [r0, #0]
	mov	pc, r0
	movs	r0, r0
	.word	0x06002000
	.word	0x01000400
	.word	gUnk_0200B050
	.word	0x0802336C
	adds	r3, #132
	lsrs	r2, r0, #32
	adds	r3, #188
	lsrs	r2, r0, #32
	adds	r3, #132
	lsrs	r2, r0, #32
	adds	r3, #152
	lsrs	r2, r0, #32
	adds	r3, #188
	lsrs	r2, r0, #32
	adds	r3, #172
	lsrs	r2, r0, #32
	.global	loc_08023384
loc_08023384:
	ldr	r1, [pc, #12]	@ 0x08023394
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802a9cc	@ 0x0802A9CC
	bl	sub_080292b0	@ 0x080292B0
	b.n	loc_080233d0	@ 0x080233D0
	.word	gUnk_03005604
	ldr	r0, [pc, #12]	@ 0x080233A8
	ldrh	r0, [r0, #0]
	bl	sub_0802b074	@ 0x0802B074
	bl	sub_080292b0	@ 0x080292B0
	b.n	loc_080233d0	@ 0x080233D0
	movs	r0, r0
	.word	gUnk_03005604
	ldr	r0, [pc, #8]	@ 0x080233B8
	ldrh	r0, [r0, #2]
	bl	sub_0802aeac	@ 0x0802AEAC
	b.n	loc_080233d0	@ 0x080233D0
	movs	r0, r0
	.word	gUnk_03005604
	ldr	r1, [pc, #24]	@ 0x080233D8
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802a9cc	@ 0x0802A9CC
	ldr	r1, [pc, #20]	@ 0x080233DC
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802ab30	@ 0x0802AB30
	.global	loc_080233d0
loc_080233d0:
	add	sp, #4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	.word	gUnk_03005604
	.word	gUnk_03005690
	.thumb_func
	.global	sub_080233e0
sub_080233e0:
	.thumb
	push	{r4, r5, r6, lr}
	sub	sp, #4
	ldr	r4, [pc, #264]	@ 0x080234F0
	ldrb	r1, [r4, #0]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	ldrb	r1, [r4, #0]
	movs	r0, #15
	bl	sub_080055c4	@ 0x080055C4
	ldrb	r0, [r4, #0]
	bl	sub_08077d38	@ 0x08077D38
	ldr	r1, [pc, #244]	@ 0x080234F4
	movs	r0, #0
	strb	r0, [r1, #0]
	ldr	r1, [pc, #244]	@ 0x080234F8
	ldr	r5, [pc, #244]	@ 0x080234FC
	ldrb	r0, [r5, #0]
	strb	r0, [r1, #0]
	ldr	r1, [pc, #244]	@ 0x08023500
	ldr	r4, [pc, #244]	@ 0x08023504
	ldrb	r0, [r4, #0]
	strb	r0, [r1, #0]
	ldr	r1, [pc, #244]	@ 0x08023508
	movs	r0, #0
	strh	r0, [r1, #0]
	movs	r0, #1
	bl	sub_08008c64	@ 0x08008C64
	movs	r0, #0
	bl	sub_080235ec	@ 0x080235EC
	ldr	r6, [pc, #228]	@ 0x0802350C
	ldr	r2, [pc, #232]	@ 0x08023510
	movs	r1, #0
	ldrsb	r1, [r4, r1]
	lsls	r1, r1, #2
	movs	r0, #0
	ldrsb	r0, [r5, r0]
	lsls	r0, r0, #5
	adds	r1, r1, r0
	adds	r1, r1, r2
	ldr	r0, [pc, #216]	@ 0x08023514
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	ldr	r1, [r1, #0]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r1, [r0, #0]
	str	r1, [r6, #0]
	ldr	r2, [pc, #204]	@ 0x08023518
	adds	r0, r1, #0
	adds	r0, #87
	ldrb	r0, [r0, #0]
	strb	r0, [r2, #0]
	ldr	r2, [pc, #196]	@ 0x0802351C
	adds	r1, #85
	ldrb	r0, [r1, #0]
	strb	r0, [r2, #0]
	bl	sub_0802923c	@ 0x0802923C
	bl	sub_080291d0	@ 0x080291D0
	bl	sub_08029204	@ 0x08029204
	bl	sub_08029270	@ 0x08029270
	ldr	r0, [pc, #176]	@ 0x08023520
	ldr	r2, [r6, #0]
	ldrh	r4, [r2, #20]
	strh	r4, [r0, #0]
	ldr	r0, [pc, #172]	@ 0x08023524
	ldrh	r1, [r2, #22]
	strh	r1, [r0, #0]
	ldr	r3, [pc, #172]	@ 0x08023528
	adds	r0, r4, #0
	muls	r0, r1
	strh	r0, [r3, #0]
	ldr	r1, [pc, #168]	@ 0x0802352C
	ldrh	r0, [r2, #36]
	movs	r4, #0
	strh	r0, [r1, #0]
	ldrh	r0, [r2, #38]
	strh	r0, [r1, #2]
	ldr	r1, [pc, #160]	@ 0x08023530
	ldrh	r0, [r2, #52]
	strh	r0, [r1, #0]
	ldrh	r0, [r2, #54]
	strh	r0, [r1, #2]
	ldr	r1, [pc, #152]	@ 0x08023534
	ldrh	r0, [r2, #60]
	strh	r0, [r1, #0]
	ldrh	r0, [r2, #62]
	strh	r0, [r1, #2]
	ldr	r0, [r2, #72]
	str	r0, [r1, #4]
	ldr	r1, [pc, #144]	@ 0x08023538
	ldr	r0, [pc, #144]	@ 0x0802353C
	str	r0, [r1, #0]
	ldr	r1, [r2, #32]
	ldr	r2, [pc, #144]	@ 0x08023540
	movs	r0, #8
	movs	r3, #0
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [pc, #136]	@ 0x08023544
	strh	r4, [r0, #0]
	bl	sub_08030724	@ 0x08030724
	bl	sub_0802cd24	@ 0x0802CD24
	bl	sub_0802885c	@ 0x0802885C
	bl	sub_08028948	@ 0x08028948
	bl	sub_08028130	@ 0x08028130
	bl	sub_080b4ea8	@ 0x080B4EA8
	bl	sub_08029318	@ 0x08029318
	bl	sub_080307b0	@ 0x080307B0
	bl	sub_080290ac	@ 0x080290AC
	ldr	r0, [pc, #100]	@ 0x08023548
	ldrh	r0, [r0, #0]
	cmp	r0, #1
	bne.n	loc_0802354c	@ 0x0802354C
	bl	sub_08028b1c	@ 0x08028B1C
	b.n	loc_08023550	@ 0x08023550
	movs	r0, r0
	.word	0x02007E8C
	.word	gUnk_03002444
	.word	gUnk_030023B8
	.word	gUnk_0300238C
	.word	gUnk_03001F20
	.word	gUnk_030023EC
	.word	gUnk_030055C0
	.word	gUnk_030055EC
	.word	gUnk_087E1D58
	.word	gUnk_03002468
	.word	gUnk_02007D64
	.word	gUnk_02000000
	.word	gUnk_03005620
	.word	gUnk_0300561C
	.word	gUnk_030055E4
	.word	gUnk_03005600
	.word	gUnk_03005608
	.word	gUnk_020055D8
	.word	gUnk_03005660
	.word	gUnk_02000040
	.word	gUnk_0200B080
	.word	gUnk_03005624
	.word	gUnk_030023AC
	.global	loc_0802354c
loc_0802354c:
	bl	sub_08028990	@ 0x08028990
	.global	loc_08023550
loc_08023550:
	ldr	r0, [pc, #20]	@ 0x08023568
	ldrh	r0, [r0, #0]
	cmp	r0, #3
	beq.n	loc_0802356c	@ 0x0802356C
	cmp	r0, #3
	ble.n	loc_08023560	@ 0x08023560
	cmp	r0, #5
	beq.n	loc_08023572	@ 0x08023572
	.global	loc_08023560
loc_08023560:
	bl	sub_0802b4bc	@ 0x0802B4BC
	b.n	loc_08023576	@ 0x08023576
	movs	r0, r0
	.word	gUnk_030055C0
	.global	loc_0802356c
loc_0802356c:
	bl	sub_0802be80	@ 0x0802BE80
	b.n	loc_08023576	@ 0x08023576
	.global	loc_08023572
loc_08023572:
	bl	sub_0802c42c	@ 0x0802C42C
	.global	loc_08023576
loc_08023576:
	bl	sub_080290dc	@ 0x080290DC
	ldr	r4, [pc, #60]	@ 0x080235B8
	ldrb	r0, [r4, #0]
	cmp	r0, #2
	bne.n	loc_0802358a	@ 0x0802358A
	ldr	r0, [pc, #56]	@ 0x080235BC
	ldr	r1, [pc, #56]	@ 0x080235C0
	ldrh	r1, [r1, #0]
	strh	r1, [r0, #0]
	.global	loc_0802358a
loc_0802358a:
	bl	sub_08029930	@ 0x08029930
	movs	r0, #0
	str	r0, [sp, #0]
	ldr	r1, [pc, #48]	@ 0x080235C4
	ldr	r2, [pc, #48]	@ 0x080235C8
	mov	r0, sp
	bl	CpuFastSet	@ 0x080CFA54
	ldrb	r0, [r4, #0]
	cmp	r0, #1
	bne.n	loc_080235d0	@ 0x080235D0
	ldr	r1, [pc, #40]	@ 0x080235CC
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802a9cc	@ 0x0802A9CC
	ldr	r1, [pc, #12]	@ 0x080235BC
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802ab30	@ 0x0802AB30
	b.n	loc_080235de	@ 0x080235DE
	.word	gUnk_0200B050
	.word	gUnk_03005690
	.word	0x02004B80
	.word	0x06002000
	.word	0x01000400
	.word	gUnk_03005604
	.global	loc_080235d0
loc_080235d0:
	ldr	r1, [pc, #20]	@ 0x080235E8
	ldrh	r0, [r1, #0]
	ldrh	r1, [r1, #2]
	bl	sub_0802a9cc	@ 0x0802A9CC
	bl	sub_080292b0	@ 0x080292B0
	.global	loc_080235de
loc_080235de:
	add	sp, #4
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03005604
