@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_080653ec_0806ef5c_0809113c_08093f64_08099b20_0809cb90_0809d994_0809f2f4_0809f9dc_080a00ec_080a1590_080b2fe8_080b5670_080b6154_080b6b08_080b6f38_080b75a4, chunk 1/2: 0x080B75A4-0x080B76A8 (thumb_code, 0x104 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x080B75A4 sub_080b75a4

	.section .game_code_and_rodata_080653ec_0806ef5c_0809113c_08093f64_08099b20_0809cb90_0809d994_0809f2f4_0809f9dc_080a00ec_080a1590_080b2fe8_080b5670_080b6154_080b6b08_080b6f38_080b75a4, "ax"
	.global	game_code_and_rodata_080653ec_0806ef5c_0809113c_08093f64_08099b20_0809cb90_0809d994_0809f2f4_0809f9dc_080a00ec_080a1590_080b2fe8_080b5670_080b6154_080b6b08_080b6f38_080b75a4
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_080653ec_0806ef5c_0809113c_08093f64_08099b20_0809cb90_0809d994_0809f2f4_0809f9dc_080a00ec_080a1590_080b2fe8_080b5670_080b6154_080b6b08_080b6f38_080b75a4:
	.thumb_func
	.global	sub_080b75a4
sub_080b75a4:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r9
	mov	r6, r8
	push	{r6, r7}
	movs	r0, #0
	mov	r8, r0
	ldr	r0, [pc, #40]	@ 0x080B75DC
	ldrh	r0, [r0, #0]
	cmp	r8, r0
	bge.n	loc_080b768e	@ 0x080B768E
	movs	r1, #150
	lsls	r1, r1, #1
	mov	r9, r1
	.global	loc_080b75be
loc_080b75be:
	ldr	r0, [pc, #32]	@ 0x080B75E0
	mov	r3, r8
	lsls	r2, r3, #1
	adds	r7, r2, r0
	ldr	r0, [pc, #28]	@ 0x080B75E4
	adds	r0, r2, r0
	ldrh	r1, [r7, #0]
	ldrh	r0, [r0, #0]
	cmp	r1, r0
	bcc.n	loc_080b75ec	@ 0x080B75EC
	ldr	r1, [pc, #20]	@ 0x080B75E8
	movs	r0, #0
	strb	r0, [r1, #0]
	b.n	loc_080b768e	@ 0x080B768E
	movs	r0, r0
	.word	gUnk_030023AC
	.word	gUnk_0200EC78
	.word	gUnk_0200EC70
	.word	gUnk_0200EC54
	.global	loc_080b75ec
loc_080b75ec:
	ldr	r0, [pc, #60]	@ 0x080B762C
	adds	r0, r2, r0
	ldrh	r1, [r0, #0]
	ldr	r3, [pc, #60]	@ 0x080B7630
	adds	r0, r3, #0
	adds	r6, r0, #0
	ands	r6, r1
	ldr	r1, [pc, #56]	@ 0x080B7634
	mov	r3, r8
	adds	r0, r3, r1
	ldrb	r4, [r0, #0]
	ldr	r0, [pc, #52]	@ 0x080B7638
	adds	r3, r2, r0
	ldrh	r0, [r3, #0]
	mov	ip, r0
	ldr	r0, [pc, #48]	@ 0x080B763C
	adds	r2, r2, r0
	ldrh	r5, [r2, #0]
	cmp	r5, r6
	beq.n	loc_080b7644	@ 0x080B7644
	movs	r4, #1
	strh	r6, [r2, #0]
	ldrh	r0, [r7, #0]
	strh	r0, [r3, #0]
	ldr	r0, [pc, #32]	@ 0x080B7640
	ldrh	r0, [r0, #0]
	ldrh	r2, [r7, #0]
	adds	r0, r0, r2
	strh	r0, [r7, #0]
	ldrh	r3, [r3, #0]
	mov	ip, r3
	b.n	loc_080b765c	@ 0x080B765C
	.word	gUnk_03000F98
	.word	0x000003FF
	.word	gUnk_0200EC68
	.word	gUnk_02016480
	.word	gUnk_0200EC60
	.word	gUnk_030023AC
	.global	loc_080b7644
loc_080b7644:
	lsls	r0, r4, #24
	movs	r3, #128
	lsls	r3, r3, #17
	adds	r0, r0, r3
	lsrs	r4, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #63
	bne.n	loc_080b765c	@ 0x080B765C
	ldr	r3, [pc, #68]	@ 0x080B769C
	adds	r0, r3, #0
	orrs	r0, r5
	strh	r0, [r2, #0]
	.global	loc_080b765c
loc_080b765c:
	mov	r2, r8
	adds	r0, r2, r1
	strb	r4, [r0, #0]
	ldr	r0, [pc, #60]	@ 0x080B76A0
	ldr	r0, [r0, #0]
	mov	r1, ip
	lsls	r3, r1, #1
	mov	r1, r9
	adds	r2, r0, r1
	adds	r2, r2, r3
	lsls	r1, r4, #24
	asrs	r1, r1, #14
	orrs	r6, r1
	strh	r6, [r2, #0]
	add	r3, r9
	adds	r0, r0, r3
	mov	r1, ip
	bl	sub_080b83a0	@ 0x080B83A0
	movs	r2, #1
	add	r8, r2
	ldr	r0, [pc, #28]	@ 0x080B76A4
	ldrh	r0, [r0, #0]
	cmp	r8, r0
	blt.n	loc_080b75be	@ 0x080B75BE
	.global	loc_080b768e
loc_080b768e:
	pop	{r3, r4}
	mov	r8, r3
	mov	r9, r4
	pop	{r4, r5, r6, r7}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	0x0000FFFF
	.word	gUnk_0200EC6C
	.word	gUnk_030023AC
