@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment actor_rodata_0874369c: 0x0874369C-0x08743B4C (data, 0x4B0 bytes)
@ Structure only (docs/data.md): labels, symbolic pointer words and
@ .incbin slices of the user's baserom.gba; no ROM bytes are committed.
@ 63 label(s), 65 code pointer(s), 90 data pointer(s), 44 .incbin slice(s) (0x244 bytes).
@ 90 of the pointers are in next-label tables (docs/data.md 5.1).

	.section .actor_rodata_0874369c, "a"
	.global	actor_rodata_0874369c
actor_rodata_0874369c:
	.global	gUnk_0874369C
gUnk_0874369C:
	.incbin	"baserom.gba", 0x74369C, 0x1C
	.global	gUnk_087436B8
gUnk_087436B8:
	.incbin	"baserom.gba", 0x7436B8, 0x1C
	.global	gUnk_087436D4
gUnk_087436D4:
	.incbin	"baserom.gba", 0x7436D4, 0x8
	.global	gUnk_087436DC
gUnk_087436DC:
	.incbin	"baserom.gba", 0x7436DC, 0x8
	.global	gUnk_087436E4
gUnk_087436E4:
	.incbin	"baserom.gba", 0x7436E4, 0x1C
	.global	gUnk_08743700
gUnk_08743700:
	.incbin	"baserom.gba", 0x743700, 0x1C
	.global	gUnk_0874371C
gUnk_0874371C:
	.incbin	"baserom.gba", 0x74371C, 0xC
	.global	gUnk_08743728
gUnk_08743728:
	.incbin	"baserom.gba", 0x743728, 0xC
	.global	gUnk_08743734
gUnk_08743734:
	.incbin	"baserom.gba", 0x743734, 0x8
	.global	gUnk_0874373C
gUnk_0874373C:
	.incbin	"baserom.gba", 0x74373C, 0x8
	.global	gUnk_08743744
gUnk_08743744:
	.incbin	"baserom.gba", 0x743744, 0xA
	.global	gUnk_0874374E
gUnk_0874374E:
	.incbin	"baserom.gba", 0x74374E, 0x2
	.global	gUnk_08743750
gUnk_08743750:
	.incbin	"baserom.gba", 0x743750, 0x8
	.global	gUnk_08743758
gUnk_08743758:
	.incbin	"baserom.gba", 0x743758, 0x8
	.global	gUnk_08743760
gUnk_08743760:
	.incbin	"baserom.gba", 0x743760, 0x24
	.global	gUnk_08743784
gUnk_08743784:
	.incbin	"baserom.gba", 0x743784, 0x44
	.global	gUnk_087437C8
gUnk_087437C8:
	.word	gUnk_08743760
	.word	gUnk_08743784
	.global	gUnk_087437D0
gUnk_087437D0:
	.incbin	"baserom.gba", 0x7437D0, 0x24
	.global	gUnk_087437F4
gUnk_087437F4:
	.word	gUnk_08743BD0
	.word	gUnk_08743C24
	.word	gUnk_08743C78
	.word	gUnk_08743CCC
	.word	gUnk_08743D20
	.word	gUnk_08743C40
	.word	gUnk_08743D74
	.global	gUnk_08743810
gUnk_08743810:
	.word	gUnk_0874402C
	.word	gUnk_08744034
	.word	gUnk_0874403C
	.word	gUnk_08744044
	.word	gUnk_0874404C
	.word	gUnk_08744034
	.word	gUnk_0874404C
	.global	gUnk_0874382C
gUnk_0874382C:
	.word	gUnk_08743C08
	.word	gUnk_08743C5C
	.word	gUnk_08743CB0
	.word	gUnk_08743D04
	.word	gUnk_08743D58
	.word	gUnk_08743C5C
	.word	gUnk_08743D90
	.global	gBonkersVariants
gBonkersVariants:
	.word	BonkersInit+1
	.global	gBonkersStates
gBonkersStates:
	.word	sub_080901e0+1
	.word	BonkersWalk+1
	.word	BonkersJump+1
	.word	BonkersHop+1
	.word	BonkersDash+1
	.word	BonkersThrow+1
	.word	BonkersSlam+1
	.word	BonkersJumpSlam+1
	.word	BonkersTripleSlam+1
	.word	sub_08090c18+1
	.word	sub_08090cd0+1
	.global	gBonkersStateUpdates
gBonkersStateUpdates:
	.word	sub_08090270+1
	.word	sub_080903c8+1
	.word	sub_080904ac+1
	.word	sub_080905b0+1
	.word	sub_08090724+1
	.word	sub_080908ec+1
	.word	sub_080909ac+1
	.word	sub_08090b18+1
	.word	sub_08090bf0+1
	.word	sub_08090ca8+1
	.word	sub_08090de4+1
	.global	gUnk_087438A4
gUnk_087438A4:
	.incbin	"baserom.gba", 0x7438A4, 0xE
	.global	gUnk_087438B2
gUnk_087438B2:
	.incbin	"baserom.gba", 0x7438B2, 0xE
	.global	gUnk_087438C0
gUnk_087438C0:
	.word	gUnk_08743DC8
	.word	gUnk_08743DAC
	.word	gUnk_08743DAC
	.word	gUnk_08743DAC
	.word	gUnk_08743DC8
	.word	gUnk_08743DAC
	.word	gUnk_08743DAC
	.global	gUnk_087438DC
gUnk_087438DC:
	.incbin	"baserom.gba", 0x7438DC, 0x8
	.global	gUnk_087438E4
gUnk_087438E4:
	.incbin	"baserom.gba", 0x7438E4, 0x8
	.global	gUnk_087438EC
gUnk_087438EC:
	.word	gUnk_08743E8C
	.word	gUnk_08743E8C
	.word	gUnk_08743E8C
	.word	gUnk_08743E8C
	.word	gUnk_08743DE4
	.word	gUnk_08743DE4
	.word	gUnk_08743DE4
	.word	gUnk_08743DE4
	.word	gUnk_08743E38
	.word	gUnk_08743E38
	.word	gUnk_08743E8C
	.word	gUnk_08743EC4
	.global	gUnk_0874391C
gUnk_0874391C:
	.word	gUnk_08744064
	.word	gUnk_08744064
	.word	gUnk_08744064
	.word	gUnk_08744064
	.word	gUnk_08744054
	.word	gUnk_08744054
	.word	gUnk_08744054
	.word	gUnk_08744054
	.word	gUnk_0874405C
	.word	gUnk_0874405C
	.word	gUnk_08744064
	.word	gUnk_08744064
	.global	gUnk_0874394C
gUnk_0874394C:
	.word	gUnk_08743EA8
	.word	gUnk_08743EA8
	.word	gUnk_08743EA8
	.word	gUnk_08743EA8
	.word	gUnk_08743E1C
	.word	gUnk_08743E1C
	.word	gUnk_08743E1C
	.word	gUnk_08743E1C
	.word	gUnk_08743E70
	.word	gUnk_08743E70
	.word	gUnk_08743EA8
	.word	gUnk_08743EE0
	.global	gUnk_0874397C
gUnk_0874397C:
	.incbin	"baserom.gba", 0x74397C, 0x8
	.global	gPoppyBrosSrVariants
gPoppyBrosSrVariants:
	.word	PoppyBrosSrInit+1
	.global	gPoppyBrosSrStates
gPoppyBrosSrStates:
	.word	sub_0809128c+1
	.word	sub_08091320+1
	.word	sub_08091390+1
	.word	sub_080915a4+1
	.word	sub_080915f8+1
	.word	sub_080916ec+1
	.word	sub_08091824+1
	.global	gPoppyBrosSrStateUpdates
gPoppyBrosSrStateUpdates:
	.word	sub_080912f8+1
	.word	sub_08091368+1
	.word	sub_08091558+1
	.word	sub_080915d0+1
	.word	sub_080916c4+1
	.word	sub_080917fc+1
	.word	sub_0809191c+1
	.global	gUnk_087439C0
gUnk_087439C0:
	.incbin	"baserom.gba", 0x7439C0, 0x6
	.global	gUnk_087439C6
gUnk_087439C6:
	.incbin	"baserom.gba", 0x7439C6, 0x1A
	.global	gUnk_087439E0
gUnk_087439E0:
	.incbin	"baserom.gba", 0x7439E0, 0x6
	.global	gUnk_087439E6
gUnk_087439E6:
	.incbin	"baserom.gba", 0x7439E6, 0x1A
	.global	gUnk_08743A00
gUnk_08743A00:
	.word	gUnk_087439C0
	.word	gUnk_087439C6
	.word	gUnk_087439E0
	.word	gUnk_087439E6
	.global	gUnk_08743A10
gUnk_08743A10:
	.word	gUnk_08743F18
	.word	gUnk_08743EFC
	.word	gUnk_08743EFC
	.word	gUnk_08743F50
	.word	gUnk_08743FA4
	.word	gUnk_08743EFC
	.global	gUnk_08743A28
gUnk_08743A28:
	.word	gUnk_0874406C
	.word	gUnk_0874406C
	.word	gUnk_0874406C
	.word	gUnk_08744074
	.word	gUnk_0874406C
	.word	gUnk_0874406C
	.global	gUnk_08743A40
gUnk_08743A40:
	.word	gUnk_08743F34
	.word	gUnk_08743F34
	.word	gUnk_08743F34
	.word	gUnk_08743F88
	.word	gUnk_08743FC0
	.word	gUnk_08743F34
	.global	gUnk_08743A58
gUnk_08743A58:
	.incbin	"baserom.gba", 0x743A58, 0x4
	.word	gUnk_08743FDC
	.incbin	"baserom.gba", 0x743A60, 0x4
	.word	gUnk_08743FF8
	.incbin	"baserom.gba", 0x743A68, 0x8
	.global	gUnk_08743A70
gUnk_08743A70:
	.incbin	"baserom.gba", 0x743A70, 0x4
	.global	gUnk_08743A74
gUnk_08743A74:
	.incbin	"baserom.gba", 0x743A74, 0x8
	.global	gUnk_08743A7C
gUnk_08743A7C:
	.incbin	"baserom.gba", 0x743A7C, 0x6
	.global	gUnk_08743A82
gUnk_08743A82:
	.incbin	"baserom.gba", 0x743A82, 0x6
	.global	gUnk_08743A88
gUnk_08743A88:
	.incbin	"baserom.gba", 0x743A88, 0x6
	.global	gUnk_08743A8E
gUnk_08743A8E:
	.incbin	"baserom.gba", 0x743A8E, 0x6
	.global	gUnk_08743A94
gUnk_08743A94:
	.incbin	"baserom.gba", 0x743A94, 0x8
	.global	gUnk_08743A9C
gUnk_08743A9C:
	.incbin	"baserom.gba", 0x743A9C, 0x8
	.global	gUnk_08743AA4
gUnk_08743AA4:
	.incbin	"baserom.gba", 0x743AA4, 0x8
	.global	gUnk_08743AAC
gUnk_08743AAC:
	.incbin	"baserom.gba", 0x743AAC, 0x8
	.global	gUnk_08743AB4
gUnk_08743AB4:
	.incbin	"baserom.gba", 0x743AB4, 0x4
	.global	gUnk_08743AB8
gUnk_08743AB8:
	.incbin	"baserom.gba", 0x743AB8, 0xA
	.global	gUnk_08743AC2
gUnk_08743AC2:
	.incbin	"baserom.gba", 0x743AC2, 0x6
	.global	gUnk_08743AC8
gUnk_08743AC8:
	.incbin	"baserom.gba", 0x743AC8, 0x14
	.global	gBugzzyVariants
gBugzzyVariants:
	.word	BugzzyInit+1
	.global	gBugzzyStates
gBugzzyStates:
	.word	sub_08092198+1
	.word	sub_08092250+1
	.word	sub_080925b8+1
	.word	sub_080926fc+1
	.word	sub_08092a14+1
	.word	sub_08092b58+1
	.word	sub_08092c00+1
	.word	sub_08092cdc+1
	.word	sub_08092e68+1
	.word	sub_08092f2c+1
	.word	sub_080930ac+1
	.word	sub_0809301c+1
	.word	sub_08093380+1
	.global	gBugzzyStateUpdates
gBugzzyStateUpdates:
	.word	sub_08092228+1
	.word	sub_08092590+1
	.word	sub_080926d4+1
	.word	sub_080929ec+1
	.word	sub_08092b30+1
	.word	sub_08092bd8+1
	.word	sub_08092cb4+1
	.word	sub_08092e40+1
	.word	sub_08092f04+1
	.word	sub_08092ff4+1
	.word	sub_08093354+1
	.word	sub_08093084+1
	.word	sub_08093488+1
	.global	gUnk_08743B48
gUnk_08743B48:
	.incbin	"baserom.gba", 0x743B48, 0x4
