@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment actor_rodata_08743bd0: 0x08743BD0-0x0874402C (data, 0x45C bytes)
@ Structure only (docs/data.md): labels, symbolic pointer words and
@ .incbin slices of the user's baserom.gba; no ROM bytes are committed.
@ 42 label(s), 0 code pointer(s), 0 data pointer(s), 42 .incbin slice(s) (0x45C bytes).

	.section .actor_rodata_08743bd0, "a"
	.global	actor_rodata_08743bd0
actor_rodata_08743bd0:
	.global	gUnk_08743BD0
gUnk_08743BD0:
	.incbin	"baserom.gba", 0x743BD0, 0x1C
	.global	gUnk_08743BEC
gUnk_08743BEC:
	.incbin	"baserom.gba", 0x743BEC, 0x1C
	.global	gUnk_08743C08
gUnk_08743C08:
	.incbin	"baserom.gba", 0x743C08, 0x1C
	.global	gUnk_08743C24
gUnk_08743C24:
	.incbin	"baserom.gba", 0x743C24, 0x1C
	.global	gUnk_08743C40
gUnk_08743C40:
	.incbin	"baserom.gba", 0x743C40, 0x1C
	.global	gUnk_08743C5C
gUnk_08743C5C:
	.incbin	"baserom.gba", 0x743C5C, 0x1C
	.global	gUnk_08743C78
gUnk_08743C78:
	.incbin	"baserom.gba", 0x743C78, 0x1C
	.global	gUnk_08743C94
gUnk_08743C94:
	.incbin	"baserom.gba", 0x743C94, 0x1C
	.global	gUnk_08743CB0
gUnk_08743CB0:
	.incbin	"baserom.gba", 0x743CB0, 0x1C
	.global	gUnk_08743CCC
gUnk_08743CCC:
	.incbin	"baserom.gba", 0x743CCC, 0x1C
	.global	gUnk_08743CE8
gUnk_08743CE8:
	.incbin	"baserom.gba", 0x743CE8, 0x1C
	.global	gUnk_08743D04
gUnk_08743D04:
	.incbin	"baserom.gba", 0x743D04, 0x1C
	.global	gUnk_08743D20
gUnk_08743D20:
	.incbin	"baserom.gba", 0x743D20, 0x1C
	.global	gUnk_08743D3C
gUnk_08743D3C:
	.incbin	"baserom.gba", 0x743D3C, 0x1C
	.global	gUnk_08743D58
gUnk_08743D58:
	.incbin	"baserom.gba", 0x743D58, 0x1C
	.global	gUnk_08743D74
gUnk_08743D74:
	.incbin	"baserom.gba", 0x743D74, 0x1C
	.global	gUnk_08743D90
gUnk_08743D90:
	.incbin	"baserom.gba", 0x743D90, 0x1C
	.global	gUnk_08743DAC
gUnk_08743DAC:
	.incbin	"baserom.gba", 0x743DAC, 0x1C
	.global	gUnk_08743DC8
gUnk_08743DC8:
	.incbin	"baserom.gba", 0x743DC8, 0x1C
	.global	gUnk_08743DE4
gUnk_08743DE4:
	.incbin	"baserom.gba", 0x743DE4, 0x1C
	.global	gUnk_08743E00
gUnk_08743E00:
	.incbin	"baserom.gba", 0x743E00, 0x1C
	.global	gUnk_08743E1C
gUnk_08743E1C:
	.incbin	"baserom.gba", 0x743E1C, 0x1C
	.global	gUnk_08743E38
gUnk_08743E38:
	.incbin	"baserom.gba", 0x743E38, 0x1C
	.global	gUnk_08743E54
gUnk_08743E54:
	.incbin	"baserom.gba", 0x743E54, 0x1C
	.global	gUnk_08743E70
gUnk_08743E70:
	.incbin	"baserom.gba", 0x743E70, 0x1C
	.global	gUnk_08743E8C
gUnk_08743E8C:
	.incbin	"baserom.gba", 0x743E8C, 0x1C
	.global	gUnk_08743EA8
gUnk_08743EA8:
	.incbin	"baserom.gba", 0x743EA8, 0x1C
	.global	gUnk_08743EC4
gUnk_08743EC4:
	.incbin	"baserom.gba", 0x743EC4, 0x1C
	.global	gUnk_08743EE0
gUnk_08743EE0:
	.incbin	"baserom.gba", 0x743EE0, 0x1C
	.global	gUnk_08743EFC
gUnk_08743EFC:
	.incbin	"baserom.gba", 0x743EFC, 0x1C
	.global	gUnk_08743F18
gUnk_08743F18:
	.incbin	"baserom.gba", 0x743F18, 0x1C
	.global	gUnk_08743F34
gUnk_08743F34:
	.incbin	"baserom.gba", 0x743F34, 0x1C
	.global	gUnk_08743F50
gUnk_08743F50:
	.incbin	"baserom.gba", 0x743F50, 0x1C
	.global	gUnk_08743F6C
gUnk_08743F6C:
	.incbin	"baserom.gba", 0x743F6C, 0x1C
	.global	gUnk_08743F88
gUnk_08743F88:
	.incbin	"baserom.gba", 0x743F88, 0x1C
	.global	gUnk_08743FA4
gUnk_08743FA4:
	.incbin	"baserom.gba", 0x743FA4, 0x1C
	.global	gUnk_08743FC0
gUnk_08743FC0:
	.incbin	"baserom.gba", 0x743FC0, 0x1C
	.global	gUnk_08743FDC
gUnk_08743FDC:
	.incbin	"baserom.gba", 0x743FDC, 0x1C
	.global	gUnk_08743FF8
gUnk_08743FF8:
	.incbin	"baserom.gba", 0x743FF8, 0x1C
	.global	gUnk_08744014
gUnk_08744014:
	.incbin	"baserom.gba", 0x744014, 0x8
	.global	gUnk_0874401C
gUnk_0874401C:
	.incbin	"baserom.gba", 0x74401C, 0x8
	.global	gUnk_08744024
gUnk_08744024:
	.incbin	"baserom.gba", 0x744024, 0x8
