@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment compressed_graphics: 0x083D0000-0x085C0000 (data, 0x1F0000 bytes)
@ Structure only (docs/data.md): labels, symbolic pointer words and
@ .incbin slices of the user's baserom.gba; no ROM bytes are committed.
@ 112 label(s), 0 code pointer(s), 0 data pointer(s), 113 .incbin slice(s) (0x1F0000 bytes).
@ Asset segment: its bytes stay extracted from baserom.gba forever; only
@ labels and consumer-proven pointer tables are structure.

	.section .compressed_graphics, "a"
	.global	compressed_graphics
compressed_graphics:
	.incbin	"baserom.gba", 0x3D0000, 0x171D98
	.global	gUnk_08541D98
gUnk_08541D98:
	.incbin	"baserom.gba", 0x541D98, 0x1C0
	.global	gUnk_08541F58
gUnk_08541F58:
	.incbin	"baserom.gba", 0x541F58, 0xEC44
	.global	gUnk_08550B9C
gUnk_08550B9C:
	.incbin	"baserom.gba", 0x550B9C, 0x574
	.global	gUnk_08551110
gUnk_08551110:
	.incbin	"baserom.gba", 0x551110, 0x2100
	.global	gUnk_08553210
gUnk_08553210:
	.incbin	"baserom.gba", 0x553210, 0x300
	.global	gUnk_08553510
gUnk_08553510:
	.incbin	"baserom.gba", 0x553510, 0x300
	.global	gUnk_08553810
gUnk_08553810:
	.incbin	"baserom.gba", 0x553810, 0x1350
	.global	gUnk_08554B60
gUnk_08554B60:
	.incbin	"baserom.gba", 0x554B60, 0x18
	.global	gUnk_08554B78
gUnk_08554B78:
	.incbin	"baserom.gba", 0x554B78, 0x202
	.global	gUnk_08554D7A
gUnk_08554D7A:
	.incbin	"baserom.gba", 0x554D7A, 0x6
	.global	gUnk_08554D80
gUnk_08554D80:
	.incbin	"baserom.gba", 0x554D80, 0x1648
	.global	gUnk_085563C8
gUnk_085563C8:
	.incbin	"baserom.gba", 0x5563C8, 0x37A0
	.global	gUnk_08559B68
gUnk_08559B68:
	.incbin	"baserom.gba", 0x559B68, 0x28
	.global	gUnk_08559B90
gUnk_08559B90:
	.incbin	"baserom.gba", 0x559B90, 0x14
	.global	gUnk_08559BA4
gUnk_08559BA4:
	.incbin	"baserom.gba", 0x559BA4, 0x80
	.global	gUnk_08559C24
gUnk_08559C24:
	.incbin	"baserom.gba", 0x559C24, 0xC2
	.global	gUnk_08559CE6
gUnk_08559CE6:
	.incbin	"baserom.gba", 0x559CE6, 0x6
	.global	gUnk_08559CEC
gUnk_08559CEC:
	.incbin	"baserom.gba", 0x559CEC, 0x90C
	.global	gUnk_0855A5F8
gUnk_0855A5F8:
	.incbin	"baserom.gba", 0x55A5F8, 0x2D00
	.global	gUnk_0855D2F8
gUnk_0855D2F8:
	.incbin	"baserom.gba", 0x55D2F8, 0x28
	.global	gUnk_0855D320
gUnk_0855D320:
	.incbin	"baserom.gba", 0x55D320, 0x14
	.global	gUnk_0855D334
gUnk_0855D334:
	.incbin	"baserom.gba", 0x55D334, 0x3A88
	.global	gUnk_08560DBC
gUnk_08560DBC:
	.incbin	"baserom.gba", 0x560DBC, 0x1E0
	.global	gUnk_08560F9C
gUnk_08560F9C:
	.incbin	"baserom.gba", 0x560F9C, 0x288
	.global	gUnk_08561224
gUnk_08561224:
	.incbin	"baserom.gba", 0x561224, 0x1DC0
	.global	gUnk_08562FE4
gUnk_08562FE4:
	.incbin	"baserom.gba", 0x562FE4, 0x40
	.global	gUnk_08563024
gUnk_08563024:
	.incbin	"baserom.gba", 0x563024, 0x408
	.global	gUnk_0856342C
gUnk_0856342C:
	.incbin	"baserom.gba", 0x56342C, 0xAC
	.global	gUnk_085634D8
gUnk_085634D8:
	.incbin	"baserom.gba", 0x5634D8, 0x1A5C
	.global	gUnk_08564F34
gUnk_08564F34:
	.incbin	"baserom.gba", 0x564F34, 0x4
	.global	gUnk_08564F38
gUnk_08564F38:
	.incbin	"baserom.gba", 0x564F38, 0x48C
	.global	gUnk_085653C4
gUnk_085653C4:
	.incbin	"baserom.gba", 0x5653C4, 0x9EE4
	.global	gUnk_0856F2A8
gUnk_0856F2A8:
	.incbin	"baserom.gba", 0x56F2A8, 0x60
	.global	gUnk_0856F308
gUnk_0856F308:
	.incbin	"baserom.gba", 0x56F308, 0xE44
	.global	gUnk_0857014C
gUnk_0857014C:
	.incbin	"baserom.gba", 0x57014C, 0x380
	.global	gUnk_085704CC
gUnk_085704CC:
	.incbin	"baserom.gba", 0x5704CC, 0x308
	.global	gUnk_085707D4
gUnk_085707D4:
	.incbin	"baserom.gba", 0x5707D4, 0xD4
	.global	gUnk_085708A8
gUnk_085708A8:
	.incbin	"baserom.gba", 0x5708A8, 0x144
	.global	gUnk_085709EC
gUnk_085709EC:
	.incbin	"baserom.gba", 0x5709EC, 0x13C
	.global	gUnk_08570B28
gUnk_08570B28:
	.incbin	"baserom.gba", 0x570B28, 0x3F4
	.global	gUnk_08570F1C
gUnk_08570F1C:
	.incbin	"baserom.gba", 0x570F1C, 0x200
	.global	gUnk_0857111C
gUnk_0857111C:
	.incbin	"baserom.gba", 0x57111C, 0x100
	.global	gUnk_0857121C
gUnk_0857121C:
	.incbin	"baserom.gba", 0x57121C, 0x2C
	.global	gUnk_08571248
gUnk_08571248:
	.incbin	"baserom.gba", 0x571248, 0x4E4
	.global	gUnk_0857172C
gUnk_0857172C:
	.incbin	"baserom.gba", 0x57172C, 0x10C
	.global	gUnk_08571838
gUnk_08571838:
	.incbin	"baserom.gba", 0x571838, 0x3A8
	.global	gUnk_08571BE0
gUnk_08571BE0:
	.incbin	"baserom.gba", 0x571BE0, 0x194
	.global	gUnk_08571D74
gUnk_08571D74:
	.incbin	"baserom.gba", 0x571D74, 0x3F0
	.global	gUnk_08572164
gUnk_08572164:
	.incbin	"baserom.gba", 0x572164, 0x12A4C
	.global	gUnk_08584BB0
gUnk_08584BB0:
	.incbin	"baserom.gba", 0x584BB0, 0x149FC
	.global	gUnk_085995AC
gUnk_085995AC:
	.incbin	"baserom.gba", 0x5995AC, 0x360
	.global	gUnk_0859990C
gUnk_0859990C:
	.incbin	"baserom.gba", 0x59990C, 0x790
	.global	gUnk_0859A09C
gUnk_0859A09C:
	.incbin	"baserom.gba", 0x59A09C, 0x14
	.global	gUnk_0859A0B0
gUnk_0859A0B0:
	.incbin	"baserom.gba", 0x59A0B0, 0x20
	.global	gUnk_0859A0D0
gUnk_0859A0D0:
	.incbin	"baserom.gba", 0x59A0D0, 0x20
	.global	gUnk_0859A0F0
gUnk_0859A0F0:
	.incbin	"baserom.gba", 0x59A0F0, 0x20
	.global	gUnk_0859A110
gUnk_0859A110:
	.incbin	"baserom.gba", 0x59A110, 0x6528
	.global	gUnk_085A0638
gUnk_085A0638:
	.incbin	"baserom.gba", 0x5A0638, 0x600
	.global	gUnk_085A0C38
gUnk_085A0C38:
	.incbin	"baserom.gba", 0x5A0C38, 0x6C0
	.global	gUnk_085A12F8
gUnk_085A12F8:
	.incbin	"baserom.gba", 0x5A12F8, 0x900
	.global	gUnk_085A1BF8
gUnk_085A1BF8:
	.incbin	"baserom.gba", 0x5A1BF8, 0x900
	.global	gUnk_085A24F8
gUnk_085A24F8:
	.incbin	"baserom.gba", 0x5A24F8, 0x900
	.global	gUnk_085A2DF8
gUnk_085A2DF8:
	.incbin	"baserom.gba", 0x5A2DF8, 0xEC0
	.global	gUnk_085A3CB8
gUnk_085A3CB8:
	.incbin	"baserom.gba", 0x5A3CB8, 0xC4C
	.global	gUnk_085A4904
gUnk_085A4904:
	.incbin	"baserom.gba", 0x5A4904, 0xE4
	.global	gUnk_085A49E8
gUnk_085A49E8:
	.incbin	"baserom.gba", 0x5A49E8, 0xC6C
	.global	gUnk_085A5654
gUnk_085A5654:
	.incbin	"baserom.gba", 0x5A5654, 0x10C0
	.global	gUnk_085A6714
gUnk_085A6714:
	.incbin	"baserom.gba", 0x5A6714, 0x820
	.global	gUnk_085A6F34
gUnk_085A6F34:
	.incbin	"baserom.gba", 0x5A6F34, 0x28
	.global	gUnk_085A6F5C
gUnk_085A6F5C:
	.incbin	"baserom.gba", 0x5A6F5C, 0x4
	.global	gUnk_085A6F60
gUnk_085A6F60:
	.incbin	"baserom.gba", 0x5A6F60, 0x4
	.global	gUnk_085A6F64
gUnk_085A6F64:
	.incbin	"baserom.gba", 0x5A6F64, 0x4
	.global	gUnk_085A6F68
gUnk_085A6F68:
	.incbin	"baserom.gba", 0x5A6F68, 0x3C
	.global	gUnk_085A6FA4
gUnk_085A6FA4:
	.incbin	"baserom.gba", 0x5A6FA4, 0x20
	.global	gUnk_085A6FC4
gUnk_085A6FC4:
	.incbin	"baserom.gba", 0x5A6FC4, 0x4
	.global	gUnk_085A6FC8
gUnk_085A6FC8:
	.incbin	"baserom.gba", 0x5A6FC8, 0x28
	.global	gUnk_085A6FF0
gUnk_085A6FF0:
	.incbin	"baserom.gba", 0x5A6FF0, 0x8
	.global	gUnk_085A6FF8
gUnk_085A6FF8:
	.incbin	"baserom.gba", 0x5A6FF8, 0x4
	.global	gUnk_085A6FFC
gUnk_085A6FFC:
	.incbin	"baserom.gba", 0x5A6FFC, 0x6D20
	.global	gUnk_085ADD1C
gUnk_085ADD1C:
	.incbin	"baserom.gba", 0x5ADD1C, 0x2CA0
	.global	gUnk_085B09BC
gUnk_085B09BC:
	.incbin	"baserom.gba", 0x5B09BC, 0x20
	.global	gUnk_085B09DC
gUnk_085B09DC:
	.incbin	"baserom.gba", 0x5B09DC, 0x34
	.global	gUnk_085B0A10
gUnk_085B0A10:
	.incbin	"baserom.gba", 0x5B0A10, 0x20
	.global	gUnk_085B0A30
gUnk_085B0A30:
	.incbin	"baserom.gba", 0x5B0A30, 0x34
	.global	gUnk_085B0A64
gUnk_085B0A64:
	.incbin	"baserom.gba", 0x5B0A64, 0x4C
	.global	gUnk_085B0AB0
gUnk_085B0AB0:
	.incbin	"baserom.gba", 0x5B0AB0, 0x20
	.global	gUnk_085B0AD0
gUnk_085B0AD0:
	.incbin	"baserom.gba", 0x5B0AD0, 0x4
	.global	gUnk_085B0AD4
gUnk_085B0AD4:
	.incbin	"baserom.gba", 0x5B0AD4, 0x28
	.global	gUnk_085B0AFC
gUnk_085B0AFC:
	.incbin	"baserom.gba", 0x5B0AFC, 0x4
	.global	gUnk_085B0B00
gUnk_085B0B00:
	.incbin	"baserom.gba", 0x5B0B00, 0x8
	.global	gUnk_085B0B08
gUnk_085B0B08:
	.incbin	"baserom.gba", 0x5B0B08, 0x8
	.global	gUnk_085B0B10
gUnk_085B0B10:
	.incbin	"baserom.gba", 0x5B0B10, 0x18
	.global	gUnk_085B0B28
gUnk_085B0B28:
	.incbin	"baserom.gba", 0x5B0B28, 0x34
	.global	gUnk_085B0B5C
gUnk_085B0B5C:
	.incbin	"baserom.gba", 0x5B0B5C, 0x58
	.global	gUnk_085B0BB4
gUnk_085B0BB4:
	.incbin	"baserom.gba", 0x5B0BB4, 0x20
	.global	gUnk_085B0BD4
gUnk_085B0BD4:
	.incbin	"baserom.gba", 0x5B0BD4, 0x58
	.global	gUnk_085B0C2C
gUnk_085B0C2C:
	.incbin	"baserom.gba", 0x5B0C2C, 0x510
	.global	gUnk_085B113C
gUnk_085B113C:
	.incbin	"baserom.gba", 0x5B113C, 0x60
	.global	gUnk_085B119C
gUnk_085B119C:
	.incbin	"baserom.gba", 0x5B119C, 0x15B0
	.global	gUnk_085B274C
gUnk_085B274C:
	.incbin	"baserom.gba", 0x5B274C, 0x5C0
	.global	gUnk_085B2D0C
gUnk_085B2D0C:
	.incbin	"baserom.gba", 0x5B2D0C, 0x80
	.global	gUnk_085B2D8C
gUnk_085B2D8C:
	.incbin	"baserom.gba", 0x5B2D8C, 0x1780
	.global	gUnk_085B450C
gUnk_085B450C:
	.incbin	"baserom.gba", 0x5B450C, 0x5C0
	.global	gUnk_085B4ACC
gUnk_085B4ACC:
	.incbin	"baserom.gba", 0x5B4ACC, 0x80
	.global	gUnk_085B4B4C
gUnk_085B4B4C:
	.incbin	"baserom.gba", 0x5B4B4C, 0x197C
	.global	gUnk_085B64C8
gUnk_085B64C8:
	.incbin	"baserom.gba", 0x5B64C8, 0x5C8
	.global	gUnk_085B6A90
gUnk_085B6A90:
	.incbin	"baserom.gba", 0x5B6A90, 0x30
	.global	gUnk_085B6AC0
gUnk_085B6AC0:
	.incbin	"baserom.gba", 0x5B6AC0, 0x8
	.global	gUnk_085B6AC8
gUnk_085B6AC8:
	.incbin	"baserom.gba", 0x5B6AC8, 0x3B0
	.global	gUnk_085B6E78
gUnk_085B6E78:
	.incbin	"baserom.gba", 0x5B6E78, 0x120
	.global	gUnk_085B6F98
gUnk_085B6F98:
	.incbin	"baserom.gba", 0x5B6F98, 0x2BD4
	.global	gUnk_085B9B6C
gUnk_085B9B6C:
	.incbin	"baserom.gba", 0x5B9B6C, 0x6494
