@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment sample_set_index: 0x087E1D58-0x087E3088 (data, 0x1330 bytes)
@ Structure only (docs/data.md): labels, symbolic pointer words and
@ .incbin slices of the user's baserom.gba; no ROM bytes are committed.
@ 2 label(s), 0 code pointer(s), 0 data pointer(s), 2 .incbin slice(s) (0x1330 bytes).

	.section .sample_set_index, "a"
	.global	sample_set_index
sample_set_index:
	.global	gUnk_087E1D58
gUnk_087E1D58:
	.incbin	"baserom.gba", 0x7E1D58, 0x1C8
	.global	gUnk_087E1F20
gUnk_087E1F20:
	.incbin	"baserom.gba", 0x7E1F20, 0x1168
