@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804, chunk 2/2: 0x08034F70-0x08034F8C (thumb_code, 0x1C bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08034F70 sub_08034f70

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_01:
	.thumb_func
	.global	sub_08034f70
sub_08034f70:
	.thumb
	push	{lr}
	ldr	r0, [pc, #20]	@ 0x08034F88
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #0
	str	r0, [r1, #104]
	bl	sub_08034f8c	@ 0x08034F8C
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
