@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804, chunk 2/2: 0x08033414-0x080337F4 (thumb_code, 0x3E0 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x08033414 sub_08033414

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_08030804_01:
	.thumb_func
	.global	sub_08033414
sub_08033414:
	.thumb
	push	{r4, r5, lr}
	ldr	r0, [pc, #128]	@ 0x08033498
	ldr	r1, [r0, #0]
	adds	r1, #136
	ldr	r2, [r1, #0]
	ldrb	r1, [r2, #1]
	adds	r5, r0, #0
	cmp	r1, #31
	bls.n	loc_08033432	@ 0x08033432
	ldr	r0, [pc, #116]	@ 0x0803349C
	ldrb	r0, [r0, #0]
	cmp	r0, #1
	bne.n	loc_08033432	@ 0x08033432
	movs	r0, #0
	strb	r0, [r2, #1]
	.global	loc_08033432
loc_08033432:
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #124
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #1
	bne.n	loc_08033444	@ 0x08033444
	b.n	loc_08033564	@ 0x08033564
	.global	loc_08033444
loc_08033444:
	cmp	r0, #2
	bne.n	loc_0803344a	@ 0x0803344A
	b.n	loc_08033586	@ 0x08033586
	.global	loc_0803344a
loc_0803344a:
	ldr	r0, [pc, #84]	@ 0x080334A0
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_0803350c	@ 0x0803350C
	adds	r3, r1, #0
	adds	r3, #136
	ldr	r2, [r3, #0]
	adds	r0, r2, #0
	adds	r0, #64
	ldrh	r1, [r0, #0]
	movs	r0, #32
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803350c	@ 0x0803350C
	ldr	r0, [pc, #60]	@ 0x080334A4
	movs	r1, #0
	ldrsb	r1, [r2, r1]
	lsls	r1, r1, #1
	adds	r0, r1, r0
	ldrh	r2, [r0, #0]
	movs	r4, #0
	ldrsh	r0, [r0, r4]
	cmp	r0, #0
	beq.n	loc_080334b4	@ 0x080334B4
	ldr	r0, [pc, #44]	@ 0x080334A8
	adds	r0, r1, r0
	strh	r2, [r0, #0]
	ldr	r2, [pc, #40]	@ 0x080334AC
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #1
	adds	r2, r0, r2
	ldr	r1, [pc, #32]	@ 0x080334B0
	adds	r0, r0, r1
	ldrh	r0, [r0, #0]
	strh	r0, [r2, #0]
	b.n	loc_080334ce	@ 0x080334CE
	.word	gUnk_03002490
	.word	gUnk_02007CF0
	.word	gUnk_03001F30
	.word	gUnk_02004B50
	.word	gUnk_02008008
	.word	gUnk_02007FA8
	.word	gUnk_0200AF18
	.global	loc_080334b4
loc_080334b4:
	ldr	r0, [pc, #68]	@ 0x080334FC
	adds	r0, r1, r0
	movs	r1, #4
	strh	r1, [r0, #0]
	ldr	r1, [pc, #64]	@ 0x08033500
	ldr	r0, [r3, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	lsls	r0, r0, #1
	adds	r0, r0, r1
	ldr	r1, [pc, #56]	@ 0x08033504
	strh	r1, [r0, #0]
	.global	loc_080334ce
loc_080334ce:
	ldr	r2, [pc, #56]	@ 0x08033508
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #4
	strb	r0, [r1, #11]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #255
	strb	r0, [r1, #12]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #55
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #29
	strb	r0, [r1, #1]
	b.n	loc_080335ca	@ 0x080335CA
	.word	gUnk_02008008
	.word	gUnk_02007FA8
	.word	0x0000FFFF
	.word	gUnk_03002490
	.global	loc_0803350c
loc_0803350c:
	ldr	r4, [pc, #76]	@ 0x0803355C
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r2, [r0, #0]
	adds	r0, r2, #0
	adds	r0, #64
	ldrh	r1, [r0, #0]
	movs	r0, #64
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080335ca	@ 0x080335CA
	ldrb	r2, [r2, #0]
	lsls	r2, r2, #24
	asrs	r2, r2, #24
	movs	r0, #5
	movs	r1, #0
	bl	sub_0803e1b8	@ 0x0803E1B8
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r1, #64
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #36]	@ 0x08033560
	ands	r0, r2
	strh	r0, [r1, #0]
	movs	r0, #19
	bl	sub_08003110	@ 0x08003110
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	movs	r1, #3
	bl	sub_08040894	@ 0x08040894
	b.n	loc_080335ca	@ 0x080335CA
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x0000FFBF
	.global	loc_08033564
loc_08033564:
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r2, #0
	movs	r0, #17
	strb	r0, [r1, #1]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #34
	strb	r2, [r0, #0]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	strh	r2, [r0, #32]
	strh	r2, [r0, #30]
	b.n	loc_080335ca	@ 0x080335CA
	.global	loc_08033586
loc_08033586:
	adds	r0, r1, #0
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r0, r1, #0
	adds	r0, #55
	ldrb	r0, [r0, #0]
	cmp	r0, #2
	beq.n	loc_080335a6	@ 0x080335A6
	movs	r0, #16
	strb	r0, [r1, #1]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #255
	strb	r0, [r1, #22]
	b.n	loc_080335b2	@ 0x080335B2
	.global	loc_080335a6
loc_080335a6:
	movs	r0, #58
	strb	r0, [r1, #1]
	ldr	r0, [r5, #0]
	adds	r0, #115
	movs	r1, #3
	strb	r1, [r0, #0]
	.global	loc_080335b2
loc_080335b2:
	ldr	r2, [pc, #164]	@ 0x08033658
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #34
	movs	r1, #0
	strb	r1, [r0, #0]
	ldr	r0, [r2, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	strh	r1, [r0, #32]
	strh	r1, [r0, #30]
	.global	loc_080335ca
loc_080335ca:
	ldr	r5, [pc, #140]	@ 0x08033658
	ldr	r0, [r5, #0]
	adds	r0, #124
	movs	r4, #0
	strb	r4, [r0, #0]
	ldr	r3, [r5, #0]
	adds	r0, r3, #0
	adds	r0, #136
	ldr	r2, [r0, #0]
	ldrb	r0, [r2, #1]
	cmp	r0, #0
	beq.n	loc_08033660	@ 0x08033660
	adds	r0, r2, #0
	adds	r0, #64
	ldrh	r1, [r0, #0]
	.word	0x40082001
	cmp	r0, #0
	beq.n	loc_08033620	@ 0x08033620
	adds	r0, r2, #0
	adds	r0, #40
	strb	r4, [r0, #0]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #41
	movs	r1, #1
	strb	r1, [r0, #0]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #43
	strb	r4, [r0, #0]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	strh	r4, [r0, #38]
	strh	r4, [r0, #36]
	ldr	r0, [pc, #68]	@ 0x0803365C
	ldr	r1, [r0, #0]
	movs	r0, #0
	bl	sub_080055b0	@ 0x080055B0
	.global	loc_08033620
loc_08033620:
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r2, #44
	ldrsh	r1, [r0, r2]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_08033636	@ 0x08033636
	bl	sub_0803e3ac	@ 0x0803E3AC
	.global	loc_08033636
loc_08033636:
	ldr	r1, [r5, #0]
	adds	r0, r1, #0
	adds	r0, #118
	movs	r2, #0
	strh	r4, [r0, #0]
	adds	r1, #136
	ldr	r0, [r1, #0]
	adds	r0, #64
	strh	r4, [r0, #0]
	ldr	r0, [r1, #0]
	adds	r0, #80
	strb	r2, [r0, #0]
	ldr	r0, [r5, #0]
	adds	r0, #128
	strb	r2, [r0, #0]
	b.n	loc_080336b4	@ 0x080336B4
	movs	r0, r0
	.word	gUnk_03002490
	.word	gCurTaskIdx
	.global	loc_08033660
loc_08033660:
	ldr	r0, [pc, #148]	@ 0x080336F8
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_080336b4	@ 0x080336B4
	adds	r0, r3, #0
	adds	r0, #118
	ldrh	r1, [r0, #0]
	movs	r0, #2
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_0803369e	@ 0x0803369E
	adds	r2, #64
	ldrh	r1, [r2, #0]
	movs	r0, #2
	orrs	r0, r1
	strh	r0, [r2, #0]
	adds	r1, r3, #0
	adds	r1, #115
	movs	r0, #1
	strb	r0, [r1, #0]
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	movs	r0, #8
	strb	r0, [r1, #1]
	ldr	r1, [r5, #0]
	adds	r1, #118
	ldrh	r2, [r1, #0]
	ldr	r0, [pc, #96]	@ 0x080336FC
	ands	r0, r2
	strh	r0, [r1, #0]
	.global	loc_0803369e
loc_0803369e:
	ldr	r0, [r5, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #64
	ldrh	r1, [r0, #0]
	movs	r0, #128
	ands	r0, r1
	cmp	r0, #0
	bne.n	loc_080336b4	@ 0x080336B4
	bl	sub_0803ce98	@ 0x0803CE98
	.global	loc_080336b4
loc_080336b4:
	ldr	r4, [pc, #72]	@ 0x08033700
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	ldrb	r0, [r0, #1]
	cmp	r0, #0
	beq.n	loc_080336cc	@ 0x080336CC
	ldr	r0, [pc, #64]	@ 0x08033704
	ldr	r1, [pc, #64]	@ 0x08033708
	ldr	r1, [r1, #0]
	bl	sub_08006148	@ 0x08006148
	.global	loc_080336cc
loc_080336cc:
	ldr	r0, [pc, #40]	@ 0x080336F8
	ldrb	r0, [r0, #0]
	cmp	r0, #0
	bne.n	loc_08033750	@ 0x08033750
	ldr	r0, [r4, #0]
	adds	r0, #136
	ldr	r2, [r0, #0]
	adds	r0, r2, #0
	adds	r0, #64
	ldrh	r1, [r0, #0]
	movs	r0, #4
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_08033712	@ 0x08033712
	movs	r0, #13
	ldrsb	r0, [r2, r0]
	cmp	r0, #0
	bne.n	loc_0803370c	@ 0x0803370C
	movs	r0, #0
	bl	sub_0803c9b4	@ 0x0803C9B4
	b.n	loc_08033712	@ 0x08033712
	.word	gUnk_03001F30
	.word	0x0000FFFD
	.word	gUnk_03002490
	.word	sub_08032bd0+1
	.word	gCurTaskIdx
	.global	loc_0803370c
loc_0803370c:
	movs	r0, #1
	bl	sub_0803c9b4	@ 0x0803C9B4
	.global	loc_08033712
loc_08033712:
	ldr	r0, [pc, #152]	@ 0x080337AC
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r1, [r0, #0]
	adds	r0, r1, #0
	adds	r0, #54
	ldrb	r0, [r0, #0]
	lsls	r0, r0, #24
	asrs	r0, r0, #24
	cmp	r0, #0
	beq.n	loc_08033750	@ 0x08033750
	ldrb	r0, [r1, #3]
	cmp	r0, #33
	bgt.n	loc_08033742	@ 0x08033742
	cmp	r0, #32
	blt.n	loc_08033742	@ 0x08033742
	movs	r0, #0
	ldrsb	r0, [r1, r0]
	movs	r1, #15
	movs	r2, #0
	bl	sub_0805afac	@ 0x0805AFAC
	bl	sub_08049a58	@ 0x08049A58
	.global	loc_08033742
loc_08033742:
	ldr	r0, [pc, #104]	@ 0x080337AC
	ldr	r0, [r0, #0]
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #54
	movs	r1, #0
	strb	r1, [r0, #0]
	.global	loc_08033750
loc_08033750:
	ldr	r1, [pc, #88]	@ 0x080337AC
	ldr	r2, [r1, #0]
	adds	r0, r2, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	adds	r0, #55
	ldrb	r0, [r0, #0]
	adds	r5, r1, #0
	cmp	r0, #2
	bne.n	loc_0803378a	@ 0x0803378A
	movs	r3, #74
	adds	r3, r3, r2
	mov	ip, r3
	movs	r4, #0
	ldrsh	r1, [r3, r4]
	ldr	r4, [pc, #64]	@ 0x080337B0
	movs	r3, #0
	ldrsh	r0, [r4, r3]
	adds	r1, r1, r0
	movs	r3, #225
	lsls	r3, r3, #2
	cmp	r1, r3
	ble.n	loc_0803378a	@ 0x0803378A
	ldrh	r0, [r4, #0]
	subs	r0, r3, r0
	mov	r4, ip
	strh	r0, [r4, #0]
	lsls	r0, r0, #16
	str	r0, [r2, #80]
	.global	loc_0803378a
loc_0803378a:
	ldr	r2, [r5, #0]
	ldr	r3, [r2, #76]
	adds	r0, r2, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r4, #36
	ldrsh	r1, [r0, r4]
	movs	r0, #128
	lsls	r0, r0, #8
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080337b4	@ 0x080337B4
	lsls	r0, r1, #8
	movs	r1, #255
	lsls	r1, r1, #24
	orrs	r0, r1
	b.n	loc_080337b6	@ 0x080337B6
	.word	gUnk_03002490
	.word	gUnk_030023E4
	.global	loc_080337b4
loc_080337b4:
	lsls	r0, r1, #8
	.global	loc_080337b6
loc_080337b6:
	adds	r0, r3, r0
	lsrs	r1, r0, #16
	adds	r0, r2, #0
	adds	r0, #72
	strh	r1, [r0, #0]
	ldr	r2, [r5, #0]
	ldr	r3, [r2, #80]
	adds	r0, r2, #0
	adds	r0, #136
	ldr	r0, [r0, #0]
	movs	r4, #38
	ldrsh	r1, [r0, r4]
	movs	r0, #128
	lsls	r0, r0, #8
	ands	r0, r1
	cmp	r0, #0
	beq.n	loc_080337e2	@ 0x080337E2
	lsls	r0, r1, #8
	movs	r1, #255
	lsls	r1, r1, #24
	orrs	r0, r1
	b.n	loc_080337e4	@ 0x080337E4
	.global	loc_080337e2
loc_080337e2:
	lsls	r0, r1, #8
	.global	loc_080337e4
loc_080337e4:
	adds	r0, r3, r0
	lsrs	r1, r0, #16
	adds	r0, r2, #0
	adds	r0, #74
	strh	r1, [r0, #0]
	pop	{r4, r5}
	pop	{r0}
	bx	r0
