@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc, chunk 2/2: 0x080301E8-0x08030238 (thumb_code, 0x50 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x080301E8 sub_080301e8

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc_01:
	.thumb_func
	.global	sub_080301e8
sub_080301e8:
	.thumb
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	movs	r0, #236
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r2, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r2, r0
	beq.n	loc_0803022a	@ 0x0803022A
	lsls	r0, r2, #3
	adds	r0, r0, r2
	lsls	r0, r0, #4
	ldr	r1, [pc, #40]	@ 0x08030234
	adds	r3, r0, r1
	adds	r0, r3, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	adds	r0, #2
	strh	r5, [r0, #0]
	lsls	r0, r4, #16
	str	r0, [r3, #76]
	lsls	r0, r5, #16
	str	r0, [r3, #80]
	strb	r6, [r3, #20]
	adds	r1, r3, #0
	adds	r1, #114
	movs	r0, #9
	strb	r0, [r1, #0]
	.global	loc_0803022a
loc_0803022a:
	adds	r0, r2, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002790
