#ifndef GUARD_ACTOR_H
#define GUARD_ACTOR_H

#include "gba/types.h"
#include "task.h"

/* actor.h: the RAM cells and ROM tables of the actor core: the struct Task
   field API (M17) and the player-state task bodies (M18).  One declaration
   per symbol, with the type its consumers prove (issue #36 phase 2,
   docs/header-conventions.md). */

struct ActorDef;

/* The 0x0824A9E4 record MetaKnightWarpStarRideInit uploads from (two tile-count halfwords
   plus two source pointers). */
struct GfxSrc
{
    /*0x00*/ u16 paletteBankCount;
    /*0x02*/ u16 tileCount;
    /*0x04*/ u32 unk04;
    /*0x08*/ void *palette;
    /*0x0C*/ void *tiles;
};

struct Unk0873EAC0
{
    /*0x00*/ s32 unk00;
    /*0x04*/ s32 unk04;
};

/* Seven-entry handler table hanging off Actor.terrainHandlers (and
   ActorDef.terrainHandlers); every entry is a u8 (*)(void) that returns 1 when
   it consumed the frame.  ActorCollideTerrain, ActorCollideTerrainInCameraBounds and ActorCollideTerrainFloor
   (src/actor_692fc.c) walk it. */
struct ActorHandlers
{
    /*0x00*/ u32 landCallback;
    /*0x04*/ u32 leaveGroundCallback;
    /*0x08*/ u32 enterWaterCallback;
    /*0x0C*/ u32 leaveWaterCallback;
    /*0x10*/ u32 hitWallCallback;
    /*0x14*/ u32 unk14;
    /*0x18*/ u32 hitCeilingCallback;
};

/* Block Actor.hitReactions (and ActorDef.hitReactions) points at: two s8 mode
   bytes and two u8 (*)(void) hooks (ActorReactToDamage, ActorReactToDefeat,
   src/actor_692fc.c).  Compare struct ActorAux, which is the Actor.unk60
   block. */
struct ActorVt
{
    /*0x00*/ s8 damageKind;
    /*0x01*/ s8 defeatKind;
    /*0x02*/ u8 filler02[2];
    /*0x04*/ u32 damageCallback;
    /*0x08*/ u32 defeatCallback;
};

/* EWRAM */
extern u16 gNextActorSerial;
extern u32 gBossHitStunFlashPalette;
extern u16 gWarpStarRideSlot;
extern s32 gUnk_02006040[];
extern s8 gCannonFuseState;
extern u8 gScreenAttackActive;
extern s32 gUnk_02006190[];
extern s8 gPaletteAnimTasks[];
extern u8 gUnk_02007CF4[];
extern s32 gUnk_02007D00[];
extern u32 gBossSubtype;
extern s8 gPaletteAnimRefCounts[];
extern u32 gBossHitStunCallback;
extern u8 gHudHpBarFilled;
extern u8 gMidBossDropsIn;
extern struct Actor gActors[];

/* IWRAM */
extern u32 gObjPaletteBank13[];
extern u8 gPauseDisabled;
extern struct PlayerState gPlayerStates[];
extern s32 gUnk_030023B4;
extern s32 gUnk_030023D4;
extern u8 gAttackHitTimer;

/* ROM */
extern struct GfxSrc gUnk_0824A9E4;
extern u8 gUnk_0825088C[];
extern u8 gUnk_082530C8[];
extern u8 gUnk_0825CA44[];
extern u32 gUnk_08334DC0[];
extern s16 gUnk_0873D384[];
extern s16 gUnk_0873D420[][3];
extern s32 gUnk_0873DF14[];
extern u32 gPaletteAnimVariants[];
extern u32 gUnk_0873DF38[][4];
extern u8 gUnk_0873DF78[];
extern u32 gUnk_0873DF7C[][3];
extern u8 gUnk_0873DFAC[];
extern u16 gUnk_0873E16C[];
extern s16 gUnk_0873E184[];
extern s8 gUnk_0873E1B4[];
extern s32 gParasolDriftSwayVelX[];
extern s16 gUnk_0873E1E8[];
extern s8 gUnk_0873E1F8[];
extern s16 gUnk_0873E220[];
extern u32 gStarRodPiecePalettes[];
extern u32 gInhalableStarStates[];
extern u32 gInhalableStarStateUpdates[];
extern u32 gHeldPlayerStates[];
extern u32 gHeldPlayerStateUpdates[];
extern s32 gUnk_0873E348[];
extern s32 gUnk_0873E388[];
extern u16 gUnk_0873E3C8[];
extern u16 gUnk_0873E58C[];
extern s16 gUnk_0873E5A4[];
extern u32 gActorDefeats[];
extern u32 gActorDefeatsByEffect[];
extern s16 gUnk_0873E5F8[];
extern u16 gUnk_0873E610[];
extern u16 gUnk_0873E620[];
extern u16 gUnk_0873E634[];
extern u16 gUnk_0873E640[];
extern u32 gActorDefeatFrozenStates[];
extern u32 gActorDefeatFrozenStateUpdates[];
extern u32 gActorExplodeDefeatsByEffect[];
extern u16 gUnk_0873E698[];
extern u16 gUnk_0873E69A;
extern u16 gUnk_0873E69C;
extern u32 gUnk_0873E6A0[];
extern u32 gUnk_0873E6D0[];
extern u16 gUnk_0873E700[];
extern u16 gUnk_0873E72E;
extern u16 gUnk_0873E730;
extern u32 gUnk_0873E734[];
extern u32 gUnk_0873E758[];
extern u32 gUnk_0873E77C[];
extern u32 gActorDrownStates[];
extern u32 gActorDrownStateUpdates[];
extern s16 gUnk_0873E7A4[];
extern s16 gUnk_0873E7C4[];
extern s16 gUnk_0873E864[];
extern u32 gActorAttachedStates[];
extern struct Unk0873EAC0 gUnk_0873EAC0[];
extern u16 gUnk_0873EAD8[][4];
extern s16 gUnk_0873EAF0[];
extern s8 gUnk_0873EB30[];
extern s8 gUnk_0873EB38[];
extern s16 gUnk_0873EB40[];
extern s16 gUnk_0873EB60[];
extern s16 gUnk_0873EB80[];
extern u32 gUnk_0873EBA0[];
extern u32 gUnk_0873EC20[];
extern s32 gUnk_0873ECA0[];
extern s32 gUnk_0873ECC0[];
extern u16 gUnk_0873ECD0[];
extern u32 gLandingImpactVariants[];
extern struct ActorDef *const gEnemyDefs[];
extern struct ActorDef *const gMidBossDefs[];
extern struct ActorDef *const gBossDefs[];
extern struct ActorDef *const gChildActorDefs[];
extern struct ActorDef *const gObjectDefs[];
extern struct ActorDef *const gItemDefs[];
extern u32 *gEnemyPaletteVariants[];
extern u32 gUnk_0873F01C[];
extern u32 *gUnk_0873F0C4[];
extern u32 *gMidBossPaletteVariants[];
extern u32 *gUnk_0873F138[];
extern u32 gEnemyTaskTypes[];
extern u32 gMidBossTaskTypes[];
extern u32 gBossTaskTypes[];
extern u32 gObjectTaskTypes[];
extern u32 gItemTaskTypes[];
extern struct ActorDef gAbilityStarDef;
extern struct ActorDef gOneUpDef;
extern struct ActorDef gMaximTomatoDef;
extern struct ActorDef gInvincibleCandyDef;
extern struct ActorDef gEnergyDrinkDef;
extern struct ActorDef gUnk_0873F394;
extern struct ActorDef gWarpStarDef;
extern struct ActorDef gCannonDef;
extern struct ActorDef gCannonFuseDef;
extern struct ActorDef gBigSwitchDef;
extern struct ActorDef gStakeDef;
extern struct ActorDef gUnk_0873F49C;
extern u8 gUnk_0873F5D4[];
extern struct ActorDef gInhalableStarDef;
extern struct ActorDef gUnk_0873F690;
extern struct ActorDef gUnk_0873F6BC;
extern struct ActorDef gUnk_0873F6E8;
extern struct ActorDef gUnk_0873F704;
extern u8 gUnk_0873F7E4[];
extern u8 gUnk_0873F81C[];
extern u32 gUnk_0873F830[];
extern u32 gUnk_0873F844[];
extern u32 gUnk_0873F858[];
extern u32 gUnk_0873F86C[];
extern u8 gUnk_0873F880[];
extern u32 gUnk_0873F894[];
extern u32 gUnk_0873F8B4[];
extern u32 gUnk_0873F8BC[];
extern u32 gUnk_0873F8CC[];
extern u32 gUnk_0873F8DC[];
extern struct ActorHandlers gUnk_0873F8F4[];
extern struct ActorHandlers gActorDrownTerrainHandlers[];
extern struct ActorVt gUnk_0873F92C[];
extern struct ActorVt gUnk_0873F938[];
extern s16 *gPlayerWarpStarRideFrames[];
extern u16 gPlayerTumbleFrames[];
extern u8 gUnk_0873FAE8[];
extern u32 gPlayerWarpStarRideStates[];
extern u32 gPlayerWarpStarRideStateUpdates[];
extern u32 gMetaKnightWarpStarRideStates[];
extern u32 gMetaKnightWarpStarRideStateUpdates[];
extern struct ActorDef gPengyDef;
extern struct ActorDef gBomberDef;
extern struct ActorDef gSparkyDef;
extern struct ActorDef gScarfyDef;
extern struct ActorDef gSwordKnightDef;
extern struct ActorDef gBladeKnightDef;
extern struct ActorDef gBlockStarDef;
extern struct ActorDef gNeedlousDef;
extern struct ActorDef gUFODef;
extern struct ActorDef gParasolDef;
extern struct ActorDef gPengyIceBreathDef;
extern struct ActorDef gUFOLaserDef;
extern struct ActorDef gRockyDef;
extern struct ActorDef gSirKibbleDef;
extern struct ActorDef gCappyDef;
extern struct ActorDef gGordoDef;
extern struct ActorDef gCoolSpookDef;
extern struct ActorDef gKabuDef;
extern struct ActorDef gTwisterDef;
extern struct ActorDef gStarmanDef;
extern struct ActorDef gHotHeadDef;
extern struct ActorDef gPoppyBrosJrDef;
extern struct ActorDef gPoppyBrosJrOnAppleDef;
extern struct ActorDef gPoppyBrosJrOnMaximTomatoDef;
extern struct ActorDef gWheelieDef;
extern struct ActorDef gFlamerDef;
extern struct ActorDef gSirKibbleCutterDef;
extern struct ActorDef gHotHeadFireDef;
extern struct ActorDef gNoddyDef;
extern struct ActorDef gChillyDef;
extern struct ActorDef gBrontoBurtDef;
extern struct ActorDef gTwizzyDef;
extern struct ActorDef gSquishyDef;
extern struct ActorDef gBubblesDef;
extern struct ActorDef gGlunkDef;
extern struct ActorDef gSlippyDef;
extern struct ActorDef gBlipperDef;
extern struct ActorDef gGipDef;
extern struct ActorDef gChillyFreezeDef;
extern struct ActorDef gWaddleDooBeamDef;
extern struct ActorDef gGlunkShotDef;
extern struct ActorDef gGipStarDef;
extern struct ActorDef gBroomHatterDef;
extern struct ActorDef gLaserBallDef;
extern struct ActorDef gCoconutDef;
extern struct ActorDef gConerDef;
extern struct ActorDef gLaserBallLaserDef;
extern struct ActorDef gShotzoCannonballDef;
extern struct ActorDef gBonkersDef;
extern struct ActorDef gPoppyBrosSrDef;
extern struct ActorDef gBugzzyDef;
extern struct ActorDef gBonkersNutDef;
extern struct ActorDef gPoppyBrosSrBombDef;
extern struct ActorDef gBugzzyLadybugDef;
extern struct ActorDef gGrandWheelieDef;
extern struct ActorDef gFireLionDef;
extern struct ActorDef gPhanPhanDef;
extern struct ActorDef gGrandWheelieMiniWheelieDef;
extern struct ActorDef gPhanPhanAppleDef;
extern struct ActorDef gMrFrostyDef;
extern struct ActorDef gMrTickTockDef;
extern struct ActorDef gMrFrostyIceCubeDef;
extern struct ActorDef gMrTickTockRingDef;
extern struct ActorDef gMrTickTockNoteDef;
extern struct ActorDef gAxeKnightAxeDef;
extern struct ActorDef gMaceKnightMaceDef;
extern struct ActorDef gTridentKnightTridentDef;
extern struct ActorDef gJavelinKnightJavelinDef;
extern struct ActorDef gKingDededeDef;
extern struct ActorDef gMrShineAndMrBrightDef;
extern struct ActorDef gKingDededeStarDef;
extern struct ActorDef gKingDededeAirPuffDef;
extern struct ActorDef gUnk_08748B08;
extern struct ActorDef gMetaKnightDef;
extern struct ActorDef gKrackoDef;
extern struct ActorDef gNightmareWizardDef;
extern struct ActorDef gMetaKnightSwordDef;
extern struct ActorDef gKrackoStarmanDef;
extern struct ActorDef gNightmareWizardStarDef;
extern struct ActorDef gPaintRollerDef;
extern struct ActorDef gHeavyMoleDef;
extern struct ActorDef gNightmarePowerOrbDef;
extern struct ActorDef gNightmarePowerOrbStarDef;
extern struct ActorDef gPaintRollerPaintingDef;
extern struct ActorDef gHeavyMoleArmDef;
extern struct ActorDef gHeavyMoleYellowMissileDef;
extern struct ActorDef gHeavyMoleRedMissileDef;
extern struct ActorDef gWhispyWoodsDef;
extern struct ActorDef gWhispyWoodsAppleDef;
extern struct ActorDef gWhispyWoodsAirPuffDef;
extern u32 gUnk_0874C520[];
extern u32 gUnk_0874C9D8[];
extern u32 gUnk_0874CA1C[];
extern u32 gUnk_0874CA78[];
extern u32 gUnk_0874CAD8[];
extern u32 gUnk_0874CB3C[];
extern u32 gUnk_0874CB7C[];
extern u32 gUnk_0874CB90[];
extern u32 gUnk_0874CBC8[];
extern u32 gUnk_0874CBD0[];
extern u32 gUnk_0874CC38[];
extern u32 gUnk_0874CC48[];
extern u32 gUnk_0874CC60[];
extern u32 gUnk_0874CC84[];
extern u32 gUnk_0874CCA4[];
extern u32 gInhalableStarFrames[];
extern u32 gParasolFrames[];
extern u32 gUnk_08752D20[];
extern u32 gWarpStarFrames[];
extern u32 gUnk_08752E48[];


/* Functions (defined in the files named above each group). */

struct InputState;

/* src/actor_62584.c */
void PlayerDance12(void);
void PlayerDance13(void);

/* src/actor_63698.c */
s32 TaskCreatePausedInScreenAttack(u32 type, s32 start);
void ActorInitSlot(u32 i);
void ActorBindDefSlot(u32 i);
void ActorResetHealthSlot(u32 i);
void ActorInitFromDefSlot(u32 i);
void ActorLoadDefSlot(u32 i, struct ActorDef *d);
void ActorSetAttackBoxSlot(u32 i, u32 v);
void ActorSetExtraAttackBoxSlot(u32 i, u32 v);
s32 sub_08063a2c(void);
s32 TaskFindNearestPlayerSlot(u32 i);
s32 TaskFindNearestPlayer(void);
s32 GetDistSq(struct PointPair *p);
s32 GetTaskDistSq(u32 i, u32 j);
s32 TaskGetDistSqTo(u32 i);
s32 TaskGetNearestPlayerDistSq(void);
s32 GetTaskDx(u32 i, u32 j);
s32 TaskGetNearestPlayerDx(void);
s32 GetTaskDy(u32 i, u32 j);
s32 TaskGetDyTo(u32 i);
s32 TaskGetNearestPlayerDy(void);
void TaskGetPosSlot(u32 i);
void TaskGetNearestPlayerPos(void);
s32 TaskGetFacingToward(u32 i);
void TaskFaceToward(u32 i);
s32 TaskGetFacingTowardNearestPlayer(void);
void TaskFaceNearestPlayer(void);
u8 IsPointInRect(struct Rect *r, s16 x, u16 y);
void ActorDestroySlot(s32 i);
void ActorDestroy(void);
void TaskTurnAroundAndReverseX(void);
void TaskTurnAround(void);
void TaskToggleFacingAndReverseX(void);
void ActorStopAnim(void);
s32 ActorStartAnim(struct AnimCmd *p);
s32 ActorStepAnim(void);
s32 ActorTickAnimFacingNearestPlayer(s32 delay);
s32 ActorTickAnim(s32 delay);
u32 sub_080641b0(s16 x0, s16 y0, s16 x1, s16 y1, u16 mag);
u16 GetPointAngle(s16 x0, s16 y0, s16 x1, s16 y1, s32 prec);
u16 GetTaskAngle(u32 i, u32 j, s32 prec);
u16 TaskGetAngleTo(u32 i, s32 prec);
u8 TaskGetYDirBitTo(u32 i);
u8 TaskGetYDirBitToNearestPlayer(void);
u8 TaskGetXDirBitTo(u32 i);
u8 TaskGetXDirBitToNearestPlayer(void);
u8 TaskGetCompassDirTo(u32 i);
u8 TaskGetCompassDirToNearestPlayer(void);
void TaskAccelerateAxisPlus(s32 step, s32 limit, u8 axis);
void TaskAccelerateAxisMinus(s32 step, s32 limit, u8 axis);
void TaskDecelerateAxis(s32 step, u8 axis);
void TaskAccelerateTowardNearestPlayer(s32 step, s32 limit);
void TaskAccelerateInDir(s32 step, s32 limit, u16 dir);
s32 TaskFindNearestPlayerInScreenXBand(u16 lo, u16 hi);
s32 TaskFindNearestPlayerInScreenYBand(u16 lo, u16 hi);
void TaskGetScreenPosSlot(u32 i);
s32 TaskGetNearestPlayerScreenPos(void);
void TaskGetScreenPos(void);
s32 TaskIsNearestPlayerWithinX(s32 range);
void ActorAwardScore(u32 arg, s32 mul);
s8 TaskGetParentFacing(void);
void TaskFaceLikeParent(void);
s32 CreateChildActor(struct ActorSpawn *p);
s32 CreateActorFromDescHere(struct ActorSpawn *p, u8 keepPrio);
s32 CreateActorFromDescAtOffsetFacing(struct ActorSpawn *p, u8 keepPrio);
s32 CreateActorFromDesc(struct ActorSpawn *p, u8 keepPrio);
void TaskStepSpinFrameFacing(void);
s32 CreateChildTask(u32 type, int xArg, int yArg, int prioArg);
s32 CreateChildTaskAtOffsetFacing(u32 type, s16 dx, s16 dy, u8 keepPrio);
s32 CreateChildTaskHere(u32 type, u8 keepPrio);
s32 CreateChildTaskAt(u32 type, s16 xArg, s16 yArg, u8 keepPrio);
s32 CreateItemOrObject(u32 sub, u32 type, int p2Arg, int xArg, int yArg, int prioArg, int altArg);
s32 CreateItemHere(u32 sub, u32 type, u8 p2);
s32 CreateItemAt(u32 sub, u32 type, u8 p2, s16 xArg, s16 yArg);
s32 CreateAbilityStar(u8 p2);
s32 CreateActorByKind(u8 cls, u32 sub, u8 p3, u8 p4, int x, int y, u16 prio);
s32 CreateChildActorOfSameType(u8 p3, u8 p4, u32 x, u32 y, u16 prio);
u8 ActorIsInView(void);
void ActorDrawWorldInView(void);
void ActorDrawWorldInViewOrDestroy(void);
void sub_080652c8(void);
void sub_08065350(void);

/* src/actor_653ec.c */
void ActorDrawStreamedFrameNearViewOrDestroy(void);
void ActorDrawStreamedFrameNearView(void);
void ActorDrawStreamedFrame(void);
void ActorDrawSpriteAndExtra(void);
void ActorDrawWorldInViewOrDestroyWithExtra(void);
void ActorDrawSpriteAndExtraInView(void);
void ActorMove(void);
void TaskMoveRelativeToView(void);
void SetPaletteAnimSource(u32 i, u32 p1, u8 p2);
void ResetBgPaletteBlend(void);
void EndBgPaletteBlend(u32 v);
void StartBgPaletteBlend(u32 a, u32 b);
void AcquirePaletteAnim(u32 p0, s32 idx);
void Task_PaletteAnim(void);
void PaletteAnimVariant0(void);
void PaletteAnimCycle(void);
void PaletteAnimFlashColor(void);
void PaletteAnimVariant3(void);
void PaletteAnimBgBlend(void);
void ActorSelectPaletteVariant(u32 i);
void LoadActorPaletteVariant(u32 slot, u32 sub, u32 level, u32 n, u8 kind, u32 src);
void LoadEnemyPaletteVariant(u32 slot, u32 sub, u32 level);
void sub_08065dd0(u32 slot, u32 i);
void sub_08065dfc(u32 slot);
void ActorPlaySfx(u32 def, u32 which);
void LockAllActorPalettes(void);
void ClearActorPaletteOverrides(void);
u8 TaskHasSameSerial(u32 i);
u32 *sub_0806601c(void);
u16 ActorInitBossGfx(u32 mode);
void sub_08066144(void);
void BossStartHitStun(u32 p0, u32 p1, u32 p2, u16 p3, u8 p4);
void BossEndHitStun(void);
void BossHitStunShake(void);
void BossHitStunLateUpdate(void);
s32 GetLivingActivePlayerHealth(void);
void ActorFlashPalette(void *src, u32 size);
void ActorClearPaletteOverride(void);
void ActorFlashHeaderPalette(struct GfxHeader *h, u32 src, u32 size);
void ActorLoadHeaderPalette(struct GfxHeader *h);
void ActorIntroPoseUntilHpBarFull(struct AnimCmd *p);
void sub_08066544(void);
void ActorResetAttackBox(void);
void sub_08066580(void);
void ActorShowHpBar(void);
u16 ActorGetGfxTileWord(void);
u16 ActorGetGfxTileWordPalOffset(u16 a);
u16 ActorGetTileWordPalOffset(u16 a);
void ActorStartIntroPose(struct AnimCmd *p);
void ActorEndIntroPose(void);
void ActorIntroPoseUntilMidBossFight(struct AnimCmd *p);
void ActorIntroPoseUntilScrollLocked(struct AnimCmd *p);
u32 BossCheckScrollLock(void);
void ActorIntroPoseUpdate(void);
void ArenaDropMaximTomato(void);
void sub_080667c0(u8 a, u16 b);
void EndMidBossFightWithReward(void);
void ActorLoadPalette(void *src, u32 size, u8 force);
void BossDefeatSweep(void);
void sub_08066988(u32 i);
u8 ActorIsInViewMargin(s16 dx, u16 dy);
u8 ActorIsInNearView(void);
u8 ActorIsInFarView(void);
void ActorSetDefaultPalette(u8 mode);
void MidBossResetHealth(void);
void TaskBounceParasolDriftOffWall(void);
void TaskStartParasolDrift(void);
void TaskStepParasolDrift(void);
void ActorDrawWorldInViewOrDestroyWithParasol(void);
void ActorGetParasolOffset(void);
void CreateDroppedParasol(u8 a);
void CreateNextRoomWarpStar(s32 x, s32 y);
void LoadStarRodPieceGfx(void);
void CreateStarRodPiece(u8 p3, s16 x, s16 y);
void CreateRoomStarRodPiece(void);
u8 IsMidBossDroppingIn(void);
u8 CountActivePlayers(void);
void FreezeStage(u16 a);
void ThawStage(void);
void DisablePause(void);
void EnablePause(void);
void InhalableStarInitVariant(void);
void Task_InhalableStar(void);
void InhalableStarUpdate(void);
void InhalableStarState0(void);
void InhalableStarState0Update(void);
void HeldPlayerInit(void);

/* src/actor_673ec.c */
void HeldPlayerEnterState(void);
void HeldPlayerUpdate(void);
void HeldPlayerSwallow(void);
void HeldPlayerSwallowUpdate(void);
void HeldPlayerSpitFlight(void);
void HeldPlayerSpitFlightUpdate(void);
void HeldPlayerSpitBounceOff(void);
void HeldPlayerSpitBounceOffUpdate(void);
void HeldPlayerBackdropHeld(void);
void HeldPlayerBackdropHeldUpdate(void);
void HeldPlayerFollowCaptorPose(void);
void HeldPlayerBackdropBounceOff(void);
void HeldPlayerBackdropBounceOffUpdate(void);
void HeldPlayerState5(void);
void HeldPlayerState5Update(void);
void HeldPlayerState6(void);
void HeldPlayerState6Update(void);
void HeldPlayerThrowHeld(void);
void HeldPlayerThrowHeldUpdate(void);
void HeldPlayerThrowFlightForward(void);
void HeldPlayerThrowFlightForwardUpdate(void);
void HeldPlayerThrowFlightBackward(void);
void HeldPlayerThrowFlightBackwardUpdate(void);
void HeldPlayerThrowBounceOff(void);
void HeldPlayerThrowBounceOffUpdate(void);
s32 HeldPlayerAddAbilityFrameOffset(void);
void HoldPlayer(s32 i, s32 j, u8 c);
void DropHeldPlayer(s32 i);
void HeldPlayerStartSwallow(void);
void HeldPlayerPullTowardCaptor(void);
u32 HeldPlayerIsNearCaptor(void);
void HeldPlayerEnterMouth(void);
void HeldPlayerSwallowAdvanceFrame(void);
void HeldPlayerStartSpitFlight(void);
void HeldPlayerStartSpitBounceOff(void);
void SetHeldPlayerState(s32 i, u8 c);
void sub_08068950(s16 x, s16 y, s16 d);
void HeldPlayerStepTumble(void);
s32 HeldPlayerDamage(s32 a, s32 b);
void PlayerSuspendControl(s32 i, u8 flag);
void PlayerResumeControl(s32 i, u16 b, u8 c, u8 d);
u32 ActorTestColliders(u8 a);
void ActorStoreHit(u8 a);

/* src/actor_692fc.c */
u32 sub_080694e0(void);
u32 ActorCollideTerrainCeilingAndFloor(void);
u32 ActorCollideTerrainWalls(void);
u32 ActorCollideTerrainInCameraBounds(void);
void ActorGetTerrainBox(struct InputState *out);
u32 ActorReactToHitKind(s8 a);
u32 ActorReactToHitOrTerrainDamage(void);
u32 PickupReactToHit(void);
s8 ActorHitKindWithTerrainDamage(void);
void ActorPlayHitSfx(void);
void ActorPlayDefaultHitSfx(void);
void ActorStartHitStun(void);
void ActorEndHitStun(void);
u32 ActorReactToDamage(void);
void ActorHitStunShake(void);
void ActorHitStunBlink(void);
void ActorHitStunLateUpdate(void);
void sub_08069fc8(void);
void ActorFaceHitter(void);
s16 TaskGetHitAngle(void);
void ActorPlayRandomDefeatSfx(void);
void ActorStartDrown(s32 a);
void PickupCollect(void);
u32 ActorReactToDefeat(void);

/* src/actor_6a344.c */
void ActorDie(void);
void ActorDefeatByEffect(void);
void ActorDefeatKnockAway(void);
void ActorDefeatBlinkAndBurst(void);
void ActorDefeatPlain(void);
void ActorDefeatPlainUpdate(void);
void ActorDefeatBurning(void);
void ActorDefeatBurningUpdate(void);
void ActorDefeatShocked(void);
void ActorDefeatShockedUpdate(void);
void ActorDefeatFrozenBlink(void);
void ActorFreezeIntoIceBlock(void);
void sub_0806a6a0(void);
void sub_0806a6e0(void);
void ActorDefeatFrozen(void);
void ActorDefeatFrozenUpdate(void);
void ActorDefeatFrozenEnterState(void);
void ActorDefeatFrozenShake(void);
void ActorDefeatFrozenShakeUpdate(void);
void ActorDefeatFrozenSlide(void);
void ActorDefeatFrozenSlideUpdate(void);
void ActorDefeatFrozenState2(void);
void sub_0806aa0c(void);
void ActorDefeatExplodeByEffect(void);
void ActorDefeatExplode(void);
void ActorExplodeDefeat1(void);
void ActorExplodeDefeat2(void);
void ActorExplodeDefeat3(void);
void ExplosionScreenFlash(void);
void ActorDefeat2(void);
void ActorDefeat2Update(void);
void ActorDefeat3(void);
void ActorDefeat3Update(void);
void ActorDefeat4(void);
void ActorDefeat4Update(void);
void ActorDefeatAbilityStar(void);

/* src/actor_6ad18.c */
void ActorShakeVertically(void);
void sub_0806adb0(void);
void sub_0806ae94(void);
void ActorDefeatMidBoss(void);
void BossDefeatScreenFlash(void);
void BossDefeatFlash(void);
void BossRunDefeatHook(void);
void BossDefeatExplode(void);
s32 BossDefeatStopBgm(void);
void ActorDefeatBoss(void);
void ActorDefeat8(void);
void sub_0806b1a8(void);
void sub_0806b1c4(void);
void sub_0806b1f4(void);
void sub_0806b224(void);
void ActorDefeat9(void);
s32 ActorDrownLand(void);
void ActorDrownInit(void);
void ActorDrownUpdate(void);

/* src/actor_6b2e4.c */
void ActorDrownEnterState(void);
void ActorDrownSink(void);
void ActorDrownSinkUpdate(void);
void ActorDrownState1(void);
void ActorDrownState1Update(void);
void ActorDrownState2(void);
void ActorDrownState2Update(void);
void ActorDefeatPickup(void);
void sub_0806b40c(void);
void ActorAttachedThrowHeldFollowCarrier(void);
void ActorAttachedBackdropHeldFollowCarrier(void);
void ActorAttachedHeldAddPlayerOffset(void);
void ActorAttachedRestorePalette(void);
void ActorAttachedDie(void);
void ActorAttachedDieUnlessInhaling(void);
void sub_0806b95c(void);
void ActorAttachedBindCarrier(void);
void ActorAttachedReloadPalette(void);
void TaskSetPosRelativeToParent(void);
s32 TaskIsParentWithinX(s32 a);
void sub_0806bb34(s32 a);
s32 ActorAttachToHitter(void);
void ActorAttachedPullTowardCarrier(void);
void ActorAttachedPullInStep(void);
void ActorInitCarryOffset(void);
void sub_0806bc9c(void);
void ActorAttachedSwallowStep(void);
void ActorAttachedEnterMouth(void);
void sub_0806be4c(u32 i);
u8 ActorAttachedCheckScreenAttack(void);
void ActorAttachedEnterState(void);
void ActorAttachedRunState(void);
void ActorAttachedSwallow(void);
void ActorAttachedSwallowLateUpdate(void);
void ActorAttachedBackdropHeld(void);
void ActorAttachedBackdropHeldUpdate(void);
void ActorAttachedBackdropHeldLateUpdate(void);
void ActorAttachedBackdropFlight(void);
void ActorAttachedBackdropFlightUpdate(void);

/* src/actor_6c2a4.c */
void ActorAttachedBackdropBounceOff(void);
void ActorAttachedBackdropBounceOffUpdate(void);
void ActorAttachedPullIn(void);
void ActorAttachedPullInLateUpdate(void);
void ActorAttachedThrowHeld(void);
void ActorAttachedThrowHeldUpdate(void);
void ActorAttachedThrowHeldLateUpdate(void);
void ActorAttachedThrowFlight(void);
void ActorAttachedThrowFlightUpdate(void);
void ActorAttachedThrowFlightLateUpdate(void);
void ActorAttachedThrowBounceOff(void);
void ActorAttachedThrowBounceOffUpdate(void);
void Task_ActorSplash(void);
s16 CreateStarFlash(u8 kind, s32 dx, s32 dy);
void Task_StarFlash(void);
void Task_StarFlashOnParent(void);
void StarFlashFollowParent(void);
s16 CreateDustTrail(u8 flag, u16 vx, s32 c, s32 d);
void CreateDustPuff(void);

/* src/actor_6cd40.c */
void Task_DustTrail(void);
void Task_DustPuff(void);
void Task_BackwardDustPuff(void);
void CreateLandingDust(s16 dx, s16 dy);
void sub_0806d08c(s16 a, s16 b, s16 c);
void Task_LandingDust(void);
s32 CreateDustBurst(s16 a, s16 b);

/* src/actor_6d22c.c */
void Task_DustBurst(void);
void DustBurstCheckParent(void);
void CreateBurstEffect(u32 a, s32 b);
void Task_StarScatter(void);
void Task_RayBurst(void);
void Task_SmallBlast(void);
void BurstStickToParent(void);
void Task_StarScatterOnParent(void);
void Task_RayBurstOnParent(void);
void Task_SmallBlastOnParent(void);
void BurstStickToParentUpdate(void);
void PlayRayBurstAnim(void);
void PlayStarScatterAnim(void);
void PlayExplosionAnim(void);
void PlaySmallBlastAnim(void);
void Task_ImpactStar(void);
void CreateStarRing(void);
void Task_RingStar(void);
void RingStarUpdate(void);
void Task_BossScreenFlash(void);
void Task_ExplosionScreenFlash(void);
void CreateCannonSmoke(u32 a, u32 b);
void CannonSmokeInit(void);
void Task_CannonSmoke(void);
void CannonFuseSparkDraw(void);
void Task_CannonFuseSpark(void);
void CannonFuseSparkCheckParent(void);
void Task_TrailFlash(void);
void ActorUpdateAttachedEffect(void);
void ActorAttachEffect(s32 a, s32 b);
void Task_HitFrost(void);

/* src/actor_6e0f0.c */
void HitFrostCheckParent(void);
void Task_HitFlames(void);
void HitFlamesCheckParent(void);
void Task_HitSparks(void);
void HitSparksCheckParent(void);
void Task_WarpStarSparkle(void);
void WarpStarSparkleCheckParent(void);
void Task_AbilityReleaseFlash(void);
void AbilityReleaseFlashCheckParent(void);
s32 CreateDashFlame(s16 x, s16 y);
void Task_DashFlame(void);
void DashFlameCheckParent(void);
s32 CreateDashFireTrail(s16 x, s16 y);
void Task_DashFireTrail(void);
void DashFireTrailCheckParent(void);
s32 CreateLandingImpact(u8 a, s16 x, s16 y);
void Task_LandingImpact(void);
void LandingImpactVariant0(void);
void LandingImpactVariant1(void);
void LandingImpactVariant2(void);
void Task_IceBlock(void);
void IceBlockUpdate(void);
void IceBlockBlink(void);
void PlaySmokeRingAnim(void);
void Task_SmokeRing(void);
void sub_0806ee2c(void);
void PlayerWarpStarRideInit(void);
void PlayerWarpStarRideUpdate(void);
void PlayerWarpStarRideEnterState(void);

/* src/actor_6ef5c.c */
void PlayerWarpStarRideState2(void);
void PlayerWarpStarRideState2Update(void);
void PlayerWarpStarRideState1(void);
void PlayerWarpStarRideState1Update(void);
void PlayerWarpStarRideState3(void);
void PlayerWarpStarRideState3Update(void);
void PlayerWarpStarRideState4(void);
void PlayerWarpStarRideState4Update(void);
void PlayerWarpStarRideState5(void);
void PlayerWarpStarRideState5Update(void);
void PlayerWarpStarRideState6(void);
void PlayerWarpStarRideState6Update(void);
void PlayerWarpStarRideState7(void);

/* src/actor_6ff24.c */
void PlayerWarpStarRideState7Update(void);
void PlayerWarpStarRideDraw(void);
void PlayerSetWarpStarRideFrame(void);
void sub_08070174(void);
void sub_08070208(void);
void sub_0807022c(void);
void sub_08070264(void);
void PlayerStartTumble(void);
void sub_080702d8(void);
void PlayerStepTumble(void);
void sub_080703a8(void);
void sub_0807042c(void);
void TaskCopyParentPixelPos(void);
void PlayerBoardWarpStar(u32 a, s32 b);
void PlayerEndRideLanding(u32 a);
void MetaKnightWarpStarRideInit(void);
void MetaKnightWarpStarRideUpdate(void);
void MetaKnightWarpStarRideEnterState(void);
void MetaKnightWarpStarRideState2(void);
void MetaKnightWarpStarRideState2Update(void);
void MetaKnightWarpStarRideState1(void);
void MetaKnightWarpStarRideState1Update(void);
void MetaKnightWarpStarRideState3(void);
void MetaKnightWarpStarRideState3Update(void);
void MetaKnightWarpStarRideState4(void);
void MetaKnightWarpStarRideState4Update(void);
void MetaKnightWarpStarRideState5(void);
void MetaKnightWarpStarRideState5Update(void);
void MetaKnightWarpStarRideState6(void);
void MetaKnightWarpStarRideState6Update(void);

#endif /* GUARD_ACTOR_H */
