@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc_0802d38c_0802f62c, chunk 1/2: 0x0802F62C-0x080301E8 (thumb_code, 0xBBC bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x0802F62C sub_0802f62c
@   0x0802F684 sub_0802f684
@   0x0802F6C0 sub_0802f6c0
@   0x0802F6F4 sub_0802f6f4
@   0x0802F718 sub_0802f718
@   0x0802F7DC sub_0802f7dc
@   0x0802F84C sub_0802f84c
@   0x0802F8C8 sub_0802f8c8
@   0x0802F93C sub_0802f93c
@   0x0802FA3C sub_0802fa3c
@   0x0802FAA8 sub_0802faa8
@   0x0802FD98 sub_0802fd98
@   0x0802FDF4 sub_0802fdf4
@   0x0802FE64 sub_0802fe64
@   0x0802FEA4 sub_0802fea4
@   0x0802FF70 sub_0802ff70
@   0x0802FFE8 sub_0802ffe8
@   0x08030034 sub_08030034
@   0x08030074 sub_08030074
@   0x080300C0 sub_080300c0
@   0x08030100 sub_08030100
@   0x08030140 sub_08030140
@   0x080301A4 sub_080301a4

	.section .game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc_0802d38c_0802f62c, "ax"
	.global	game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc_0802d38c_0802f62c
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_08018b84_08019eec_0801a3e4_0801a8c8_08021b18_0802b4bc_0802d38c_0802f62c:
	.thumb_func
	.global	sub_0802f62c
sub_0802f62c:
	.thumb
	push	{lr}
	ldr	r2, [pc, #44]	@ 0x0802F65C
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x0802F660
	str	r0, [r1, #0]
	ldr	r0, [pc, #44]	@ 0x0802F664
	str	r0, [r1, #12]
	ldr	r0, [pc, #44]	@ 0x0802F668
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #15
	strb	r0, [r1, #0]
	ldr	r2, [r2, #0]
	adds	r1, r2, #0
	adds	r1, #64
	movs	r0, #136
	lsls	r0, r0, #8
	strh	r0, [r1, #0]
	ldr	r0, [r2, #32]
	cmp	r0, #0
	bne.n	loc_0802f66c	@ 0x0802F66C
	bl	sub_0802f6f4	@ 0x0802F6F4
	b.n	loc_0802f67c	@ 0x0802F67C
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_0802f718+1
	.word	0x08755948
	.global	loc_0802f66c
loc_0802f66c:
	ldr	r0, [r2, #28]
	cmp	r0, #0
	bne.n	loc_0802f678	@ 0x0802F678
	bl	sub_0802f6c0	@ 0x0802F6C0
	b.n	loc_0802f67c	@ 0x0802F67C
	.global	loc_0802f678
loc_0802f678:
	bl	sub_0802f684	@ 0x0802F684
	.global	loc_0802f67c
loc_0802f67c:
	bl	TaskDispatchTrampoline	@ 0x080CFDD4
	pop	{r0}
	bx	r0
	.thumb_func
	.global	sub_0802f684
sub_0802f684:
	.thumb
	push	{r4, lr}
	ldr	r2, [pc, #48]	@ 0x0802F6B8
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #48]	@ 0x0802F6BC
	str	r0, [r1, #52]
	adds	r4, r2, #0
	.global	loc_0802f690
loc_0802f690:
	ldr	r1, [r4, #0]
	movs	r0, #0
	str	r0, [r1, #40]
	ldr	r0, [r1, #24]
	lsls	r0, r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	movs	r0, #1
	str	r0, [r1, #40]
	ldrh	r0, [r1, #60]
	adds	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0802f690	@ 0x0802F690
	movs	r0, r0
	.word	gUnk_03002490
	.word	gUnk_087558DC
	.thumb_func
	.global	sub_0802f6c0
sub_0802f6c0:
	.thumb
	push	{r4, r5, lr}
	ldr	r2, [pc, #40]	@ 0x0802F6EC
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #40]	@ 0x0802F6F0
	str	r0, [r1, #52]
	ldr	r0, [r1, #24]
	lsls	r0, r0, #1
	strh	r0, [r1, #60]
	adds	r4, r2, #0
	movs	r5, #0
	.global	loc_0802f6d4
loc_0802f6d4:
	ldr	r0, [r4, #0]
	str	r5, [r0, #40]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	movs	r0, #1
	str	r0, [r1, #40]
	movs	r0, #2
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0802f6d4	@ 0x0802F6D4
	.word	gUnk_03002490
	.word	gUnk_087558DC
	.thumb_func
	.global	sub_0802f6f4
sub_0802f6f4:
	.thumb
	push	{lr}
	ldr	r0, [pc, #24]	@ 0x0802F710
	ldr	r1, [r0, #0]
	ldr	r0, [pc, #24]	@ 0x0802F714
	str	r0, [r1, #52]
	movs	r0, #0
	str	r0, [r1, #40]
	ldr	r0, [r1, #24]
	lsls	r0, r0, #1
	strh	r0, [r1, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	0x087558C4
	.thumb_func
	.global	sub_0802f718
sub_0802f718:
	.thumb
	push	{r4, r5, r6, lr}
	sub	sp, #8
	ldr	r5, [pc, #132]	@ 0x0802F7A4
	ldr	r0, [r5, #0]
	mov	ip, r0
	movs	r2, #60
	ldrsh	r1, [r0, r2]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_0802f760	@ 0x0802F760
	mov	r3, ip
	ldr	r2, [r3, #56]
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	movs	r4, #60
	ldrsh	r1, [r3, r4]
	lsls	r1, r1, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r4, ip
	adds	r4, #72
	movs	r6, #0
	ldrsh	r4, [r4, r6]
	str	r4, [sp, #0]
	mov	r4, ip
	adds	r4, #74
	movs	r6, #0
	ldrsh	r4, [r4, r6]
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802f760
loc_0802f760:
	ldr	r5, [r5, #0]
	mov	ip, r5
	ldr	r2, [r5, #52]
	ldr	r0, [pc, #64]	@ 0x0802F7A8
	mov	r1, ip
	adds	r1, #118
	ldrh	r1, [r1, #0]
	lsls	r1, r1, #3
	adds	r1, r1, r0
	ldrb	r0, [r1, #1]
	cmp	r0, #0
	beq.n	loc_0802f7ac	@ 0x0802F7AC
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	mov	r3, ip
	ldr	r1, [r3, #40]
	lsls	r1, r1, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	ldr	r4, [r5, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r5, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	b.n	loc_0802f7d2	@ 0x0802F7D2
	.word	gUnk_03002490
	.word	0x02004B90
	.global	loc_0802f7ac
loc_0802f7ac:
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	ldr	r1, [r2, #8]
	mov	r6, ip
	ldrh	r2, [r6, #62]
	mov	r3, ip
	adds	r3, #64
	ldrh	r3, [r3, #0]
	ldr	r4, [r6, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r6, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802f7d2
loc_0802f7d2:
	add	sp, #8
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.thumb_func
	.global	sub_0802f7dc
sub_0802f7dc:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	mov	r8, r3
	movs	r0, #230
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r3, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r3, r0
	beq.n	loc_0802f83a	@ 0x0802F83A
	lsls	r0, r3, #3
	adds	r0, r0, r3
	lsls	r0, r0, #4
	ldr	r1, [pc, #64]	@ 0x0802F848
	adds	r1, r0, r1
	adds	r0, r1, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #16
	str	r0, [r1, #76]
	adds	r0, r5, #0
	subs	r0, #28
	adds	r2, r1, #0
	adds	r2, #74
	strh	r0, [r2, #0]
	movs	r7, #0
	ldrsh	r0, [r2, r7]
	lsls	r0, r0, #16
	str	r0, [r1, #80]
	str	r4, [r1, #84]
	str	r5, [r1, #88]
	str	r6, [r1, #24]
	movs	r0, #1
	str	r0, [r1, #32]
	adds	r0, r1, #0
	adds	r0, #118
	mov	r1, r8
	strh	r1, [r0, #0]
	.global	loc_0802f83a
loc_0802f83a:
	adds	r0, r3, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002790
	.thumb_func
	.global	sub_0802f84c
sub_0802f84c:
	.thumb
	push	{r4, lr}
	ldr	r3, [pc, #100]	@ 0x0802F8B4
	ldr	r1, [r3, #0]
	ldr	r0, [pc, #100]	@ 0x0802F8B8
	str	r0, [r1, #0]
	ldr	r0, [pc, #100]	@ 0x0802F8BC
	str	r0, [r1, #12]
	ldr	r0, [pc, #100]	@ 0x0802F8C0
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r4, #0
	movs	r0, #14
	strb	r0, [r1, #0]
	ldr	r2, [r3, #0]
	adds	r1, r2, #0
	adds	r1, #64
	movs	r0, #136
	lsls	r0, r0, #8
	strh	r0, [r1, #0]
	movs	r0, #2
	strb	r0, [r2, #18]
	ldr	r0, [r3, #0]
	ldr	r1, [pc, #72]	@ 0x0802F8C4
	str	r1, [r0, #4]
	strh	r4, [r0, #60]
	str	r4, [r0, #52]
	adds	r4, r3, #0
	.global	loc_0802f882
loc_0802f882:
	ldr	r1, [r4, #0]
	movs	r0, #0
	str	r0, [r1, #52]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	movs	r0, #1
	str	r0, [r1, #52]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	movs	r0, #2
	str	r0, [r1, #52]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r4, #0]
	movs	r0, #3
	str	r0, [r1, #52]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0802f882	@ 0x0802F882
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_0802f93c+1
	.word	0x08755978
	.word	sub_0802f8c8+1
	.thumb_func
	.global	sub_0802f8c8
sub_0802f8c8:
	.thumb
	push	{r4, r5, r6, lr}
	ldr	r5, [pc, #92]	@ 0x0802F928
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #52]
	movs	r6, #1
	negs	r6, r6
	cmp	r0, r6
	beq.n	loc_0802f920	@ 0x0802F920
	lsls	r1, r0, #3
	adds	r1, r1, r0
	lsls	r1, r1, #5
	ldr	r4, [pc, #76]	@ 0x0802F92C
	adds	r1, r1, r4
	ldr	r2, [pc, #76]	@ 0x0802F930
	movs	r0, #4
	movs	r3, #96
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #52]
	lsls	r1, r0, #3
	adds	r1, r1, r0
	adds	r1, #3
	lsls	r1, r1, #5
	adds	r1, r1, r4
	ldr	r2, [pc, #56]	@ 0x0802F934
	movs	r0, #4
	movs	r3, #96
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [r5, #0]
	ldr	r0, [r0, #52]
	lsls	r1, r0, #3
	adds	r1, r1, r0
	adds	r1, #6
	lsls	r1, r1, #5
	adds	r1, r1, r4
	ldr	r2, [pc, #36]	@ 0x0802F938
	movs	r0, #4
	movs	r3, #96
	bl	sub_080017e4	@ 0x080017E4
	ldr	r0, [r5, #0]
	str	r6, [r0, #52]
	.global	loc_0802f920
loc_0802f920:
	pop	{r4, r5, r6}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x085A2DF8
	.word	0x06013980
	.word	0x06013D80
	.word	0x06014180
	.thumb_func
	.global	sub_0802f93c
sub_0802f93c:
	.thumb
	push	{r4, r5, lr}
	sub	sp, #8
	ldr	r0, [pc, #28]	@ 0x0802F960
	ldr	r0, [r0, #0]
	mov	ip, r0
	ldr	r0, [r0, #24]
	cmp	r0, #0
	beq.n	loc_0802f968	@ 0x0802F968
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	adds	r0, #1
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	ldr	r1, [pc, #8]	@ 0x0802F964
	ldr	r1, [r1, #4]
	b.n	loc_0802f98a	@ 0x0802F98A
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x087558D0
	.global	loc_0802f968
loc_0802f968:
	ldr	r0, [pc, #64]	@ 0x0802F9AC
	mov	r1, ip
	adds	r1, #118
	ldrh	r1, [r1, #0]
	lsls	r1, r1, #3
	adds	r1, r1, r0
	ldrb	r0, [r1, #1]
	cmp	r0, #0
	beq.n	loc_0802f9b4	@ 0x0802F9B4
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	adds	r0, #1
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	ldr	r1, [pc, #40]	@ 0x0802F9B0
	ldr	r1, [r1, #0]
	.global	loc_0802f98a
loc_0802f98a:
	mov	r3, ip
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r5, ip
	ldr	r4, [r5, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r5, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	b.n	loc_0802f9e2	@ 0x0802F9E2
	movs	r0, r0
	.word	0x02004B90
	.word	0x087558D0
	.global	loc_0802f9b4
loc_0802f9b4:
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	adds	r0, #1
	lsls	r0, r0, #24
	lsrs	r0, r0, #24
	ldr	r1, [pc, #108]	@ 0x0802FA30
	ldr	r1, [r1, #8]
	mov	r3, ip
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r5, ip
	ldr	r4, [r5, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r5, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802f9e2
loc_0802f9e2:
	ldr	r0, [pc, #80]	@ 0x0802FA34
	ldr	r0, [r0, #0]
	mov	ip, r0
	movs	r2, #60
	ldrsh	r1, [r0, r2]
	.word	0x42402001
	cmp	r1, r0
	beq.n	loc_0802fa28	@ 0x0802FA28
	mov	r3, ip
	ldr	r2, [r3, #56]
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	movs	r4, #60
	ldrsh	r1, [r3, r4]
	lsls	r1, r1, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	ldr	r2, [pc, #44]	@ 0x0802FA38
	ldrh	r2, [r2, #0]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r4, ip
	adds	r4, #72
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #0]
	mov	r4, ip
	adds	r4, #74
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802fa28
loc_0802fa28:
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	0x087558D0
	.word	gUnk_03002490
	.word	0x020055D4
	.thumb_func
	.global	sub_0802fa3c
sub_0802fa3c:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r5, r0, #0
	adds	r6, r1, #0
	adds	r7, r2, #0
	mov	r8, r3
	movs	r0, #231
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r4, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r4, r0
	beq.n	loc_0802fa94	@ 0x0802FA94
	lsls	r0, r4, #3
	adds	r0, r0, r4
	lsls	r0, r0, #4
	ldr	r1, [pc, #56]	@ 0x0802FAA0
	adds	r3, r0, r1
	adds	r0, r3, #0
	adds	r0, #72
	movs	r1, #0
	strh	r5, [r0, #0]
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #16
	str	r0, [r3, #76]
	adds	r0, r6, #0
	subs	r0, #28
	adds	r2, r3, #0
	adds	r2, #74
	strh	r0, [r2, #0]
	movs	r5, #0
	ldrsh	r0, [r2, r5]
	lsls	r0, r0, #16
	str	r0, [r3, #80]
	str	r7, [r3, #36]
	mov	r0, r8
	str	r0, [r3, #32]
	ldr	r0, [pc, #16]	@ 0x0802FAA4
	strb	r1, [r0, #0]
	.global	loc_0802fa94
loc_0802fa94:
	adds	r0, r4, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.word	gUnk_03002790
	.word	0x02007FC4
	.thumb_func
	.global	sub_0802faa8
sub_0802faa8:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, sl
	mov	r6, r9
	mov	r5, r8
	push	{r5, r6, r7}
	ldr	r3, [pc, #708]	@ 0x0802FD78
	ldr	r1, [r3, #0]
	ldr	r0, [pc, #708]	@ 0x0802FD7C
	str	r0, [r1, #0]
	ldr	r0, [pc, #708]	@ 0x0802FD80
	str	r0, [r1, #12]
	ldr	r0, [pc, #708]	@ 0x0802FD84
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #14
	strb	r0, [r1, #0]
	ldr	r2, [r3, #0]
	adds	r1, r2, #0
	adds	r1, #64
	movs	r0, #136
	lsls	r0, r0, #8
	strh	r0, [r1, #0]
	movs	r0, #1
	strb	r0, [r2, #18]
	ldr	r1, [r3, #0]
	ldr	r0, [pc, #684]	@ 0x0802FD88
	strh	r0, [r1, #60]
	ldr	r0, [r1, #32]
	cmp	r0, #0
	beq.n	loc_0802fafa	@ 0x0802FAFA
	ldr	r1, [pc, #676]	@ 0x0802FD8C
	ldrb	r0, [r1, #0]
	cmp	r0, #0
	bne.n	loc_0802fafa	@ 0x0802FAFA
	adds	r4, r1, #0
	.global	loc_0802faee
loc_0802faee:
	movs	r0, #1
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldrb	r0, [r4, #0]
	cmp	r0, #0
	beq.n	loc_0802faee	@ 0x0802FAEE
	.global	loc_0802fafa
loc_0802fafa:
	ldr	r7, [pc, #636]	@ 0x0802FD78
	ldr	r1, [r7, #0]
	ldr	r0, [r1, #36]
	cmp	r0, #0
	beq.n	loc_0802fbd6	@ 0x0802FBD6
	movs	r0, #3
	mov	r8, r0
	mov	r0, r8
	strb	r0, [r1, #18]
	ldr	r1, [r7, #0]
	ldr	r0, [pc, #640]	@ 0x0802FD90
	str	r0, [r1, #84]
	movs	r0, #128
	lsls	r0, r0, #9
	str	r0, [r1, #88]
	subs	r0, #1
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r4, #4
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r7, #0]
	ldr	r0, [pc, #608]	@ 0x0802FD94
	mov	sl, r0
	str	r0, [r1, #84]
	movs	r0, #128
	lsls	r0, r0, #8
	mov	r9, r0
	str	r0, [r1, #88]
	movs	r0, #5
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r7, #0]
	movs	r0, #6
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #0
	str	r1, [r0, #84]
	str	r1, [r0, #88]
	movs	r1, #7
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r4, #1
	strb	r4, [r0, #18]
	ldr	r0, [r7, #0]
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r5, #2
	strh	r5, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, r8
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, r9
	str	r1, [r0, #84]
	mov	r1, sl
	str	r1, [r0, #88]
	movs	r1, #0
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #128
	lsls	r1, r1, #9
	str	r1, [r0, #84]
	ldr	r1, [pc, #464]	@ 0x0802FD90
	str	r1, [r0, #88]
	strh	r5, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, r8
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	.global	loc_0802fbd6
loc_0802fbd6:
	movs	r6, #0
	.global	loc_0802fbd8
loc_0802fbd8:
	ldr	r0, [r7, #0]
	movs	r1, #128
	lsls	r1, r1, #9
	str	r1, [r0, #84]
	ldr	r1, [pc, #428]	@ 0x0802FD90
	str	r1, [r0, #88]
	strh	r6, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #1
	.word	0x20048781
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #128
	lsls	r1, r1, #8
	str	r1, [r0, #84]
	ldr	r1, [pc, #400]	@ 0x0802FD94
	str	r1, [r0, #88]
	movs	r1, #2
	mov	r9, r1
	mov	r1, r9
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r4, #3
	movs	r1, #3
	mov	sl, r1
	mov	r1, sl
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	str	r6, [r0, #84]
	str	r6, [r0, #88]
	strh	r6, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #1
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, r9
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	strb	r4, [r0, #18]
	ldr	r0, [r7, #0]
	movs	r5, #7
	strh	r5, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r4, #4
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	ldr	r1, [pc, #296]	@ 0x0802FD94
	str	r1, [r0, #84]
	movs	r1, #128
	lsls	r1, r1, #8
	str	r1, [r0, #88]
	movs	r1, #5
	mov	r8, r1
	mov	r1, r8
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #6
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	ldr	r1, [pc, #256]	@ 0x0802FD90
	str	r1, [r0, #84]
	movs	r1, #128
	lsls	r1, r1, #9
	str	r1, [r0, #88]
	strh	r5, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r7, #0]
	ldr	r0, [pc, #228]	@ 0x0802FD88
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r1, [r7, #0]
	ldr	r0, [pc, #224]	@ 0x0802FD90
	str	r0, [r1, #84]
	movs	r0, #128
	lsls	r0, r0, #9
	str	r0, [r1, #88]
	movs	r0, #1
	negs	r0, r0
	strh	r0, [r1, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	ldr	r1, [pc, #192]	@ 0x0802FD94
	str	r1, [r0, #84]
	movs	r1, #128
	lsls	r1, r1, #8
	str	r1, [r0, #88]
	mov	r1, r8
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #6
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	str	r6, [r0, #84]
	str	r6, [r0, #88]
	strh	r5, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	strh	r4, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #1
	strb	r1, [r0, #18]
	ldr	r0, [r7, #0]
	movs	r1, #1
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, r9
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, sl
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #128
	lsls	r1, r1, #8
	str	r1, [r0, #84]
	ldr	r1, [pc, #88]	@ 0x0802FD94
	str	r1, [r0, #88]
	strh	r6, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #1
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	movs	r1, #128
	lsls	r1, r1, #9
	str	r1, [r0, #84]
	ldr	r1, [pc, #52]	@ 0x0802FD90
	str	r1, [r0, #88]
	mov	r1, r9
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	ldr	r0, [r7, #0]
	mov	r1, sl
	strh	r1, [r0, #60]
	movs	r0, #4
	bl	TaskYieldTrampoline	@ 0x080CFDCC
	b.n	loc_0802fbd8	@ 0x0802FBD8
	movs	r0, r0
	.word	gUnk_03002490
	.word	sub_080059d8+1
	.word	sub_0802fd98+1
	.word	0x0875597C
	.word	0x0000FFFF
	.word	0x02007FC4
	.word	0xFFFF0000
	.word	0xFFFF8000
	.thumb_func
	.global	sub_0802fd98
sub_0802fd98:
	.thumb
	.short	0xB530
	sub	sp, #8
	ldr	r0, [pc, #76]	@ 0x0802FDEC
	ldr	r0, [r0, #0]
	mov	ip, r0
	movs	r2, #60
	ldrsh	r1, [r0, r2]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_0802fde2	@ 0x0802FDE2
	mov	r3, ip
	ldr	r2, [r3, #56]
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	movs	r4, #60
	ldrsh	r1, [r3, r4]
	lsls	r1, r1, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	ldr	r2, [pc, #44]	@ 0x0802FDF0
	ldrh	r2, [r2, #0]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r4, ip
	adds	r4, #72
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #0]
	mov	r4, ip
	adds	r4, #74
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802fde2
loc_0802fde2:
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	0x020055D4
	.thumb_func
	.global	sub_0802fdf4
sub_0802fdf4:
	.thumb
	push	{r4, r5, r6, r7, lr}
	mov	r7, r8
	push	{r7}
	adds	r4, r0, #0
	adds	r5, r1, #0
	adds	r6, r2, #0
	mov	r8, r3
	movs	r0, #232
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r3, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r3, r0
	beq.n	loc_0802fe52	@ 0x0802FE52
	lsls	r0, r3, #3
	adds	r0, r0, r3
	lsls	r0, r0, #4
	ldr	r1, [pc, #64]	@ 0x0802FE60
	adds	r1, r0, r1
	adds	r0, r1, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	movs	r2, #0
	ldrsh	r0, [r0, r2]
	lsls	r0, r0, #16
	str	r0, [r1, #76]
	adds	r0, r5, #0
	subs	r0, #28
	adds	r2, r1, #0
	adds	r2, #74
	strh	r0, [r2, #0]
	movs	r7, #0
	ldrsh	r0, [r2, r7]
	lsls	r0, r0, #16
	str	r0, [r1, #80]
	str	r4, [r1, #84]
	str	r5, [r1, #88]
	str	r6, [r1, #24]
	movs	r0, #1
	str	r0, [r1, #32]
	adds	r0, r1, #0
	adds	r0, #118
	mov	r1, r8
	strh	r1, [r0, #0]
	.global	loc_0802fe52
loc_0802fe52:
	adds	r0, r3, #0
	pop	{r3}
	mov	r8, r3
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002790
	.thumb_func
	.global	sub_0802fe64
sub_0802fe64:
	.thumb
	push	{lr}
	ldr	r2, [pc, #44]	@ 0x0802FE94
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x0802FE98
	str	r0, [r1, #0]
	ldr	r0, [pc, #44]	@ 0x0802FE9C
	str	r0, [r1, #12]
	ldr	r0, [pc, #44]	@ 0x0802FEA0
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #15
	strb	r0, [r1, #0]
	ldr	r1, [r2, #0]
	adds	r2, r1, #0
	adds	r2, #64
	movs	r0, #136
	lsls	r0, r0, #8
	strh	r0, [r2, #0]
	ldr	r0, [r1, #24]
	strh	r0, [r1, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_0802fea4+1
	.word	0x0875599C
	.thumb_func
	.global	sub_0802fea4
sub_0802fea4:
	.thumb
	push	{r4, r5, lr}
	sub	sp, #8
	ldr	r1, [pc, #60]	@ 0x0802FEE8
	ldr	r0, [pc, #64]	@ 0x0802FEEC
	ldr	r0, [r0, #0]
	mov	ip, r0
	adds	r0, #118
	ldrh	r0, [r0, #0]
	lsls	r0, r0, #3
	adds	r0, r0, r1
	ldrb	r0, [r0, #1]
	cmp	r0, #0
	beq.n	loc_0802fef4	@ 0x0802FEF4
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	ldr	r1, [pc, #40]	@ 0x0802FEF0
	ldr	r1, [r1, #0]
	mov	r3, ip
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r5, ip
	ldr	r4, [r5, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r5, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	b.n	loc_0802ff1c	@ 0x0802FF1C
	.word	0x02004B90
	.word	gUnk_03002490
	.word	0x087558D0
	.global	loc_0802fef4
loc_0802fef4:
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	ldr	r1, [pc, #108]	@ 0x0802FF68
	ldr	r1, [r1, #8]
	mov	r3, ip
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r5, ip
	ldr	r4, [r5, #84]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #0]
	ldr	r4, [r5, #88]
	lsls	r4, r4, #16
	asrs	r4, r4, #16
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802ff1c
loc_0802ff1c:
	ldr	r0, [pc, #76]	@ 0x0802FF6C
	ldr	r0, [r0, #0]
	mov	ip, r0
	movs	r2, #60
	ldrsh	r1, [r0, r2]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_0802ff60	@ 0x0802FF60
	mov	r3, ip
	ldr	r2, [r3, #56]
	mov	r0, ip
	adds	r0, #66
	ldrb	r0, [r0, #0]
	movs	r4, #60
	ldrsh	r1, [r3, r4]
	lsls	r1, r1, #2
	adds	r1, r1, r2
	ldr	r1, [r1, #0]
	ldrh	r2, [r3, #62]
	adds	r3, #64
	ldrh	r3, [r3, #0]
	mov	r4, ip
	adds	r4, #72
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #0]
	mov	r4, ip
	adds	r4, #74
	movs	r5, #0
	ldrsh	r4, [r4, r5]
	str	r4, [sp, #4]
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802ff60
loc_0802ff60:
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	0x087558D0
	.word	gUnk_03002490
	.thumb_func
	.global	sub_0802ff70
sub_0802ff70:
	.thumb
	push	{r4, r5, lr}
	sub	sp, #8
	ldr	r4, [pc, #104]	@ 0x0802FFE0
	ldr	r0, [r4, #0]
	mov	ip, r0
	movs	r2, #60
	ldrsh	r1, [r0, r2]
	movs	r0, #1
	negs	r0, r0
	cmp	r1, r0
	beq.n	loc_0802ffb4	@ 0x0802FFB4
	mov	r3, ip
	ldr	r1, [r3, #56]
	movs	r5, #60
	ldrsh	r0, [r3, r5]
	lsls	r0, r0, #2
	adds	r0, r0, r1
	ldr	r1, [r0, #0]
	ldrh	r2, [r3, #62]
	mov	r0, ip
	adds	r0, #64
	ldrh	r3, [r0, #0]
	adds	r0, #8
	movs	r5, #0
	ldrsh	r0, [r0, r5]
	str	r0, [sp, #0]
	mov	r0, ip
	adds	r0, #74
	movs	r5, #0
	ldrsh	r0, [r0, r5]
	str	r0, [sp, #4]
	movs	r0, #15
	bl	sub_080306b4	@ 0x080306B4
	.global	loc_0802ffb4
loc_0802ffb4:
	ldr	r0, [pc, #44]	@ 0x0802FFE4
	ldr	r1, [r0, #4]
	ldr	r4, [r4, #0]
	ldrh	r2, [r4, #62]
	adds	r0, r4, #0
	adds	r0, #64
	ldrh	r3, [r0, #0]
	ldr	r0, [r4, #84]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [sp, #0]
	ldr	r0, [r4, #88]
	lsls	r0, r0, #16
	asrs	r0, r0, #16
	str	r0, [sp, #4]
	movs	r0, #15
	bl	sub_080306b4	@ 0x080306B4
	add	sp, #8
	pop	{r4, r5}
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	0x087558D0
	.thumb_func
	.global	sub_0802ffe8
sub_0802ffe8:
	.thumb
	push	{r4, r5, r6, lr}
	adds	r6, r0, #0
	adds	r4, r1, #0
	adds	r5, r2, #0
	movs	r0, #233
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r2, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r2, r0
	beq.n	loc_08030026	@ 0x08030026
	lsls	r0, r2, #3
	adds	r0, r0, r2
	lsls	r0, r0, #4
	ldr	r1, [pc, #36]	@ 0x08030030
	adds	r3, r0, r1
	adds	r0, r3, #0
	adds	r0, #72
	strh	r4, [r0, #0]
	adds	r1, r5, #0
	subs	r1, #28
	adds	r0, #2
	strh	r1, [r0, #0]
	lsls	r0, r4, #16
	str	r0, [r3, #76]
	lsls	r1, r1, #16
	str	r1, [r3, #80]
	str	r6, [r3, #24]
	.global	loc_08030026
loc_08030026:
	adds	r0, r2, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002790
	.thumb_func
	.global	sub_08030034
sub_08030034:
	.thumb
	push	{lr}
	ldr	r2, [pc, #44]	@ 0x08030064
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x08030068
	str	r0, [r1, #0]
	ldr	r0, [pc, #44]	@ 0x0803006C
	str	r0, [r1, #12]
	ldr	r0, [pc, #44]	@ 0x08030070
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #15
	strb	r0, [r1, #0]
	ldr	r1, [r2, #0]
	adds	r2, r1, #0
	adds	r2, #64
	movs	r0, #216
	lsls	r0, r0, #8
	strh	r0, [r2, #0]
	ldr	r0, [r1, #24]
	strh	r0, [r1, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_08005d9c+1
	.word	0x087559A4
	.thumb_func
	.global	sub_08030074
sub_08030074:
	.thumb
	push	{r4, lr}
	adds	r4, r0, #0
	movs	r0, #234
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r3, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r3, r0
	beq.n	loc_080300b4	@ 0x080300B4
	lsls	r0, r3, #3
	adds	r0, r0, r3
	lsls	r0, r0, #4
	ldr	r1, [pc, #40]	@ 0x080300BC
	adds	r2, r0, r1
	adds	r1, r2, #0
	adds	r1, #72
	movs	r0, #128
	strh	r0, [r1, #0]
	adds	r1, #2
	movs	r0, #210
	lsls	r0, r0, #1
	strh	r0, [r1, #0]
	movs	r0, #128
	lsls	r0, r0, #16
	str	r0, [r2, #76]
	movs	r0, #210
	lsls	r0, r0, #17
	str	r0, [r2, #80]
	str	r4, [r2, #24]
	.global	loc_080300b4
loc_080300b4:
	adds	r0, r3, #0
	pop	{r4}
	pop	{r1}
	bx	r1
	.word	gUnk_03002790
	.thumb_func
	.global	sub_080300c0
sub_080300c0:
	.thumb
	push	{lr}
	ldr	r2, [pc, #44]	@ 0x080300F0
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x080300F4
	str	r0, [r1, #0]
	ldr	r0, [pc, #44]	@ 0x080300F8
	str	r0, [r1, #12]
	ldr	r0, [pc, #44]	@ 0x080300FC
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #15
	strb	r0, [r1, #0]
	ldr	r1, [r2, #0]
	adds	r2, r1, #0
	adds	r2, #64
	movs	r0, #216
	lsls	r0, r0, #8
	strh	r0, [r2, #0]
	ldr	r0, [r1, #24]
	strh	r0, [r1, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r0}
	bx	r0
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_08005d9c+1
	.word	0x087559C0
	.thumb_func
	.global	sub_08030100
sub_08030100:
	.thumb
	push	{r4, r5, r6, r7, lr}
	adds	r1, r0, #0
	lsls	r1, r1, #24
	lsrs	r6, r1, #24
	cmp	r6, #5
	bhi.n	loc_08030136	@ 0x08030136
	adds	r0, r6, #0
	bl	sub_08008f10	@ 0x08008F10
	movs	r5, #0
	lsls	r2, r6, #2
	ldr	r1, [pc, #36]	@ 0x0803013C
	movs	r7, #1
	negs	r7, r7
	adds	r4, r2, r1
	.global	loc_0803011e
loc_0803011e:
	movs	r2, #0
	ldrsh	r1, [r4, r2]
	cmp	r1, r7
	beq.n	loc_0803012e	@ 0x0803012E
	adds	r0, r6, #0
	adds	r1, r5, #0
	bl	sub_08030140	@ 0x08030140
	.global	loc_0803012e
loc_0803012e:
	adds	r4, #2
	adds	r5, #1
	cmp	r5, #1
	ble.n	loc_0803011e	@ 0x0803011E
	.global	loc_08030136
loc_08030136:
	pop	{r4, r5, r6, r7}
	pop	{r1}
	bx	r1
	.word	0x087328C0
	.thumb_func
	.global	sub_08030140
sub_08030140:
	.thumb
	push	{r4, r5, r6, lr}
	adds	r6, r1, #0
	lsls	r0, r0, #24
	lsrs	r5, r0, #24
	movs	r0, #235
	movs	r1, #32
	movs	r2, #63
	bl	sub_08005904	@ 0x08005904
	adds	r4, r0, #0
	movs	r0, #1
	negs	r0, r0
	cmp	r4, r0
	beq.n	loc_08030192	@ 0x08030192
	lsls	r0, r4, #3
	adds	r0, r0, r4
	lsls	r0, r0, #4
	ldr	r1, [pc, #56]	@ 0x0803019C
	adds	r3, r0, r1
	ldr	r2, [pc, #56]	@ 0x080301A0
	.global	loc_08030168
loc_08030168:
	lsls	r0, r6, #1
	lsls	r1, r5, #2
	adds	r0, r0, r1
	adds	r0, r0, r2
	ldrh	r0, [r0, #0]
	adds	r1, r3, #0
	adds	r1, #72
	strh	r0, [r1, #0]
	adds	r2, r3, #0
	adds	r2, #74
	movs	r0, #96
	strh	r0, [r2, #0]
	movs	r5, #0
	ldrsh	r0, [r1, r5]
	lsls	r0, r0, #16
	str	r0, [r3, #76]
	movs	r1, #0
	ldrsh	r0, [r2, r1]
	lsls	r0, r0, #16
	str	r0, [r3, #80]
	str	r6, [r3, #24]
	.global	loc_08030192
loc_08030192:
	adds	r0, r4, #0
	pop	{r4, r5, r6}
	pop	{r1}
	bx	r1
	movs	r0, r0
	.word	gUnk_03002790
	.word	0x087328C0
	.thumb_func
	.global	sub_080301a4
sub_080301a4:
	.thumb
	push	{lr}
	ldr	r2, [pc, #44]	@ 0x080301D4
	ldr	r1, [r2, #0]
	ldr	r0, [pc, #44]	@ 0x080301D8
	str	r0, [r1, #0]
	ldr	r0, [pc, #44]	@ 0x080301DC
	str	r0, [r1, #12]
	ldr	r0, [pc, #44]	@ 0x080301E0
	str	r0, [r1, #56]
	adds	r1, #66
	movs	r0, #15
	strb	r0, [r1, #0]
	ldr	r1, [r2, #0]
	adds	r2, r1, #0
	adds	r2, #64
	ldr	r0, [pc, #32]	@ 0x080301E4
	strh	r0, [r2, #0]
	ldr	r0, [r1, #24]
	strh	r0, [r1, #60]
	bl	sub_08006138	@ 0x08006138
	pop	{r0}
	bx	r0
	movs	r0, r0
	.word	gUnk_03002490
	.word	sub_08005a74+1
	.word	sub_08005d9c+1
	.word	0x087559DC
	.word	0x0000D3C0
