#!/usr/bin/env python3
"""The final audit (issue #37): what the matching source still holds that is
not plain, named C, each item listed with its reason.

`make audit` runs it; it needs no baserom and no build (it reads the
committed tree only), so CI runs it on every push.  The checks:

  1. `.incbin`: only `baserom.gba` slices in `data/*.s` (structure-only data,
     docs/data.md) and the Nintendo logo in `asm/rom_header.s`; none in the
     rest of `asm/`, in `src/` or in `include/`.
  2. Raw numeric directives in `asm/` (`.byte`, `.short`/`.hword`/`.2byte`,
     `.inst`, and `.word`/`.4byte`/`.long` with a number operand): each is
     an instruction or a symbol, or it carries a same-line `@ raw: <reason>`
     comment (for generated files, tools/split.py emits it).
  3. The sanctioned asm: every file in `asm/` carries a `@ Stays asm:`
     header comment in its first lines, and the enumerated list in
     docs/audit.md section 2 names exactly the files in `asm/`; its
     "excluded" rows equal `tools/calcrom.pl`'s `%decomp_excluded_asm`.
  4. Raw addresses in `src/` and the game headers `include/*.h`: no ROM
     (0x08-0x0D), SRAM (0x0E), EWRAM (0x02), IWRAM (0x03), I/O (0x04),
     palette (0x05), VRAM (0x06) or OAM (0x07) address as a bare number.
     Allowed: a comment containing `raw:` on the same line or the line
     above, and the last argument of CpuSet/CpuFastSet (a control word,
     not an address).  `include/gba/` defines the region macros and is
     exempt.
  5. Code exceptions: every `register ... asm("rN")` pin, `asm(...)`
     statement, `BLOCK_CROSS_JUMP` and zero-code `while (0)` in `src/` is a
     row of docs/audit.md section 3 (file:line or file:first-last, the
     enclosing function, a reason), and every row there still points at
     such a site (or, for kind `stand-in`, at a line of that function).
  6. The placeholder census: `sub_*` functions, `gUnk_*` RAM, I/O and ROM
     symbols, `unk*` struct fields and `loc_*` labels, by kind, category and
     zone, each category with its reason.  The generated summary lives in
     docs/naming.md between the `audit:placeholders` markers; the audit
     fails when the committed summary is stale (regenerate with `--write`).

Usage:
  python3 tools/audit.py            # check; exit 1 on any failure
  python3 tools/audit.py --write    # regenerate docs/naming.md's summary
  python3 tools/audit.py --list     # also print every listed item
"""

import argparse
import csv
import importlib.util
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

AUDIT_DOC = "docs/audit.md"
NAMING_DOC = "docs/naming.md"
CENSUS_BEGIN = "<!-- audit:placeholders:begin (generated by tools/audit.py --write; do not edit) -->"
CENSUS_END = "<!-- audit:placeholders:end -->"
HEADER_MARK = "@ Stays asm:"
HEADER_LINES = 40

# ---------------------------------------------------------------------------
# helpers


def rel(path):
    return os.path.relpath(path, ROOT)


def read(path):
    with open(os.path.join(ROOT, path), encoding="utf-8", errors="replace") as f:
        return f.read()


def files_under(top, exts):
    out = []
    base = os.path.join(ROOT, top)
    for dirpath, dirnames, filenames in os.walk(base):
        dirnames.sort()
        for name in sorted(filenames):
            if name.endswith(exts):
                out.append(rel(os.path.join(dirpath, name)))
    return out


def strip_c(text):
    """Blank out C comments (keeping newlines) and keep string literals."""
    out = []
    i, n = 0, len(text)
    while i < n:
        if text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = n if j < 0 else j + 2
            out.append("".join(c if c == "\n" else " " for c in text[i:j]))
            i = j
        elif text.startswith("//", i):
            j = text.find("\n", i)
            j = n if j < 0 else j
            out.append(" " * (j - i))
            i = j
        elif text[i] in "\"'":
            q = text[i]
            j = i + 1
            while j < n and text[j] != q and text[j] != "\n":
                if text[j] == "\\":
                    j += 1
                j += 1
            out.append(text[i:j + 1])
            i = j + 1
        else:
            out.append(text[i])
            i += 1
    return "".join(out)


class Report:
    def __init__(self):
        self.failures = []
        self.sections = []

    def fail(self, msg):
        self.failures.append(msg)

    def section(self, title, lines):
        self.sections.append((title, lines))


# ---------------------------------------------------------------------------
# 1. .incbin

INCBIN_RE = re.compile(r'^\s*\.incbin\s+"([^"]+)"\s*(?:,\s*([^,@]+))?(?:,\s*([^,@]+))?')
LOGO_INCBIN = ("asm/rom_header.s", "0x04", "0x9C")


def check_incbin(rep):
    ok_data = 0
    bad = []
    logo = 0
    for top in ("asm", "data", "src", "include"):
        for path in files_under(top, (".s", ".inc", ".c", ".h")):
            for ln, line in enumerate(read(path).split("\n"), 1):
                if ".incbin" not in line and "INCBIN" not in line:
                    continue
                code = line.split("@", 1)[0]
                if top in ("src", "include"):
                    if re.search(r"\.incbin|INCBIN", strip_c(line)):
                        bad.append("%s:%d: %s" % (path, ln, line.strip()))
                    continue
                m = INCBIN_RE.match(code)
                if not m:
                    if ".incbin" in code:
                        bad.append("%s:%d: %s" % (path, ln, line.strip()))
                    continue
                name = m.group(1)
                if path.startswith("data/") and name == "baserom.gba":
                    ok_data += 1
                elif (path, (m.group(2) or "").strip(), (m.group(3) or "").strip()) == LOGO_INCBIN \
                        and name == "baserom.gba":
                    logo += 1
                else:
                    bad.append("%s:%d: %s" % (path, ln, line.strip()))
    for b in bad:
        rep.fail(".incbin outside data/*.s and the header logo: " + b)
    if logo != 1:
        rep.fail("expected exactly one header-logo .incbin in asm/rom_header.s, found %d" % logo)
    rep.section("1. .incbin", [
        "baserom.gba slices in data/*.s: %d" % ok_data,
        "header logo slice (asm/rom_header.s, 0x04+0x9C): %d" % logo,
        "anywhere else (asm/, src/, include/): %d" % len(bad),
    ])
    return {"data_slices": ok_data, "logo": logo, "other": len(bad)}


# ---------------------------------------------------------------------------
# 2. raw numeric directives in asm/

RAW_DIRECTIVE_RE = re.compile(
    r"^\s*(?:[A-Za-z_.$][\w.$]*:\s*)?\.(byte|short|hword|half|2byte|inst|inst\.n|inst\.w|word|4byte|long|int)\b\s*(.*)$")
NUMBER_RE = re.compile(r"^[-+~]?\s*(?:0[xX][0-9A-Fa-f]+|0[bB][01]+|\d+|'.')$")


def asm_code_and_comment(line):
    """Split a gas ARM line into its code and its comment (@ or /* */)."""
    code, comment = line, ""
    at = line.find("@")
    if at >= 0:
        code, comment = line[:at], line[at + 1:]
    m = re.search(r"/\*(.*?)(\*/|$)", code)
    if m:
        comment = (m.group(1) + " " + comment).strip()
        code = code[:m.start()]
    return code, comment


def check_raw_directives(rep, listing):
    rows = []
    unjustified = []
    for path in files_under("asm", (".s", ".inc")):
        for ln, line in enumerate(read(path).split("\n"), 1):
            code, comment = asm_code_and_comment(line)
            m = RAW_DIRECTIVE_RE.match(code)
            if not m:
                continue
            ops = [o.strip() for o in m.group(2).split(",") if o.strip()]
            if not any(NUMBER_RE.match(o) for o in ops):
                continue
            why = re.search(r"\braw:\s*(.*)$", comment)
            item = "%s:%d: .%s %s" % (path, ln, m.group(1), ", ".join(ops))
            if why:
                rows.append((path, item, why.group(1).strip()))
            else:
                unjustified.append(item)
    for u in unjustified:
        rep.fail("raw numeric directive without an `@ raw:` reason: " + u)
    by_file = {}
    for path, _, _ in rows:
        by_file[path] = by_file.get(path, 0) + 1
    lines = ["justified (`@ raw:` on the line): %d" % len(rows),
             "unjustified: %d" % len(unjustified)]
    for path in sorted(by_file):
        lines.append("  %s: %d justified" % (path, by_file[path]))
    if listing:
        lines += ["  " + item + "  -- " + why for _, item, why in rows]
        lines += ["  UNJUSTIFIED " + u for u in unjustified]
    rep.section("2. Raw numeric directives in asm/", lines)
    return {"justified": len(rows), "unjustified": len(unjustified)}


# ---------------------------------------------------------------------------
# 3. the sanctioned asm


def calcrom_excluded():
    text = read("tools/calcrom.pl")
    m = re.search(r"%decomp_excluded_asm\s*=\s*map\s*\{[^}]*\}\s*qw\(([^)]*)\)", text)
    if not m:
        raise SystemExit("tools/calcrom.pl: %decomp_excluded_asm not found")
    return set(m.group(1).split())


SANCTIONED_ROW_RE = re.compile(r"^\|\s*`asm/([\w./-]+\.s)`\s*\|\s*(excluded|data|symbols)\s*\|\s*(.+?)\s*\|\s*$")


def doc_section(text, number):
    """The body of `## <number>. ...` up to the next `## ` heading."""
    m = re.search(r"^## %s\. .*$" % re.escape(str(number)), text, re.M)
    if not m:
        return None
    rest = text[m.end():]
    n = re.search(r"^## ", rest, re.M)
    return rest[:n.start()] if n else rest


def check_sanctioned_asm(rep):
    files = [p[len("asm/"):] for p in files_under("asm", (".s",))]
    excluded = calcrom_excluded()
    lines = []
    doc = read(AUDIT_DOC) if os.path.exists(os.path.join(ROOT, AUDIT_DOC)) else ""
    body = doc_section(doc, 2) or ""
    rows = {}
    for line in body.split("\n"):
        m = SANCTIONED_ROW_RE.match(line)
        if m:
            rows[m.group(1)] = (m.group(2), m.group(3))
    if not rows:
        rep.fail("%s section 2 has no sanctioned-asm rows" % AUDIT_DOC)
    for f in files:
        if f not in rows:
            rep.fail("asm/%s is not listed in %s section 2" % (f, AUDIT_DOC))
    for f in rows:
        if f not in files:
            rep.fail("%s section 2 lists asm/%s, which does not exist" % (AUDIT_DOC, f))
    doc_excluded = {os.path.splitext(os.path.basename(f))[0]
                    for f, (kind, _) in rows.items() if kind == "excluded"}
    if doc_excluded != excluded:
        rep.fail("sanctioned asm: docs 'excluded' rows %s != tools/calcrom.pl %s"
                 % (sorted(doc_excluded), sorted(excluded)))
    missing_header = []
    for f in files:
        head = read("asm/" + f).split("\n")[:HEADER_LINES]
        if not any(l.strip().startswith(HEADER_MARK) for l in head):
            missing_header.append(f)
    for f in missing_header:
        rep.fail("asm/%s has no `%s <reason>` header comment" % (f, HEADER_MARK))
    for f in sorted(files):
        kind, why = rows.get(f, ("?", "?"))
        lines.append("  asm/%s: %s" % (f, kind))
    lines.insert(0, "files in asm/: %d; calcrom.pl excluded: %s; header comments missing: %d"
                 % (len(files), " ".join(sorted(excluded)), len(missing_header)))
    rep.section("3. The sanctioned asm", lines)
    return {"files": len(files), "excluded": sorted(excluded), "missing_header": len(missing_header)}


# ---------------------------------------------------------------------------
# 4. raw addresses in src/ and include/*.h

ADDR_RE = re.compile(r"\b0[xX]0*([2-9A-Ea-e])([0-9A-Fa-f]{6})[uUlL]*\b")
REGION_NAMES = {
    0x2: "EWRAM", 0x3: "IWRAM", 0x4: "I/O", 0x5: "palette", 0x6: "VRAM",
    0x7: "OAM", 0x8: "ROM", 0x9: "ROM", 0xA: "ROM", 0xB: "ROM", 0xC: "ROM",
    0xD: "ROM", 0xE: "SRAM",
}
CONTROL_WORD_CALLS = ("CpuSet", "CpuFastSet")


def enclosing_call(stripped, pos):
    """(callee, is_last_argument) of the innermost call around pos."""
    depth = 0
    i = pos - 1
    while i >= 0:
        c = stripped[i]
        if c in ")]}":
            depth += 1
        elif c in "([{":
            if depth == 0:
                if c != "(":
                    return None, False
                m = re.search(r"([A-Za-z_]\w*)\s*$", stripped[:i])
                callee = m.group(1) if m else None
                # last argument: no top-level comma between pos and the ')'
                d = 0
                j = pos
                while j < len(stripped):
                    cj = stripped[j]
                    if cj in "([{":
                        d += 1
                    elif cj in ")]}":
                        if d == 0:
                            return callee, True
                        d -= 1
                    elif cj == "," and d == 0:
                        return callee, False
                    j += 1
                return callee, False
            depth -= 1
        elif c == ";" and depth == 0:
            return None, False
        i -= 1
    return None, False


def check_raw_addresses(rep, listing):
    paths = files_under("src", (".c", ".h")) + [
        p for p in files_under("include", (".h",)) if not p.startswith("include/gba/")]
    justified, control, bad = [], [], []
    for path in paths:
        text = read(path)
        raw_lines = text.split("\n")
        stripped = strip_c(text)
        line_starts = [0]
        for k, c in enumerate(stripped):
            if c == "\n":
                line_starts.append(k + 1)
        for m in ADDR_RE.finditer(stripped):
            ln = _line_of(line_starts, m.start())
            region = REGION_NAMES[int(m.group(1), 16)]
            item = "%s:%d: %s (%s): %s" % (path, ln, m.group(0), region, raw_lines[ln - 1].strip())
            callee, last = enclosing_call(stripped, m.start())
            if callee in CONTROL_WORD_CALLS and last:
                control.append(item)
                continue
            here = raw_lines[ln - 1]
            above = raw_lines[ln - 2] if ln >= 2 else ""
            if "raw:" in here or "raw:" in above:
                justified.append(item)
            else:
                bad.append(item)
    for b in bad:
        rep.fail("raw address without a symbol, macro or `raw:` comment: " + b)
    lines = [
        "control words (last argument of CpuSet/CpuFastSet): %d" % len(control),
        "justified (`raw:` comment): %d" % len(justified),
        "unjustified: %d" % len(bad),
    ]
    by_region = {}
    for b in bad:
        r = b.split("(", 1)[1].split(")", 1)[0]
        by_region[r] = by_region.get(r, 0) + 1
    for r in sorted(by_region):
        lines.append("  unjustified %s: %d" % (r, by_region[r]))
    if listing:
        lines += ["  " + j for j in justified]
        lines += ["  UNJUSTIFIED " + b for b in bad]
    rep.section("4. Raw addresses in src/ and include/*.h", lines)
    return {"control_words": len(control), "justified": len(justified), "unjustified": len(bad)}


def _line_of(starts, pos):
    lo, hi = 0, len(starts)
    while lo + 1 < hi:
        mid = (lo + hi) // 2
        if starts[mid] <= pos:
            lo = mid
        else:
            hi = mid
    return lo + 1


# ---------------------------------------------------------------------------
# 5. code exceptions

# Checked in order; the first match names the line's kind.
EXC_PATTERNS = (
    ("pin", re.compile(r"\bregister\b[^;]*\basm\s*\(")),
    ("cross-jump", re.compile(r"\bBLOCK_CROSS_JUMP\b")),
    ("alias", re.compile(r"\)\s*(?:asm|__asm__)\s*\(\s*\"\w+\"\s*\)\s*;")),
    ("lever", re.compile(r"\b(?:asm|__asm__)\s*(?:volatile\s*|__volatile__\s*)?\(\s*\"\"")),
    ("inline-asm", re.compile(r"\b(?:asm|__asm__)\s*(?:volatile\s*|__volatile__\s*)?\(")),
    ("zero-code", re.compile(r"\bwhile\s*\(\s*0\s*\)")),
)
EXC_KINDS = "pin|lever|cross-jump|alias|inline-asm|zero-code|stand-in"
EXC_ROW_RE = re.compile(
    r"^\|\s*`(src/[\w./-]+\.c):(\d+)(?:-(\d+))?`\s*\|\s*`?(\w+|\(file scope\))`?\s*\|\s*(" + EXC_KINDS + r")\s*\|\s*(.+?)\s*\|\s*$")
FILE_SCOPE = "(file scope)"


def function_of_lines(stripped):
    """The function each line (1-based list index - 1) lies in, from brace
    depth: a `{` at depth 0 preceded by `name(...)` opens function `name`."""
    funcs = []
    depth = 0
    current = None
    pending = ""
    for line in stripped.split("\n"):
        at_start = current if depth > 0 else None
        for k, c in enumerate(line):
            if c == "{":
                if depth == 0:
                    before = (pending + " " + line[:k])
                    m = re.search(r"([A-Za-z_]\w*)\s*\([^()]*(?:\([^()]*\)[^()]*)*\)\s*$", before)
                    current = m.group(1) if m else None
                depth += 1
            elif c == "}":
                depth -= 1
                if depth == 0:
                    current = None
            elif c == ";" and depth == 0:
                pending = ""
        funcs.append(at_start if at_start is not None else (current if depth > 0 else None))
        pending = (pending + " " + line)[-400:] if depth == 0 else ""
    return funcs


def enclosing_function(lines, ln):
    funcs = function_of_lines(strip_c("\n".join(lines)))
    f = funcs[ln - 1] if 0 < ln <= len(funcs) else None
    return f or FILE_SCOPE


def scan_exceptions():
    found = []
    for path in files_under("src", (".c",)):
        text = read(path)
        stripped = strip_c(text)
        funcs = function_of_lines(stripped)
        for ln, line in enumerate(stripped.split("\n"), 1):
            for kind, pat in EXC_PATTERNS:
                if pat.search(line):
                    found.append((path, ln, kind, funcs[ln - 1] or FILE_SCOPE))
                    break
    return found


def check_exceptions(rep, listing):
    doc = read(AUDIT_DOC) if os.path.exists(os.path.join(ROOT, AUDIT_DOC)) else ""
    body = doc_section(doc, 3) or ""
    rows = []
    for line in body.split("\n"):
        m = EXC_ROW_RE.match(line)
        if m:
            first = int(m.group(2))
            last = int(m.group(3) or m.group(2))
            rows.append((m.group(1), first, last, m.group(4), m.group(5), m.group(6)))
    found = scan_exceptions()
    covered = set()
    for path, first, last, func, kind, why in rows:
        if not os.path.exists(os.path.join(ROOT, path)):
            rep.fail("%s section 3: %s does not exist" % (AUDIT_DOC, path))
            continue
        hits = [f for f in found if f[0] == path and first <= f[1] <= last and f[2] == kind]
        if kind == "stand-in":
            lines = read(path).split("\n")
            if last > len(lines) or enclosing_function(lines, first) != func:
                rep.fail("%s section 3: %s:%d is not inside %s any more" % (AUDIT_DOC, path, first, func))
            continue
        if not hits:
            rep.fail("%s section 3: no %s at %s:%d-%d any more" % (AUDIT_DOC, kind, path, first, last))
        for h in hits:
            covered.add(h)
            if h[3] != func:
                rep.fail("%s section 3: %s:%d is in %s, not %s" % (AUDIT_DOC, path, h[1], h[3], func))
    for f in found:
        if f not in covered:
            rep.fail("code exception not listed in %s section 3: %s:%d (%s, in %s)"
                     % (AUDIT_DOC, f[0], f[1], f[2], f[3]))
    counts = {}
    for f in found:
        counts[f[2]] = counts.get(f[2], 0) + 1
    standins = sum(1 for r in rows if r[4] == "stand-in")
    lines = ["mechanically found: %s" % ", ".join("%s %d" % (k, counts[k]) for k in sorted(counts)),
             "documented rows: %d (of which stand-in rows: %d)" % (len(rows), standins)]
    funcs = sorted({r[3] for r in rows})
    lines.append("functions with an exception: %d (%s)" % (len(funcs), ", ".join(funcs)))
    if listing:
        lines += ["  %s:%d %s in %s" % f for f in found]
    rep.section("5. Code exceptions", lines)
    return {"found": counts, "rows": len(rows), "functions": funcs}


# ---------------------------------------------------------------------------
# 6. the placeholder census

# Code zones: the #34 module map's census modules (docs/analysis/module-map.md)
# and the zones around them, by start address.
ZONES = (
    ("crt0", 0x08000000, "cartridge header, crt0, master ISR and the ARM task switch"),
    ("engine", 0x08000310, "the engine zone: AgbInit, tasks, sprites, fades, sound front end, link"),
    ("M01", 0x08007300, "AgbMain"),
    ("M02", 0x080075B8, "game-state bodies, title, screen loaders, pause, HUD"),
    ("M03", 0x0800B920, "main menu and its sprite tasks"),
    ("M04", 0x08010358, "scripted-sequence director and scripts"),
    ("M05", 0x08017668, "player animation bank and collision registry"),
    ("M06", 0x0801A8C8, "collision engine and hit tests"),
    ("M07", 0x08021B18, "level / room builder"),
    ("M08", 0x080296A0, "camera, BG streaming, map events, stage objects"),
    ("M09", 0x08030804, "breakable blocks and the player task"),
    ("M10", 0x08036280, "player action bodies, part 2"),
    ("M11", 0x0803CD60, "player mode machine and stage services"),
    ("M12", 0x080449C8, "player action bodies, part 3"),
    ("M13", 0x08047FE8, "player action bodies, part 4"),
    ("M14", 0x0804CC7C, "player action bodies, part 5, and task type #6"),
    ("M15", 0x08053AF4, "the player's effect objects (task type #7)"),
    ("M16", 0x0805AFAC, "effect spawner (task types #81-#90)"),
    ("M17", 0x08062584, "actor core"),
    ("M18", 0x080692FC, "actor core, part 2"),
    ("M19", 0x08070EC0, "cutscenes and ending sequences"),
    ("M20", 0x08078B68, "enemies, bank 1"),
    ("M21", 0x0807F044, "enemies, bank 2"),
    ("M22", 0x08082E68, "enemies, bank 3"),
    ("M23", 0x080860F8, "enemies, bank 4, and two bosses"),
    ("M24", 0x0808CCE8, "enemies, bank 5"),
    ("M25", 0x0809000C, "bosses"),
    ("M26", 0x08093F64, "enemies, bank 7"),
    ("M27", 0x080988F8, "mid-bosses"),
    ("M28", 0x0809BA44, "enemies, bank 9, and the player's death sequence"),
    ("M29", 0x080A1590, "enemies, bank 10"),
    ("M30", 0x080A5644, "enemies, bank 11"),
    ("M31", 0x080AA338, "enemies, bank 12"),
    ("M32", 0x080AE3BC, "enemies, bank 13"),
    ("M33", 0x080B2FE8, "HUD effects"),
    ("M34", 0x080B6154, "wavy scroll, save file, input recorder"),
    ("M35", 0x080B9D0C, "sub-game framework and Quick Draw"),
    ("M36", 0x080BDA2C, "Bomb Rally"),
    ("M37", 0x080C1FFC, "Air Grind and game state 11"),
    ("M38", 0x080C6420, "ending, staff credits, game over"),
    ("m4a", 0x080CD89C, "the m4a sound engine (asm core and C driver)"),
    ("sdk", 0x080CFA4C, "SDK stubs: SWI thunks, SoftReset, SRAM driver, lib1funcs, trampolines, veneer"),
    ("data", 0x080CFDE4, "(data)"),
)

# Struct Task fields whose meaning changes with the task family: the
# registers include/task_vars.h names per family (#155 run 5), and u76's
# unk76 member.
TASK_FAMILY_FIELDS = {"unk18", "unk1C", "unk20", "unk24", "unk28", "unk2C",
                      "unk30", "unk34", "unk46", "unk6C", "unk6E", "unk70",
                      "unk74", "unk76"}

REASONS = {
    "fn-game": "tracked by #155: role not settled (mostly enemy and boss state bodies and one-caller helpers, docs/naming.md section 5)",
    "fn-engine": "tracked by #155: engine-zone helpers whose role is not settled",
    "fn-lib": "runtime and library code with no upstream name: the m4a `bx r3` shims, the task-done hang helper, the ARM halves of the task trampolines and the veneer (docs/analysis/rom-map.md sections 6 and 8)",
    "ram": "tracked by #155: role not proven; many are proven shared scratch or hold two encodings",
    "io": "none left: the four I/O registers kept as symbols (the m4a_1 and SoftReset asm pools, and early_4734.c's IME, where REG_IME changes the allocation, lesson 3.523) are named gRegVcount, gRegSound1CntL, gRegDma1Sad and gRegIme (#170); the rest of the C spells REG_*",
    "rom-asset": "asset label, unnamed by policy until a consumer gives it a role (docs/naming.md section 5, docs/data.md)",
    "rom-data": "tracked by #155: functional data whose consumer does not settle a name",
    "rom-position": "documented by position: the record's slot in a consumer-proven table (docs/naming.md section 2.4)",
    "rom-position-format": "documented by position in a format-only chain: a slot no code reads, such as the frame list a graphics descriptor's trailer word points at (docs/naming.md section 2.4, docs/data.md 5.3)",
    "field-task-family": "per-family registers, named per family by the aliases in include/task_vars.h (docs/header-conventions.md; the member keeps its unk name, lessons and history cite it); `unk76` is u76's member for the player's bits",
    "field-header": "tracked by #155: the field's role is not proven",
    "field-local": "local struct copies and module-local records: tracked by #155 (tools/rename_field.py `copies`)",
    "loc": "none left: the code is C",
    "field-player-scratch": "struct PlayerState's per-action scratch: each player action keeps its own value there, named per action by the aliases in include/task_vars.h (#155 run 7; the member keeps its unk name)",
    "field-task-family-local": "the per-family registers in the task engine's local copies of struct Task (src/early_58e4.c, early_5c4c.c): named per family by the aliases of include/task_vars.h, which the engine never uses",
    # ROM labels by their referrers (#155 run 7, mechanical)
    "rom-shared": "shared: two or more slots, records or consumers point at it, so no single slot or role is its identity (docs/naming.md section 2.4)",
    "rom-via-unnamed": "reached only through a record or consumer that is itself unnamed (a `gUnk_` record, a `sub_*`): it is named with that referrer",
    "rom-via-slot": "one slot of a named record holds it and nothing else names it; its position name waits for the slot's word (docs/naming.md section 2.4)",
    "rom-local": "read by one function only: its meaning is local to that function's algorithm, as for RAM cells (docs/naming.md section 5)",
    "rom-several": "read by several named functions; the row in docs/analysis/unnamed.csv gives its reason",
    "rom-unreferenced": "no code or record names it: a record boundary the data census cut, reached by an offset from a named neighbour",
}

# #155 run 7: why each placeholder stays unnamed (docs/analysis/unnamed.csv,
# `symbol,kind,reason,note`).  Once the file exists every `sub_*`, `gUnk_`
# RAM cell and header `unk*` field must have a row with one of these codes;
# a placeholder without one is "not examined" and fails the audit.
UNNAMED_CSV = "docs/analysis/unnamed.csv"
UNNAMED_REASONS = {
    "pair": "one verb fits it and a sibling state, and the code proves no qualifier that sets them apart (docs/naming.md 2.3, R1)",
    "identity": "the name needs an identity (enemy, object, picture, scene) with fewer than three agreeing sources (docs/naming.md 2.3)",
    "unnamed-input": "its role rests on a cell, field or value that stays unnamed (the row names it)",
    "no-verb": "no defined verb or noun fits the whole of it; only an ordinal or a vague word would (docs/naming.md 1)",
    "restates": "a thin helper whose name would only restate its body or its one caller's step (docs/naming.md 5)",
    "mixed": "several unrelated jobs chosen by a parameter or a sub-state; no one role",
    "dead": "nothing references it: no call, table slot or data word (kept for the match)",
    "library": "runtime or library code with no upstream name (docs/analysis/rom-map.md sections 6 and 8)",
    "two-meanings": "two encodings or meanings that no single noun covers (docs/naming.md 5)",
    "local": "read and written by one function only; its meaning is local to that algorithm (docs/naming.md 5)",
    "write-only": "written but never read, or only cleared",
    "never-accessed": "no code reads or writes it",
    "unproven-bits": "a flag word whose bits are not all proven (docs/naming.md 7.0, R3)",
    "asset": "a graphic, palette, tilemap or text picture in a functional segment: an asset label, unnamed by the data policy (docs/naming.md 5)",
}
UNNAMED_KINDS = {"function": "fn", "ram": "ram", "field": "field", "rom": "rom"}


def load_unnamed():
    """{(kind, symbol): (reason, note)} of docs/analysis/unnamed.csv, or None."""
    path = os.path.join(ROOT, UNNAMED_CSV)
    if not os.path.exists(path):
        return None
    out = {}
    with open(path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            out[(row["kind"], row["symbol"])] = (row["reason"], row.get("note", ""))
    return out


ROM_TOK_RE = re.compile(r"\bgUnk_08[0-9A-Fa-f]{6}\b")


def c_definitions(text):
    """yield (name, kind, body) of the top-level definitions of a C text
    (comments stripped): kind `function` or `record` (an initialised table)."""
    depth = 0
    head_start = 0
    start = 0
    head = ""
    for i, ch in enumerate(text):
        if ch == "{":
            if depth == 0:
                head = text[head_start:i]
                start = i
            depth += 1
        elif ch == "}":
            depth -= 1
            if depth == 0:
                m = re.search(r"([A-Za-z_]\w*)\s*(\[[^\]]*\])*\s*([A-Z][A-Z0-9_]*(\([^)]*\))?|"
                              r"__attribute__\(\([^)]*\)\))?\s*=\s*$", head)
                if m and "=" in head:
                    yield m.group(1), "record", text[start:i]
                else:
                    m = re.search(r"([A-Za-z_]\w*)\s*\([^;{}]*\)\s*$", head)
                    yield (m.group(1) if m else "?"), "function", text[start:i]
                head_start = i + 1
        elif ch == ";" and depth == 0:
            head_start = i + 1


def rom_referrers():
    """{label: ({(kind, referrer)}, number of references)} of every gUnk_08
    label: the C definitions of src/ and include/ that mention it (a function
    or an initialised record), and the labels of data/*.s (records) and
    asm/*.s (code) whose words name it."""
    refs = {}
    count = {}

    def add(w, kind, who):
        refs.setdefault(w, set()).add((kind, who))
        count[w] = count.get(w, 0) + 1
    for top in ("src", "include"):
        for path in files_under(top, (".c", ".h")):
            for name, kind, body in c_definitions(strip_c(read(path))):
                for w in ROM_TOK_RE.findall(body):
                    if w != name:
                        add(w, kind, name)
    for top, kind in (("data", "record"), ("asm", "function")):
        for path in files_under(top, (".s",)):
            cur = None
            for line in read(path).split("\n"):
                m = LABEL_RE.match(line)
                if m:
                    cur = m.group(1)
                    continue
                if line.lstrip().startswith((".global", ".globl", ".type", ".size")):
                    continue
                for w in ROM_TOK_RE.findall(line):
                    if w != cur:
                        add(w, kind, cur)
    return refs, count


def rom_label_class(name, refs, count):
    """The census category of an unnamed functional ROM label, from its
    referrers."""
    r = refs.get(name, set())
    if not r:
        return "rom-unreferenced"
    fns = sorted(n for k, n in r if k == "function")
    if fns:
        if all(f.startswith("sub_") for f in fns):
            return "rom-via-unnamed"
        if len(fns) == 1 and len(r) == 1:
            return "rom-local"
        return "rom-several"
    if len(r) >= 2 or count.get(name, 0) >= 2:
        return "rom-shared"
    who = next(iter(r))[1] or ""
    if who.startswith(("gUnk_", "sub_")):
        return "rom-via-unnamed"
    return "rom-via-slot"


def zone_of(addr):
    zone = None
    for zid, start, _ in ZONES:
        if addr >= start:
            zone = zid
        else:
            break
    return zone


def load_segments():
    segs = []
    for line in read("docs/analysis/segments.txt").split("\n"):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        f = line.split()
        if len(f) >= 4:
            segs.append((int(f[0], 16), int(f[1], 16), f[2], f[3]))
    return segs


def asset_segments():
    cfg = json.loads(read("tools/split_config.json"))
    return {s["name"] for s in cfg["segments"] if s.get("asset")}


def position_names(format_only=False):
    """Names whose renames.csv evidence is a slot (docs/naming.md 2.4); with
    format_only, only those of a format-only chain."""
    names = set()
    path = os.path.join(ROOT, "docs/analysis/renames.csv")
    if os.path.exists(path):
        with open(path, encoding="utf-8") as f:
            for row in csv.DictReader(f):
                ev = row.get("evidence", "")
                if ev.startswith("slot:") and (not format_only or "format-only" in ev):
                    names.add(row["new"])
    return names


LABEL_RE = re.compile(r"^([A-Za-z_][\w.$]*):")
STRUCT_HEAD_RE = re.compile(r"\b(struct|union)\s*(\w+)?\s*(?:__attribute__\s*\(\([^)]*\)\)\s*)?$")
TOKEN_RE = re.compile(r"[{};]")
FIELD_NAME_RE = re.compile(r"\b(unk[0-9A-Fa-f]+)\s*(?:\[[^\]]*\]\s*)*(?::\s*\d+\s*)?$")


def struct_fields(path):
    """Yield (struct name, field name) for the unk* members of every struct
    or union defined in a C file; a member of a nested anonymous struct or
    union counts for the enclosing named one."""
    text = strip_c(read(path))
    stack = []  # struct name, or None for any other brace (body, initializer)
    last = 0
    for m in TOKEN_RE.finditer(text):
        chunk = text[last:m.start()]
        last = m.end()
        tok = m.group(0)
        if tok == "{":
            head = STRUCT_HEAD_RE.search(chunk)
            if head and not re.search(r"=\s*$", chunk):
                name = head.group(2)
                if name is None and stack and stack[-1] is not None:
                    name = stack[-1]
                stack.append(name or "?")
            else:
                stack.append(None)
        elif tok == "}":
            if stack:
                stack.pop()
        elif tok == ";":
            if stack and stack[-1] is not None:
                fm = FIELD_NAME_RE.search(chunk.strip())
                if fm:
                    yield stack[-1], fm.group(1)


def placeholder_census():
    rows = {}  # (kind, category) -> count
    by_zone = {}  # zone -> [functions, sub_]
    extra = {}
    unnamed = load_unnamed()
    seen = set()  # (kind, symbol) of the placeholders the census found
    missing = []  # placeholders with no unnamed.csv row

    def add(kind, cat, n=1):
        rows[(kind, cat)] = rows.get((kind, cat), 0) + n

    def reason(kind, symbol, fallback):
        """The census category of a placeholder: its unnamed.csv row's code
        once the file exists, else the run-6 category `fallback`."""
        if unnamed is None:
            return fallback
        seen.add((kind, symbol))
        r = unnamed.get((kind, symbol))
        if r is None:
            missing.append("%s %s" % (kind, symbol))
            return "%s:unexamined" % UNNAMED_KINDS[kind]
        return "%s:%s" % (UNNAMED_KINDS[kind], r[0])

    add("I/O register", "io", 0)  # a row even at 0, like loc

    # functions
    with open(os.path.join(ROOT, "docs/analysis/symbols.csv"), encoding="utf-8") as f:
        for row in csv.DictReader(f):
            addr = int(row["vma"], 16)
            zone = zone_of(addr)
            z = by_zone.setdefault(zone, [0, 0])
            z[0] += 1
            if row["name"].startswith("sub_"):
                z[1] += 1
                if zone in ("m4a", "sdk", "crt0"):
                    add("function", reason("function", row["name"], "fn-lib"))
                elif zone == "engine":
                    add("function", reason("function", row["name"], "fn-engine"))
                else:
                    add("function", reason("function", row["name"], "fn-game"))
    # RAM and I/O cells
    cfg = json.loads(read("tools/split_config.json"))
    positions = position_names()
    formats = position_names(format_only=True)
    ram_named = ram_unk = ram_pos = 0
    for addr, name in cfg["data_symbols"].items():
        region = int(addr, 16) >> 24
        if region in (2, 3):
            if name.startswith("gUnk_"):
                add("RAM cell", reason("ram", name, "ram"))
                ram_unk += 1
            elif name in positions:
                ram_pos += 1
            else:
                ram_named += 1
        elif region == 4 and name.startswith("gUnk_"):
            add("I/O register", "io")
    extra["ram"] = (ram_named, ram_unk, ram_pos)
    # ROM labels: every label of data/*.s, by segment; an unnamed functional
    # label is classed by its referrers (#155 run 7)
    assets = asset_segments()
    segs = load_segments()
    rrefs, rcount = rom_referrers()

    def rom_cat(name):
        cat = rom_label_class(name, rrefs, rcount)
        if cat == "rom-several" and unnamed is not None:
            return reason("rom", name, cat)
        return cat
    rom_named = rom_unk_asset = rom_unk_data = rom_pos = 0
    for path in files_under("data", (".s",)):
        seg = os.path.splitext(os.path.basename(path))[0]
        for line in read(path).split("\n"):
            # a zone's file holds one section per piece (#167)
            m = re.match(r"\s*\.section\s+\.(\w+)", line)
            if m:
                seg = m.group(1)
                continue
            m = LABEL_RE.match(line)
            if not m:
                continue
            name = m.group(1)
            if name == seg or name.startswith(".L"):
                continue
            if name in formats:
                rom_pos += 1
                add("ROM label", "rom-position-format")
            elif name in positions:
                rom_pos += 1
                add("ROM label", "rom-position")
            elif name.startswith("gUnk_"):
                if seg in assets:
                    rom_unk_asset += 1
                    add("ROM label", "rom-asset")
                else:
                    rom_unk_data += 1
                    add("ROM label", rom_cat(name))
            else:
                rom_named += 1
    # ROM labels the C tables of src/data/ define (c_data rows): they left
    # data/*.s but are still labels, named or not
    c_rows = [(s, e) for s, e, k, _n in segs if k == "c_data"]
    for addr, name in cfg["data_symbols"].items():
        a = int(addr, 16)
        if not any(s <= a < e for s, e in c_rows):
            continue
        if name in positions:
            rom_pos += 1
            add("ROM label", "rom-position")
        elif name.startswith("gUnk_"):
            rom_unk_data += 1
            add("ROM label", rom_cat(name))
        else:
            rom_named += 1
    extra["rom"] = (rom_named, rom_unk_asset, rom_unk_data, rom_pos)
    # struct fields
    header_structs = {}
    for path in files_under("include", (".h",)):
        if path.startswith("include/gba/"):
            continue
        for s, fld in struct_fields(path):
            if not fld.startswith("unk"):
                continue
            if s == "Task" and fld in TASK_FAMILY_FIELDS:
                add("struct field", "field-task-family")
            elif s == "PlayerState" and fld in ("unk14", "unk16"):
                add("struct field", "field-player-scratch")
            else:
                add("struct field", reason("field", "%s.%s" % (s, fld), "field-header"))
            header_structs[s] = header_structs.get(s, 0) + 1
    local = 0
    for path in files_under("src", (".c",)):
        for s, fld in struct_fields(path):
            if fld.startswith("unk"):
                local += 1
                if unnamed is None:
                    continue
                if s == "Task" and fld in TASK_FAMILY_FIELDS:
                    add("struct field", "field-task-family-local")
                else:
                    add("struct field", reason("field", "%s.%s" % (s, fld), "field-local"))
    if local and unnamed is None:
        add("struct field", "field-local", local)
    extra["missing"] = missing
    extra["stale"] = sorted("%s %s" % k for k in (unnamed or {}) if k not in seen and k[0] != "rom") + \
        sorted("rom %s" % s for k, s in (unnamed or {}) if k == "rom" and ("rom", s) not in seen)
    extra["header_structs"] = header_structs
    # the per-family register aliases (include/task_vars.h, #155 run 5)
    aliases = {}
    vars_h = os.path.join(ROOT, "include", "task_vars.h")
    if os.path.exists(vars_h):
        fam = None
        for line in read("include/task_vars.h").split("\n"):
            m = re.match(r"/\* ([A-Z]\w*) - ", line)
            if m:
                fam = m.group(1)
            m = re.match(r"#define (\w+) (unk[0-9A-F]+) ", line)
            if m and fam:
                aliases.setdefault(fam, []).append(m.group(1))
    extra["aliases"] = aliases
    # the named constants (include/constants/, tools/constants.py, #155 run 6)
    extra["constants"] = None
    if os.path.isdir(os.path.join(ROOT, "include", "constants")):
        spec = importlib.util.spec_from_file_location(
            "constants", os.path.join(ROOT, "tools", "constants.py"))
        mod = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(mod)
        extra["constants"] = mod.census()
    # loc_ labels
    loc = 0
    for top in ("asm", "src", "include", "data"):
        for path in files_under(top, (".s", ".c", ".h", ".inc")):
            loc += len(re.findall(r"^\s*loc_[0-9A-Fa-f]{8}:", read(path), re.M))
    add("label", "loc", loc)
    return rows, by_zone, extra


def category_reason(cat):
    if cat in REASONS:
        return REASONS[cat]
    code = cat.split(":", 1)[1]
    if code == "unexamined":
        return "NOT EXAMINED: no row in %s (the audit fails)" % UNNAMED_CSV
    return UNNAMED_REASONS.get(code, "unknown reason code `%s` (the audit fails)" % code)


def census_markdown(rows, by_zone, extra):
    out = [CENSUS_BEGIN, ""]
    out.append("| kind | placeholder | count | reason |")
    out.append("|---|---|---:|---|")
    kinds = ["function", "RAM cell", "I/O register", "ROM label", "struct field", "label"]
    fixed = ["fn-game", "fn-engine", "fn-lib", "ram", "io", "rom-data", "rom-shared",
             "rom-via-unnamed", "rom-via-slot", "rom-local", "rom-several", "rom-unreferenced",
             "rom-asset", "rom-position", "rom-position-format", "field-task-family",
             "field-player-scratch", "field-task-family-local", "field-header", "field-local", "loc"]
    pattern = {"function": "`sub_*`", "RAM cell": "`gUnk_02*`, `gUnk_03*`",
               "I/O register": "`gUnk_04*`", "ROM label": "`gUnk_08*`",
               "struct field": "`unk*`", "label": "`loc_*`"}

    def key(item):
        (kind, cat), n = item
        coded = ":" in cat
        return (kinds.index(kind), 1 if coded and cat.endswith(":unexamined") else 0,
                fixed.index(cat) if cat in fixed else len(fixed), -n, cat)
    for (kind, cat), n in sorted(rows.items(), key=key):
        pat = "(named)" if cat.startswith("rom-position") else pattern[kind]
        out.append("| %s | %s | %d | %s |" % (kind, pat, n, category_reason(cat)))
    ram_named, ram_unk, ram_pos = extra["ram"]
    rom_named, rom_asset, rom_data, rom_pos = extra["rom"]
    out.append("")
    out.append("Named for comparison: %d RAM cells by role and %d by position, %d ROM labels by role and %d by position."
               % (ram_named, ram_pos, rom_named, rom_pos))
    out.append("")
    out.append("Functions by zone (the #34 module map, docs/analysis/module-map.md):")
    out.append("")
    out.append("| zone | content | functions | `sub_*` |")
    out.append("|---|---|---:|---:|")
    for zid, _, what in ZONES:
        if zid in by_zone:
            total, unk = by_zone[zid]
            out.append("| %s | %s | %d | %d |" % (zid, what, total, unk))
    tot = sum(v[0] for v in by_zone.values())
    unk = sum(v[1] for v in by_zone.values())
    out.append("| all | | %d | %d |" % (tot, unk))
    out.append("")
    aliases = extra["aliases"]
    if aliases:
        out.append("Register aliases (include/task_vars.h): %d in %d families: " % (
            sum(len(v) for v in aliases.values()), len(aliases)) + ", ".join(
            "%s %d" % (f, len(v)) for f, v in sorted(aliases.items())) + ".")
        out.append("")
    consts = extra["constants"]
    if consts:
        out.append("Named constants (include/constants/, docs/naming.md section 7): %d in %d headers, "
                   "spelled at %d sites: " % (
                       sum(consts["constants"].values()), len(consts["constants"]),
                       sum(consts["uses"].values())) + ", ".join(
            "`%s.h` %d (%d sites)" % (t, n, consts["uses"][t]) for t, n in consts["constants"].items())
                   + ".  Integer literals left at a mechanical family's positions whose value has a "
                   "constant: " + ", ".join("%s %d" % (f, n) for f, n in consts["literals_left"].items())
                   + ".")
        out.append("")
    out.append("`unk*` fields by header struct: " + ", ".join(
        "`%s` %d" % (s, n) for s, n in sorted(extra["header_structs"].items(), key=lambda x: (-x[1], x[0]))) + ".")
    out.append("")
    out.append(CENSUS_END)
    return "\n".join(out)


def check_census(rep, write):
    rows, by_zone, extra = placeholder_census()
    block = census_markdown(rows, by_zone, extra)
    text = read(NAMING_DOC)
    b = text.find(CENSUS_BEGIN)
    e = text.find(CENSUS_END)
    if write:
        if b < 0 or e < 0:
            raise SystemExit("%s: the audit:placeholders markers are missing" % NAMING_DOC)
        new = text[:b] + block + text[e + len(CENSUS_END):]
        if new != text:
            with open(os.path.join(ROOT, NAMING_DOC), "w", encoding="utf-8") as f:
                f.write(new)
            print("wrote %s" % NAMING_DOC)
    elif b < 0 or e < 0:
        rep.fail("%s: the audit:placeholders markers are missing" % NAMING_DOC)
    elif text[b:e + len(CENSUS_END)] != block:
        rep.fail("%s: the placeholder census is stale (run `python3 tools/audit.py --write`)" % NAMING_DOC)
    for m in extra.get("missing", []):
        rep.fail("placeholder not examined (no %s row): %s" % (UNNAMED_CSV, m))
    for s in extra.get("stale", []):
        rep.fail("%s row for a symbol that is no placeholder (renamed?): %s" % (UNNAMED_CSV, s))
    for (kind, cat), n in rows.items():
        if ":" in cat and cat.split(":", 1)[1] not in UNNAMED_REASONS and not cat.endswith(":unexamined"):
            rep.fail("%s: unknown reason code in category %s" % (UNNAMED_CSV, cat))
    lines = []
    for (kind, cat), n in sorted(rows.items()):
        lines.append("%-13s %-26s %6d  %s" % (kind, cat, n, category_reason(cat)))
    rep.section("6. Placeholder census", lines)
    return {"%s/%s" % k: v for k, v in rows.items()}


# ---------------------------------------------------------------------------


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--write", action="store_true", help="regenerate the docs/naming.md census")
    ap.add_argument("--list", action="store_true", help="print every listed item")
    ap.add_argument("--json", help="write the summary as JSON to this path")
    args = ap.parse_args()
    rep = Report()
    summary = {
        "incbin": check_incbin(rep),
        "raw_directives": check_raw_directives(rep, args.list),
        "sanctioned_asm": check_sanctioned_asm(rep),
        "raw_addresses": check_raw_addresses(rep, args.list),
        "exceptions": check_exceptions(rep, args.list),
        "placeholders": check_census(rep, args.write),
    }
    for title, lines in rep.sections:
        print(title)
        for l in lines:
            print("    " + l)
    if args.json:
        with open(args.json, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=1, sort_keys=True)
    if rep.failures:
        print("\nAUDIT FAILED: %d problem(s)" % len(rep.failures))
        for msg in rep.failures[:200]:
            print("  " + msg)
        if len(rep.failures) > 200:
            print("  ... and %d more" % (len(rep.failures) - 200))
        return 1
    print("\naudit passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
