#include "gba/gba.h"
#include "global.h"
#include "task.h"
#include "main.h"
#include "sound.h"
#include "cutscene.h"
#include "player.h"
#include "actor.h"

s32 PlaySfx(s32 id);
void RequestScreenShake(s32 a);

void CutsceneFountainKirby(void)
{
    gCurTask->moveCallback = (u32)TaskMove;
    gCurTask->drawCallback = (u32)CutsceneFountainKirbyDraw;
    gCurTask->layer = 7;
    gCurTask->frameTable = gCutsceneFountainKirbyFrames;
    gCurTask->updateCallback = (u32)CutsceneFountainKirbyUpdate;
    gCurTask->cutsceneActorBgmFadeStep = -1;
    gCurTask->tileWord = 128 << 4;
    gCurTask->posX = 128 << 16;
    gCurTask->posY = 218 << 15;
    gCurTask->spriteFlags |= 128 << 8;
    TaskStop();
    gCurTask->frame = 78;
    TaskYieldTrampoline(64);
    gCurTask->frame = 46;
    TaskYieldTrampoline(2);
    gCurTask->frame = 47;
    TaskYieldTrampoline(2);
    gCurTask->frame = 48;
    TaskYieldTrampoline(2);
    gCurTask->frame = 49;
    TaskYieldTrampoline(2);
    gCurTask->frame = 80;
    TaskYieldTrampoline(40);
    gCurTask->spriteFlags &= 0x7FFF;
    gCurTask->velX = 240 << 5;
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(4);
    gCurTask->frame = 83;
    TaskYieldTrampoline(2);
    gCurTask->frame = 84;
    TaskYieldTrampoline(2);
    gCurTask->frame = 85;
    TaskYieldTrampoline(4);
    gCurTask->frame = 86;
    TaskYieldTrampoline(8);
    gCurTask->frame = 87;
    TaskYieldTrampoline(4);
    gCurTask->frame = 88;
    TaskYieldTrampoline(2);
    gCurTask->frame = 89;
    TaskYieldTrampoline(2);
    gCurTask->frame = 90;
    TaskYieldTrampoline(4);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 81;
        TaskYieldTrampoline(8);
        gCurTask->frame = 82;
        TaskYieldTrampoline(4);
        gCurTask->frame = 83;
        TaskYieldTrampoline(2);
        gCurTask->frame = 84;
        TaskYieldTrampoline(2);
        gCurTask->frame = 85;
        TaskYieldTrampoline(4);
        gCurTask->frame = 86;
        TaskYieldTrampoline(8);
        gCurTask->frame = 87;
        TaskYieldTrampoline(4);
        gCurTask->frame = 88;
        TaskYieldTrampoline(2);
        gCurTask->frame = 89;
        TaskYieldTrampoline(2);
        gCurTask->frame = 90;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 2);
    TaskStop();
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(4);
    gCurTask->frame = 83;
    TaskYieldTrampoline(2);
    gCurTask->frame = 84;
    TaskYieldTrampoline(2);
    gCurTask->frame = 85;
    TaskYieldTrampoline(4);
    gCurTask->frame = 86;
    TaskYieldTrampoline(8);
    gCurTask->frame = 87;
    TaskYieldTrampoline(4);
    gCurTask->frame = 88;
    TaskYieldTrampoline(2);
    gCurTask->frame = 89;
    TaskYieldTrampoline(2);
    gCurTask->frame = 90;
    TaskYieldTrampoline(4);
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(4);
    gCurTask->frame = 83;
    TaskYieldTrampoline(2);
    gCurTask->frame = 84;
    TaskYieldTrampoline(2);
    gCurTask->frame = 85;
    TaskYieldTrampoline(4);
    gCurTask->velX = 0xFFFF5000;
    gCurTask->frame = 86;
    TaskYieldTrampoline(8);
    gCurTask->frame = 87;
    TaskYieldTrampoline(2);
    gCurTask->velX = 128 << 7;
    gCurTask->frame = 87;
    TaskYieldTrampoline(4);
    gCurTask->frame = 88;
    TaskYieldTrampoline(4);
    gCurTask->frame = 89;
    TaskYieldTrampoline(4);
    gCurTask->frame = 90;
    TaskYieldTrampoline(8);
    gCurTask->velX = 0xFFFF5000;
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(2);
    gCurTask->velX = 128 << 7;
    gCurTask->frame = 82;
    TaskYieldTrampoline(4);
    gCurTask->frame = 83;
    TaskYieldTrampoline(4);
    gCurTask->frame = 84;
    TaskYieldTrampoline(4);
    gCurTask->frame = 85;
    TaskYieldTrampoline(8);
    gCurTask->spriteFlags |= 128 << 8;
    TaskStop();
    gCurTask->frame = 78;
    TaskYieldTrampoline(44);
    gCurTask->frame = 50;
    TaskYieldTrampoline(4);
    gCurTask->frame = 78;
    TaskYieldTrampoline(44);
    gCurTask->frame = 51;
    TaskYieldTrampoline(8);
    gCurTask->frame = 52;
    TaskYieldTrampoline(4);
    gCurTask->frame = 51;
    TaskYieldTrampoline(2);
    gCurTask->frame = 52;
    TaskYieldTrampoline(2);
    gCurTask->frame = 51;
    TaskYieldTrampoline(32);
    gCurTask->frame = 52;
    TaskYieldTrampoline(2);
    gCurTask->frame = 51;
    TaskYieldTrampoline(36);
    gCurTask->spriteFlags &= 0x7FFF;
    gCurTask->frame = 78;
    TaskYieldTrampoline(4);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 81;
        TaskYieldTrampoline(8);
        gCurTask->frame = 82;
        TaskYieldTrampoline(4);
        gCurTask->frame = 83;
        TaskYieldTrampoline(2);
        gCurTask->frame = 84;
        TaskYieldTrampoline(2);
        gCurTask->frame = 85;
        TaskYieldTrampoline(4);
        gCurTask->frame = 86;
        TaskYieldTrampoline(8);
        gCurTask->frame = 87;
        TaskYieldTrampoline(4);
        gCurTask->frame = 88;
        TaskYieldTrampoline(2);
        gCurTask->frame = 89;
        TaskYieldTrampoline(2);
        gCurTask->frame = 90;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 1);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->velX = 0xFFFF5000;
        gCurTask->frame = 81;
        TaskYieldTrampoline(8);
        gCurTask->frame = 82;
        TaskYieldTrampoline(2);
        gCurTask->velX = 128 << 7;
        gCurTask->frame = 82;
        TaskYieldTrampoline(4);
        gCurTask->frame = 83;
        TaskYieldTrampoline(4);
        gCurTask->frame = 84;
        TaskYieldTrampoline(4);
        gCurTask->frame = 85;
        TaskYieldTrampoline(8);
        gCurTask->velX = 0xFFFF5000;
        gCurTask->frame = 86;
        TaskYieldTrampoline(8);
        gCurTask->frame = 87;
        TaskYieldTrampoline(2);
        gCurTask->velX = 128 << 7;
        gCurTask->frame = 87;
        TaskYieldTrampoline(4);
        gCurTask->frame = 88;
        TaskYieldTrampoline(4);
        gCurTask->frame = 89;
        TaskYieldTrampoline(4);
        gCurTask->frame = 90;
        TaskYieldTrampoline(8);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 1);
    gCurTask->velX = 0xFFFF5000;
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(2);
    gCurTask->velX = 128 << 7;
    gCurTask->frame = 82;
    TaskYieldTrampoline(6);
    gCurTask->frame = 83;
    TaskYieldTrampoline(6);
    gCurTask->frame = 84;
    TaskYieldTrampoline(6);
    gCurTask->velX = 128 << 6;
    gCurTask->frame = 85;
    TaskYieldTrampoline(12);
    gCurTask->velX = 128 << 6;
    gCurTask->frame = 86;
    TaskYieldTrampoline(8);
    gCurTask->frame = 87;
    TaskYieldTrampoline(2);
    gCurTask->velX = 152 << 9;
    gCurTask->frame = 87;
    TaskYieldTrampoline(4);
    gCurTask->frame = 88;
    TaskYieldTrampoline(4);
    gCurTask->frame = 89;
    TaskYieldTrampoline(4);
    gCurTask->frame = 90;
    TaskYieldTrampoline(8);
    gCurTask->velX = 128 << 6;
    gCurTask->frame = 81;
    TaskYieldTrampoline(8);
    gCurTask->frame = 82;
    TaskYieldTrampoline(2);
    gCurTask->velX = 152 << 9;
    gCurTask->frame = 82;
    TaskYieldTrampoline(4);
    gCurTask->frame = 83;
    TaskYieldTrampoline(4);
    gCurTask->frame = 84;
    TaskYieldTrampoline(4);
    gCurTask->frame = 85;
    TaskYieldTrampoline(8);
    gCurTask->velX = 128 << 6;
    gCurTask->frame = 86;
    TaskYieldTrampoline(8);
    gCurTask->frame = 87;
    TaskYieldTrampoline(2);
    gCurTask->velX = 152 << 9;
    gCurTask->frame = 87;
    TaskYieldTrampoline(4);
    gCurTask->frame = 88;
    TaskYieldTrampoline(4);
    gCurTask->spriteFlags |= 128 << 8;
    TaskStop();
    gCurTask->frame = 78;
    TaskYieldTrampoline(44);
    gCurTask->frame = 53;
    TaskYieldTrampoline(2);
    gCurTask->frame = 54;
    TaskYieldTrampoline(2);
    gCurTask->frame = 55;
    TaskYieldTrampoline(2);
    gCurTask->frame = 56;
    TaskYieldTrampoline(2);
    gCurTask->frame = 57;
    TaskYieldTrampoline(2);
    gCurTask->frame = 58;
    TaskYieldTrampoline(2);
    gCurTask->frame = 59;
    TaskYieldTrampoline(2);
    gCurTask->velY = 0xFFF90000;
    gCurTask->accelY = 158 << 7;
    gCurTask->frame = 60;
    TaskYieldTrampoline(2);
    gCurTask->frame = 61;
    TaskYieldTrampoline(2);
    gCurTask->frame = 62;
    TaskYieldTrampoline(2);
    gCurTask->frame = 63;
    TaskYieldTrampoline(10);
    gCurTask->frame = 64;
    TaskYieldTrampoline(1);
    gCurTask->velY = 0;
    gCurTask->frame = 64;
    TaskYieldTrampoline(1);
    gCurTask->frame = 65;
    TaskYieldTrampoline(2);
    gCurTask->frame = 66;
    TaskYieldTrampoline(2);
    gCurTask->frame = 67;
    TaskYieldTrampoline(4);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 95;
        TaskYieldTrampoline(2);
        gCurTask->frame = 94;
        TaskYieldTrampoline(2);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 2);
    TaskStop();
    gCurTask->frame = 93;
    TaskYieldTrampoline(2);
    gCurTask->frame = 79;
    TaskYieldTrampoline(8);
    gCurTask->frame = 78;
    TaskYieldTrampoline(44);
    gCurTask->cutsceneActorBgmFadeStep = 4;
    gCurTask->cutsceneActorBgmVolume = 255;
    PlaySfx(SE_JUMP);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        TaskSetMotion(0xFFFF2000, 0xFFFFE700, 0x5A5A5A5A, 0xFFFB8B00, 246 << 7, 0x5A5A5A5A);
        gCurTask->frame = 68;
        TaskYieldTrampoline(2);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 6);
    gCurTask->frame = 69;
    TaskYieldTrampoline(6);
    gCurTask->frame = 68;
    TaskYieldTrampoline(4);
    gCurTask->frame = 70;
    TaskYieldTrampoline(6);
    TaskStop();
    gCurTask->frame = 71;
    TaskYieldTrampoline(8);
    PlaySfx(SE_JUMP);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        TaskSetMotion(0xFFFF0000, 0xFFFFF900, 0x5A5A5A5A, 0xFFFAB000, 138 << 8, 0x5A5A5A5A);
        gCurTask->frame = 91;
        TaskYieldTrampoline(2);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 3);
    gCurTask->frame = 96;
    TaskYieldTrampoline(2);
    gCurTask->frame = 97;
    TaskYieldTrampoline(2);
    gCurTask->frame = 100;
    TaskYieldTrampoline(2);
    gCurTask->spriteFlags &= 0x7FFF;
    gCurTask->frame = 72;
    TaskYieldTrampoline(2);
    gCurTask->spriteFlags |= 128 << 8;
    gCurTask->frame = 102;
    TaskYieldTrampoline(2);
    gCurTask->frame = 73;
    TaskYieldTrampoline(2);
    gCurTask->frame = 104;
    TaskYieldTrampoline(2);
    gCurTask->frame = 105;
    TaskYieldTrampoline(2);
    gCurTask->frame = 106;
    TaskYieldTrampoline(2);
    TaskStop();
    gCurTask->frame = 79;
    TaskYieldTrampoline(4);
    PlaySfx(SE_JUMP);
    gCurTask->velY = 0xFFF90000;
    gCurTask->accelY = 142 << 8;
    gCurTask->frame = 91;
    TaskYieldTrampoline(2);
    gCurTask->frame = 93;
    TaskYieldTrampoline(2);
    gCurTask->frame = 94;
    TaskYieldTrampoline(2);
    gCurTask->frame = 95;
    TaskYieldTrampoline(2);
    gCurTask->frame = 74;
    TaskYieldTrampoline(6);
    gCurTask->frame = 75;
    TaskYieldTrampoline(10);
    PlaySfx(238);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        TaskStop();
        gCurTask->frame = 76;
        TaskYieldTrampoline(2);
        gCurTask->frame = 77;
        TaskYieldTrampoline(2);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 4);
    CreateCutsceneActor(57, 32);
    TaskSetMotion(0xFFFEB000, 0, 0x5A5A5A5A, 0xFFFCB000, 222 << 7, 0x5A5A5A5A);
    gCurTask->frame = 10;
    TaskYieldTrampoline(10);
    gCurTask->frame = 20;
    TaskYieldTrampoline(8);
    gCurTask->frame = 20;
    TaskYieldTrampoline(4);
    gCurTask->frame = 19;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->frame = 9;
    TaskYieldTrampoline(2);
    gCurTask->spriteFlags &= 0x7FFF;
    gCurTask->velY = 0xFFFD0000;
    gCurTask->accelY = 212 << 6;
    gCurTask->frame = 0;
    TaskYieldTrampoline(4);
    gCurTask->frame = 1;
    TaskYieldTrampoline(6);
    gCurTask->frame = 2;
    TaskYieldTrampoline(6);
    gCurTask->frame = 3;
    TaskYieldTrampoline(6);
    gCurTask->frame = 4;
    TaskYieldTrampoline(6);
    TaskStop();
    gCurTask->frame = 5;
    TaskYieldTrampoline(64);
    PlayBgm(56);
    ResetBgmPlayer();
    gCurTask->cutsceneActorBgmFadeStep = -1;
    TaskStop();
    gCurTask->frame = 5;
    TaskYieldTrampoline(72);
    gCurTask->velX = 0xFFFB0000;
    gCurTask->frame = 6;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->frame = 6;
    TaskYieldTrampoline(100);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->velX = 160 << 7;
        gCurTask->accelX = 192 << 3;
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->velX = 0xFFFFB000;
        gCurTask->accelX = 0xFFFFFA00;
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 3);
    gCurTask->cutsceneActorBgmFadeStep = 2;
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->velX = 160 << 7;
        gCurTask->accelX = 192 << 3;
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->velX = 0xFFFFB000;
        gCurTask->accelX = 0xFFFFFA00;
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 8;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 3);
    gCurTask->velX = 160 << 11;
    gCurTask->velY = 0xFFFD8000;
    gCurTask->frame = 41;
    TaskYieldTrampoline(2);
    gCurTask->frame = 40;
    TaskYieldTrampoline(2);
    gCurTask->velY = 0;
    gCurTask->frame = 39;
    TaskYieldTrampoline(2);
    gCurTask->frame = 38;
    TaskYieldTrampoline(2);
    gCurTask->frame = 37;
    TaskYieldTrampoline(2);
    gCurTask->frame = 36;
    TaskYieldTrampoline(2);
    TaskStop();
    gCurTask->frame = 0xFFFF;
    TaskYieldTrampoline(80);
    gCurTask->posX = 150 << 15;
    gCurTask->posY = 176 << 15;
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->velX = 128 << 11;
        gCurTask->velY = 0xFFFD0000;
        gCurTask->frame = 118;
        TaskYieldTrampoline(2);
        gCurTask->frame = 117;
        TaskYieldTrampoline(2);
        gCurTask->frame = 116;
        TaskYieldTrampoline(2);
        gCurTask->frame = 115;
        TaskYieldTrampoline(2);
        gCurTask->frame = 114;
        TaskYieldTrampoline(2);
        gCurTask->frame = 113;
        TaskYieldTrampoline(2);
        gCurTask->frame = 112;
        TaskYieldTrampoline(2);
        gCurTask->frame = 111;
        TaskYieldTrampoline(2);
        gCurTask->frame = 110;
        TaskYieldTrampoline(2);
        gCurTask->frame = 109;
        TaskYieldTrampoline(2);
        gCurTask->frame = 108;
        TaskYieldTrampoline(2);
        gCurTask->frame = 107;
        TaskYieldTrampoline(2);
        gCurTask->frame = 122;
        TaskYieldTrampoline(2);
        gCurTask->frame = 121;
        TaskYieldTrampoline(2);
        gCurTask->frame = 120;
        TaskYieldTrampoline(2);
        gCurTask->frame = 119;
        TaskYieldTrampoline(2);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 1);
    TaskStop();
    gCurTask->frame = 0xFFFF;
    TaskSleepForever();
}

void CutsceneFountainKirbyUpdate(void)
{
    struct Task *t = gCurTask;
    s32 d = t->cutsceneActorBgmFadeStep;
    s32 v;

    if (d < 0)
    {
        v = 255;
    }
    else
    {
        v = t->cutsceneActorBgmVolume - d;
        t->cutsceneActorBgmVolume = v;
        if (v >= 0)
            goto done;
        v = 0;
    }
    t->cutsceneActorBgmVolume = v;
done:
    SetBgmVolume((u16)gCurTask->cutsceneActorBgmVolume);
}

void CutsceneFountainKingDedede(void)
{
    gCurTask->moveCallback = (u32)TaskMove;
    gCurTask->drawCallback = (u32)sub_0801a310;
    gCurTask->layer = 11;
    gCurTask->frameTable = gCutsceneFountainKingDededeFrames;
    gCurTask->updateCallback = (u32)CutsceneFountainKingDededeUpdate;
    gUnk_02007D00[0] = -1;
    gCurTask->cutsceneActorSfxTimer = -1;
    gCurTask->tileWord = 0x8010;
    gCurTask->posX = 184 << 14;
    gCurTask->posY = 0xFFDA0000;
    gCurTask->cutsceneActorChildGate = 0;
    CreateCutsceneActor(53, 32);
    gCurTask->spriteFlags &= 0x7FFF;
    TaskStop();
    gCurTask->frame = 0xFFFF;
    TaskYieldTrampoline(200);
    gCurTask->frame = -1;
    TaskYieldTrampoline(72);
    gCurTask->frame = -1;
    TaskYieldTrampoline(4);
    gCurTask->velY = 0x00025500;
    gCurTask->accelY = 180 << 6;
    gCurTask->frame = 12;
    TaskYieldTrampoline(27);
    RequestScreenShake(2);
    PlaySfx(0x1F7);
    TaskStop();
    gCurTask->frame = 13;
    TaskYieldTrampoline(4);
    PlaySfx(0x113);
    TaskSetMotion(160 << 7, 160 << 7, 0x5A5A5A5A, 0xFFFDAB00, 0xFFFFF000, 0x5A5A5A5A);
    gCurTask->frame = 14;
    TaskYieldTrampoline(10);
    gCurTask->accelX = 0;
    gCurTask->accelY = 128 << 9;
    gCurTask->frame = 15;
    TaskYieldTrampoline(10);
    TaskSetMotion(184 << 9, 0, 0x5A5A5A5A, 0, 0, 0x5A5A5A5A);
    gCurTask->frame = 16;
    TaskYieldTrampoline(9);
    gCurTask->cutsceneActorChildGate = 1;
    gCurTask->cutsceneActorSfxTimer = 0;
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->velX = 0xFFFF5000;
        gCurTask->frame = 17;
        TaskYieldTrampoline(10);
        gCurTask->velX = 128 << 7;
        gCurTask->frame = 16;
        TaskYieldTrampoline(20);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 1);
    gCurTask->cutsceneActorChildGate = 0;
    gCurTask->cutsceneActorSfxTimer = -1;
    TaskStop();
    gCurTask->frame = 1;
    TaskYieldTrampoline(40);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 0;
        TaskYieldTrampoline(8);
        gCurTask->frame = 2;
        TaskYieldTrampoline(8);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 3);
    gCurTask->frame = 1;
    TaskYieldTrampoline(84);
    gCurTask->velX = 0xFFFEB400;
    gCurTask->frame = 1;
    TaskYieldTrampoline(44);
    gCurTask->frame = 4;
    TaskYieldTrampoline(8);
    PlaySfx(0x113);
    TaskSetMotion(224 << 8, 192 << 7, 0x5A5A5A5A, 0xFFFDF000, 0xFFFFF000, 0x5A5A5A5A);
    gCurTask->frame = 14;
    TaskYieldTrampoline(8);
    gCurTask->accelX = 0;
    gCurTask->accelY = 0x00011900;
    gCurTask->frame = 15;
    TaskYieldTrampoline(8);
    gCurTask->cutsceneActorChildGate = 1;
    gCurTask->cutsceneActorSfxTimer = 0;
    TaskSetMotion(0x00025500, 0, 0x5A5A5A5A, 0, 0, 0x5A5A5A5A);
    gCurTask->frame = 16;
    TaskYieldTrampoline(7);
    TaskStop();
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->velX = 0xFFFF5000;
        gCurTask->frame = 16;
        TaskYieldTrampoline(10);
        gCurTask->velX = 128 << 7;
        gCurTask->frame = 3;
        TaskYieldTrampoline(20);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 4);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->velX = 128 << 6;
        gCurTask->frame = 16;
        TaskYieldTrampoline(10);
        gCurTask->velX = 152 << 9;
        gCurTask->frame = 3;
        TaskYieldTrampoline(20);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 1);
    gCurTask->velX = 128 << 6;
    gCurTask->frame = 16;
    TaskYieldTrampoline(10);
    gCurTask->velX = 152 << 9;
    gCurTask->frame = 3;
    TaskYieldTrampoline(9);
    gCurTask->cutsceneActorChildGate = 0;
    gCurTask->cutsceneActorSfxTimer = -1;
    TaskStop();
    gCurTask->frame = 3;
    TaskYieldTrampoline(20);
    gCurTask->frame = 1;
    TaskYieldTrampoline(40);
    PlaySfx(254 << 1);
    TaskSetMotion(0xFFFAE000, 152 << 6, 0x5A5A5A5A, 0xFFF90000, 133 << 8, 0x5A5A5A5A);
    gCurTask->frame = 18;
    TaskYieldTrampoline(18);
    gCurTask->frame = 15;
    TaskYieldTrampoline(8);
    RequestScreenShake(2);
    PlaySfx(0x1F7);
    gCurTask->velX = 0;
    gCurTask->velY = 0;
    gCurTask->accelY = 0;
    gCurTask->frame = 16;
    TaskYieldTrampoline(2);
    gCurTask->velX = 0xFFFD0000;
    gCurTask->velY = 0xFFFB0000;
    gCurTask->accelY = 135 << 8;
    gCurTask->frame = 16;
    TaskYieldTrampoline(10);
    gCurTask->frame = 17;
    TaskYieldTrampoline(8);
    TaskStop();
    gCurTask->frame = 17;
    TaskYieldTrampoline(66);
    gCurTask->frame = 5;
    TaskYieldTrampoline(10);
    gCurTask->frame = 4;
    TaskYieldTrampoline(16);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 6;
        TaskYieldTrampoline(4);
        gCurTask->frame = 7;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 31);
    gCurTask->frame = 6;
    TaskYieldTrampoline(4);
    gCurTask->velX = 0xFFFB0000;
    gCurTask->frame = 8;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->frame = 8;
    TaskYieldTrampoline(100);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->velX = 160 << 7;
        gCurTask->accelX = 192 << 3;
        gCurTask->frame = 9;
        TaskYieldTrampoline(4);
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->frame = 9;
        TaskYieldTrampoline(4);
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->velX = 0xFFFFB000;
        gCurTask->accelX = 0xFFFFFA00;
        gCurTask->frame = 9;
        TaskYieldTrampoline(4);
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags |= 128 << 8;
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->frame = 9;
        TaskYieldTrampoline(4);
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->spriteFlags &= 0x7FFF;
        gCurTask->frame = 10;
        TaskYieldTrampoline(4);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 5);
    gCurTask->spriteFlags &= 0x7FFF;
    TaskStop();
    gCurTask->frame = 19;
    TaskYieldTrampoline(10);
    PlaySfx(0x113);
    TaskSetMotion(128 << 11, 0xFFFFFB00, 0x5A5A5A5A, 0xFFF7D000, 136 << 8, 0x5A5A5A5A);
    gCurTask->frame = 14;
    TaskYieldTrampoline(20);
    gCurTask->frame = 12;
    TaskYieldTrampoline(10);
    TaskStop();
    gCurTask->frame = 13;
    TaskYieldTrampoline(6);
    gCurTask->frame = 19;
    TaskYieldTrampoline(4);
    gCurTask->spriteFlags |= 128 << 8;
    gCurTask->frame = 19;
    TaskYieldTrampoline(4);
    gCurTask->frame = 20;
    TaskYieldTrampoline(16);
    CreateCutsceneActor(52, 32);
    gUnk_02007D00[0] = PlaySfx(0x21B);
    gCurTask->cutsceneActorLoopCount = 0;
    do
    {
        gCurTask->frame = 21;
        TaskYieldTrampoline(10);
        gCurTask->frame = 22;
        TaskYieldTrampoline(10);
        gCurTask->cutsceneActorLoopCount++;
    } while ((s16)gCurTask->cutsceneActorLoopCount <= 2);
    if (gUnk_02007D00[0] != -1)
    {
        StopSfxOnPlayer(gUnk_02007D00[0], 0x21B);
        gUnk_02007D00[0] = -1;
    }
    PlaySfx(135 << 2);
    gCurTask->frame = 23;
    TaskYieldTrampoline(10);
    gCurTask->spriteFlags &= 0x7FFF;
    gCurTask->frame = 23;
    TaskYieldTrampoline(4);
    PlaySfx(0x113);
    TaskSetMotion(0xFFFC0000, 192 << 5, 0x5A5A5A5A, 0xFFF7D000, 136 << 8, 0x5A5A5A5A);
    gCurTask->frame = 23;
    TaskYieldTrampoline(30);
    TaskStop();
    gCurTask->frame = 23;
    TaskYieldTrampoline(2);
    TaskSetMotion(0xFFFF0000, 128 << 2, 0x5A5A5A5A, 0xFFFD0000, 153 << 8, 0x5A5A5A5A);
    gCurTask->frame = 23;
    TaskYieldTrampoline(8);
    PlaySfx(0x21D);
    TaskStop();
    gCurTask->frame = 11;
    TaskYieldTrampoline(60);
    TaskSleepForever();
}
