#include "gba/gba.h"
#include "global.h"
#include "task.h"

extern s32 gUnk_02007D00[];
extern struct Task *gCurTask;
extern u32 gUnk_08755068[];
extern u32 gUnk_08755378[];

void TaskYieldTrampoline(s32 frames);
void PlayBgm(u32 a);
void sub_08003184(void);
s32 PlaySfx(s32 id);
void StopSfxOnPlayer(s32 player, s32 songId);
void SetBgmVolume(u16 v);
void TaskMove(void);
void TaskSleepForever(void);
void TaskSetMotion(s32 a, s32 b, s32 c, s32 d, s32 e, s32 f);
void TaskStop(void);
void CreateCutsceneActor(s32 a, s32 b);
void sub_08018464(void);
void sub_08018b84(void);
void sub_0801a1ec(void);
void sub_0801a310(void);
void RequestScreenShake(s32 a);

void sub_08017668(void)
{
    gCurTask->unk00 = (u32)TaskMove;
    gCurTask->unk0C = (u32)sub_0801a1ec;
    gCurTask->unk42 = 7;
    gCurTask->unk38 = gUnk_08755068;
    gCurTask->unk04 = (u32)sub_08018464;
    gCurTask->unk24 = -1;
    gCurTask->unk40 = 128 << 4;
    gCurTask->unk4C = 128 << 16;
    gCurTask->unk50 = 218 << 15;
    gCurTask->unk3E |= 128 << 8;
    TaskStop();
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(64);
    gCurTask->unk3C = 46;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 47;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 48;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 49;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 80;
    TaskYieldTrampoline(40);
    gCurTask->unk3E &= 0x7FFF;
    gCurTask->unk54 = 240 << 5;
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 86;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 88;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 89;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 90;
    TaskYieldTrampoline(4);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 81;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 82;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 83;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 84;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 85;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 86;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 87;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 88;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 89;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 90;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 2);
    TaskStop();
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 86;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 88;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 89;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 90;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(4);
    gCurTask->unk54 = 0xFFFF5000;
    gCurTask->unk3C = 86;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 128 << 7;
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 88;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 89;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 90;
    TaskYieldTrampoline(8);
    gCurTask->unk54 = 0xFFFF5000;
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 128 << 7;
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(8);
    gCurTask->unk3E |= 128 << 8;
    TaskStop();
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(44);
    gCurTask->unk3C = 50;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(44);
    gCurTask->unk3C = 51;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 52;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 51;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 52;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 51;
    TaskYieldTrampoline(32);
    gCurTask->unk3C = 52;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 51;
    TaskYieldTrampoline(36);
    gCurTask->unk3E &= 0x7FFF;
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(4);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 81;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 82;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 83;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 84;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 85;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 86;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 87;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 88;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 89;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 90;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk54 = 0xFFFF5000;
        gCurTask->unk3C = 81;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 82;
        TaskYieldTrampoline(2);
        gCurTask->unk54 = 128 << 7;
        gCurTask->unk3C = 82;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 83;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 84;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 85;
        TaskYieldTrampoline(8);
        gCurTask->unk54 = 0xFFFF5000;
        gCurTask->unk3C = 86;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 87;
        TaskYieldTrampoline(2);
        gCurTask->unk54 = 128 << 7;
        gCurTask->unk3C = 87;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 88;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 89;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 90;
        TaskYieldTrampoline(8);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk54 = 0xFFFF5000;
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 128 << 7;
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(6);
    gCurTask->unk54 = 128 << 6;
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(12);
    gCurTask->unk54 = 128 << 6;
    gCurTask->unk3C = 86;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 152 << 9;
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 88;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 89;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 90;
    TaskYieldTrampoline(8);
    gCurTask->unk54 = 128 << 6;
    gCurTask->unk3C = 81;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 152 << 9;
    gCurTask->unk3C = 82;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 83;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 84;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 85;
    TaskYieldTrampoline(8);
    gCurTask->unk54 = 128 << 6;
    gCurTask->unk3C = 86;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 152 << 9;
    gCurTask->unk3C = 87;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 88;
    TaskYieldTrampoline(4);
    gCurTask->unk3E |= 128 << 8;
    TaskStop();
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(44);
    gCurTask->unk3C = 53;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 54;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 55;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 56;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 57;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 58;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 59;
    TaskYieldTrampoline(2);
    gCurTask->unk58 = 0xFFF90000;
    gCurTask->unk60 = 158 << 7;
    gCurTask->unk3C = 60;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 61;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 62;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 63;
    TaskYieldTrampoline(10);
    gCurTask->unk3C = 64;
    TaskYieldTrampoline(1);
    gCurTask->unk58 = 0;
    gCurTask->unk3C = 64;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 65;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 66;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 67;
    TaskYieldTrampoline(4);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 95;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 94;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 2);
    TaskStop();
    gCurTask->unk3C = 93;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 79;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 78;
    TaskYieldTrampoline(44);
    gCurTask->unk24 = 4;
    gCurTask->unk20 = 255;
    PlaySfx(100);
    gCurTask->unk6C = 0;
    do
    {
        TaskSetMotion(0xFFFF2000, 0xFFFFE700, 0x5A5A5A5A, 0xFFFB8B00, 246 << 7, 0x5A5A5A5A);
        gCurTask->unk3C = 68;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 6);
    gCurTask->unk3C = 69;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 68;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 70;
    TaskYieldTrampoline(6);
    TaskStop();
    gCurTask->unk3C = 71;
    TaskYieldTrampoline(8);
    PlaySfx(100);
    gCurTask->unk6C = 0;
    do
    {
        TaskSetMotion(0xFFFF0000, 0xFFFFF900, 0x5A5A5A5A, 0xFFFAB000, 138 << 8, 0x5A5A5A5A);
        gCurTask->unk3C = 91;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 3);
    gCurTask->unk3C = 96;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 97;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 100;
    TaskYieldTrampoline(2);
    gCurTask->unk3E &= 0x7FFF;
    gCurTask->unk3C = 72;
    TaskYieldTrampoline(2);
    gCurTask->unk3E |= 128 << 8;
    gCurTask->unk3C = 102;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 73;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 104;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 105;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 106;
    TaskYieldTrampoline(2);
    TaskStop();
    gCurTask->unk3C = 79;
    TaskYieldTrampoline(4);
    PlaySfx(100);
    gCurTask->unk58 = 0xFFF90000;
    gCurTask->unk60 = 142 << 8;
    gCurTask->unk3C = 91;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 93;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 94;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 95;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 74;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 75;
    TaskYieldTrampoline(10);
    PlaySfx(238);
    gCurTask->unk6C = 0;
    do
    {
        TaskStop();
        gCurTask->unk3C = 76;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 77;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 4);
    CreateCutsceneActor(57, 32);
    TaskSetMotion(0xFFFEB000, 0, 0x5A5A5A5A, 0xFFFCB000, 222 << 7, 0x5A5A5A5A);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(10);
    gCurTask->unk3C = 20;
    TaskYieldTrampoline(8);
    gCurTask->unk3C = 20;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 19;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(2);
    gCurTask->unk3E &= 0x7FFF;
    gCurTask->unk58 = 0xFFFD0000;
    gCurTask->unk60 = 212 << 6;
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(6);
    TaskStop();
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(64);
    PlayBgm(56);
    sub_08003184();
    gCurTask->unk24 = -1;
    TaskStop();
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(72);
    gCurTask->unk54 = 0xFFFB0000;
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(100);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk54 = 160 << 7;
        gCurTask->unk5C = 192 << 3;
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk54 = 0xFFFFB000;
        gCurTask->unk5C = 0xFFFFFA00;
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 3);
    gCurTask->unk24 = 2;
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk54 = 160 << 7;
        gCurTask->unk5C = 192 << 3;
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk54 = 0xFFFFB000;
        gCurTask->unk5C = 0xFFFFFA00;
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 3);
    gCurTask->unk54 = 160 << 11;
    gCurTask->unk58 = 0xFFFD8000;
    gCurTask->unk3C = 41;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 40;
    TaskYieldTrampoline(2);
    gCurTask->unk58 = 0;
    gCurTask->unk3C = 39;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 38;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 37;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 36;
    TaskYieldTrampoline(2);
    TaskStop();
    gCurTask->unk3C = 0xFFFF;
    TaskYieldTrampoline(80);
    gCurTask->unk4C = 150 << 15;
    gCurTask->unk50 = 176 << 15;
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk54 = 128 << 11;
        gCurTask->unk58 = 0xFFFD0000;
        gCurTask->unk3C = 118;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 117;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 116;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 115;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 114;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 113;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 112;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 111;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 110;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 109;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 108;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 107;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 122;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 121;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 120;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 119;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    TaskStop();
    gCurTask->unk3C = 0xFFFF;
    TaskSleepForever();
}

void sub_08018464(void)
{
    struct Task *t = gCurTask;
    s32 d = t->unk24;
    s32 v;

    if (d < 0)
    {
        v = 255;
    }
    else
    {
        v = t->unk20 - d;
        t->unk20 = v;
        if (v >= 0)
            goto done;
        v = 0;
    }
    t->unk20 = v;
done:
    SetBgmVolume((u16)gCurTask->unk20);
}

void sub_08018498(void)
{
    gCurTask->unk00 = (u32)TaskMove;
    gCurTask->unk0C = (u32)sub_0801a310;
    gCurTask->unk42 = 11;
    gCurTask->unk38 = gUnk_08755378;
    gCurTask->unk04 = (u32)sub_08018b84;
    gUnk_02007D00[0] = -1;
    gCurTask->unk20 = -1;
    gCurTask->unk40 = 0x8010;
    gCurTask->unk4C = 184 << 14;
    gCurTask->unk50 = 0xFFDA0000;
    gCurTask->unk28 = 0;
    CreateCutsceneActor(53, 32);
    gCurTask->unk3E &= 0x7FFF;
    TaskStop();
    gCurTask->unk3C = 0xFFFF;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = -1;
    TaskYieldTrampoline(72);
    gCurTask->unk3C = -1;
    TaskYieldTrampoline(4);
    gCurTask->unk58 = 0x00025500;
    gCurTask->unk60 = 180 << 6;
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(27);
    RequestScreenShake(2);
    PlaySfx(0x1F7);
    TaskStop();
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(4);
    PlaySfx(0x113);
    TaskSetMotion(160 << 7, 160 << 7, 0x5A5A5A5A, 0xFFFDAB00, 0xFFFFF000, 0x5A5A5A5A);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(10);
    gCurTask->unk5C = 0;
    gCurTask->unk60 = 128 << 9;
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(10);
    TaskSetMotion(184 << 9, 0, 0x5A5A5A5A, 0, 0, 0x5A5A5A5A);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(9);
    gCurTask->unk28 = 1;
    gCurTask->unk20 = 0;
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk54 = 0xFFFF5000;
        gCurTask->unk3C = 17;
        TaskYieldTrampoline(10);
        gCurTask->unk54 = 128 << 7;
        gCurTask->unk3C = 16;
        TaskYieldTrampoline(20);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk28 = 0;
    gCurTask->unk20 = -1;
    TaskStop();
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(40);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(8);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(8);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 3);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(84);
    gCurTask->unk54 = 0xFFFEB400;
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(44);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(8);
    PlaySfx(0x113);
    TaskSetMotion(224 << 8, 192 << 7, 0x5A5A5A5A, 0xFFFDF000, 0xFFFFF000, 0x5A5A5A5A);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(8);
    gCurTask->unk5C = 0;
    gCurTask->unk60 = 0x00011900;
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(8);
    gCurTask->unk28 = 1;
    gCurTask->unk20 = 0;
    TaskSetMotion(0x00025500, 0, 0x5A5A5A5A, 0, 0, 0x5A5A5A5A);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(7);
    TaskStop();
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk54 = 0xFFFF5000;
        gCurTask->unk3C = 16;
        TaskYieldTrampoline(10);
        gCurTask->unk54 = 128 << 7;
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(20);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 4);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk54 = 128 << 6;
        gCurTask->unk3C = 16;
        TaskYieldTrampoline(10);
        gCurTask->unk54 = 152 << 9;
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(20);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk54 = 128 << 6;
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(10);
    gCurTask->unk54 = 152 << 9;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(9);
    gCurTask->unk28 = 0;
    gCurTask->unk20 = -1;
    TaskStop();
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(20);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(40);
    PlaySfx(254 << 1);
    TaskSetMotion(0xFFFAE000, 152 << 6, 0x5A5A5A5A, 0xFFF90000, 133 << 8, 0x5A5A5A5A);
    gCurTask->unk3C = 18;
    TaskYieldTrampoline(18);
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(8);
    RequestScreenShake(2);
    PlaySfx(0x1F7);
    gCurTask->unk54 = 0;
    gCurTask->unk58 = 0;
    gCurTask->unk60 = 0;
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 0xFFFD0000;
    gCurTask->unk58 = 0xFFFB0000;
    gCurTask->unk60 = 135 << 8;
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(10);
    gCurTask->unk3C = 17;
    TaskYieldTrampoline(8);
    TaskStop();
    gCurTask->unk3C = 17;
    TaskYieldTrampoline(66);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(10);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(16);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 6;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 31);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(4);
    gCurTask->unk54 = 0xFFFB0000;
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(4);
    TaskStop();
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(100);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk54 = 160 << 7;
        gCurTask->unk5C = 192 << 3;
        gCurTask->unk3C = 9;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 9;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk54 = 0xFFFFB000;
        gCurTask->unk5C = 0xFFFFFA00;
        gCurTask->unk3C = 9;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3E |= 128 << 8;
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 9;
        TaskYieldTrampoline(4);
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk3E &= 0x7FFF;
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(4);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 5);
    gCurTask->unk3E &= 0x7FFF;
    TaskStop();
    gCurTask->unk3C = 19;
    TaskYieldTrampoline(10);
    PlaySfx(0x113);
    TaskSetMotion(128 << 11, 0xFFFFFB00, 0x5A5A5A5A, 0xFFF7D000, 136 << 8, 0x5A5A5A5A);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(20);
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(10);
    TaskStop();
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(6);
    gCurTask->unk3C = 19;
    TaskYieldTrampoline(4);
    gCurTask->unk3E |= 128 << 8;
    gCurTask->unk3C = 19;
    TaskYieldTrampoline(4);
    gCurTask->unk3C = 20;
    TaskYieldTrampoline(16);
    CreateCutsceneActor(52, 32);
    gUnk_02007D00[0] = PlaySfx(0x21B);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 21;
        TaskYieldTrampoline(10);
        gCurTask->unk3C = 22;
        TaskYieldTrampoline(10);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 2);
    if (gUnk_02007D00[0] != -1)
    {
        StopSfxOnPlayer(gUnk_02007D00[0], 0x21B);
        gUnk_02007D00[0] = -1;
    }
    PlaySfx(135 << 2);
    gCurTask->unk3C = 23;
    TaskYieldTrampoline(10);
    gCurTask->unk3E &= 0x7FFF;
    gCurTask->unk3C = 23;
    TaskYieldTrampoline(4);
    PlaySfx(0x113);
    TaskSetMotion(0xFFFC0000, 192 << 5, 0x5A5A5A5A, 0xFFF7D000, 136 << 8, 0x5A5A5A5A);
    gCurTask->unk3C = 23;
    TaskYieldTrampoline(30);
    TaskStop();
    gCurTask->unk3C = 23;
    TaskYieldTrampoline(2);
    TaskSetMotion(0xFFFF0000, 128 << 2, 0x5A5A5A5A, 0xFFFD0000, 153 << 8, 0x5A5A5A5A);
    gCurTask->unk3C = 23;
    TaskYieldTrampoline(8);
    PlaySfx(0x21D);
    TaskStop();
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(60);
    TaskSleepForever();
}
