#include "gba/gba.h"
#include "global.h"
#include "task.h"

extern u32 gUnk_03001610[];
extern u16 gSpriteCameraX;
extern u16 gSpriteCameraY;
extern struct Task *gCurTask;
extern u32 gUnk_082FE0D0[];
extern u32 gUnk_082FE0E4[];
extern u32 gUnk_082FE104[];
extern u16 gUnk_0874AD44[];
extern u32 gUnk_087553DC[];
extern u32 gUnk_087553FC[];
extern u32 gUnk_08755440[];
extern u32 gUnk_0875546C[];
extern u32 gUnk_08755484[];

void TaskYieldTrampoline(s32 frames);
void RequestCopy(u32 mode, u32 src, u32 dst, u32 size);
void BlendColors(s32 a, s32 b, s32 c, s32 d, void *e);
s32 PlaySfx(s32 id);
void TaskMove(void);
void TaskDrawScreen(void);
void TaskSleepForever(void);
void TaskSetMotion(s32 a, s32 b, s32 c, s32 d, s32 e, s32 f);
void TaskStop(void);
void CreateCutsceneActor(s32 a, s32 b);
void sub_08019590(void);
void sub_08019ecc(void);
void sub_0801a310(void);
void sub_0801a3e4(void);
void SetCameraFocus(s32 x, s32 y);

void sub_08019000(void)
{

    gCurTask->unk00 = (u32)TaskMove;
    gCurTask->unk0C = (u32)TaskDrawScreen;
    gCurTask->unk42 = 12;
    gCurTask->unk38 = gUnk_087553DC;
    gCurTask->unk04 = (u32)sub_08019590;
    gCurTask->unk70 = 0;
    gCurTask->unk40 = 0x9210;
    LZ77UnCompWram((const void *)gUnk_082FE0D0[3], (void *)0x02026000);
    RequestCopy(4, 0x02026000, 0x06014000, 128 << 6);
    RequestCopy(2, gUnk_082FE0D0[2], 0x03001590, 32);
    gCurTask->unk4C = 240 << 15;
    gCurTask->unk50 = 144 << 15;
    TaskStop();
    gCurTask->unk3C = 0xFFFF;
    TaskYieldTrampoline(120);
    TaskYieldTrampoline(200);
    TaskYieldTrampoline(200);
    TaskYieldTrampoline(200);
    TaskYieldTrampoline(200);
    TaskYieldTrampoline(200);
    TaskYieldTrampoline(88);
    CreateCutsceneActor(56, 32);
    TaskYieldTrampoline(66);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(2);
        gCurTask->unk3C |= -1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 6;
        TaskYieldTrampoline(2);
        gCurTask->unk3C |= -1;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 3);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(2);
    gCurTask->unk58 = 0xFFFA0000;
    gCurTask->unk60 = 160 << 7;
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    TaskStop();
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk58 = 128 << 9;
        gCurTask->unk60 = 0xFFFFF000;
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk58 = 0xFFFF0000;
        gCurTask->unk60 = 128 << 5;
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 4);
    TaskSetMotion(0xFFF80000, 160 << 7, 0x5A5A5A5A, 0, 192 << 2, 0x5A5A5A5A);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk60 = 0xFFFFFD00;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk5C = 0xFFFFF000;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk54 = 0;
    gCurTask->unk60 = 0;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    PlaySfx(144 << 2);
    gCurTask->unk5C = 128 << 9;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk60 = 0xFFFFB000;
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(2);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 2);
    TaskStop();
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(2);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(2);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 15);
    TaskStop();
    gCurTask->unk3C = 0xFFFF;
    TaskSleepForever();
}

void sub_08019590(void)
{
    struct Task *t = gCurTask;

    if ((s16)t->unk70 > 23)
        t->unk70 = 0;
    BlendColors((s32)gUnk_082FE0E4, (s32)gUnk_082FE104,
                 gUnk_0874AD44[(s16)gCurTask->unk70], 16, (void *)0x03001590);
    gCurTask->unk70++;
}

void sub_080195ec(void)
{
    struct Task *t = gCurTask;

    t->unk00 = (u32)TaskMove;
    t->unk0C = (u32)sub_0801a310;
    t->unk42 = 6;
    gCurTask->unk38 = gUnk_087553FC;
    gCurTask->unk40 = 0xA310;
    gCurTask->unk4C = 240 << 15;
    gCurTask->unk50 = 192 << 14;
    TaskStop();
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(156);
    PlaySfx(138 << 1);
    TaskSetMotion(0xFFFF0000, 160 << 3, 0x5A5A5A5A, 0xFFFB8000, 158 << 7, 0x5A5A5A5A);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 4;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 6;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 8;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 10;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 12;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 14;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 16;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 15;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 13;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 11;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 9;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 7;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 5;
        TaskYieldTrampoline(1);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(1);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 1);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    TaskStop();
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    PlaySfx(0x00000115);
    TaskSetMotion(0, 0, 0x5A5A5A5A, 0xFFFA0000, 158 << 7, 0x5A5A5A5A);
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 7;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 7;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(1);
    TaskStop();
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(1);
    PlaySfx(0x00000115);
    gCurTask->unk58 = 0xFFFCB000;
    gCurTask->unk60 = 160 << 7;
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 7;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 12;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 14;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 16;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 15;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 13;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 11;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 7;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(1);
    TaskStop();
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(255);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(190);
    gCurTask->unk54 = 160 << 11;
    gCurTask->unk58 = 0xFFFB0000;
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(1);
    gCurTask->unk58 = 0;
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(1);
    TaskStop();
    gCurTask->unk3C = 0x0000FFFF;
    TaskSleepForever();
}

void sub_08019b30(void)
{
    struct Task *t = gCurTask;

    t->unk00 = (u32)TaskMove;
    t->unk0C = (u32)sub_0801a3e4;
    t->unk42 = 15;
    gCurTask->unk38 = gUnk_08755440;
    gCurTask->unk40 = 0xD350;
    RequestCopy(2, 0x085E0070, (u32)gUnk_03001610, 32);
    gCurTask->unk4C = 160 << 17;
    gCurTask->unk50 = 160 << 15;
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 4;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 5;
        TaskYieldTrampoline(5);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 40);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 6;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 7;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 8;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 9;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 10;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 0xFFFF;
    TaskSleepForever();
}

void sub_08019c44(void)
{
    struct Task *t = gCurTask;

    t->unk00 = (u32)TaskMove;
    t->unk0C = (u32)sub_0801a3e4;
    t->unk42 = 15;
    gCurTask->unk38 = gUnk_0875546C;
    gCurTask->unk40 = 0xD350;
    RequestCopy(2, 0x085E0070, (u32)gUnk_03001610, 32);
    gCurTask->unk4C = 160 << 17;
    gCurTask->unk50 = 160 << 15;
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(200);
    gCurTask->unk3C = 5;
    TaskYieldTrampoline(27);
    gCurTask->unk3C = 4;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 3;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 0xFFFF;
    TaskSleepForever();
}

void sub_08019d30(void)
{
    struct Task *t = gCurTask;

    t->unk00 = (u32)TaskMove;
    t->unk0C = (u32)sub_0801a3e4;
    t->unk42 = 14;
    gCurTask->unk38 = gUnk_08755484;
    gCurTask->unk40 = 0xD350;
    RequestCopy(2, 0x085E0070, (u32)gUnk_03001610, 32);
    gCurTask->unk4C = 160 << 17;
    gCurTask->unk50 = 160 << 15;
    gCurTask->unk6C = 0;
    do
    {
        gCurTask->unk3C = 0;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 1;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 2;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 3;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 4;
        TaskYieldTrampoline(5);
        gCurTask->unk3C = 5;
        TaskYieldTrampoline(5);
        gCurTask->unk6C++;
    } while ((s16)gCurTask->unk6C <= 39);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 0;
    TaskYieldTrampoline(5);
    gCurTask->unk3C = 0xFFFF;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = 1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = -1;
    TaskYieldTrampoline(2);
    gCurTask->unk3C = 2;
    TaskYieldTrampoline(1);
    gCurTask->unk3C = -1;
    TaskSleepForever();
}

void sub_08019e48(void)
{
    struct Task *t = gCurTask;
    struct Task *u;
    s32 v;

    t->unk00 = (u32)TaskMove;
    t->unk0C = 0;
    t->unk04 = (u32)sub_08019ecc;
    t->unk4C = ((s16)gSpriteCameraX + 120) << 16;
    t->unk50 = ((s16)gSpriteCameraY + 90) << 16;
    TaskStop();
    TaskYieldTrampoline(76);
    TaskYieldTrampoline(40);
    u = gCurTask;
    v = 0x10000;
    u->unk54 = v;
    TaskYieldTrampoline(255);
    TaskYieldTrampoline(20);
    TaskStop();
    TaskYieldTrampoline(190);
    gCurTask->unk54 = v;
    TaskYieldTrampoline(237);
    TaskStop();
    TaskSleepForever();
}

void sub_08019ecc(void)
{
    struct Task *t = gCurTask;

    SetCameraFocus(t->unk48, t->unk4A);
}
