@ Auto-generated by tools/split.py from baserom.gba - DO NOT EDIT.
@ Regenerate with: make split
@ Segment game_code_and_rodata_080653ec_0806ef5c_080bf994_080c1ffc, chunk 2/2: 0x080C2FB8-0x080C2FF8 (thumb_code, 0x40 bytes)
@ Functions (docs/analysis/symbols.csv):
@   0x080C2FB8 sub_080c2fb8

	.section .game_code_and_rodata_080653ec_0806ef5c_080bf994_080c1ffc, "ax"
	.syntax	unified
	.cpu	arm7tdmi
game_code_and_rodata_080653ec_0806ef5c_080bf994_080c1ffc_01:
	.thumb_func
	.global	sub_080c2fb8
sub_080c2fb8:
	.thumb
	push	{r4, lr}
	ldr	r2, [pc, #44]	@ 0x080C2FE8
	ldr	r1, [pc, #44]	@ 0x080C2FEC
	movs	r0, #0
	strh	r0, [r1, #0]
	movs	r1, #160
	lsls	r1, r1, #19
	ldr	r0, [pc, #40]	@ 0x080C2FF0
	ldr	r3, [r0, #0]
	movs	r4, #191
	lsls	r4, r4, #2
	adds	r0, r3, r4
	ldrh	r0, [r0, #0]
	strh	r0, [r1, #0]
	movs	r4, #222
	lsls	r4, r4, #1
	adds	r0, r3, r4
	str	r0, [r2, #0]
	str	r1, [r2, #4]
	ldr	r0, [pc, #20]	@ 0x080C2FF4
	str	r0, [r2, #8]
	pop	{r4}
	pop	{r0}
	bx	r0
	.word	0x040000B0
	.word	0x040000BA
	.word	gUnk_02017094
	.word	0xA2400001
